### ISSUE TITLE
Next.js links on pages that use SWR do not work

### ISSUE THREAD

**Issue by garyking** [vercel/swr#1047]
# Bug report

## Description / Observed Behavior

When SWR is used to fetch data on a page with links in Next.js, the links on that page do not work.

## Expected Behavior

The links should work.

## Repro Steps / Code Example

1. To reproduce, clone the repo here: https://github.com/garyking/test-next-js-app
2. Start with `next dev`, and open `http://localhost:3000/` in the browser.
3. On the homepage, click on `Users`. On the next page, there should be three links: `Alpha`, `Bravo`, `Charlie`.
4. Clicking on any of the three links will do nothing. Yet, the links work fine if you open them in a new tab. And if you kill the server, then the link will load at that point.

If you remove SWR on the `users` page, then the links work fine. And this issue occurs in `next dev` but not in `next start`.

## Additional Context

SWR version 0.5.3

**Comment by huozhi** [comment]
I've tried to deploy this project mentiond above into codesandbox, it works fine with both clicking through links and opening a new page. codesandox is also using `next dev` as running script.

<img src="https://user-images.githubusercontent.com/4800338/111401871-19a8a100-8705-11eb-8419-eb2f3353daae.png" width="400">

**Comment by garyking** [comment]
Removing `response.end()` from the API file fixed it.
