### ISSUE TITLE
Record pops up again after using bound mutate

### ISSUE THREAD

**Issue by Jonofat** [vercel/swr#1048]
I am on version 0.4.2 of SWR and don't know if this is a bug (apologies if not) or if my implementation is just incorrect. Basically I am trying to perform an optimistic update and pop the row off from the UI straight away once it is clicked. This happens but then it pops back up again before the http request is complete and then vanishes once more afterwards. It should remain gone unless there is a server error and the record is not removed from the database. 

This is my custom hook:

```
import axios from "axios";
import useSwr, { mutate } from "swr";

export const useHttp = (url, token) => {
  const fetcher = (url, token) =>
    axios
      .get(url, { headers: { Authorization: "Bearer " + token } })
      .then((res) => res.data);
  const { data, error, mutate } = useSwr(token ? [url, token] : null, fetcher);

  return {
    data: data,
    isLoading: !error && !data,
    isError: error,
    mutate: mutate,
  };
};

```

And the click handler 

```
  const handleApprove = async (bid) => {
    mutate(data.filter((d) => d._id !== bid));

    try {
      const config = {
        method: "PATCH",
        url: `http://localhost:8000/api/admin/endpoint/${bid}`,
        headers: { Authorization: "Bearer " + session.user.servertoken },
      };
      const res = await axios(config);
      if (res.status === 201) {
        mutate();
        toast.success("Approved");
      }
    } catch (err) {
      console.log(err);
    }
  };
```

**Comment by shuding** [comment]
Your first mutate call (optimistic update) doesn't have `false` as the second parameter, so it triggers a revalidation right after the mutation. Adding `false` should fix it:

```js
mutate(data.filter((d) => d._id !== bid), false)
```
