### ISSUE TITLE
Illegal Invocation

### ISSUE THREAD

**Issue by tehpsalmist** [vercel/swr#1050]
# Bug report

## Description / Observed Behavior

The code below is producing a `TypeError: Illegal Invocation` when the same key is passed to useSWR.

## Expected Behavior

Not to throw an illegal invocation error.

## Repro Steps / Code Example

 Run the code, then simulate by typing in some letters and backspacing.

```js
import React, { useState } from 'react'
import { render } from 'react-dom'
import useSWR from 'swr'

export const App = props => {
  const [search, setSearch] = useState('')

  const { data: src, error } = useSWR(search, (key) => {
    return fetch(`http://www.omdbapi.com/?apikey=276414e9&&t=${key}`)
      .then(res => res.ok ? res.json() : res.text())
      .then(json => json.Poster)
  })

  return <main>
    <input type='text' value={search} onChange={e => setSearch(e.target.value || '')} />
    <button type='submit' >submit</button>
    <img src={src || ''} alt='movie poster' />
  </main>
}

render(<App />, document.getElementById('app'))
```

## Additional Context

SWR version: 0.5.3
React/ReactDOM: 17.0.1
Can't reproduce in CodeSandbox
Using Parcel2 and React Fast Refresh to serve app.
Example code is literally all of the code in the project (except package.json and minimal index.html)

**Comment by koba04** [comment]
@tehpsalmist Could you create a GitHub repository for reproducing this?

**Comment by tehpsalmist** [comment]
Most definitely, I should have done that first. Uno momento.

**Comment by tehpsalmist** [comment]
Reproduce with this repo: https://github.com/tehpsalmist/illegal-invocation-bug

**Comment by tehpsalmist** [comment]
Noice. You can venmo me the bug bounty. :trollface:
