### ISSUE TITLE
[useSWRPages] loadMore should scroll up to last search result

### ISSUE THREAD

**Issue by aequasi** [vercel/swr#107]

**Comment by quietshu** [comment]
Can you elaborate?

**Comment by aequasi** [comment]
This may be more of an implementation detail, but when I was testing, if you `loadMore`, the page would stay scrolled to the `loadMore` button, instead of leaving the user at the bottom of last page they saw

**Comment by shuding** [comment]
This issue should be gone (since with the new API you will be able to control the "load more" behavior by yourself).
