### ISSUE TITLE
Bound mutate based on current data inconsistently update data

### ISSUE THREAD

**Issue by jacklimwenjie** [vercel/swr#1070]
# Bug report

## Description / Observed Behavior

When using [mutate based on current data](https://swr.vercel.app/docs/mutation#mutate-based-on-current-data) in a [bounded fashion](https://swr.vercel.app/docs/mutation#bound-mutate), 
and the data contains an array, 
sometimes the data is _not_ updated.

## Expected Behavior

The data is updated consistently when a bound mutate based on current data is used.

## Repro Steps / Code Example

https://codesandbox.io/s/useswr-async-mutate-bug-y77z1?file=/src/App.js

1. Click on the "X" button to attempt to delete a line
2. The line is supposed to disappear after 2 seconds, observe sometimes it fails. (somehow it tends to fail more easily if start to delete from the middle of the list). You can verify the mutation indeed takes place by checking the console logs, it should have a "delete fired" log every time the "X" button is clicked.

## Additional Context

swr: 0.5.4

**Comment by promer94** [comment]
Thanks for your repro !

ts set ------------------> ts cleared
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;read ts----------------> read ts

1. When data is fetched, ```CONCURRENT_PROMISES_TS``` is set
2. ```CONCURRENT_PROMISES_TS``` will be cleared in 2s (dedupingInterval default)
3. If user mutates before ```CONCURRENT_PROMISES_TS```  is cleared and the update function resolves after  ```CONCURRENT_PROMISES_TS```  is cleared 
4. https://github.com/vercel/swr/blob/eb7fa36920fa5eaca5d68a61ece6eabe54c64907/src/use-swr.ts#L143-L152
    The mutation will be abort since ```CONCURRENT_PROMISES_TS``` is now undefined
