### ISSUE TITLE
useSWR fails with {onError: undefined} in unsuccessful case

### ISSUE THREAD

**Issue by demidyuk** [vercel/swr#1071]
# Bug report

## Description / Observed Behavior

I faced with useSWR failure in an error case with  providing the `onError` prop as undefined. After unsuccessful fetching from the endpoint useSWR throws an internal error.

## Expected Behavior

Providing `{onError: undefined}` should not affect anything, as it does without the `onError` property.

## Repro Steps / Code Example

Example of failure: [CodeSandbox link](https://codesandbox.io/s/relaxed-matsumoto-eudv1).
To see an error inside an iframe you may need refresh app. Without `onError` it should work as expected.

## Additional Context

SWR version: ^0.5.4

**Comment by huozhi** [comment]
Could you change the `undefined` case to an empty function `onError() {}` as we'd like to specify the callback types as function, to skip from various invalid user input types like `null` / number / object etc.
