### ISSUE TITLE
Add revalidate() to the api return values

### ISSUE THREAD

**Issue by coldhu** [vercel/swr#1078]
const { data, error, isValidating, mutate } = useSWR(key, fetcher, options)

Also **_revalidate_** should be added to "Return Values", or is it not recommended to use?

**Comment by shuding** [comment]
`revalidate` was deprecated and it’s not recommended anymore. You can call `mutate()` without any arguments to do the exact same thing.

If you are seeing that API mentioned somewhere could you please let me know?
