### ISSUE TITLE
Manually triggering new requests

### ISSUE THREAD

**Issue by vinay-deshmukh** [vercel/swr#1082]
In my application, I don't want `useSWR` hook to automatically call the fetcher function. I want to call it in one of my event handlers.

## What did you try?

- I tried setting `refetchOnMount` as false, but then on the next render, the fetch request happened anyway.

- Tried making `isPaused()` return true always, but this means `mutate()` calls also don't work.

##Expected behaviour

Flag/boolean config that disables "auto fetching", and only fetches when user calls `mutate()`.

**Comment by promer94** [comment]
currently you could use ```isPaused``` to build a customized hook.

```js
function useControlledSWR(key, fetcher) {
  const [control, setControl] = React.useState(true);
  const swr = useSWR(key, fetcher, {
    isPaused: () => {
      return control;
    }
  });
  const { mutate } = swr;
  const start = () => {
    setControl(false);
  };

  const pause = () => {
    setControl(true);
  };

  React.useEffect(() => {
    if (!control) {
      mutate();
      /* auto pause
      .then((v) => pause());
      */
    }
  }, [control, mutate]);

  return [swr, { status: control, start, pause }];
}
```

FYI: https://codesandbox.io/s/control-swr-vf9gu?file=/src/App.js

**Comment by vinay-deshmukh** [comment]
I actually don't want to start/stop the hook. I just need a stable mutate callback that will retrigger the fetching.

I tried showing a loading message using your hook, but it seems your hook is eternally in a loading state for some reason, until I call button.

![image](https://user-images.githubusercontent.com/32487576/112789853-a9dad480-907b-11eb-8c62-2105c358affd.png)
I added that line and your hook is eternally in a loading state.

https://codesandbox.io/s/useswr-try-lezg7

This sandbox shows what I want to achieve.

It will work once your comment `isPaused()` config option. Once that is done, it will only run if you call mutate, but if the component rerenders, the fetcher fucntion gets run which is undesirable.

**Comment by shuding** [comment]
FWIW – You can use `useSWR(enabled ? 'key' : null)` to enable/disable the hook. But #1450 will give you the ability to manually trigger a fetch. Going to change the issue description for accuracy.

**Comment by shuding** [comment]
#1450 is merged, and we can close this issue now :)

**Comment by anthonyalayo** [comment]
@shuding I feel like `useSWRMutation` doesn't solve the use case.

`useSWRMutation` is intended to mutate remote state, and as such it provides no flexibility on the caching options. The scenario here is to have a trigger for `useSWR` so that we can trigger it inside event handlers (ie. useCallback).

I'll give my example that landed me on this page. I am attempting to make a request on click, and then have that data persist for a specified `dedupingInterval`. Using `useSWR` and `mutate()` doesn't work on its own because I still need to give a condition to `useSWR` to tell it _when_ its okay to run. This ends up reducing to yet another state variable, `iClickedAButton`. I would need to toggle it true in `onClick` and then toggle it false afterwards. This seems overly complicated. Am I missing another better way?

**Comment by damianobarbati** [comment]
@anthonyalayo did you find any solution for this?

**Comment by anthonyalayo** [comment]
@damianobarbati I didn't unfortunately

**Comment by ndianabasi** [comment]
I think what the OP is referring to is something like this: https://github.com/simoneb/axios-hooks#manual-requests

It would be great if it is supported by SWR.

**Comment by QingjiaTsang** [comment]
```
import useSWR from 'swr';

function MyComponent() {
  const { data, mutate } = useSWR('/api/data', fetcher, { revalidateOnMount: false, revalidateOnFocus: false });

  const fetchData = () => {
    mutate(); // Manually trigger data fetch
  };

  return (
    <div>
      <button onClick={fetchData}>Fetch Data</button>
      {data ? (
        // Render your data
      ) : (
        // Render loading or placeholder
      )}
    </div>
  );
}
```
You can config your useSwr like above and trigger the fetching data function. It'll promise data fetching only when you need it.

**Comment by QingjiaTsang** [comment]
> ```
> import useSWR from 'swr';
> 
> function MyComponent() {
>   const { data, mutate } = useSWR('/api/data', fetcher, { revalidateOnMount: false, revalidateOnFocus: false });
> 
>   const fetchData = () => {
>     mutate(); // Manually trigger data fetch
>   };
> 
>   return (
>     <div>
>       <button onClick={fetchData}>Fetch Data</button>
>       {data ? (
>         // Render your data
>       ) : (
>         // Render loading or placeholder
>       )}
>     </div>
>   );
> }
> ```
> 
> You can config your useSwr like above and trigger the fetching data function. It'll promise data fetching only when you need it.

update: for now you can use [useSWRMutation](https://swr.vercel.app/docs/mutation#useswrmutation) to achieve that

**Comment by guotingchao** [comment]
> > ```
> > import useSWR from 'swr';
> > 
> > function MyComponent() {
> >   const { data, mutate } = useSWR('/api/data', fetcher, { revalidateOnMount: false, revalidateOnFocus: false });
> > 
> >   const fetchData = () => {
> >     mutate(); // Manually trigger data fetch
> >   };
> > 
> >   return (
> >     <div>
> >       <button onClick={fetchData}>Fetch Data</button>
> >       {data ? (
> >         // Render your data
> >       ) : (
> >         // Render loading or placeholder
> >       )}
> >     </div>
> >   );
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can config your useSwr like above and trigger the fetching data function. It'll promise data fetching only when you need it.
> 
> update: for now you can use [useSWRMutation](https://swr.vercel.app/docs/mutation#useswrmutation) to achieve that

It seems that if you use 'useSWRMuntation', 'dedupingInterval' won't take effect, you need to handle it manually.
