### ISSUE TITLE
useSWR with Suspense remains in loading state when response data is identical

### ISSUE THREAD

**Issue by damusnet** [vercel/swr#1083]
# Bug report

## Description / Observed Behavior

When using suspense mode, if two API calls with different urls return the same data, the component remains in a loading state.

## Expected Behavior

The component should update to reflect the new data, even if it's identical to the previous data.

## Repro Steps / Code Example

https://codesandbox.io/s/recursing-williams-lsh4m?file=/pages/index.js

Click the button. It changes the url, but the data returned is always the same, since it's a static function.
Component remains in loading state, instead of displaying the new url.
See also the incrementing counter in the console for the new url, indicating that `useSWR` keeps re-fetching the data.

https://user-images.githubusercontent.com/433409/112905358-7e6ddf00-90a7-11eb-81ab-3730b19d81da.mp4

You can toggle lines 29 and 34 and see that a different API response triggers a render, whereas the same response remains in loading.

You can toggle line 22 and see that without suspense things work fine, but as soon as suspense is on, it keeps loading forever when the response is the same.

## Additional Context

I was under the impression that this worked before v0.5 but changing the version on CodeSanbox yields the same result, so I'm not so sure anymore

**Comment by promer94** [comment]
Thanks for your detailed repro. 
This bug is a duplicate of #1056. 
It has been fixed in #1058

**Comment by damusnet** [comment]
Oh, great, thanks!
Sorry for the duplicate, I only looked through the open issues 😅
