### ISSUE TITLE
Resource preloaded was not used by SWR

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/swr#1095]
# Bug report

## Description / Observed Behavior

When using `<link rel='preload' />` prefetching, the following warning occurs in Mozilla Firefox 87.0 (on Pop_OS! 20.04):

> The resource at “http://localhost:3000/api/account” preloaded with link preload was not used within a few seconds.
> Make sure all attributes of the preload tag are set correctly.

## Expected Behavior

SWR should use the prefetched data and that warning should not occur. I'm guessing that the reason why the data wasn't used by SWR is because I'm using `axios` (which, in turn, uses `XMLHttpRequest`) in my SWR fetcher function (instead of using the browser built-in `fetch` function). If this is the case, you should definitely add it to the documentation.

## Repro Steps / Code Example

I followed [the docs on preloading data](https://swr.vercel.app/docs/prefetching#top-level-page-data) and added the following:

```tsx
<Head>
  <link rel='preload' href='/api/account' as='fetch' />
</Head>
```

I then use SWR to fetch that data client-side (using `axios` which uses `XMLHttpRequest` under the hood):

```typescript
const { data } = useSWR<UserJSON>('/api/account', fetcher);
```

That `fetcher` function is defined as the following:

```typescript
export async function fetcher<T, D = T>(
  url: string,
  method: 'get' | 'put' | 'post' | 'patch' | 'delete' = 'get',
  data?: D
): Promise<T> {
  const headers: Record<string, string> = {};
  if (typeof data === 'string') headers['Content-Type'] = 'text/plain';
  const [err, res] = await to<AxiosResponse<T>, AxiosError<APIErrorJSON>>(
    axios({ method, url, data, headers })
  );
  if (err && err.response) {
    const msg = `API (${url}) responded with error: ${err.response.data.message}`;
    throw new APIError(msg, err.response.status);
  } else if (err && err.request) {
    throw new APIError(`API (${url}) did not respond.`);
  } else if (err) {
    throw new APIError(`${err.name} calling API (${url}): ${err.message}`);
  }
  return (res as AxiosResponse<T>).data;
}
```

**Comment by nicholaschiang** [comment]
@shuding Is this the case then? Should I not include the `<link rel='preload' as='fetch' />` then? From [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#what_types_of_content_can_be_preloaded), it seems that such tags would also be used for `XMLHttpRequests` as well as the `fetch()` API so this should work:

> Resource to be accessed by a fetch or **XHR request**, such as an ArrayBuffer or JSON file.

**Comment by nicholaschiang** [comment]
@shuding I just switched over to using the native `fetch` API like so:

```typescript
import { mutate } from 'swr';
import to from 'await-to-js';

import { APIError, APIErrorJSON } from 'lib/model/error';

export async function fetcher<T, D = T>(
  url: string,
  method: 'get' | 'put' | 'post' | 'patch' | 'delete' = 'get',
  data?: D
): Promise<T> {
  const headers: Record<string, string> = {};
  const body = JSON.stringify(data);
  const [err, res] = await to<Response>(fetch(url, { headers, method, body }));
  if (res && !res.ok) {
    const { message } = (await res.json()) as APIErrorJSON;
    const msg = `API (${url}) responded with error: ${message}`;
    throw new APIError(msg, res.status);
  } else if (err) {
    throw new APIError(`${err.name} calling API (${url}): ${err.message}`);
  } else if (!res) {
    throw new APIError(`No response from API (${url})`);
  }
  return res.json() as Promise<T>;
}
```

And Firefox still gives me this warning that the resource preloaded wasn't used within a few seconds. Does this work on Firefox?

**Comment by koba04** [comment]
@nicholaschiang 
The example in the documentation has a `crossorigin` attribute, but your code doesn't.

```
<link rel="preload" href="/api/data" as="fetch" crossorigin="anonymous">
```

https://swr.vercel.app/docs/prefetching#top-level-page-data

I think the `crossorigin` attribute is necessary to preload a fetch request.

> When preloading resources that are fetched with CORS enabled (e.g. fetch(), XMLHttpRequest or fonts), special care needs to be taken to setting the crossorigin attribute on your <link> element. The attribute needs to be set to match the resource's CORS and credentials mode, even when the fetch is not cross-origin.

https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#cors-enabled_fetches

**Comment by nicholaschiang** [comment]
@koba04 I've updated my code to set the `crossOrigin` attribute:
```tsx
          <link
            rel='preload'
            href='/api/subscriptions'
            crossOrigin='anonymous'
            type='application/json'
            as='fetch'
          />
```
And it still gives me the same warning on Firefox:
> The resource at “http://localhost:3000/api/subscriptions” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.

**Comment by nicholaschiang** [comment]
@koba04 turns out the reason why my preloaded requests weren't being used is because I'm specifying custom headers when SWR makes the request:

```typescript
const headers = { 'Content-Type': 'application/json', Accept: 'application/json' };
await fetch('/api/account', { headers, method: 'get' });
```
That makes the request made by SWR different than the request preloaded by the browser (because the browser doesn't specify those same `Content-Type` and `Accept` headers that I did manually in my JS). This prevents SWR from reusing the preloaded fetch. **You should definitely add this important caveat about preloading to [SWR's documentation](https://swr.vercel.app/docs/prefetching#top-level-page-data).**

**Comment by shuding** [comment]
We now have a preload API in SWR that covers this case better, check out the release: https://github.com/vercel/swr/releases/tag/2.0.0-beta.4

It will be documented with the upcoming 2.0 stable release.
