### ISSUE TITLE
Use slow connection mode when `navigator.connection.saveData` is enabled

### ISSUE THREAD

**Issue by shuding** [vercel/swr#1122]
We are already considering cases like 2g network here: https://github.com/vercel/swr/blob/69ec9df931e4ca84b70104f414ccba6c2a82ec20/src/config.ts#L45 just need to consider the data saving mode to the same place.

Ref: https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/save-data

**Comment by Tak-Iwamoto** [comment]
@shuding 
Can I try this?

**Comment by shuding** [comment]
@Tak-Iwamoto yeah feel free to take it.
