### ISSUE TITLE
Error on example "autocomplete-suggestions"

### ISSUE THREAD

**Issue by ChangJoo-Park** [vercel/swr#1129]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

Example autocomplete-suggestions not working on my environment. it has problem with useLayoutEffect.
I think it cause by @reach/combobox. but I did not find why it is.

I made [sandbox](https://codesandbox.io/s/exciting-haze-ej4vd) for this issue. I works well. 

```log
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
    in ForwardRef(ComboboxInput) (at pages/index.js:28)
    in div
    in Context.Provider
    in ForwardRef(Combobox) (at pages/index.js:27)
    in div (at pages/index.js:25)
    in Unknown
    in App
    in Unknown
    in Context.Provider
    in Context.Provider
    in Context.Provider
    in AppContainer
```

## Expected Behavior

How did you expect SWR to behave here?

## Repro Steps / Code Example

https://codesandbox.io/s/exciting-haze-ej4vd

## Additional Context

SWR version : 0.5.4

**Comment by koba04** [comment]
@ChangJoo-Park I've confirmed this issue, so I've fixed it as #1183
