### ISSUE TITLE
Clear cache or mutate all keys react native?

### ISSUE THREAD

**Issue by alimertcakar** [vercel/swr#1151]
Fresh install with swr and expo: [Repo](https://github.com/alimertcakar/useSwrBugReport1)

I open the app see the data:
![image](https://user-images.githubusercontent.com/56369392/116883336-2e49e580-ac2e-11eb-9b2b-3ee7d52d80c7.png)

Then I go to mockapi and add some more mock data:
![image](https://user-images.githubusercontent.com/56369392/116883441-47eb2d00-ac2e-11eb-975e-615e8ceb2da4.png)

I press logout (which runs cache.clear()) on the app, data is not refetched.

When I reload the app: (new data is there)
![image](https://user-images.githubusercontent.com/56369392/116883528-618c7480-ac2e-11eb-93eb-437e0f07131f.png)

In the production app, my problem is when you re-login with another user, swr still returns the old users data for a while.
I need to reset the cache without mutating every key one by one.

Maybe this is a misuse of cache.clear. I would be glad to be enlightened

**Comment by shuding** [comment]
With our new Cache API, you should be able to provide your own cache like this https://github.com/vercel/swr/blob/master/test/use-swr-cache.test.tsx#L47-L53

And you can manually clear the cache. It's not documented yet but you can upgrade to the latest `swr@beta` to try it out!

**Comment by sharanrprasad** [comment]
@shuding I tried with the beta version on React Native as well, still the cache persists. We need a way to clear initialData and the cache so that the when the user logs out we can start fresh again. 

Currently we have disabled validateOnMount option, to avoid unnecessary reloads between screen transitions.

**Comment by huozhi** [comment]
@sharanrprasad I tried your codesandbox and did a little change for swr@beta integration. the new mutation works well. let us know if you have further questions

```diff
- import useSWR, { SWRConfig, mutate, cache } from "swr";
+ import useSWR, { SWRConfig, createCache } from "swr";

const customCache = new Map();
+ const { cache, mutate: mutateCache } = createCache(customCache);

let sleep = (time) =>
  new Promise((res) => {
    setTimeout(res, time);
  });

let fetchPost = async () => {
  await sleep(3000);
  return fetch(
    "https://jsonplaceholder.typicode.com/todos/1"
  ).then((response) => response.json());
};
let usePost = () => {
  return useSWR("/post", fetchPost);
};
let Comp1 = () => {
  let { data: post, isValidating } = usePost();
  console.log({ post, isValidating });

  return <div>{post ? post.title : "fetching"}</div>;
};

export default function App() {
  let [show, showSet] = useState(false);

  return (
    <SWRConfig
      value={{
+        cache,
        revalidateOnFocus: false,
        dedupingInterval: 1000
      }}
    >
      <div className="App">
        <button onClick={() => showSet(!show)}>toggle</button>
        {show && <Comp1 />}
        <button
          onClick={() => {
-            // cache.clear();
+            mutateCache("/post", null, true);
          }}
        >
          clear cache
        </button>
      </div>
    </SWRConfig>
  );
}
```

the mutate

**Comment by alimertcakar** [comment]
> @sharanrprasad I tried your codesandbox and did a little change for swr@beta integration. the new mutation works well. let us know if you have further questions
> 
> ```diff
> - import useSWR, { SWRConfig, mutate, cache } from "swr";
> + import useSWR, { SWRConfig, createCache } from "swr";
> 
> const customCache = new Map();
> + const { cache, mutate: mutateCache } = createCache(customCache);
> 
> let sleep = (time) =>
>   new Promise((res) => {
>     setTimeout(res, time);
>   });
> 
> let fetchPost = async () => {
>   await sleep(3000);
>   return fetch(
>     "https://jsonplaceholder.typicode.com/todos/1"
>   ).then((response) => response.json());
> };
> let usePost = () => {
>   return useSWR("/post", fetchPost);
> };
> let Comp1 = () => {
>   let { data: post, isValidating } = usePost();
>   console.log({ post, isValidating });
> 
>   return <div>{post ? post.title : "fetching"}</div>;
> };
> 
> export default function App() {
>   let [show, showSet] = useState(false);
> 
>   return (
>     <SWRConfig
>       value={{
> +        cache,
>         revalidateOnFocus: false,
>         dedupingInterval: 1000
>       }}
>     >
>       <div className="App">
>         <button onClick={() => showSet(!show)}>toggle</button>
>         {show && <Comp1 />}
>         <button
>           onClick={() => {
> -            // cache.clear();
> +            mutateCache("/post", null, true);
>           }}
>         >
>           clear cache
>         </button>
>       </div>
>     </SWRConfig>
>   );
> }
> ```
> 
> the mutate

This mutates only "/post", how would you mutate keys?

**Comment by huozhi** [comment]
@alimertcakar checkout the [cache#mutate-multiple-keys](https://swr.vercel.app/advanced/cache#mutate-multiple-keys) section. With the new cache API you can customized those logic into regex or glob pattern gracefully
