### ISSUE TITLE
Bug: onErrorRetry is not de-duped

### ISSUE THREAD

**Issue by mark-dr** [vercel/swr#1152]
# Bug report

## Description / Observed Behavior

When I have multiple mounted components using `useSWR` over the same key, and the fetcher throws an error, `onErrorRetry` is called once per component, each starting a separate retry loop. This is true whether using a custom `onErrorRetry` or the default one.

Consequence: If the `onErrorRetry` waits for a non-deterministic time before triggering revalidation (as the default handler does), the separate retry loops get out of sync and the fetcher is called too often.

## Expected Behavior

There should be one shared retry loop. `onErrorRetry` should only be called once per failure per key.

## Repro Steps / Code Example

Small reproduction case:

https://codesandbox.io/s/zealous-colden-hxm40

## Additional Context

SWR version: First seen in `0.3.6`, also confirmed (and demonstrated in repro above) in `0.5.6`.

**Comment by hgupta2363** [comment]
here in the codesandbox link you haven't mentioned stopping condition of retry loop so it is not even rendering second component

**Comment by mark-dr** [comment]
I'm not sure what you mean. It's absolutely rendering the second component, `swr` can't prevent that.

**Comment by shuding** [comment]
This issue was fixed with #1522 (forgot to link & close here), thanks for the reproduction!
