### ISSUE TITLE
useSwrInfinite with react-infinite-scroll-component | after changing fetch key -> current index does not reset

### ISSUE THREAD

**Issue by talkl** [vercel/swr#1168]
# Bug report

userSwrInfinite + react-infinite-scroll-component bug

## Description / Observed Behavior

I have react-infinite-scroll-component with useSwrInfinite integration. I also have an input to search by name the api. if i'm beyond page 1 and do a search (thus changing the useSwrInfinite key), useSwrInifinite will start searching serially all pages until the current page i am 1...N.
It's interesting to observe that if my scroll position is viewing only the first page, then only the first page will be fetched not 1...N

## Expected Behavior

I expect that on change of key in useSwrInfinite get key function will reset the index to 0 and only the first page will be fetched.

## Repro Steps / Code Example

https://codesandbox.io/s/react-infiinite-scroll-component-with-userswrinfinite-bug-reproduce-ch7hi

Reproduce steps:

1. click the repositories link to go to the page where the bug happens
2. if you need to refresh please refresh the whole page (because of detecting mobile css)
3. scroll a few pages down (see that react-infinite-scroll-component fetches the pages)
4. now search for a name in the input field.
5. you can see useSwrInfinite serially fetching 1...N (pages) one by one.

Expected Behaviour steps:

1. instead of scrolling -> search after the first load of the page
2. you can see now useSwrInfinite only fetches the first (1) page.

another way to see expected behaviour:
1. scroll a few pages
2. pages are fetched normally
3. now scroll back to first (1) page
4. now search for a term
5. see that useSwrInfinite only fetches the first page

SWR version
0.4.0

Thank you guys I

https://user-images.githubusercontent.com/9368630/118966849-b04a4600-b972-11eb-8871-7cf439284d34.mov

 appreciate it :)

**Comment by talkl** [comment]
@nandorojo can you help?

**Comment by nandorojo** [comment]
My guess is it defaults to just refetching the latest page. Not sure though, since I don't maintain swr.

You could try toggling `revalidateAll`, although I'm not totally sure what your expected behavior is.

**Comment by talkl** [comment]
> My guess is it defaults to just refetching the latest page. Not sure though, since I don't maintain swr.
> 
> You could try toggling `revalidateAll`, although I'm not totally sure what your expected behavior is.

@nandorojo basically I want the option to reset the page. If the key is changed because of propane it is obviousness that I want to always start from page 1 and not fetch all pages up until the page I was at for the precious key

**Comment by nandorojo** [comment]
What if you `setSize(1)`

**Comment by talkl** [comment]
> What if you `setSize(1)`

@nandorojo doesn't work. niether do revalidateAll

**Comment by nandorojo** [comment]
🤷‍♂️

**Comment by promer94** [comment]
The actual problem in this example is that the next callback of react-infinite-scroll-component would be called multiply times after changing the input (because the scroll position does not reset to top) 

**useSWRInfinite does reset the current index by default**

According to the implementation https://github.com/ankeetmaini/react-infinite-scroll-component/blob/d5b4e5250669022db5217763afd22fb3995a505a/src/index.tsx#L88-L95

I try to use the initialScrollY and key to reset the scroll position but it does not work.

```js
<InfiniteScroll
      key={repo}
      initialScrollY={0}
      dataLength={repos.length}
      next={() => {
        console.log('next')
        setSize(size + 1)
      }}
      hasMore={!hasReachedEnd}
      loader={
        !isLoadingInitialData ? (
          <div className={Styles.loaderContainer}>
            <Spin />
          </div>
        ) : null
      }
      endMessage={
        repos.length ? (
          <p className={Styles.endMessage}>
            <b>Yay! You have seen it all</b>
          </p>
        ) : null
      }
    >
```

I have a temporary workaround for this example by using the window.scrollTo 

```js
React.useEffect(() => {
    window.scrollTo(0, 0);
  }, [repo]);
```
FYI: https://codesandbox.io/s/using-window-scrollto-gv5pu

**Comment by talkl** [comment]
@promer94 You rock!! it works

**Comment by supuwoerc** [comment]
useInfiniteQuery of react-query has the same problem, and manually setting the scroll position to 0 doesn't work...
