### ISSUE TITLE
Calling useSWR immediately after mutate returns undefined and does not rerender component

### ISSUE THREAD

**Issue by mittalsuraj18** [vercel/swr#1188]
# Bug report

## Description / Observed Behavior

1. Call a useSWR immediately method with the same key as mutate.
2. Component should re render due to new data.

## Expected Behavior

useSWR data should have a value

## Repro Steps / Code Example

```
import useSWR, { mutate, cache } from "swr";
import axios from "axios";

const apiCall = async () => {
    const {data} = await axios.get("https://httpbin.org/get");
    return data
}

const key = ["myRandomKey"]
mutate(key, () => apiCall());
const {data, error} = useSWR(key, () => apiCall());
console.log(data);

```

**Comment by promer94** [comment]
I think this problem might be a duplicate of #1074 which got fixed in #1075 
Could you try the latest beta version of SWR ?

**Comment by mittalsuraj18** [comment]
@promer94 I updated to beta version. But it broke compatibility as the cache object was not accessible in the code.

For context, the reason i try to access cache object is for prefetching.

Example: if i hover over an element, i perform prefetch using mutate. But if i have the data and perform hover again, the data should not be fetched again.

Is there any way to perform this check on mutate object during prefetching.

**Comment by promer94** [comment]
It might be helpful that you could access cache data by providing a update function to the mutate
```js
mutate("key", (data) => data ? data : axiosApiCall())
```
FYI: https://codesandbox.io/s/simple-prefetch-yp9kz

**Comment by mittalsuraj18** [comment]
Thanks a lot @promer94 
This fixed my issue.
I can confirm that this issue is resolved in the beta.

Closing this issue.
Thanks.
