### ISSUE TITLE
Confusing explanation of how errors work when data is returned from the mutate method using function

### ISSUE THREAD

**Issue by conquestmakes** [vercel/swr#1214]
# Bug report

## Description / Observed Behavior

[The explanation](https://swr.vercel.app/docs/mutation#returned-data-from-mutate) of how errors work/are thrown when returning data from the mutate method and using a function is confusing. It could potentially be undetstood as errors are always thrown.

## Expected Behavior

I am assuming that the errors mentioned are thrown by the provided method, so it could be changed to something like:
`The function provided will return an updated document to let mutate update the corresponding cache value. If there is an error thown while executing the provided function, the error will be returned so it can be handled appropriately.`

## Repro Steps / Code Example

[Confusing sentence in documentation here](https://swr.vercel.app/docs/mutation#returned-data-from-mutate) `It could throw an error somehow, every time when you call it.`

**Comment by huozhi** [comment]
Closed via https://github.com/vercel/swr-site/pull/105
