### ISSUE TITLE
Conditional Fetching throws "TypeError: Cannot read property 'protocol' of null" when multiple arguments

### ISSUE THREAD

**Issue by vishnuvchandar** [vercel/swr#1223]
# Bug report
when using conditional fetching (with axios) multiple arguments, swr throws an error. Due to this, unable to differentiate with other valid errors

## Description / Observed Behavior
"TypeError: Cannot read property 'protocol' of null" when using below code 

`requestInfo=[url,data]  /* here url is null and a non null data*/

fetcher = (url,data) => axios.post(url, JSON.parse(data)).then(res=>res.data)
const { data, error}  = useSWR(requestInfo, fetcher, {revalidateOnFocus: false})"`

What kind of issues did you encounter with SWR?

SWR invokes an axios call even when the url is null and a valid non null Data
_[null, "{\"startDate\":\"2021-06-14T08:03:57.773Z\",\"endDate\":\"2021-06-21T08:03:57.773Z\"}"]_

## Expected Behavior

It should cancel the request like it works when passing url alone

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version. 
"swr": "0.5.6"

**Comment by shuding** [comment]
It seems you are running `JSON.parse` over an object (`data`), which is not needed.

**Comment by vishnuvchandar** [comment]
@shuding I have used stringify. If you look carefully that my fetcher parsing it. SWR uses stringify and the axios fetcher parses it before invoking the rest call.

**Comment by shuding** [comment]
I see. To conditionally skip a request, you should pass null as the key, not just the URL in your case.

```
useSWR(skip ? null : [url, data], fetcher)
```
