### ISSUE TITLE
React Native crash with swr@1.0.0-beta.7

### ISSUE THREAD

**Issue by beetlebum** [vercel/swr#1237]
# Bug report

## Description / Observed Behavior

There is a crash with swr@1.0.0-beta.7 on React Native 0.64.2, just by importing the module:

```
Requiring module "node_modules/swr/dist/index.esm.js", which threw an exception: TypeError: Cannot read property 'bind' of undefined
```

which seems to point to `window.addEventListener.bind(window)`

**Comment by javascripter** [comment]
I submitted a PR that fixes this issue:
https://github.com/vercel/swr/pull/1234

**Comment by beetlebum** [comment]
> I've submitted a PR that fixes this issue:
> #1234

thank you, I'll close this issue.
