### ISSUE TITLE
isValidating is undefined when changing key from null to a string

### ISSUE THREAD

**Issue by jjerror-sequoia** [vercel/swr#1265]
# Bug report

## Description / Observed Behavior

When changing key from `null` to a valid string value, there is an extra rerender where `isValidating` is undefine.

## Expected Behavior

Once the key is set to non-null value. it should return `isValidating` to be `true`.

## Repro Steps / Code Example

Code example: https://codesandbox.io/s/undefined-isvalidating-0jkpw

## Additional Context

SWR version. 0.5.6

**Comment by huozhi** [comment]
Should be already fixed in `swr@beta`, could you try to upgrade and check it again?
