### ISSUE TITLE
useSWRInfinite: setSize stops working when getKey fn is updated

### ISSUE THREAD

**Issue by harshtyagi** [vercel/swr#1269]
# Bug report

## Description / Observed Behavior

After updating the getKey fn, useSWRInfinite's setSize stops updating the size.
Issue occurs for swr 0.5.6, works as expected on 0.5.0

## Expected Behavior

Expected to work like version 0.5.0 where setSize changes the page after getKey fn is updated.

## Repro Steps / Code Example

Code example: https://codesandbox.io/s/recursing-dhawan-ucefb

1. Click on "Next Page" button to see the value of page increment 
2. Type anything in the "change getKey" text box and then click on "Next Page"
3. Page value will increment in swr 0.5.0 but not in 0.5.6

## Additional Context

SWR version. 0.5.6 & 0.5.0

**Comment by promer94** [comment]
Hi, Thank for your codesandbox !

However, this is not a bug of useSWRInfinite

The reason for the current behavior is because 
```jsx
const Paginate = useMemo(
    () => ({ children }) => {
      return (
        <>
          <FormGroup>
            <InputGroup
              type="search"
              placeholder={"change getKey"}
              onChange={(e) => debouncedSave(e.target.value)}
            />
          </FormGroup>
          <div>{children}</div>
          <button onClick={() => setPage((p) => p + 1)}> Next Page</button>
        </>
      );
    },
    // setPage will change every time you input new word 
    // you should include setPage in the array
    []
  );
```

**Comment by harshtyagi** [comment]
@promer94 Thanks a lot. This fixed my issue.
