### ISSUE TITLE
How can I cache the InitialData of useSWRInfinite?

### ISSUE THREAD

**Issue by johnvonneumann7** [vercel/swr#1287]
As the title says, you need to cache the InitialData with useSWRInfinite.
Every time I load a page after the first page, the InitialData is lost.
What should I do?

## Repro Steps / Code Example

```javascript
const { data, error, setSize, size } = useSWRInfinite(
    (pageIndex, previousPageData) => {
      if (previousPageData && !previousPageData.next) return null;
      return previousPageData?.next ?? initialData.next;
    },
    fetcher,
    { initialData: [initialData] }
  );
```

SWR version: 0.5.6

**Comment by johnvonneumann7** [comment]
It turns out that this just means that InitialData is not cached, but is it impossible to cache InitialData?

**Comment by shuding** [comment]
Please check the new cache API, you should be able to provide a prefilled cache with it: https://swr.vercel.app/docs/advanced/cache.
