### ISSUE TITLE
Problem calling mutate twice in a row, second call ignored

### ISSUE THREAD

**Issue by pkellner** [vercel/swr#1302]
# Bug report

## Expected Behavior

display should show 11,12,13,14,15

## Code

I get that if I push the two values in one mutate call that I will get both values, but I need to programmatically update the data array multiple times in the same event.  The code below seems to ignore the second mutate.

https://codesandbox.io/s/billowing-shadow-1wx6f?file=/src/App.js

```
import useSWR from 'swr';

function Profile() {
  const { data, mutate } = useSWR(
    '/api/user',
    async function fetchNoteAttributes() {
      await new Promise((resolve) => setTimeout(resolve, 1000));
      return [];
    },
    {
      initialData: [11, 12, 13],
    },
  );

  console.log(data);

  function clickNow() {
    mutate(() => {
      return [...data, Math.max(...data) + 1];
    });

    mutate(() => {
      return [...data, Math.max(...data) + 1];
    });
  }

  return (
    <div>
      <h1>data: {JSON.stringify(data)}</h1>
      <button onClick={clickNow}>Add Two</button>
    </div>
  );
}

export default Profile;
```

**Comment by chilingling** [comment]
you should use the third params `false`, so it will not revalidation and use return data directly
```javascript
mutate(() => {
      return [...data, Math.max(...data) + 1];
}, false);
```

**Comment by pkellner** [comment]
Not following how I'd do that.

**Comment by shuding** [comment]
This is not a bug if I understand your code correctly. You’re mutating with the **same** data twice here:

```js
    mutate(() => {
      return [...data, Math.max(...data) + 1];
    });

    mutate(() => {
      return [...data, Math.max(...data) + 1];
    });
```

Please take a look at Mutate Based on Current Data: https://swr.vercel.app/docs/mutation#mutate-based-on-current-data.

**Comment by chilingling** [comment]
@pkellner sorry i misunderstand what you want to do firtsly, as shuding say, you can't mutating same data twice,swr will deduplication the second mutation automaticly, you can try a hack way like this
```javascript
function clickNow() {
    mutate(() => {
      return [...data, Math.max(...data) + 1];
    }, false);
    setShouldAddSec(true);
  }
  const [shouldAddSec, setShouldAddSec] = useState(false);
  useEffect(() => {
    if(shouldAddSec) {
      mutate(() => {
        return [...data, Math.max(...data) + 1];
      }, false);
      setShouldAddSec(false);
    }
  }, [shouldAddSec, setShouldAddSec, mutate, data])
```
https://codesandbox.io/s/gifted-davinci-lo93i?file=/src/App.js

**Comment by pkellner** [comment]
@shuding I now understand that I'm mutating the same data twice.  The problem I'm trying to solve is that I am calling mutate from a far away method twice (creating two records where I can't easily update the method to mutate both at the same time).  With useState, I can do the following and it works as expected.  Is there anything similar for SWR?

```
const [data, setData] = useState([]);

setData(function (oriState) {
    return oriState.filter(function (rec) {
      rec.push ( [...rec], Math.max(...oriState) + 1] )
    });
  });

```

**Comment by shuding** [comment]
@pkellner You can do the same with SWR, please read the docs: [swr.vercel.app/docs/mutation#mutate-based-on-current-data](https://swr.vercel.app/docs/mutation#mutate-based-on-current-data)

> With mutate, you can pass an async function which will receive the current cached value, if any, and returns an updated document.

So you can use it the same way too:

```js
mutate(data => {
  return [...data, Math.max(...data) + 1];
});
```

I updated your sandbox: https://codesandbox.io/s/mutable-wave-in167.

**Comment by pkellner** [comment]
Thanks! I thought I tried that unsuccessfully but apparently not. Appreciate the help.
