### ISSUE TITLE
'isValidating' becomes an empty string when 'key' changes from null

### ISSUE THREAD

**Issue by yakovenkomax** [vercel/swr#1314]
# Bug report

## Description / Observed Behavior

When a `key` switches from null to a string, `isValidating` becomes an empty string for a brief moment.

<img width="410" alt="Screenshot 2021-07-30 at 16 50 04" src="https://user-images.githubusercontent.com/5172360/127671392-a42e830e-242b-42d9-a42f-43965deda83d.png">

## Expected Behavior

`isValidating` is expected to be boolean at all times.

## Code Example

https://codesandbox.io/s/isvalidating-empty-string-x7u7h?file=/src/App.js

## Additional Context

SWR version 0.5.6.

**Comment by shuding** [comment]
Thanks for reporting! This bug has been fixed in `swr@beta`, see #1195.
