### ISSUE TITLE
SWRConfig cannot be changed after first definition

### ISSUE THREAD

**Issue by PhiloNL** [vercel/swr#1333]
# Bug report
I've set my SWRConfig to refresh every 5 seconds and I want to toggle this behavior so a user can turn off this option.

```javascript
const [refreshInterval, setRefreshInterval] = useState(5000);

function disableRefresh() {
    setRefreshInterval(0);
}

<SWRConfig value={{
    refreshInterval: refreshInterval
}}>
    <button onClick={disableRefresh}>Disable refresh interval</button>

    Interval is set to: {refreshInterval}

    <Component {...pageProps} />
</SWRConfig>
```

## Description / Observed Behavior
When I use `setRefreshInterval` to change the interval the change is reflected in the UI, e.g. "Interval is set to: 0". The actual SWR config hasn't changed however and requests are still made every 5 seconds.

What kind of issues did you encounter with SWR?
SWR doesn't seem to pick up any changes made to the global configuration after the initial initialization. 

## Expected Behavior
SWR should respect changes made to dynamic settings.

## Repro Steps / Code Example
See your console for XHR requests, when you click the button to disable the interval you will see the requests continue every 5 seconds.
https://codesandbox.io/s/hardcore-hodgkin-3c2vx?file=/pages/index.js

## Additional Context
SWR version: 0.5.6

**Comment by chilingling** [comment]
Didn't Reproduce, you made a mistake in the codeSandbox example.
`refreshInterval: 5000` should be `refreshInterval: refreshInterval`.
after correct it, it work as expected.

**Comment by PhiloNL** [comment]
Thanks! That indeed works, I thought it was not working given I want to turn the interval off when an error occurred but I just noticed this has its own setting (`errorRetryCount` & `errorRetryInterval`) 🙈
