### ISSUE TITLE
No data comes to SWR variable

### ISSUE THREAD

**Issue by vtarelkin** [vercel/swr#1340]
### Discussed in https://github.com/vercel/swr/discussions/1338

<div type='discussions-op-text'>

<sup>Originally posted by **vtarelkin** August 13, 2021</sup>
Please consider such component.

I sucessfully get image from server but I cannot see any data in console log. 

Also I can't access SWR's error - it tells me error is not defined. And if I move 

`    const {data, error} = useSWR(imageId && 'someUrl\getImage', getExistingFile);
`
above it tells me that getExistingFile function is not defined. 

Also I wonder how could I implement cache for my images in future - to avoid downloading them again and again

```
const Image = ({imageId}) => {

    const getExistingFile = (url) => {

        axios
            .get(
                url,
                {
                    responseType: 'blob'
                }
            )
            .then (response => response.data)
           //  .catch(error => error(error));  --- it tells me it cannot access it! 
    };

    const {data, error} = useSWR(imageId && 'someUrl\getImage', getExistingFile);

    console.log("data", data)  // here is undefined

    return (
      <>
      </>
    );
};

export default Image;

```</div>

**Comment by huozhi** [comment]
Close as dicussion is already created
