### ISSUE TITLE
Cache cannot be deleted

### ISSUE THREAD

**Issue by Clebal** [vercel/swr#1353]
# Bug report

## Description / Observed Behavior

I'm trying to delete all the SWR cache that have a certain key because I want to reset the cache that I have from a table view that paginate in backend.

## Expected Behavior

I expect that after cache is clear, the callback is being called again.

## Repro Steps / Code Example

Here you have a [CodeSandbox example](https://codesandbox.io/s/cache-clear-swr-slbnv?file=/src/App.js). Idk if I'm not doing it correctly but after reading some threads in this repo I think this is the way some people use.

1. Once you load the webpage, a `Result: 1` appears and you can see `Hey, I'm being called` from the slowRequest function in the console.
2. Click on `Delete cache`. In the console, you can see the before/after state.
3. Click on `Load`, and you can see that `Hey, I'm being called` doesn't appear again, because the slowRequest fn isn't called.

**Comment by shuding** [comment]
Please take a look at the new cache API in `swr@beta` ([docs](https://swr.vercel.app/docs/advanced/cache)). The previous internal API `import { cache } from 'swr'` is not going to be supported anymore.

**Comment by Clebal** [comment]
@shuding the same is still happening with `swr@beta`. I've updated the CodeSandbox example. Can you reopen the issue?

**Comment by Clebal** [comment]
@shuding still happening in 1.0.0

**Comment by huozhi** [comment]
The `load` button in the codesandbox above doesn't do any revalidation work, it just toggle display of the result. If you want to revalidate the result, please look at [mutation](https://swr.vercel.app/docs/mutation) for details.

**Comment by Clebal** [comment]
@huozhi it was a dumb example to force useSWR to be executed after the cache was modified.

@shuding thank you so much. I read in docs:

`The revalidateIfStale controls if SWR should revalidate when it mounts and there is stale data.`

When does SWR consider the data is stale? When cache is removed? Something else?
