### ISSUE TITLE
`cache.get` doesn't work for array keys

### ISSUE THREAD

**Issue by nandorojo** [vercel/swr#1355]
# Bug report

Using the new `swr@beta`, `cache.get` always returns `undefined` if the `key` is an array.

@shuding mentioned that array keys should still be fine [here](https://github.com/vercel/swr/issues/1345#issuecomment-899110457), so I think it hasn't been implemented for the `cache` yet.

## Description / Observed Behavior

`cache.get` works fine for when the key is a `string`, but it breaks for arrays.

## Expected Behavior

These should both work:

```js
cache.get(['user'])
cache.get('user')
```

However, only the second one does.

## Repro Steps / Code Example

[CodeSandbox](https://codesandbox.io/s/youthful-andras-kxpys?file=/pages/index.js:0-692) link

If you change the key from an array to a string, you can toggle it working / breaking.

<details>
<summary>View code</summary>

```tsx
import useSWR, { SWRConfig, createCache } from "swr";

const fetcher = async (url) => {
  return fetch(url).then((res) => res.json());
};

const map = new Map();
const swrScope = createCache(map);

// turning this into a string fixes it.
const key = ["https://api.github.com/repos/vercel/swr"];

function App() {
  const { data } = useSWR(key, fetcher);

  if (!data) return "loading...";

  return (
    <div>
      <h1>{data.name}</h1>
      <button
        onClick={() => {
          console.log(swrScope.cache.get(key));
        }}
      >
        Get cache
      </button>
    </div>
  );
}

export default function Example() {
  return (
    <SWRConfig value={{ cache: swrScope.cache }}>
      <App />
    </SWRConfig>
  );
}
```
</details>

## Additional Context

SWR version. 
`1.0.0-beta.11`

## Solution

It seems the solution is to use `unstable_serialize`

```js
swrScope.cache.get(unstable_serialize(key))
```

But I'm not sure if this should be done by the consumer of `cache.get` or not. Presumably users shouldn't be serializing, and `cache.get` should do it for you.

**Comment by shuding** [comment]
Yeah, this is exactly why `unstable_serialize` exists if you really need to get data directly from the cache. I don't think this is a bug.

The array keys still work for `useSWR` (it does serialization before passing to the cache provider), but the cache provider only accepts string keys. This is for simplifying the API to allow users create their own cache backend.

**Comment by nandorojo** [comment]
Got it, good to know. So I assume the serialize function is planned to stick around in some form for this use case.

**Comment by shuding** [comment]
Yeah, it will be supported as an advanced API. But we might want to change the structure of cache key-values in the future, so it’s marked as unstable for now.
