### ISSUE TITLE
SWR should throw an error when suspense is enabled but key is not ready

### ISSUE THREAD

**Issue by shuding** [vercel/swr#1359]
Related to #339. When the `suspense` option is enabled, SWR can not return any value to continue rendering, neither throwing any promise if it can't fetch. This includes 2 situations:
1. `suspense: true` and `key` is falsy.
2. `suspense: true` and `fetcher` is `null`.

In both cases SWR should throw an error.

**Comment by koba04** [comment]
@shuding
How are you going to add the error? 
The easiest way to add this is like the following.

```js
if (suspense && (!key || fetcher === null)) { 
  throw new Error("Either key or fetcher must be specified with suspense mode");
}
```

But I think SWR hasn't had any errors like this yet and its bundle size is important. Those error messages cannot be minified and would increase the bundle size. Is it acceptable for SWR?
Or are you going to adopt a way to avoid increasing its bundle size like what React and Redux do?
- https://github.com/reduxjs/redux/pull/4057
- https://github.com/facebook/react/tree/main/scripts/error-codes

I remember that there was a similar discussion before.
https://github.com/vercel/swr/pull/898

**Comment by shuding** [comment]
I think maintaining a list of error codes like React is a good idea. 👍

And in longer term we need to create 2 builds, one for development (warnings, errors, `useDebugValue`) and one for production use (minimal bundle with only error codes).

**Comment by shuding** [comment]
That said I'm good with fixing this with the proper error message for now and address error codes later, correctness is more important than size. 👍
