### ISSUE TITLE
types (beta): initialData doesn't exist in PublicConfiguration

### ISSUE THREAD

**Issue by hazae41** [vercel/swr#1375]
# Bug report

## Repro Steps / Code Example

Here is my code:
```typescript
const { data } = useSWR<Data>(
  getKey(), fetcher,
  { initialData: props.data })
```

This throws a typescript error
> `Object literal may only specify known properties, and 'initialData' does not exist in type 'Partial<PublicConfiguration<Data, any, Fetcher<Data>>>'`

After research `initialData` is NOT in PublicConfiguration
https://github.com/vercel/swr/blob/master/src/types.ts#L9

## Additional Context

I use swr@1.0.0-beta.13

**Comment by huozhi** [comment]
`initData` is replaced with `fallbackData`, we'll document it soon 🙏
