### ISSUE TITLE
immutable (beta): SWRGlobalState.get(cache) is undefined when using SSG

### ISSUE THREAD

**Issue by hazae41** [vercel/swr#1376]
# Bug report

## Description / Observed Behavior

I encounter this error on build when using useSWRImmutable on a Server-Side Generated page (getStaticProps)

```typescript
const { data } = useSWRImmutable(key, fetcher)
```

> `TypeError: Cannot read property '0' of undefined`

This code seems to be the cause:

https://github.com/vercel/swr/blob/master/src/use-swr.ts#L46

```typescript
const [
  EVENT_REVALIDATORS,
  STATE_UPDATERS,
  MUTATION_TS,
  MUTATION_END_TS,
  CONCURRENT_PROMISES,
  CONCURRENT_PROMISES_TS
] = SWRGlobalState.get(cache) as GlobalState
```

`SWRGlobalState.get(cache)` seems to be undefined in this case

## Additional Context

swr@1.0.0-beta.13

**Comment by huozhi** [comment]
@hazae41 Thanks for reporting and using the beta version of swr 🙏
