### ISSUE TITLE
Make returned state (data, error, isValidating) readonly

### ISSUE THREAD

**Issue by shuding** [vercel/swr#1386]
We can use mark the properties of the SWR return state readonly, to avoid modifying them. For example it's dangerous to directly modify the `data` object, which could cause an infinite loop of rerender.

**Comment by shuding** [comment]
Yep feel free to pick it up 👍

**Comment by swarup4741** [comment]
https://github.com/vercel/swr/blob/b819c25c6238a45bcec80ac8d978e849698302e7/src/types.ts#L39

Do I need to change the types to readonly ?

**Comment by swarup4741** [comment]
Could this be a possible fix ?

```ts
export type SWRHook = <Data = any, Error = any>(
  ...args:
    | readonly [Key]
    | readonly [Key, Fetcher<Data> | null]
    | readonly [Key, SWRConfiguration<Data, Error> | undefined]
    | readonly [
        Key,
        Fetcher<Data> | null,
        SWRConfiguration<Data, Error> | undefined
      ]
) => SWRResponse<Data, Error>
```

**Comment by shuding** [comment]
I think this only marks the parameters as read only, not the return value.

**Comment by swarup4741** [comment]
> I think this only marks the parameters as read only, not the return value.

Then i think we need to freeze the data and error object while returning them

```ts
return {
    mutate: boundMutate,
    get data() {
      stateDependencies.data = true
      return Object.freeze(data)
    },
    get error() {
      stateDependencies.error = true
      return Object.freeze(error)
    },
    get isValidating() {
      stateDependencies.isValidating = true
      return isValidating
    }
  } as SWRResponse<Data, Error>
}
```
