### ISSUE TITLE
Type issue with the isolatedModules flag on

### ISSUE THREAD

**Issue by nstepien** [vercel/swr#1420]
# Bug report

## Description / Observed Behavior

I'm getting the following type issues with TypeScript and `swr@1.0.0`:
```
node_modules/swr/dist/types.d.ts:80:6 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

80     [RevalidateEvent.FOCUS_EVENT]: void;
        ~~~~~~~~~~~~~~~

node_modules/swr/dist/types.d.ts:81:6 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

81     [RevalidateEvent.RECONNECT_EVENT]: void;
        ~~~~~~~~~~~~~~~

node_modules/swr/dist/types.d.ts:82:6 - error TS2748: Cannot access ambient const enums when the '--isolatedModules' flag is provided.

82     [RevalidateEvent.MUTATE_EVENT]: Promise<boolean>;
        ~~~~~~~~~~~~~~~
```

## Expected Behavior

No type errors.

## Repro Steps / Code Example

My `tsconfig.json` looks like this:
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "baseUrl": "./src",
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "pretty": true,
    "resolveJsonModule": true,
    "strict": true,
    "target": "esnext",
    "tsBuildInfoFile": ".cache/tsBuildInfoFile",
    "types": ["jest", "@testing-library/jest-dom"],
    "useUnknownInCatchVariables": false
  },
  "include": ["src/**/*"]
}
```

## Additional Context

SWR version. 1.0.0

This wasn't an issue with the previous versions of swr.

**Comment by huozhi** [comment]
It's a known limitation for `isolatedModules` flag. check [isolatedModules doc](https://www.typescriptlang.org/tsconfig#isolatedModules)

> These limitations can cause runtime problems with some TypeScript features like const enums and namespaces. Setting the isolatedModules flag tells TypeScript to warn you if you write certain code that can’t be correctly interpreted by a single-file transpilation process.

SWR is using enum in 1.0.0.

Wonder if we could get rid it but still keep the same bundle size. Will try

**Comment by nstepien** [comment]
Yes I'm aware, we use this flag as we transpile ts via babel.
Babel also added limited support for const enums recently: https://babeljs.io/blog/2021/07/26/7.15.0

Maybe simple `const`s would be good enough:
```ts
// Revalidate Events
export const FOCUS_EVENT = 0;
export const RECONNECT_EVENT = 1;
export const MUTATE_EVENT = 2;
```
JS minifiers would take care of them I believe.

**Comment by huozhi** [comment]
Using pure number constants might not be helper for typing in development. Like the part below. enum are easier to be identified than `typeof numberValue`

```ts
type RevalidateCallbackReturnType = {
  [RevalidateEvent.FOCUS_EVENT]: void
  [RevalidateEvent.RECONNECT_EVENT]: void
  [RevalidateEvent.MUTATE_EVENT]: Promise<boolean>
}
export type RevalidateCallback = <K extends RevalidateEvent>(
  type: K
) => RevalidateCallbackReturnType[K]
```

If you got any better idea, feel free to submit a PR to polish 🙏

**Comment by huozhi** [comment]
Yeah I mean it's doable but manually enumerate the type is not ideal 😂 Like 👇

```ts
export type RevalidateEvent = typeof FOCUS_EVENT | typeof RECONNECT_EVENT | typeof MUTATE_EVENT;
```
