### ISSUE TITLE
data is undefined when `fallbackData` and `revalidateOnMount: false` are provided

### ISSUE THREAD

**Issue by hugoazevedosoares** [vercel/swr#1422]
# Bug report

## Description / Observed Behavior
if I provide both  `fallbackData` and `revalidateOnMount: false` as options to useSWR, the initial `data` that is returned is undefined and not `fallbackData`. Before that could be done with `initialData` property and for what I could understand of `fallbackData` is that it would have the same behaviour.

```javascript
 const initialData = { id: 1 }
 const { data, error, mutate } = useSWR('/api/templates', { fallbackData: initialData, revalidateOnMount: false });

 console.log(data); // undefined
```

## Expected Behavior

`data` should assume the `fallbackData` value.

## Additional Context

SWR version: 1.0.0 

BTW, I'm using nextjs and trying to SSR a page with some initial data, avoiding the initial fetch on mount.

**Comment by shuding** [comment]
Good catch, thank you!

**Comment by hugoazevedosoares** [comment]
Testing this I discovered that `initialData` still works! But is not typed and it's not in the documentation anymore. Maybe this is just a typing issue.

**Comment by promer94** [comment]
I can't reproduce your problem.  It seems works fine. 
FYI: https://stackblitz.com/edit/nextjs-qeugdv?file=pages%2Findex.js  

And initialData only works before #1370

**Comment by huozhi** [comment]
@hugoazevedosoares I cannot repro it either with nextjs or cra. Could you check what's the installed version of swr in your node_modules? Since `initialData` is not existing in codebase after 1.0
