### ISSUE TITLE
Mutations with null as the value are ignored

### ISSUE THREAD

**Issue by shuding** [vercel/swr#1441]
### Discussed in https://github.com/vercel/swr/discussions/1439

<div type='discussions-op-text'>

<sup>Originally posted by **jacklimwenjie** September  9, 2021</sup>
Just asking out of curiosity, my project has a bug that appeared to be magically "fixed" after upgrading the `swr` package to version 1.0.0. 

However, after a deeper inspection, I found the bug is still there. 
The bug is caused by mutating a cache with a `null` value, causing a downstream component that expects the cache value to be an object and access one of its properties to crash. 

On the `swr` package version 1.0.0, the mutation with a `null` value now keeps the previously cached value, so the downstream component no longer crashes.

Is this something intended?</div>

**Comment by promer94** [comment]
https://codesandbox.io/s/mutate-null-xbqt8.
 
it seems to work. need more context about this issue

**Comment by shuding** [comment]
cc @jacklimwenjie do you mind sharing a minimal reproduction?

**Comment by huozhi** [comment]
I wonder if it because of missing to pass `false` as `shouldRevalidate` arg for mutate, which will trigger a new revalidation so mutated value will be lost
