### ISSUE TITLE
@testing-library/jest-dom and swr do not play nicely together

### ISSUE THREAD

**Issue by Schwartz10** [vercel/swr#1444]
# Bug report

## Description / Observed Behavior

I'm refactoring an application to use swr data fetching hooks. The repo uses jest for testing, and specifically uses `@testing-library/jest-dom` for better test matchers. Keeping `@testing-library/jest-dom` _and_ importing swr in a source file and/or a test file throws an Illegal invocation TypeError:

```
TypeError: Illegal invocation

    >  8 | import { cache } from 'swr'
         | ^

      at addEventListener (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:18:13)
      at Object.initFocus (node_modules/swr/dist/index.js:1:1981)
      at P (node_modules/swr/dist/index.js:1:3845)
      at Object.<anonymous> (node_modules/swr/dist/index.js:1:3915)
      at Object.<anonymous> (importSwr.test.js:8:1)
```

Commenting out the `@testing-library/jest-dom` import fixes the issue.

## Expected Behavior

I'd like to be able to test a component that uses swr for data fetching, and use extended matchers from `@testing-library/jest-dom` for assertions.

## Repro Steps / Code Example

I made a [minimal repro branch in my larger open source codebase](https://github.com/glifio/wallet/tree/debug/jest-swr-import). For your convenience:

 ```
git clone git@github.com:glifio/wallet.git (or https://github.com/glifio/wallet.git)
npm i
git fetch origin debug/jest-swr-import
git checkout debug/jest-swr-import
npm run test:watch importSwr
```

The files to look at are in this [diff](https://github.com/glifio/wallet/compare/feat/upgrade-msig-provider...debug/jest-swr-import?expand=1). Importing anything from `swr` in the test file itself breaks the tests. Here's the [@testing-library/jest-dom](https://github.com/glifio/wallet/blob/debug/jest-swr-import/jest.setup.js#L1) import.

## Additional Context
```
"swr": "^1.0.0",
"@testing-library/jest-dom": "5.5.0",
"@testing-library/react": "10.0.1",
"babel-jest": "26.6.3",
"jest": "^25.1.0",
```

**Comment by promer94** [comment]
Thanks for your reporting.  However this problem might not be related to SWR itself.  

I tried to reproduce you problem and i did see the error. But commenting out the @testing-library/jest-dom will not fix the issue.

SWR also uses @testing-library/jest-dom for testing. 
https://github.com/vercel/swr/blob/c00f0b47a01a2e89e027df6d4ec6a2986195d50c/jest-setup.ts#L1

**Comment by delikat** [comment]
@Schwartz10 I'm using Enzyme + Jest and ran into a similar issue (Illegal invocation at `addEventListener` in `EventTarget.js` whenever swr was imported). fwiw I solved it by upgrading jsdom from 14 to 16.
