### ISSUE TITLE
Not compatible ie11

### ISSUE THREAD

**Issue by philipseo** [vercel/swr#1453]
![Screenshot 2021-09-13 at 4 30 59 PM](https://user-images.githubusercontent.com/6640453/133042177-d13ba7ad-11ef-4d31-8d39-d1dd97e1aae6.png)

ENG Translate
SCRIPT5007: Cannot get property '__handlers' that is undefined or null reference.

I'm using the versions of the list below.
next.js 11.1.2
swr: 1.0.0

 I checked similar issues and tried all the settings at the bottom of the issue, but the same error continues to occur.
ISSUE : https://github.com/vercel/swr/issues/278

I would appreciate it if you could let me know which part to check or try.

**Comment by amannn** [comment]
I'm also seeing an error in IE11 on a page that only uses `SWRConfig` from `swr`:

> Invalid calling object

Help would be greatly appreciated!

**Comment by amannn** [comment]
@philipseo I've added https://github.com/vercel/swr/pull/1463 which solves the bug that I was seeing.

I couldn't reproduce your bug though. I'm currently using `SWRConfig`, `useSWR` and `useSWRImmutable` in my code base. These APIs seem to work in IE11 with the fix from the PR.
