### ISSUE TITLE
 "Maximum update depth exceeded" when setting transformed `swr` data into state from `useEffect` 

### ISSUE THREAD

**Issue by allenhj** [vercel/swr#1465]
# Bug report

## Description / Observed Behavior

I am seeing  "Maximum update depth exceeded" React error when I try to take a version of `response.data` that  has been transformed in some way (elements from `response.data` placed into named arrays, object spread assignment to a new variable, etc) and set the array/object into state with `setState` from within a `useEffect` that also has `swr` data or transformed/subset version of the `swr` data as a dependency in the dependency array. 

This may be a known issue, as something similar is mentioned here: https://github.com/vercel/swr/issues/1386

## Expected Behavior

I thought I would be able to set a modified/sorted/filtered version of `response.data` into state without errors.

## Repro Steps / Code Example

https://codesandbox.io/s/clever-firefly-bzrsq?file=/pages/index.js
(May need to rerun locally due to the nature of the error)

## Additional Context

SWR version. 1.0.1

**Comment by shuding** [comment]
This is unrelated to #1386, the cause is

```js
const typeAData = typedData?.filter((status) => status.type === "a") ?? [];
```

here a new array is always created whenever it runs, which makes the effect being triggered and a new re-render happens.

I'd do this instead:

```js
const typeAData = useMemo(() => typedData?.filter((status) => status.type === "a") ?? [], [typedData])
```
