### ISSUE TITLE
Mutate Multiple Keys from RegEx Example is invalid

### ISSUE THREAD

**Issue by Laptopmini** [vercel/swr#1468]
# Bug report

## Description / Observed Behavior

The "Mutate Multiple Keys from RegEx" example found [here](https://swr.vercel.app/docs/advanced/cache#mutate-multiple-keys-from-regex) is broken since v1 release as the `Cache` API has changed. I am currently struggling to figure out a working alternative.

I also cannot find the previously available method `cache.serializeKey()`.

## Expected Behavior

```js
const { cache } = useSWRConfig()

...

const keys = []
for (const key of cache.keys()) {
  if (matcher.test(key)) {
    keys.push(key)
  }
}
```
But this yields `Property 'keys' does not exist on type 'Cache<any>'.` Is there an issue with the types declaration?

## Repro Steps / Code Example

The previous versions offered the ability to achieve the following:
```js
import { cache } from 'swr';

...

cache
  .keys()
  .filter((key) =>
    key.startsWith(
      cache.serializeKey(['/api/todos']).forEach((key) => cache.delete(key))
    )
  );
```
However, neither `.keys()` nor `.serializeKey()` is available anymore making this impossible.

## Additional Context

swr@1.0.1
typescript@4.3.5

## Additional Question

- Where is `cache.serializeKey()`? What is the alternative in the new version?

## Related Discussion

- https://github.com/vercel/swr/discussions/525

**Comment by Laptopmini** [comment]
It seems that I missed the following in the example:
```js
if (!(cache instanceof Map)) {
  throw new Error('matchMutate requires the cache provider to be a Map instance')
}
```

I assume this means the default cache handler is a `Map` instance, unless a custom provider is required for this example to work.

I am still confused however as to where the key serializer utility method is to be found publicly. It seems like it still exists but it's undocumented and seems internal.
https://github.com/vercel/swr/blob/824abe9f2beda8be19da9291135b8f4a47c873de/src/utils/serialize.ts#L6

**Comment by koba04** [comment]
@Laptopmini 

> I am still confused however as to where the key serializer utility method is to be found publicly. It seems like it still exists but it's undocumented and seems internal.

`serialize` is exported as `unstable_serialize`, but as the name shows, the API is in experimental and is not documented yet. It might be changed in the future, but you can use the API at your own risk.
https://github.com/vercel/swr/pull/1337

**Comment by Laptopmini** [comment]
Thanks for the answer, I'll close this ticket.
