### ISSUE TITLE
Fix "ebusy" issue

### ISSUE THREAD

**Issue by quick007** [vercel/swr#1470]
# Bug report

## Description / Observed Behavior

SWR randomly stops development mode with an "EBUSY" error

What kind of issues did you encounter with SWR?

Crashing development mode (I haven't seen any issues with production though, which is nice)

## Expected Behavior

How did you expect SWR to behave here?

Not crash development mode

## Repro Steps / Code Example

Load up a nextjs application with SWR (1.0.1). I also use SWR with typescript and node fetch (2.6.1, the non-current version). Here is my fetcher: 
```ts
import fetch from "node-fetch";
export default async function fetcher(...args: any[]) {
  const res = await fetch(...args);
  return res.json();
}
```

Heres my error:
![image](https://user-images.githubusercontent.com/69743171/133719425-32d01f14-c21e-4f14-a09c-ea2f1c27713e.png)

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version (1.0.1)

**Comment by shuding** [comment]
I don't think this is an SWR issue, SWR is a React lib that doesn't have any access to your filesystem. This `EBUSY` is clearly a filesystem access error, which is likely to be caused by the dev server or related Node.js modules.

**Comment by quick007** [comment]
It only happens whenever I have swr in my dependencies, and it's happened on multiple projects now. I doubt its node fetch, but I'll make an issue there if its 100% not swr.
