### ISSUE TITLE
How to use cache globally in v.1.0.1 (in redux actions)?

### ISSUE THREAD

**Issue by olesmarola** [vercel/swr#1472]
### Discussed in https://github.com/vercel/swr/discussions/1471

<div type='discussions-op-text'>

<sup>Originally posted by **olesmarola** September 17, 2021</sup>
Hello guys! I have a question about cache. In the old version I used this import:
`import { cache } from 'swr'` to use it in redux action (for logout).
But now cache can be used only in components with hook `useSWRConfig`. I can't use hooks inside redux action... What can I do in this situation? Is any solution for this case? Thanks for your help!</div>

**Comment by shuding** [comment]
We don't recommend using the global cache without a React hook, which might be unsafe for future React features. But there is currently a way to do that:

```js
import { SWRConfig } from 'swr'

SWRConfig.default.cache // → the default cache storage
```
