### ISSUE TITLE
Returned SWRResponse state is no longer memoized

### ISSUE THREAD

**Issue by patrickshipe** [vercel/swr#1495]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

In previous pre-1.0 versions (e.g. 0.5.6), the entire SWRResponse object from the `useSWR` hook was memoized. If the data didn't change, the overall object did not change. You could use the return value from `useSWR` as dependencies for things like `useEffect`.

As a workaround, you can make `swrReponseObject.data` the dependency - which is fine, but without good guardrails this is very easy to miss, especially if you want to call `mutate()` or check `isValidating`. A mistake here often causes a "maximum update depth exceeded" error due to incessant rendering.

## Expected Behavior

How did you expect SWR to behave here?

The return object from `useSWR` should be memoized as before if data did not change.

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version: 1.0.1

**Comment by shuding** [comment]
> If the data didn't change, the overall object did not change. You could use the return value from useSWR as dependencies for things like useEffect.

This wasn't true even for old versions. If any of `[initialData, initialError, key]` changes, the object will change: https://github.com/vercel/swr/blob/38e2f4200d39b336bc1427c95f4d2caba835cff9/src/use-swr.ts#L757

And it doesn't change even if `data` changes.

Overall, there's no guarantee that it will always behave like that. Any new added feature might break it and actually it's a good thing to not rely on it. For the same reason, React won't recommend you using the return value of `useState` as the dependency.
