### ISSUE TITLE
Bug: cache object doesn't have the method `clear`

### ISSUE THREAD

**Issue by Ne0xygene** [vercel/swr#1502]
# Bug report

## Description / Observed Behavior

While cache seems to be an instance of Map, I cannot access to its methods as the following example : 
`cache.clear()`
While it stills work, my typescript linter isn't happy about it.

## Expected Behavior

`cache.clear()` should be availaible and shouldn't return a typescript error.

SWR version 1.0.1. 

Link to the discussion : 
https://github.com/vercel/swr/discussions/1494

**Comment by kelvin9314** [comment]
@huozhi @shuding  Hello guys,

we know that the return of ```cache```, it actually is  a Map instance
shall we just add a clear function in the interface , like 

```
export interface Cache<Data = any> {

    get(key: Key): Data | null | undefined;

    set(key: Key, value: Data): void;

    delete(key: Key): void;
    
    clear(): void;

}
```

then we might pass the typescript linter error ??

**Comment by allenchuang** [comment]
following because i see the same issue.

**Comment by AdamKwoka** [comment]
Me too I still have problem with cache.clear();

**Comment by huozhi** [comment]
Please checkout https://github.com/vercel/swr/issues/1887#issuecomment-1171269211 Thanks!
