### ISSUE TITLE
TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by diegoramosxyz** [vercel/swr#1503]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

When attempting to use the useSWRInfinite hook by following [the example](https://github.com/vercel/swr/blob/master/examples/infinite-scroll/pages/index.js), I get a type error coming from the useOnScreen hook.

> TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.

https://github.com/vercel/swr/blob/6746f491c649d56055ec3b239cc10b3ae2d0b448/examples/infinite-scroll/hooks/useOnScreen.js#L11

```ts
// node_modules/tyepscript/lib/lib.dom.d.ts
interface IntersectionObserver {
    ...
    observe(target: Element): void;
    ....
}
```

This is where the problem is coming from. The Element type doesn't have a `current` attribute. 
``` ts
// node_modules/tyepscript/lib
declare var Element: {
    prototype: Element;
    new(): Element;
};
```

How would I go about solving this type issue?

## Expected Behavior

How did you expect SWR to behave here?

I expected SWR to fetch initial data.

**Comment by diegoramosxyz** [comment]
I got around this issue by utilizing [react-intersection-observer](https://www.npmjs.com/package/react-intersection-observer).

```js
// Modified example
// https://github.com/vercel/swr/blob/master/examples/infinite-scroll/pages/index.js
...
import fetcher from '../libs/fetch'
import { useInView } from 'react-intersection-observer'

...

export default function App() {
   ...

   const { ref, inView } = useInView()
   
   ...

  useEffect(() => {
    if (inView && !isReachingEnd && !isRefreshing) {
      setSize(size + 1)
    }
  }, [inView, isRefreshing])

  return (
    <div style={{ fontFamily: 'sans-serif' }}>
      ...
      <div ref={ref}>
        {isLoadingMore ? 'loading...' : isReachingEnd ? 'no more issues' : ''}
      </div>
    </div>
  )
}
```

**Comment by huozhi** [comment]
Hi @diegoramosxyz I cannot repro with the example on chrome/safari/firefox. Could you provide more information about the browser you're using?

Does adding a checking condition in `useOnScreen` hook works for you? like

```diff
// useOnScreen.js
export default function useOnScreen(ref) {
  const [isIntersecting, setIntersecting] = useState(false)

  useEffect(() => {
+    if (!ref.current) return

```
