### ISSUE TITLE
useMatchMutate from the example does not revalidate

### ISSUE THREAD

**Issue by benjamintd** [vercel/swr#1510]
# Bug report

## Description / Observed Behavior

In the example linked [here](https://swr.vercel.app/docs/advanced/cache), a method is proposed to mutate all keys that match a certain regular expression. 

I am trying to revalidate several keys that have a same prefix (e.g. `/api/todo` and `/api/todo?assigned=true`), however none of them are revalidated.

There are matching keys in the cache, however they are in the form `$req$/api/todo` or `$err$/api/todo`, probably due to running through the [serialize utilities](https://github.com/vercel/swr/blob/be6958c2556126ab902eae9a4031b4353f7d8234/src/utils/serialize.ts).

## Expected Behavior

The keys `/api/todo` and `/api/todo?assigned=true` are revalidated

## Additional Context

SWR version 1.0.1

**Comment by shuding** [comment]
There should be a key that is just `/api/todo`. The `$req$/api/todo` key is for storing the `isValidating` state, and `$err$/api/todo` is for storing the `error` state, so those two don't need to be revalidated.

**Comment by benjamintd** [comment]
Hi @shuding, thanks for your answer. Chosing a better regular expression did the trick to remove `$err$/...` and `$req$/...` from the keys to mutate. Perhaps it's worth noting somewhere in the doc that keys that are not user-generated are still present in the cache. 

As for the problem I encountered, I'll try to reproduce a test case in which `/api/todo` was *not* present in the cache, but in the meantime I'll close the issue.
