### ISSUE TITLE
Fallback config doesn't load array style keys

### ISSUE THREAD

**Issue by tklever** [vercel/swr#1516]
# Bug report

When using `<SWRConfig />` to create fallback data, string keys work as expected, but array style keys do not. 

## Description / Observed Behavior

Array style keys are always a cache miss for fallback data.

## Expected Behavior

Array style keys populate fallback data, the same as string keys

## Repro Steps / Code Example

[![Edit swr-array-keys-example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-rumple-qm2fr?fontsize=14&hidenavigation=1&theme=dark)

In that sandbox, when `key` is an array, the console will read:

undefined
goodbye

if you change `key` to a string in `App.js`, the console will read:

hello
goodbye

`hello` is the fallback value defined in `index.js`

## Additional Context

SWR version: 1.0.1

**Comment by shuding** [comment]
Hi! I replied in #1520 which is a similar issue.

**Comment by tklever** [comment]
Thank you! Sorry for the duplicate.
