### ISSUE TITLE
revalidateOnMount: true and revalidateOnFocus: false do not work together.

### ISSUE THREAD

**Issue by animeshchat** [vercel/swr#1519]
Hi,

These options do not work together.
{
  revalidateOnMount: true, 
  revalidateOnFocus: false
} 

If  revalidateOnFocus is set to false, swr stops revalidating on mount. The desired behavior is that revalidation should happen only when route is changed, not on re-focus of page.

Am I missing anything?

**Comment by shuding** [comment]
> If revalidateOnFocus is set to false, swr stops revalidating on mount.

This sounds like a bug, could you provide a reproduction on CodeSandbox maybe?
