### ISSUE TITLE
 key has change, never revalidate

### ISSUE THREAD

**Issue by j-xzy** [vercel/swr#1531]
# Bug report

## Description / Observed Behavior

version: 1.0.1,  key has change, never revalidate

## Repro Steps / Code Example

[CodeSandbox](https://codesandbox.io/s/goofy-silence-4nqf7?file=/src/App.js)

## Context

https://github.com/vercel/swr/pull/1430#issuecomment-928890102

**Comment by shuding** [comment]
I think this should be the correct behavior of `revalidateOnMount: false`. When the key changes, it should not automatically revalidate if `revalidateOnMount` is manually disabled.

**Comment by GeraldHost** [comment]
@shuding I had a similar issue I want to only revalidate if the key changes but otherwise never revalidate. What combination of options should I use?

**Comment by GeraldHost** [comment]
@shuding I had a similar issue I want to only revalidate if the key changes but otherwise never revalidate. What combination of options should I use?

**Comment by filenwind** [comment]
I have the same problem, I don't want revalidateOnMount but I need revalidateOnKeyChange.

Can you add the new config revalidateOnKeyChange?

**Comment by shuding** [comment]
Reopened the issue since the following should be the correct behavior. When the key changes, useSWRImmutable should definitely refetch.

> More clear, I want using useSWRImmutable and can revalidateOnKeyChange to be true

**Comment by caydgreen** [comment]
Is this still an active bug?

**Comment by filenwind** [comment]
[here](https://codesandbox.io/s/useswrimmutableswitchkeyrevalidate-t6g8mp?file=/src/Test.tsx) is the reproduce

You can switch key by click each button, and see the revalidate log.

It won't revalidate if key already fetched, so I want a config like `revalidateOnKeyChange`
