### ISSUE TITLE
Middleware fetcher is never called with useSWRInfinite

### ISSUE THREAD

**Issue by Nfinished** [vercel/swr#1553]
# Bug report

## Description / Observed Behavior

useSWRInfinite with middleware does not call fetching function regardless of key value

## Expected Behavior

Fetcher function should be called when key is not null

## Repro Steps / Code Example

"serialize" middleware is from https://swr.vercel.app/docs/middleware#serialize-object-keys with a slight modification to accept function keys, which are required for useSWRInfinite

https://codesandbox.io/s/elated-ellis-yvxhm?file=/src/App.js

## Additional Context

SWR version 1.0.1

**Comment by Nfinished** [comment]
I can't share too much code but here's the middleware:

```ts
import stringify from 'fast-json-stable-stringify'
import { Middleware } from 'swr'
export const serialize: Middleware = (useSWRNext) => {
  return (key, fetcher, config) => {
    // Serialize the key.
    const resolvedKey = typeof key === 'function' ? key() : key
    const serializedKey = Array.isArray(resolvedKey)
      ? stringify(resolvedKey)
      : resolvedKey

    console.log({ serializedKey, fetcher })

    // Pass the serialized key, and unserialize it in fetcher.
    return useSWRNext(
      serializedKey,
      (k) => {
        console.log({ k })
        return fetcher(...JSON.parse(k))
      },
      config
    )
  }
}
```

and here's the console:
![Image 2021-10-14 at 10 37 52 AM](https://user-images.githubusercontent.com/1719791/137340000-81299e67-6090-4c69-9800-b9b6fed21511.jpg)


If `serializedKey` is defined why doesn't the fetcher function passed to `useSWRNext` run?

**Comment by shuding** [comment]
With useSWRInfinite it's a bit tricky and you can't pass a serialized string as the key argument. It has to be a function. I'd recommend doing this:

```js
const getSerializedKey = (index, previousData) => {
  const key = getKey(index, previousData)
  // do serialization here and return the serialized key
}
```

**Comment by shuding** [comment]
Also in the next major release (you can try it now with `swr@beta`!) key serialization will be built-in, so you don't have to implement this middleware in particular.

Related: #1429

**Comment by gabriel-peter** [comment]
v2.33 : I still am noticing this issue btw, all normal `useSWR` hooks obey the middleware in the SWRConfig provider but `useSWRInfinite` does not. My work-around solutions are: implement the middleware features directly in the hookcall for `useSWRInfinite` or just use `useSWR`. Neither are ideal!
