### ISSUE TITLE
key function should be able to return falsy value

### ISSUE THREAD

**Issue by morgs32** [vercel/swr#1576]
# Bug report
In the docs: https://swr.vercel.app/docs/conditional-fetching
We should be able to return a falsy value from the function to NOT fetch.
But it looks like the function is supposed to return null.
Can we make it expect falsy?

## Description / Observed Behavior
When your key function returns a falsy value it's a typescript issue

## Expected Behavior
According to the docs, I expect a falsy value to be type safe and to conditionally fetch

## Repro Steps / Code Example
Just make a key function that returns false or undefined

## Additional Context
SWR version: 1.0.1

**Comment by shuding** [comment]
Makes sense!
