### ISSUE TITLE
useSWRInfinite() is called when navigating away from a page

### ISSUE THREAD

**Issue by D2DN** [vercel/swr#1579]
# Bug report

We noticed that a network call was being made when navigation _away_ from a page that implements useSWRInfinite. The network call we’re seeing is associated with the page we’re leaving so that’s a bit confusing. The issue doesn’t seem to be related to next.js specifically since we’ve been able to reproduce the behavior in a plain react app (see repro below)

## Expected Behavior

When we leave a page, no request should be made because we no longer need the data.

## Repro Steps / Code Example

https://codesandbox.io/s/sample-react-swr-87zvo

	• Open Network tab in Chrome DevTools or equivalent.
	• Click on "load more" button
	• Click on "info" link in menu navigation.

You will see a call to https://api.github.com/repos/reactjs/react-a11y/issues?per_page=6&page=1 in network tab

## Additional Context

SWR version : reproduced with 0.5.6 and 1.0.1

**Comment by shuding** [comment]
Thanks for bringing this up, it should be the same cause as #1680 and I’ll follow up there.
