### ISSUE TITLE
No fetch when global fallback is undefined and revalidateOnMount false

### ISSUE THREAD

**Issue by ArekBartnik** [vercel/swr#1610]
# Bug report

## Description / Observed Behavior

If you use global fallback from SWRConfig with `revalidateOnMount: false` and fallback for a key is `undefined` then data from useSWR will be also `undefined`.

## Expected Behavior

I think SWR should ignore `revalidateOnMount: false` when global fallback for a key is `undefined` and fetch new data.

**Comment by shuding** [comment]
Please use the `revalidateIfStale: false` option — it does exactly what you need! :)

And what you mentioned about `revalidateOnMount` is the correct behavior, it just controls whether it should revalidate or not when mounting. It’s not affected by the existence of cache.
