### ISSUE TITLE
TS throws after changing useSWR typings

### ISSUE THREAD

**Issue by Kamahl19** [vercel/swr#1621]
# Bug report

## Description / Observed Behavior

```
Type '(org: string, repo: string) => Promise<any>' is not assignable to type '((args_0: string) => FetcherResponse<{ name: string; description: string; }>) | ((args_0: any, ...args_1: unknown[]) => FetcherResponse<{ name: string; description: string; }>) | ((args_0: Record<...>) => FetcherResponse<...>) | ((args_0: string | ... 2 more ... | Record<...>) => FetcherResponse<...>) | null'.ts(2769)
```

This error occurres when i use multiple arguments and generics for data

## Repro Steps / Code Example

https://codesandbox.io/s/create-react-app-typescript-forked-yjc49?file=/src/index.tsx

## Additional Context

Happening since 1.1.0-beta-3 , even on beta 7

**Comment by shuding** [comment]
Closed by #1640.
