### ISSUE TITLE
Error when fetching conditionally with suspense enabled and version 1.0.1

### ISSUE THREAD

**Issue by nicosampler** [vercel/swr#1627]
## Bug
Trying to fetch a query conditionally with suspense enabled throws the following error:
`Error: useSWR requires either key or fetcher with suspense mode`

## Example
When the signature is undefined, it throws. 

```
const user = useSWR(signature ? ['me', signature] : null, (path, signature) => {
    try {
      return axios.get(`${API_URL}/${path}`, { headers: { authorization: signature } })
    } catch (error) {
      console.error(error)
    }
  })
  ```

SWR version. 1.0.1

**Comment by huozhi** [comment]
Can you try to upgrate to latest version? We've reverted the error/warning since 1.1.0-beta.0?

**Comment by nicosampler** [comment]
@huozhi 💯
