### ISSUE TITLE
When using fallbackData, data type is not accurate (undefined)

### ISSUE THREAD

**Issue by vvo** [vercel/swr#1633]
# Bug report

## Description / Observed Behavior

When using this type of code:

```ts
import useSWR from "swr";

const { data } = useSWR<{name: string}[]>(
  "/api",
  { fallbackData: [] }
);
```

then data type is:

```ts
{
    name: string;
}[] | undefined
```

While there's no way it will be undefined. It's an array all the time.

## Expected Behavior

data type should reflects fallbackData.
I am not sure this is doable though.

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version: latest.

**Comment by huozhi** [comment]
Duplicate with #1410
