### ISSUE TITLE
Suspense and conditional fetching causing infinite rerenders

### ISSUE THREAD

**Issue by shuding** [vercel/swr#1660]
### Discussed in https://github.com/vercel/swr/discussions/1651

<div type='discussions-op-text'>

<sup>Originally posted by **rikutiira** November 22, 2021</sup>
Hey, and first of all thanks for the great work on the library! 

I'm new to SWR and I have been reading discussion & GH issues around this, and I'm still a bit unsure about how suspense and conditional fetching should work with the latest version (1.1.0-beta.9 at the time of writing this) so I was hoping to get some clarity around the issue 😄.

I'm having an infinite rerender issue when using suspense with conditional fetching from version 1.0.0 onwards (including current beta).

The [SWR documentation on Suspense](https://swr.vercel.app/docs/suspense#note-with-conditional-fetching) says that with conditional fetching, `data` should be `undefined` but with version 1.0.0+, it seems to fallback to the `Suspense` component instead and causes an infinite render loop where the `useSWR` hook is called. I'm new to suspense, but I suppose this is not expected behaviour?

1) Am I doing something wrong in the code?
2) Is the behaviour expected? If it is, how are you supposed to deal with conditional data fetching? Is there any additional documentation on the subject somewhere?

Here is a Codesandbox where you can test the issue: https://codesandbox.io/s/cold-dust-4dvzl?file=/src/App.js (uncomment `response` to run it). Here's the code as well:

```
import React, { useState, Suspense } from "react";
import useSWR from "swr";
import "./styles.css";

const fetcher = (str) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(str);
    }, 1000);
  });
};

const Test = (props) => {
  console.log("renders");

  const response = useSWR(props.str ?? null, fetcher, { suspense: true });

  return (
    <>
      <div>Data:</div>
      <pre>{JSON.stringify(response, null, 2)}</pre>
    </>
  );
};

export default function App() {
  const [str, setStr] = useState();
  return (
    <div className="App">
      <h1>SWR test</h1>
      <Suspense fallback={<div>loading...</div>}>
        <Test str={str} />
      </Suspense>
      <button onClick={() => setStr("hello world")}>Clicky</button>
    </div>
  );
}
```

Thanks! 🙇 </div>

**Comment by lucas-garrido** [comment]
try 
  `const response = useSWR(props.str ?? null, (url) => fetcher(url), { suspense: true });
`

**Comment by jstejada** [comment]
@shuding what version of React are you using? if you're on the 18 beta, can you check if using `React.startTransition` to schedule the update fixes this? e.g. `React.startTransition(() => setStr("..."))`

**Comment by shuding** [comment]
@jstejada There is a CodeSandbox link above that you can take a look. (This issue wasn't reported by myself if you check the discussion BTW)

**Comment by jstejada** [comment]
ah got it, apologies, missed the original discussion and sandbox link

**Comment by ppprevost** [comment]
Same issue for me with 1.1.0,
 
` const SWRConfigValue = {
	onError: (err) => console.log('SWR error', err),
	shouldRetryOnError: false,
	suspense: true,
	revalidateOnFocus: false,
	revalidateOnMount: false,
	revalidateOnReconnect: false,
};`

const get = useSWRFetcher();
	const { mutate, data, isValidating, error } = useSWR(auth ? /navigate : null, get);

	return { error, mutate, data, isValidating };


if i delete the condition it works again.

**Comment by rkoleci** [comment]
Can you assign this to me ?

**Comment by seedy** [comment]
My whole stack is based on conditional swr + suspense, I'm waiting for this fix to be able to upgrade our dependency from `0.5.6` to `latest`

**Comment by icyJoseph** [comment]
What would be the expected behavior here? I reckon, to return data `undefined`? and only activate the suspense boundary when there's a truthy key?

If that's the case we could do (roughly speaking):

```js
if (suspense && isUndefined(data) && key !== '') {
    throw isUndefined(error) ? revalidate(WITH_DEDUPE) : error
  }
```

However, this breaks a test.
