### ISSUE TITLE
refreshInterval as function

### ISSUE THREAD

**Issue by shuding** [vercel/swr#1683]
### Discussed in https://github.com/vercel/swr/discussions/1630

<div type='discussions-op-text'>

<sup>Originally posted by **correttojs** November 11, 2021</sup>
currently the `refreshInterval` option can only be a number. In some cases this number should be dynamic, dependent on the updated fetched data.
For example, the fetcher returns a list of items and a value corresponding to the next expected update. </div>

**Comment by Andrewnt219** [comment]
Hi @shuding, I want to give this a try. Do you mean this?
```ts
type refreshInterval =  number | () => number
```

**Comment by shuding** [comment]
Thank for that, @Andrewnt219!

The API signature should look like this: 

```js
type refreshInterval =
  | number
  | (latestData: Data | undefined) => number
```

If the function returns `0`, the polling should be stopped.
