### ISSUE TITLE
Beta versions should not be pushed to npm as `latest`

### ISSUE THREAD

**Issue by fabb** [vercel/swr#1712]
# Bug report

## Description / Observed Behavior

Currently beta versions are pushed as `latest` to npm:

![Screenshot 2021-12-20 at 08 30 18](https://user-images.githubusercontent.com/153960/146729106-af6ac3c7-fddf-4797-aba1-09f7060f432a.png)

This makes them show up in `npm outdated`:
```
Package           Current        Wanted        Latest  Location                  Depended by  Package Type     Homepage
swr                 1.1.1         1.1.1  1.1.2-beta.0  node_modules/swr          nasa-web     dependencies     https://swr.vercel.app
```

## Expected Behavior

Only stable versions should be pushed as `latest`.

**Comment by shuding** [comment]
Thank you! The tags were re-added and it should be good now.
