### ISSUE TITLE
Unclear migration path: revalidate => mutate

### ISSUE THREAD

**Issue by huozhi** [vercel/swr#1722]
### Discussed in https://github.com/vercel/swr/discussions/1716

<div type='discussions-op-text'>

<sup>Originally posted by **konradjurk** December 22, 2021</sup>
Hello,

we are trying to migrate from `^0.3.5` to `^1.1.1`. [According to the migration guide](https://swr.vercel.app/blog/swr-v1#change-revalidate-to-mutate), it should be possible to replace all `revalidate()` calls with `mutate()`. However, mutate does not seem to update the `data`, in contrast to `revalidate()`. 

0.3.5 working:

```
const settingsSWR = useSWR<Settings>(...);

console.log('beforeUpdate', settingsSWR.data)

await settingsSWR.mutate(settingsPayload, false);

await settingsSWR.revalidate();

console.log('afterUpdate', settingsSWR.data)
```

Now, the old data is logged once as "beforeUpdate" and the updated data as "afterUpdate"

1.1.1 not working

```
const settingsSWR = useSWR<Settings>(...);

console.log('beforeUpdate', settingsSWR.data)

await settingsSWR.mutate(settingsPayload, false);

await settingsSWR.mutate();

console.log('afterUpdate', settingsSWR.data)
```

Now, both "beforeUpdate" and "afterUpdate" log the old data.

What am I doing wrong?

Thank you!</div>

**Comment by shuding** [comment]
I think this is the correct behavior, although it breaks the behavior a bit. The returned object of SWR (`const settingsSWR = useSWR<Settings>(...)`) should be a snapshot value instead of a reference to the latest states.

**Comment by shuding** [comment]
(What we are missing here is the ability to get the latest state references. I kinda feel that's React's job thuogh.)
