### ISSUE TITLE
Option for optimistic updates

### ISSUE THREAD

**Issue by shuding** [vercel/swr#1730]
### Discussed in https://github.com/vercel/swr/discussions/1721

<div type='discussions-op-text'>

<sup>Originally posted by **SevenOutman** December 23, 2021</sup>
While there's example of making optimistic update with two separate `mutate` calls, why not add a new `mutate` signature to act as a shortcut?

```js
mutate(newUser, updateUser(newUser), false)

// Equivalent to

mutate(newUser, false)
mutate(updateUser(newUser), false)
```</div>

**Comment by koba04** [comment]
This seems to be added as the optimisticData option in #1745 🚀

**Comment by shuding** [comment]
Yep, gonna close this issue, thanks!
