### ISSUE TITLE
Broken in MS Edge

### ISSUE THREAD

**Issue by joelmoss** [vercel/swr#174]
Simply importing SWR  (`import useSWR from 'swr'`) results in an exception in MS Edge 18...

> Unhandled promise rejection SyntaxError: Expected identifier, string or number.

**Comment by quietshu** [comment]
What are your build steps? Can you create a reproduction so we can take a look?

**Comment by joelmoss** [comment]
Sandbox at https://codesandbox.io/s/busy-haslett-z06qd. Open https://z06qd.csb.app/ in Edge and you'll get the error.

**Comment by ozanbolel** [comment]
We are having the same issue. I can confirm that removing the line (import useSWR from 'swr') solves it. Any update on this?

**Comment by sergiodxa** [comment]
Maybe something in the built code it's keeping some JS feature not supported by Edge?

**Comment by derekblank** [comment]
This is possibly because MS Edge 18 does not [support dynamic import](https://caniuse.com/#feat=es6-module-dynamic-import) out of the box, but I can confirm that useSWR does work in Edge 18 with the appropriate polyfills.

Specifically in my app I am using  [@babel/plugin-syntax-dynamic-import](https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import) with babel-loader via webpack, which may or may not be suitable for your needs (based on how the rest of your app dependencies are working).

**Comment by joelmoss** [comment]
Yeah I'm using that same babel plugin with webpack, but it's still not working.

**Comment by derekblank** [comment]
It still seems like the error is caused by something not supported by IE. We are using other babel polyfills and parts of core-js as well. Trying to narrow down which one is actually required for support...

**Comment by ozanbolel** [comment]
I have getting the error for `return{...e,...t}`. Doesn't Edge support spread operators?

**Comment by joelmoss** [comment]
> I have getting the error for `return{...e,...t}`. Doesn't Edge support spread operators?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#Browser_compatibility

**Comment by jimthedev** [comment]
The issue is clear that this is for MS Edge 18 but just for anyone else's sake: this is not still an issue in MS Edge Beta (79) since it is Chromium based.

**Comment by pacocoursey** [comment]
Seeing as this is old, stale, and MS Edge has been on Chromium for over a year, I think this is safe to close. Please feel free to re-open if this is still a pressing issue and we can look further.
