### ISSUE TITLE
父子组件使用相同的useHook, 当加载新的子组件调用useHook时，父组件下的所有子组件状态全都初始化了

### ISSUE THREAD

**Issue by chineseQQQ** [vercel/swr#1750]
但是这个问题只出现在线上和部分人本地。。。

**Comment by shuding** [comment]
检查一下 `useSWR` 的返回 `data` 是否被修改了。`data` 应该是 immutable 的。

**Comment by chineseQQQ** [comment]
返回的data没有发生变化，但是已经定位到问题了，在1.1.0打包后会出现，但是1.1.1没有问题。

**Comment by shuding** [comment]
@chineseQQQ 多谢反馈，能否提供一个具体的代码示例？
