### ISSUE TITLE
Better React DevTools support

### ISSUE THREAD

**Issue by golopot** [vercel/swr#1768]
# Bug report

## Description / Observed Behavior

Hook value in dev tool looks strange.

<img width="173" alt="Observed" src="https://user-images.githubusercontent.com/16285118/148184992-e89f77ab-0ae7-48cf-8cc7-644589d51ded.png">

## Expected Behavior

<img width="120" alt="Expected" src="https://user-images.githubusercontent.com/16285118/148185030-6ed41e1e-6a6d-43c8-b075-c7fb92f34f36.png">

## Repro Steps / Code Example

```jsx
export default function Home() {
  const { data } = useSWR("123", async (_) => {
    return "done";
  });

  return <div>{String(data)}</div>;
}
```
## Additional Context

SWR version: swr@1.1.2

**Comment by huozhi** [comment]
The new react devtool seems parsing nested function calls of the hook, so you might have to click inside to check out the displayed data. We can polish the name to make `eval` more readable

**Comment by huozhi** [comment]
The outer function name is updated in #1779
