### ISSUE TITLE
Pagination issue with initialData

### ISSUE THREAD

**Issue by fi5u** [vercel/swr#178]
I have a pagination issue when I'm passing `initialData` (from `getInitialProps`) to `useSWR` inside `useSWRPages`.

Every time when the user loads more data from a button press, the first `initialData` set is briefly shown every time, before being replaced by the latest dataset. The _Loading..._ text is never displayed since data is never null due to `initialData`.

I've worked round this issue by using `useRef` for the `initialData` then nullifying it after first render in `useEffect`. However, it feels like this is something that SWR could perhaps handle internally? Or am I missing something built in for this issue?

**Comment by brunomarchioro** [comment]
This is happening to me too. Maybe they can include a parameter that lets we pass the initialData to the useSWRPages hook.

**Comment by lednhatkhanh** [comment]
This also happens for me too, currently,`initialData` doesn't work well with pagination.

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!
