### ISSUE TITLE
1.2.0-beta.1 release does not include mjs files

### ISSUE THREAD

**Issue by Alduino** [vercel/swr#1785]
# Bug report

## Description / Observed Behavior

Version 1.2.0-beta.1 includes #1760 which builds mjs files to support ESModules, however although the new release refers to them in its package.json, the files don't actually exist.

## Expected Behavior

There should be files in the package at `./dist/index.mjs`, `./infinite/dist/index.mjs`, and `./immutable/dist/index.mjs`.

## Repro Steps / Code Example

You can download the tar from https://registry.npmjs.org/swr/-/swr-1.2.0-beta.1.tgz and check for the files.

## Additional Context

SWR version 1.2.0-beta.1

**Comment by huozhi** [comment]
It's fixed in v1.2.0 now 
https://unpkg.com/browse/swr@1.2.0/dist/index.mjs
