### ISSUE TITLE
Fetcher functions seems to be cached by useSWR(?)

### ISSUE THREAD

**Issue by icyJoseph** [vercel/swr#1806]
### Discussed in https://github.com/vercel/swr/discussions/1805

<div type='discussions-op-text'>

<sup>Originally posted by **westmark** January 25, 2022</sup>
_v 1.1.2_

Hi! I have the weirdest bug. Consider this custom hook

```typescript
const useCompanyTeams = (
  companyId: Maybe<string>,
  config: SWRConfiguration = {},
) => {
  const api = useApi<CompaniesApi>('CompaniesApi');

  const rand = Math.random().toString(32).substring(2);
  console.log(rand, companyId, companyId ? companyTeamsKey(companyId) : null);

  return useSWR<Array<Team>>(
    companyId ? companyTeamsKey(companyId) : null,
    (key) => {
      console.log(
        'Calling',
        rand,
        companyId ? companyTeamsKey(companyId) : null,
        key,
      );
      return getCompanyTeams(companyId, api);
    },
    {
      suspense: true,
      ...config,
    },
  );
};
```

(`useApi` returns a generated API with all paths already baked in, and the random value is only for debugging purposes)

During page load, this hook might be called with `companyId` set to `null`, which should yield a null key leading to no data being fetched. Here is the output from the application

```
> 39ftoqmq8ng null null
> 9f0aol3gcgg undefined null
> hass14fndqg null null
> msf3pvqppk8 e6f1a6ba-febf-433c-bb94-eeeae26f6e6b /companies/e6f1a6ba-febf-433c-bb94-eeeae26f6e6b/teams
> calling bl8s3lb5j2o null  /companies/e6f1a6ba-febf-433c-bb94-eeeae26f6e6b/teams
```

The last line above is interesting. 

1. The `rand` variable is logged immediately after its creation, but `bl8s3lb5j2o` which is printed INSIDE the fetcher closure does not appear above, which it should. 
2. Furthermore, `companyId` is `null` inside the closure, but the `key` argument is valid. 

I can't explain 1) at all. This only happens if the hook is invoked with `companyId` set to null before it becomes non-null. If invoked with a non-null value the first time, everything will work and the log will be what your would expect. 

2) seems to suggest that the fetcher(i.e. the closure) is cached inside SWR. Is it?

Can anyone shine some light on this?</div>

**Comment by icyJoseph** [comment]
Will be fixed by #1803

**Comment by DanielJoyce** [comment]
Bumped into this exact same issue.

**Comment by icyJoseph** [comment]
#1803, fixes this issue and has been merged into main.
