### ISSUE TITLE
Default fetcher doesn't fetch anything

### ISSUE THREAD

**Issue by alextes** [vercel/swr#1854]
# Bug report

## Description / Observed Behavior
After upgrading from 0.4.2 to 1.2.1 when trying to fetch with the default fetcher

This doesn't work:
```ts
export const useGroupedData1 = (): FeeData | undefined => {
  const { data } = useSWR<RawFeeData>(`${feesBasePath}/all`, {
    refreshInterval: Duration.millisFromSeconds(4),
  });

  return data === undefined ? undefined : decodeFeeData(data);
};
```

This does:
```ts
export const useGroupedData1 = (): FeeData | undefined => {
  const { data } = useSWR<RawFeeData>(
    `${feesBasePath}/all`,
    async (url: string) => {
      const res = await fetch(url);
      return res.json() as Promise<RawFeeData>;
    },
    {
      refreshInterval: Duration.millisFromSeconds(4),
    },
  );

  return data === undefined ? undefined : decodeFeeData(data);
};
```

Observed behavior is nothing happens at all. I verified that useSWR does get called, undefined gets returned, but the actual request never fires. I tried to dig into the source but it's a bit hard to read after transpilation.

## Additional Context

SWR version: `1.2.1`

**Comment by shuding** [comment]
Please check https://swr.vercel.app/blog/swr-v1#migration-guide, there is no more default `fetcher` since 1.0. You can simply add it if necessary:

```js
(url) => fetch(url).then(res => res.json())
```

**Comment by alextes** [comment]
@shuding alright, I'll add a default fetcher.

How about updating the documentation: https://swr.vercel.app/docs/options

It still says _optional_

**Comment by shuding** [comment]
It is optional — you can skip that option and use SWR for pure state management. For example: https://paco.me/writing/shared-hook-state-with-swr.

**Comment by alextes** [comment]
@shuding sure. I'm guessing that's not what most users are checking the docs for but either way, I feel like we're talking past each other.

I just spent 30min trying to figure out why SWR isn't fetching my resources. No error, no nothing. Docs say omitting the fetcher is fine.

Do you think there's something we can do to help others not fall into the same waste of time?

**Comment by alextes** [comment]
I see. Fair enough! You're the maintainer. I trust your judgement. on that
(:
In that case, I'd suggest to do nothing an wait for a couple 👍, or "me
too" first.
