### ISSUE TITLE
Got a error while import SWR 1.2.2

### ISSUE THREAD

**Issue by marklee1972** [vercel/swr#1868]
### Discussed in https://github.com/vercel/swr/discussions/1867

<div type='discussions-op-text'>

<sup>Originally posted by **marklee1972** February 21, 2022</sup>
I tried to use SWR in my next.js app ,but it's not work.
For excluding other variables, I install a pure page (index.js)from next.js example.
And it's fine to work,until I add a line on the head "import useSWR from 'swr'".

npm run dev console appeared :
_error - SyntaxError: The requested module 'react' does not provide an export named 'useRef'_

My browser appeared:

_Server Error
SyntaxError: The requested module 'react' does not provide an export named 'useRef'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
file:///C:/Users/mark/Downloads/react/fo/nextjs-layout/node_modules/swr/dist/index.mjs (1)
ModuleJob._instantiate
internal/modules/esm/module_job.js (92:21)
async ModuleJob.run
internal/modules/esm/module_job.js (107:20)
async Loader.import
internal/modules/esm/loader.js (179:24)
async importModuleDynamicallyWrapper
internal/vm/module.js (422:15)_

My package.json:
_{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "latest",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "swr": "^1.2.2"
  }
}_

According CatalyticMusa's suggestion,I changed swr version back to 1.1.2.
Then the error disappered.
So I suspected the version.1.2.2 had bug.
</div>

**Comment by huozhi** [comment]
Can you share more details about the node version and next.js you're using? Will be easy to investigate. And also a minimal reproduction so we know how you configured your nextjs project. Thanks 🙏

**Comment by Ajido** [comment]
I have confirmed that this error occurs with Node.js v14.1.0 and that updating to v16.14.1 will work around this.
swr is 1.2.2

**Comment by huozhi** [comment]
I tried to repro with swr latest stable version 1.3 it works well with node 14, can you try to upgrade swr to see if it's resolved?
