### ISSUE TITLE
SWRConfig cache Provider doens't work with Webpack & useSWRInfinite

### ISSUE THREAD

**Issue by Westsaid** [vercel/swr#1880]
# Bug report

## Description / Observed Behavior

A custom provider in the SWRConfig doesn't seem to be working when using Webpack / useSWRInfinite. 
I tried to implement the [LocalStorage Based Persistent Cache](https://swr.vercel.app/docs/advanced/cache#localstorage-based-persistent-cache), somehow in the environment im working with, which is using Webpack to serve React, the Map always stays empty:
![image](https://user-images.githubusercontent.com/58175915/156597953-6fca3692-1c56-496e-a5f1-a80f2585e254.png)

I made a [repo](https://github.com/Westsaid/webpack-useSWR-cache-issue) where you can reproduce this misbehavior, the [src/Test.component.js](https://github.com/Westsaid/webpack-useSWR-cache-issue/tree/main/src/Test.component.js) is where all the React/useSWR Code is in. 

Strangely I found out that this exact same Test.component.js code, is working in this [Vanilla JS Codesandbox](https://codesandbox.io/s/quirky-lake-24sqem?file=/src/Test.component.js)

## Expected Behavior

The custom provider should work in the webpack environment same as in the vanilla sandbox environment.

## Repro Steps / Code Example

Clone the [webpack repo](https://github.com/Westsaid/webpack-useSWR-cache-issue)

- npm run start
- browser should open on localhost:8080
- open dev tools
- click on load more
- click on leave page
- you should land in a breakpoint on line 60 in the Test.component.js file
- appCache is '[]'

Also check the [Vanilla JS Codesandbox](https://codesandbox.io/s/quirky-lake-24sqem?file=/src/Test.component.js) as described

## Additional Context

SWR version: 1.2.2 
I also opened a discussions thread, which is outdated now: https://github.com/vercel/swr/discussions/1879
Use of the useSWRInfinite hook via an reusable data hook: https://swr.vercel.app/docs/getting-started#make-it-reusable

**Comment by huozhi** [comment]
Looks like the issue is caused by different core swr files are resolved:

* First `swr/dist/index.esm.js` is resolved 
* Then `swr/infinite/dist/index.esm.js` is resolved
* The infinite tries to import from swr, but `swr/dist/index.mjs` is resolved

So the default cache has been overriden.

Looks like it's a webpack issue cause it works when I down grade the webpack to previous versions (e.g. `5.16.0`)

**Comment by huozhi** [comment]
Filed https://github.com/webpack/webpack/issues/15484 to see if there's any workaround from webpack side

**Comment by Westsaid** [comment]
@huozhi great work, thanks for finding out and vielen Dank! :)

**Comment by huozhi** [comment]
@Westsaid  Seems that's caused by the plugin `@babel/plugin-transform-modules-commonjs`, I think you can safely remove it from babelrc.

webpack maintainers shared more about it here 👉  https://github.com/webpack/webpack/issues/15484#issuecomment-1060906189

**Comment by Westsaid** [comment]
@huozhi  Thank you so much for your effort! It's working now. 😍
