### ISSUE TITLE
Errors thrown in fetcher are swallowed by SWR

### ISSUE THREAD

**Issue by james-reed-toshi** [vercel/swr#1881]
# Bug report

## Description / Observed Behavior

If an error is thrown in the fetcher given to useSWR, SWR just swallows it and it does not bubble.

## Expected Behavior

How did you expect SWR to behave here?

The error should bubble so that it is obvious what is broken.

## Repro Steps / Code Example

https://codesandbox.io/s/react-swr-forked-5k8fhr?file=/src/useRequest.js

The example here is a bit contrived, but it's entirely possible that the commented out `transformData` function has a bug which isn't immediately obvious, and thus an error is thrown.

## Additional Context

Versions of libraries etc are in the codesandbox.

**Comment by huozhi** [comment]
If the error is thrown during the procedure of hook it will break the whole render all the time. 

SWR stores the `error` as property in returned value which lets you to check out the error in the declarative way of hooks. You can do:

```
const { data, error } = useSWR(key, fetcher)
```

Or for development convenience you can use `onError` config to log the errors per hook or globally. Checkout [swr error-handling docs](https://swr.vercel.app/docs/error-handling#global-error-report)

**Comment by james-reed-toshi** [comment]
Hi @huozhi 

You can clearly see in the codesandbox I linked that `error` is empty and so is the `err` in `onError`. Absolutely nothing about the error is provided to the consumer of the hook at all, making it impossible to find out what's going on without removing SWR temporarily and replacing it with fetch and then running the same code to find out what was actually the problem.

**Comment by huozhi** [comment]
You're using JSON.stringify for the error then it doesn't show everything of the error. You can change it to `error && error.toString()` then it display the error message `Error: oops i made a code mistake here` there correctly.
