### ISSUE TITLE
return wrong in Demo Infinite scroll when the data is []

### ISSUE THREAD

**Issue by sunran** [vercel/swr#1886]
# Bug report

## Description / Observed Behavior

when use useSWRInfinite  and the data is [] in first load , the demo show the message both 'isloading' and 'no more'

## Expected Behavior

How did you expect SWR to behave here?

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version.

**Comment by huozhi** [comment]
Hi, can you elaborate what do you expect here I didn't quite understand about you question. The initial loading is intended to show "loading.." and I didn't see the "no more shows up in the very early phase".

Could you share more about the context and errors if you see any? Thanks

**Comment by sunran** [comment]
mock the 'fetcher' method return []  like this :
![aa](https://user-images.githubusercontent.com/391591/156952062-bb52e361-e29f-4348-abba-dad055b8a6b1.jpg)
and the result show :
![bb](https://user-images.githubusercontent.com/391591/156952097-87b1b0a8-7f93-4d7b-a799-d5dd65376ffe.jpg)

**Comment by shuding** [comment]
Can't reproduce this issue with https://swr.vercel.app/examples/infinite-loading, if you have a reproduction feel free to post it here and I'll reopen this issue, thanks!
