### ISSUE TITLE
React 18 in concurrent mode + Cache provider

### ISSUE THREAD

**Issue by piotr-cz** [vercel/swr#1904]
# Bug report

## Description / Observed Behavior

When using React 18 in concurrent mode and a custom [cache provider](https://swr.vercel.app/docs/advanced/cache), an error is thrown:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at useSWRHandler (index.esm.js:631:1)
```

This happens when using [create-react-app](https://www.npmjs.com/package/create-react-app) v4 or v5 in dev mode (`react-scripts start`), however not when running an actual build (`react-scripts build`).

## Expected Behavior

No error is thrown

## Repro Steps / Code Example

CodeSandbox based on [Basic usage](https://swr.vercel.app/examples/basic) is available here: <https://codesandbox.io/s/eager-alex-zyijly?file=/src/index.js>:

1. Update react and react-dom to 18.0 or 18.1 in dependencies, enable concurrent mode (`ReactDOM.createRoot(rootElement).render(...)`)
2. Add new provider `const provider = () => new Map();`
3. Wrap `<App />` with `<SWRConfig value={{ provider }}></SWRConfig>`

## Additional Context

SWR version: 1.1.0 ... 1.3.0 || 2.0.0-beta.0 || 2.0.0-beta.1
Latest version with no error: 1.0.1

It looks like the `SWRGlobalState` WeakMap in the `useSWRHandler` function doesn't contain custom cache provider, even that it has been successfully added in `initCache` function.

**Comment by emreycolakoglu** [comment]
Hey, this breaks us pretty bad too. Had to create a workaround using middlewares for my use-case (persistance) but it's far from perfect.
Is there a workaround?

**Comment by piotr-cz** [comment]
Any workarounds I know of is downgrading react to v17 or swr to v1.1.
I guess this issue will receive more attention when people will start upgrading react to v18.

**Comment by shuding** [comment]
React 18 support will be our top priority for 2.0 and it’s in the works.

**Comment by promer94** [comment]
This should works in latest beta version now.
[codesandbox](https://codesandbox.io/s/runtime-tree-b2fh33?file=/src/index.js)

**Comment by piotr-cz** [comment]
@promer94 
I cannot completely confirm, as upgrading swr in [my sandbox](https://codesandbox.io/s/eager-alex-zyijly?file=/src/index.js) to 2.0.0-beta.3 as well as downgrading in yours yours leads to
```
ModuleNotFoundError
Could not find module in path: 'swr' relative to '/src/index.js'
```
I have no idea what's going on

**Comment by promer94** [comment]
@piotr-cz could you try to refresh the page. I had same problem but works after reloading page. I think it might be some cache problem of codesandbox.

**Comment by piotr-cz** [comment]
@promer94 
Thanks, it works!

right click into result page -> Reload Frame

**Comment by shuding** [comment]
Great! I guess we can close this issue now? 😁
