### ISSUE TITLE
Keep previous result while revalidating

### ISSUE THREAD

**Issue by Svish** [vercel/swr#192]
Is there an easy way, or if one could be added, to have `useSWR` keep the previous result while revalidating?

My case is a search field, and after I've gotten my first `data`, I'd really like the returned `data` to stick until a new request has completed (or failed). Currently the `data` goes back to `undefined` whenever the key changes.

**Comment by isBatak** [comment]
That means it's not `stale` xD
🤔 should we call this lib `uwr` :P

@quietshu sorry for the joke, I just couldn't resist... 
I made a reproduction sandbox example, you can check it here https://codesandbox.io/s/swr-issue-192-qq880
I hope this will get fixed soon.
Thx!

**Comment by Svish** [comment]
It should probably be an option though, because in other cases it's probably a good thing that it does go through `undefined`. 🤔

I suppose making it an option would also mean it could be added without breaking any existing usage. 👍

**Comment by isBatak** [comment]
I'm not sure... `data` should always be stale. 
If you need it to be undefined you can do this:
`const weirdData = isValidating ? undefined : data;`

**Comment by quietshu** [comment]
> Currently the data goes back to undefined whenever the key changes.

This is intended. The reason of this behavior is that although SWR returns stale data, it can't return **wrong data**. The `data` value should always be the result of that exact key. 

But I agree here from the real world use cases, it can be an option to disable the strict key-data consistency.

**Comment by isBatak** [comment]
What do you mean by **wrong data**?

**Comment by Svish** [comment]
@isBatak If you're starting out a loaded `const { data } = useSWR('foo', fetcher)`, and then switch the key to `'bar'`, then `data`, if it stuck around, would be the wrong data because it belongs to `'foo'`, not `'bar'`.

So that should be the default, but yeah, would be great with an option to switch how that works.

**Comment by sergiodxa** [comment]
If you ask SWR to give you `/api/users?id=1` and then you ask for `/api/users?id=2` in the component (let's say the id was a state) returning the data of the id 1 it's the wrong data, because the user expects the data of the user 2 and that is not yet cached, if you go back to the id 1 it will return the previously cached data while it's revalidating and this is working since I used it a lot of times.

I think this will be solved once `useTransition` is stable, then you will be able to wrap the state change of the id in a `startTransition` and let React keep rendering the component with id 1 until the data of 2 arrives, or a lot of time has passed.

**Comment by Svish** [comment]
@sergiodxa What is this `useTransition` you speak of? Sounds interesting. 🤔

**Comment by sergiodxa** [comment]
It's a new React hook coming with Concurrent Mode: https://reactjs.org/docs/concurrent-mode-reference.html#usetransition

A component using it together with SWR would look like this:

```js
const SUSPENSE_CONFIG = { timeoutMs: 1000 };

function User() {
  const [id, setID] = React.useState(null);
  const [startTransition, isPending] = useTransition(SUSPENSE_CONFIG);
  const { data } = useSWR(id ? `/api/users?id=${id}` : null, fetcher, { suspense: true });

  function handleChange(event) {
    const newID = event.target.value;
    startTransition(() => {
      setID(newID);
      mutate(`/api/users?id=${newID}`, fetcher(`/api/users?id=${newID}`));
    });
  }

  return (
    <>
      <input type="text" onChange={handleChange} value={id} />
      {isPending && <Spinner />}
      {data && 
        <h1>{data.username}</h1>
      }
    </>
  );
}
```
Something like that, without trying to run it so it may had typos, the idea here is to to tell React keep rendering what it's already on screen until the new UI triggered by setID and mutate it's ready or the value of `timeoutMs` has passed (a second in the example), meanwhile you get the `isPending` boolean to show to the user you are updating it but without clearing the old data.

**Comment by isBatak** [comment]
if we pass array as key, for example `['foo', fetcherDep1, fetcherDep2]`, could we treat first element as a key and the rest as deps for revalidation?

**Comment by Svish** [comment]
I think it's better to just add a `stickyResult: boolean` option, rather than making that key/deps thing even more confusing 😛

**Comment by quietshu** [comment]
For now you can use a custom hook for that:

```js
function useStickyResult (value) {
  const val = useRef()
  if (value !== undefined) val.current = value
  return val.current
}
```

Together with SWR:
```js
const { data } = useSWR('/user?' + id)
const stickyData = useStickyResult(data)
```

Or combine them into a new hook:
```js
function useStickySWR (...args) {
  const swr = useSWR(...args)
  const stickyData = useStickyResult(swr.data)
  swr.data = stickyData
  return swr
}
```

Adding an option `stickyResult: boolean` is a bit tricky because we need to consider errors too.

**Comment by isBatak** [comment]
@quietshu is this custom hook still relevant? 
I'm asking because of this merge https://github.com/zeit/swr/pull/186
`swr.data` is getter now, and `isValidating` is always false for some reason...

**Comment by stevewillard** [comment]
Ran into the same issue, and I don't think the above `useStickySWR` works, since as you mentioned @isBatak, you can't modify it.

Has any else worked around this? I want to differentiate _initial_ loading vs _reloading_ (with maybe slightly different params).

**Comment by isBatak** [comment]
@stevewillard I changed `useStickySWR` a bit
```
import { useRef } from 'react';
import useSWR from 'swr';

export function useStickySWR(...args) {
  const val = useRef();

  const { data, isValidating, error, ...rest } = useSWR(...args);

  if (data !== undefined) {
    val.current = data;
  }

  return {
    ...rest,
    isValidating,
    error,
    data: val.current,
  };
}
```
But now it is deoptimized and will re-render component whether you use some pros or not. 
But in my case, it is good enough solution.

**Comment by raj-altrio** [comment]
How would this work in Suspense mode?
If I want the sticky hook to work with suspense would I just catch the promise from useSWR here instead of checking if data is undefined?

**Comment by bobbyhadz** [comment]
Is there a good way to do this now? 

Can we keep **wrong data** rendered until we fetch **right data**, `useTransition` style?

I.e. in pagination, it seems a very bad user experience to show the loading skeleton (the suspense fallback) between page transitions, I'd much rather display a loading spinner to indicate a transition is taking place.

I'm new to `swr`, so apologize if I'm missing something.

**Comment by RobbyUitbeijerse** [comment]
@bobbyhadz I would consider the solution provided by @isBatak 'good enough' in a sense that it works, but it would indeed be a great feature to have withint SWR itself. 

My current situation is as follows:

1. On the server (in the build pipeline) I'm getting both items and filters - both returned by a single endpoint
2. I'm passing the data through initialData to hydrate the SWR cache and render the UI during build
3. When a user filters using one of the filter options, we build a unique key based on the combined filter options and revalidate the data
4. In the new response, only filters that will actually lead to actual results will be present (filters that will lead to 0 results will be removed)

This all works ok, but it results in the following quirk that could be considered weird/buggy from a user perspective:

While filtering, during revalidating, the user sees vacancies and filter options that were initially provided through initialData. Even when these items and filters might not even be relevant to the user anymore. In case of a mediocre performing API / a slow connection this just feels off/unacceptable.

Here's a clip of the situation:
https://user-images.githubusercontent.com/10176709/115119553-3ad10b80-9fa9-11eb-92d2-55a7ba0b1802.mp4

**Comment by shuding** [comment]
We've made a handle middleware for this use case: [Keep Previous Result](https://swr.vercel.app/docs/middleware#keep-previous-result). You can easily customize it based on your own use case.

Please also check the [SWR 1.0 blog post](https://swr.vercel.app/blog/swr-v1)! 🎉

**Comment by shuding** [comment]
Reopening as I think this can be a good built-in feature.

**Comment by rauchg** [comment]
Also worth noticing that this is impacting us when you press "back" and it loses your search state.

![CleanShot 2022-02-16 at 16 01 10](https://user-images.githubusercontent.com/13041/154377993-e58dc892-3605-4c22-90a3-3fc3cf721571.gif)

**Comment by Macfly** [comment]
> ```js
> handleChange
> ```

is the middle still the best way to handle this kind of situation?

**Comment by steven-tey** [comment]
Facing the same issue as @dqunbp! Even when I remove the `fallbackData` option, it still returns the `fallbackData` content for some reason (even with `laggy` middleware)

**Comment by shuding** [comment]
Aiming to add a built-in solution for this in the upcoming 2.0 version.

**Comment by shuding** [comment]
My first step is to add #1925, which completes the necessary states to implement laggy and fallback. And then, we will look for a way to enable the laggy middleware via just one option `{ laggy: true }`. The only thing bothers me is we can't easily tree-shake it away when not used, maybe not a big deal :)

**Comment by steven-tey** [comment]
Can confirm that adding `keepPreviousData: true` as an option in `SWRConfiguration` works perfectly for me 🤩 

https://github.com/vercel/swr/pull/1925

@dqunbp feel free to try this out and let me know if it works as well ^

**Comment by ItsTarik** [comment]
Very useful when paginating tables !
