### ISSUE TITLE
swr mutation cjs output is using module.exports instead of exports.default

### ISSUE THREAD

**Issue by huozhi** [vercel/swr#1923]
# Bug report

## Description / Observed Behavior

Latest branch swr mutation cjs output is using `module.exports`, and output warning for commonjs output

## Expected Behavior

Should build like other subpath packages, output `exports.default` instead

**Comment by shuding** [comment]
Is this a bug of Bunchee or something we're doing wrong here?

**Comment by huozhi** [comment]
I'm still checking, not sure the root cause yet
