### ISSUE TITLE
Q: useSWR doesn't work as expected

### ISSUE THREAD

**Issue by Luncher** [vercel/swr#1950]
# Bug report

## Description / Observed Behavior

When revalidateOnFocus takes effect, in the process of requesting data, the component will keep the last data obtained. But when a request occurs when the request parameters change, the data obtained by the component will first become `fallback data`. I don't understand Why is this behavior different?

## Expected Behavior

The two behaviors should be consistent, and should not get `fallbackData` when re-requesting data

## Repro Steps / Code Example

[demo](https://stackblitz.com/edit/react-swr-issue?file=App.tsx)

## Additional Context

SWR version. v1.3.0

**Comment by shuding** [comment]
Because when you change the key (request parameters), it’s not identified as the same resource anymore. You might need the new `keepPreviousData` option in 2.0.0@beta.1

**Comment by Luncher** [comment]
Thank you for your enthusiastic reply. I thought about it, and there seems to be no scene of `keepPreviousData` turned off in the actual project. Is there any more info on this `keepPreviousData` ? Is it on or off by default?
