### ISSUE TITLE
UseSwr being called twice, i have done everything but fetched is called twice

### ISSUE THREAD

**Issue by Jazzykhan** [vercel/swr#1952]
# Bug report

## Description / Observed Behavior
with simple next.js project i am suing useSwr in index.js and i saw that 
console.log(data);
just after useSwr is called twice no matter what.

What kind of issues did you encounter with SWR?
data is being fetched twice.

## Expected Behavior
It should be fetched once only.

How did you expect SWR to behave here?
twice calling?

## Repro Steps / Code Example
_app.js
`
import "../styles/globals.css";
import "antd/dist/antd.css";
import { Layout, Menu, Breadcrumb } from "antd";
import Home from ".";
import MainMenu from "./navbars/main-menu";
const { Header, Content, Footer } = Layout;
import { QueryClient, QueryClientProvider } from "react-query";
import { ReactQueryDevtools } from "react-query/devtools";
const queryClient = new QueryClient();

function MyApp({ Component, pageProps }) {
  // return <Component {...pageProps} />
  return (
    Layout
      Home 
    Layout
  );
}

export default MyApp;

`
index.js
`
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import useSWR from "swr";
const fetcher = (url) => fetch(url).then((res) => res.json());
export default function Home() {
  const { data, error } = useSWR("https://reqbin.com/echo/get/json", fetcher);
 

  console.log(data);

  return (
    <div>
      <h1>Done</h1>
    </div>
  );
}

`
Screenshot of issue:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/31903098/167013970-6be2d204-2096-4e60-b9fa-e68c586817f6.png">

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version. 

"swr": "^1.3.0"

**Comment by beforan** [comment]
If you're using React 18 and `StrictMode`, it's likely this is the result of intentional React behaviour:

https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state

> With Strict Mode starting in React 18, whenever a component mounts in development, React will simulate immediately unmounting and remounting the component

basically `useEffect` and friends **will** run twice, in development mode only.

**Comment by davidecrs** [comment]
Hi @Jazzykhan ,

I was able to avoid multiple fetching of the same data with `useSWRImmutable`: https://swr.vercel.app/docs/revalidation#disable-automatic-revalidations

Best regards
Davide

**Comment by qqc0821** [comment]
I meet the same problem and I try this approach as above.
I revise the fetch function like useSWRImmutable but it doesn't work.

**Comment by ZhenFTW** [comment]
Yeah same issue as of now, I noticed that my code is being logged twice thus as soon as I use useSWR. 
Here is my code example.
```
import useSWR from "swr";

const fetcher = url => fetch(url).then(r => r.json());

export default function Home() {
  const { data } = useSWR("https://dog.ceo/api/breeds/image/random", fetcher, {
    revalidateIfStale: false,
    revalidateOnFocus: false,
    revalidateOnReconnect: false
  });

  console.log("it is being called twice");

  return (
    <div></div>
  );
}
```
The console log below:
![image](https://user-images.githubusercontent.com/17694257/183021273-13520536-c088-4074-a7d8-ec5adc045320.png)

**Comment by bubuq3** [comment]
same here :D But in my case it is called 2 times as a page first load(as you menioted). In addition I got a search bar and when I type a one letter in `input` field the data is fetched 4 times.  I got `getServerSideProps` data to be cached in `fallbackData`

![image](https://user-images.githubusercontent.com/62507500/191516407-42c7fad9-c86e-4b00-a650-b7d5a82140a0.png)


my swr fetch
```js
const { data, error } = useSWR(
    [
      process.env.NEXT_PUBLIC_GRAPHCMS_ENDPOINT,
      `
         query getSugars($searchValue: String $skip: Int) {
        sugarsConnection(orderBy: createdAt_DESC, where: {title_contains: $searchValue}, first: 6, skip: $skip) {
          edges {
            node {
              title
              tags
              description {
                raw
              }
              id
              slug
              coverImage {
                url
              }
              price
              brand
              stock
              isNewProduct
              isOnDiscount
              discountValue
            }
          }
          pageInfo {
            hasNextPage
            hasPreviousPage
            
          }
        }
      }   
  `,
      searchValue,
      skip,
    ],
    (endpoint, query) => fetcher(endpoint, query, { searchValue, skip }),
    {
      fallbackData: sugars,
      revalidateOnFocus: true,
    }
  );
```

ssr fetch 
```js
export const getServerSideProps: GetServerSideProps = async () => {
  const data = await fetcher(
    process.env.GRAPHCMS_ENDPOINT,
    `
    query getSugars() {
      sugarsConnection(orderBy: createdAt_DESC, first: 6, skip: 0) {
        edges {
          node {
            title
            tags
            description {
              raw
            }
            id
            slug
            coverImage {
              url
            }
            price
            brand
            stock
            isNewProduct
            isOnDiscount
            discountValue
          }
        }
        pageInfo {
          hasNextPage
          hasPreviousPage
          pageSize
        }
      }
    }
    
  `
  );

  return {
    props: {
      sugars: data,
    },
  };
};
```

**Comment by maurice-ellis** [comment]
I'm having the same issue

**Comment by GouthamJM** [comment]
I am also facing the same issue

**Comment by Displee** [comment]
I only have this issue when using useSWR in a hook.

**Comment by promer94** [comment]
Example:  https://codesandbox.io/s/swr-1952-forked-zqncu5?file=/src/App.js

When using SWR

* Fetcher will only be called once
* Component will render twice (four times in strict mode) 
   first `data -> undefined`
   second `data -> somthing`
* see more details in https://swr.vercel.app/docs/advanced/performance

**Comment by markhuang19994** [comment]
I use Vite, and this is my stupid way
```typescript
import { AxiosRequestConfig } from 'axios';
import { useEffect, useMemo, useRef } from 'react';

// ref: https://vitejs.dev/guide/env-and-mode#node-env-and-modes
const isStrictMode = import.meta.env.MODE !== 'production';

export function useReqCancel(reqConfig: AxiosRequestConfig, cancelableReq: boolean) {
  const firstCancel = useRef(true);
  const abortController = useMemo(
    () => (cancelableReq ? new AbortController() : null),
    [cancelableReq]
  );
  if (abortController) {
    reqConfig.signal = abortController.signal;
  }

  useEffect(() => {
    return () => {
      if (firstCancel.current && isStrictMode) {
        firstCancel.current = false;
        return;
      }
      firstCancel.current = false;

      if (cancelableReq) {
        abortController?.abort();
      }
    };
  }, [cancelableReq, firstCancel, abortController]);
}
```

**Comment by carlos-menezes** [comment]
An easier route is to add `dedupingInterval: Infinity` to the `useSWR` options.
