### ISSUE TITLE
infinite's compare function is unpredictable 

### ISSUE THREAD

**Issue by JackCA** [vercel/swr#1958]
# Bug report

## Description / Observed Behavior

swr/infinite's `compare` function is called both with the array of pages, and the pages themselves. This doesn't seem to be documented anywhere

## Expected Behavior

This should be in the docs, but even more ideally I think there should be an API change (maybe before 2.0 is released?) for explicitly calling `compareAll` and `comparePage` (or something to that effect)

## Repro Steps / Code Example
previous discussion with example https://github.com/vercel/swr/discussions/1615

## Additional Context
swr 1.3.0

I initially thought the types were wrong and opened https://github.com/vercel/swr/pull/1957 but am just now realizing `compare` is called with different types (so that technically should be a union of both)

**Comment by shuding** [comment]
Great call! I think compare should only be called for individual pages, instead of the pages array.

**Comment by promer94** [comment]
The type of `compare` fn in `swr/infinite` has been fixed in #2431
