### ISSUE TITLE
Race condition with optimisticData and rollbackOnError

### ISSUE THREAD

**Issue by garipov** [vercel/swr#1965]
# Bug report

## Description / Observed Behavior

Hey there! First of all thank you for your great job! SWR looks very powerful to use.
However there's some weird behaviour I noticed during learning documentation and examples.
I used original example of optimistic updates and faced with unclear behaviour.
If 2 mutates are called in a short period of time, and both are failed, the "previous" optimisticData would be written into the cache.
Better to show in short [video](https://drive.google.com/file/d/1-W4hKG_xYGboqmZTbH4nOJBYcg-vOOfX/view).

## Expected Behavior

In this particular case I expect the cache shouldn't be changed. However in general it looks like there's some option is needed that allows to control the cache value in terms of the fetch is failed.

## Repro Steps / Code Example

You also able to reproduce this case in my [sandbox](https://codesandbox.io/s/swr-basic-forked-fcss5o?file=/src/App.js). Just click add button twice and you'll see there's both mutations failed, while one todo item is left in the list.

## Additional Context

SWR version: 1.3.0

**Comment by shuding** [comment]
Thanks for the detailed reproduction!
