### ISSUE TITLE
Misbehavior of the error state from useSWRMutation

### ISSUE THREAD

**Issue by shuding** [vercel/swr#1973]
I am having a little bit of trouble understanding how the error handling works with `useSWRMutation`. I copied the example from https://swr.vercel.app/examples/error-handling but updated it to use `useSWRMutation` and `trigger` instead of `useSWR` and `mutate`. Here is a code sandbox of that: https://codesandbox.io/s/exciting-ives-rvxuh2?file=/src/App.tsx

A couple things I noticed: 

* when the fetcher throws an error, it doesn't seem to be caught completely
* when there is an error followed by a successful call, the error does not clear

These two behaviors are different from `useSWR` with `mutate`. Am I thinking about `useSWRMutation` and `trigger` incorrectly?

_Originally posted by @ericponto in https://github.com/vercel/swr/discussions/1919#discussioncomment-2688176_

**Comment by anirudh1713** [comment]
Hi @shuding, can I take this on?

**Comment by anirudh1713** [comment]
> * when the fetcher throws an error, it doesn't seem to be caught completely

I think this is because of this line -
https://github.com/vercel/swr/blob/526b6508b93c9f53c6a875a238fd9d0b38456e5c/mutation/index.ts#L79
> * when there is an error followed by a successful call, the error does not clear

And this one is caused by not updating ther `error` state to `undefined` here -
https://github.com/vercel/swr/blob/526b6508b93c9f53c6a875a238fd9d0b38456e5c/mutation/index.ts#L70

**Comment by shuding** [comment]
@anirudh1713 Thanks! Feel free to open a PR 👍 

Although I think re-throwing the error should be the correct behavior here — when using `trigger` it should be wrapped with try-catch. But agree with the second issue.

**Comment by anirudh1713** [comment]
> when the fetcher throws an error, it doesn't seem to be caught completely
@shuding so this is actually wrong as the reporter didn't handle error manually (by try-catch)? and the current behaviour is actually correct?

Also if that is true, what do you think about having `triggerSync` and `triggerAsync` both?

- `triggerSync` would not return a `promise` and therefore users don't have to manually catch errors
- `triggerAsync` would return a `promise<T>`, so user can access the data on fly and they'll have to catch errors themselves.

:thinking:

**Comment by shuding** [comment]
> Also if that is true, what do you think about having triggerSync and triggerAsync both?

That's an interesting proposal! I can see both pros and cons here, I think we can make it a separate discussion and take some time to polish that idea 👍

**Comment by ericponto** [comment]
The behavior of catching the error from the fetcher through the trigger is still confusing to me in 2.0.0-rc.0.

I have updated this example to include the latest rc version: https://codesandbox.io/s/exciting-ives-rvxuh2?file=/src/App.tsx

What I am seeing is that wrapping the `trigger` in try/catch is not catching the error. It is still thrown from the `fetcher`.

**Comment by koba04** [comment]
@ericponto 
You can catch the error by changing the event handler to an async function and await the `trigger()`.

```jsx
        onClick={async () => {
          try {
            await trigger();
          } catch (e) {
            console.log(e);
          }
        }}
```

**Comment by ericponto** [comment]
@koba04 perfect, that makes total sense. Thank you.

**Comment by frouo** [comment]
It seems we can avoid `trigger()` to throw on error by setting the option `throwOnError` to `false` (default is true)

```js
const { trigger, error } = useSWRMutation('/api/user', updateUser, { throwOnError: false })

const onClick={() => {
  trigger('my_token') // <- this won't throw in case of error
}}
```

Ref: https://swr.vercel.app/docs/mutation#parameters

**Comment by harrygreen** [comment]
> It seems we can avoid `trigger()` to throw on error by setting the option `throwOnError` to `false` (default is true)
> 
> 
> 
> ```js
> 
> const { trigger, error } = useSWRMutation('/api/user', updateUser, { throwOnError: false })
> 
> 
> 
> const onClick={() => {
> 
>   trigger('my_token') // <- this won't throw in case of error
> 
> }}
> 
> ```
> 
> 
> 
> Ref: https://swr.vercel.app/docs/mutation#parameters

Thanks. With `throwOnError: false`, this works perfectly as expected now: errors thrown inside `fetcher` are handled and passed to the `error` in the response. 

I don't understand how this isn't the default.

**Comment by silcro-123** [comment]
<svg viewBox="0 0 24 24" width="24" height="24" class="darkToggleIcon_wfgR"><path fill="currentColor" d="M9.37,5.51C9.19,6.15,9.1,6.82,9.1,7.5c0,4.08,3.32,7.4,7.4,7.4c0.68,0,1.35-0.09,1.99-0.27C17.45,17.19,14.93,19,12,19 c-3.86,0-7-3.14-7-7C5,9.07,6.81,6.55,9.37,5.51z M12,3c-4.97,0-9,4.03-9,9s4.03,9,9,9s9-4.03,9-9c0-0.46-0.04-0.92-0.1-1.36 c-0.98,1.37-2.58,2.26-4.4,2.26c-2.98,0-5.4-2.42-5.4-5.4c0-1.81,0.89-3.42,2.26-4.4C12.92,3.04,12.46,3,12,3L12,3z"></path></svg>
