### ISSUE TITLE
Beta feedback issue: isLoading and isValidating are changing indefinitely like in a loop in 2.0.0-beta.3

### ISSUE THREAD

**Issue by mislavmiocevic** [vercel/swr#1974]
# DISCLAIMER
I am using beta version, and I want to give an early feedback. Probably you will encounter the issue but I wanted to help a bit. Sorry but I do not have a time atm to dig more. Ignore this issue if you do not take bug reports for beta versions.
And thanks for SWR 2 :)

# Bug report

## Description / Observed Behavior

isLoading and isValidating is updating all the time from true to false and again in a loop even if there is no revalidation or mutation.

## Expected Behavior

If there is no mutation or revalidation, `isLoading` and `isValidating` props should NOT transition from true to false and again in a loop.

## Additional Context

It is working in SWR version: 2.0.0-beta.1
It is **NOT** working in SWR version: 2.0.0-beta.3

**Comment by promer94** [comment]
Thanks for reporting. 
Would you mind create a repro based on [this codesandbox](https://codesandbox.io/s/loading-nh4jtc). It would be really helpfull

**Comment by mislavmiocevic** [comment]
@promer94 here it is (I also updated the codesandbox example):

```
import "./styles.css";
import useSWR from "swr";

const fetcher = async (url) => {
  await new Promise((resolve) => {
    setTimeout(() => resolve(true), 2000);
  });

  return "hello";
};

const useDummyData = () => {
  return useSWR("some-key", fetcher);
};

const Child = () => {
  const { data } = useDummyData();

  if (!data) {
    return null;
  }

  return <div>{data}</div>;
};

const Parent = () => {
  const { data, isLoading, isValidating } = useDummyData();

  console.log('hi');
  
  if (isValidating) {
    return "Loading...";
  }

  return (
    <div>
      <div>{data}</div>
      <Child />
    </div>
  );
};

export default function App() {
  return (
    <div className="App">
      <Parent />
    </div>
  );
}
```

For some reason, when using `swr` with the same key in the parent and in the child, and if there is `isValidating` usage such as return loading state, then the component gets into some loop. It is not behaving like that in `v2.0.0-beta.1`

https://user-images.githubusercontent.com/67387665/169483174-74edf845-15bc-4c02-9f72-f1de197091fa.mov
