### ISSUE TITLE
Fetcher never called when testing a `useSWR` hook with `fallbackData` with `react-test-render`

### ISSUE THREAD

**Issue by Ploppy3** [vercel/swr#1985]
# Bug report

## Description / Observed Behavior

The fetcher is never called when testing a `useSWR` hook with `fallbackData` with `react-test-render`

## Expected Behavior

When testing `useSWR` hook with `fallbackData` with `react-test-render` with `revalidateOnMount` set to `true` the fetcher should be called and wait for the mocked response so that the data could be used to generate the snapshot.

## Repro Steps / Code Example

```jsx
const fetcher = (url) => fetch(url).then((res) => { console.log("ok"); return res.json() });

function Component() {
  const { data } = useSWR("https://a.com", fetcher, {
    fallbackData: "init",
    revalidateOnMount: true, // even forcing revalidation of fallback data on mount
  });

  return <>{data}</>;
}
```

```jsx

fetch.mockResponse((req) => {
  return Promise.resolve({
    status: 200,
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify("the-data"),
  });
});

let root;
await act(async () => {
  root = create(
    <SWRConfig value={{ provider: () => new Map() }}>
      <Component />,
    </SWRConfig>
  );
});
expect(root).toMatchSnapshot();
```

```
Snapshot: "init"
```
(instead of `the-data`)

## Additional Context

SWR version. 
1.3.0

**Comment by shuding** [comment]
It seems that you are checking the initial render result, which is expected to be the fallback data. The actual response will be returned asynchronously so you'll have to wait a bit and check the rendered result again ([an example](https://github.com/vercel/swr/blob/main/test/use-swr-focus.test.tsx#L55-L61)). 

If that's not the case, could you create a reproduction on [stackblitz.com](https://stackblitz.com)? Happy to take a look!

**Comment by Ploppy3** [comment]
**Please do not aggressively close issues until acknowledge, that's not how problems are solved.**

Reproduction is provided.

The render is asynchronous. Check the `act` method.

I don't have time currently to setup a stackblitz example. It would be easier if you provided a starter.

Please re-open the issue.

**Comment by Ploppy3** [comment]
@shuding ping

**Comment by Ploppy3** [comment]
@shuding the problem persists, can you please reopen. There was no reason to close it.
