### ISSUE TITLE
Using provider doesn't work

### ISSUE THREAD

**Issue by blackhu0804** [vercel/swr#1996]
# Bug report

## Description / Observed Behavior

I use the cache as instructed on the documentation, but the cache I get is empty and I don't know what's wrong. Documentation needs more detail.

## Expected Behavior

I expect that the cache can be fetched from local and initialized.

## Repro Steps / Code Example

https://codesandbox.io/s/vigorous-poincare-h3m3vd?file=/src/App.js

## Additional Context

1.3.0

**Comment by shuding** [comment]
`SWRConfig` should wrap your components and hooks, not the displayed data. It works like a React context provider: 

https://swr.vercel.app/docs/global-configuration

**Comment by blackhu0804** [comment]
> `SWRConfig` should wrap your components and hooks, not the displayed data. It works like a React context provider:
> 
> https://swr.vercel.app/docs/global-configuration


I followed this document. I don't know where is the problem.I want to store cached data locally.

https://swr.vercel.app/docs/advanced/cache#localstorage-based-persistent-cache

**Comment by shuding** [comment]
Hey @blackhu0804! The docs have this example:

```jsx
<SWRConfig value={{ provider: localStorageProvider }}>
  <App/>
</SWRConfig>
```

Where `SWRConfig` wraps the top-level component `<App/>` which has `useSWR` inside. But in your example it's wrapping the data, not the `useSWR` hook:

```jsx
<SWRConfig value={{ provider: localStorageProvider }}>
  <h1>{data}</h1>
</SWRConfig>
```

Instead, you need to move it up to index.js: https://codesandbox.io/s/awesome-grass-leutqx?file=/src/index.js

**Comment by pociej** [comment]
@shuding indeed example says : 

```
<SWRConfig value={{ provider: localStorageProvider }}>
  <App/>
</SWRConfig>
```

and 

```
function localStorageProvider() {
  // When initializing, we restore the data from `localStorage` into a map.
  const map = new Map(JSON.parse(localStorage.getItem('app-cache') || '[]'))

  // Before unloading the app, we write back all the data into `localStorage`.
  window.addEventListener('beforeunload', () => {
    const appCache = JSON.stringify(Array.from(map.entries()))
    localStorage.setItem('app-cache', appCache)
  })

  // We still use the map for write & read for performance.
  return map
}
```
Let try to use it with next js.t The it throws 'window is udnefined'.  Here is similar issue https://github.com/vercel/swr/issues/2113 where authro suggest to check if `typeof window === 'undefined' to prevent window usage on SSR. But then it throws hydration error. What is proper approach to use nextJs with localStorage as swr cache ?
