### ISSUE TITLE
suspense documentation may need updating

### ISSUE THREAD

**Issue by laurencefass** [vercel/swr#2028]
# Bug report
This isnt a software bug, more of a document error/query, but you dont have  a issue classification for that.

## Description / Observed Behavior
https://swr.vercel.app/docs/suspense says:

```
Suspense is currently an experimental feature of React. These APIs may change significantly and without a warning before they become a part of React.... Note that React Suspense is not yet supported in SSR mode.
```
I think Suspense SSR is now a feature....

https://github.com/reactwg/react-18/discussions/37

Is this documentation still relevant/up-to-date?

Thanks

What kind of issues did you encounter with SWR?

## Expected Behavior

How did you expect SWR to behave here?

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version.

**Comment by guilherssousa** [comment]
You could open the issue or even a PR correcting the observed notes on the official docs repo [vercel/swr-site](https://github.com/vercel/swr-site).

**Comment by shuding** [comment]
Suspense is still not recommended for data-fetching libraries, please see #1906 for more details.
