### ISSUE TITLE
isLoading: wrong state

### ISSUE THREAD

**Issue by khasbilegt** [vercel/swr#2030]
# Bug report

## Description / Observed Behavior

Sometimes, the value of isLoading returned by useSWR is true when there is data and no errors.

## Expected Behavior

The isLoading should be false when there is data returned from useSWR.

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version: [2.0.0-beta.3](https://github.com/vercel/swr/releases/tag/2.0.0-beta.3).

**Comment by shuding** [comment]
Hi! Do you have a way to easily reproduce this? Thanks.

(BTW when the key changes, isLoading can be true again even if there’s previous data loaded)

**Comment by meerns** [comment]
@shuding same issue for the same key also, I fetched the data in one component when I change the pages sometimes the isLoading set to true and the network request is finished in the network tab

**Comment by promer94** [comment]
reproduction: https://codesandbox.io/s/swr-2030-fm0g36
