### ISSUE TITLE
Duplicate code in webpack bundle

### ISSUE THREAD

**Issue by magiskboy** [vercel/swr#2049]
# Bug report

## Description / Observed Behavior

Duplicate code in bundle file
![image](https://user-images.githubusercontent.com/13352088/175475064-273c24fa-a8a0-43c4-a342-5c34f7caae3c.png)
![image](https://user-images.githubusercontent.com/13352088/175478742-16fa71e6-bd8e-40ac-85fa-8afccfcfa879.png)

You can see that index.mjs was included 2 times in the output file

## Expected Behavior

Webpack should bundle once it

![image](https://user-images.githubusercontent.com/13352088/175475268-c7b79646-e60e-4c58-be86-cc46abc58be1.png)

## Additional Context

SWR version: 1.3.0
Used in NextJS 12

**Comment by huozhi** [comment]
It feels like the issue with bundling process not swr itself. Can you share a miminal repro that?

**Comment by magiskboy** [comment]
@huozhi I'm using monorepo of yarn berry.

- package.json of lib1 uses swr 1.3.0
```json
{
   "dependencies": {
      "swr": "1.3.0"
   }
}
```
- package.json of application uses swr 1.3.0
```json
{
   "dependencies": {
      "swr": "1.3.0",
     "lib1": "workspace:packages/lib1"
   }
}
```

But application depends on lib1 so I think that problem is here
