### ISSUE TITLE
can add "refresh" method for "useSWRPages" ?

### ISSUE THREAD

**Issue by roytan883** [vercel/swr#205]
Only `loadMore` exposed so far, can add a `refresh` method for **useSWRPages** ? 

In some scenarios, we need allow user manually refresh whole pages, because some new items may add to list by someone else, the pages count may be changed and old `isReachingEnd` may be wrong.

Seems we can iterate `pageSWRs[x].revalidate()` to achieve that right now, but it looks weird. Will `isReachingEnd` change after iterate `pageSWRs[x].revalidate()`? Maybe an explicit `refresh` method make it easier.

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!
