### ISSUE TITLE
License issue in version 1.3.0

### ISSUE THREAD

**Issue by yonayarin** [vercel/swr#2081]
# Bug report

Hi,
we have tried to update swr to the latest version (1.3.0) and got a new error during the build:

``` WebpackLicensePlugin: Could not find license info for swr-infinite@0.0.1```

We are using **WebpackLicensePlugin** and it seems the repo changed to a mono-repo causing an issue to access the license for the internal packages (since he is only in the root).

**Comment by huozhi** [comment]
Thanks for reporting, TIL that's affecting license plugin. I think in short term you can only try to manually give a license for it, we're planning to remove those subpath package.json in v2 and respect to the license in root package.json

**Comment by codepunkt** [comment]
@huozhi Hi, author of webpack-license-plugin here 👋

With every published version of a package on npm (or any other package registry for that matter), you should either include a `LICENSE` file that includes the license text and copyright   for this version of the package or have a `license` key in your `package.json`, set to the SPDX identifier of the open source license that this version of your package is published as.

It is always preferable to do both - but if you do neither, you’re just making the life of your users harder for no good reason.

**Comment by huozhi** [comment]
hi @codepunkt , those are not separate published packages, the package.json under those sub folders are indent to help bundler to resolve the cjs/esm assets previously. The swr itself does have a MIT license field for it [here](https://github.com/vercel/swr/blob/c5ef50a6b097e4949fa2ff3336a59cc67265f5c1/package.json#L65)

The idea is too remove the duplicated package.json which were just designed for module resolving, not to ignore any license we had already. Thanks

**Comment by codepunkt** [comment]
@huozhi Understood, thanks for explaining. Do these `package.json` have any other distinguishing feature that could be used to distinguish them from relevant `package.json` files and search the parent folder hierarchy for the "correct" one - besides being `private: true`?

**Comment by huozhi** [comment]
@codepunkt Does the package.json with `"name"` and marked as `"private: true"` but without `"version"` field can be ignored? We're using turbo repo now which requires the package name. But I feel a private package without a version can also be treated as a dummy package? If it's not a case license plugin has that would be perfect to support it 🙏
