### ISSUE TITLE
reValidateOnMount doesn't work when component is unmounted while the data is being fetched

### ISSUE THREAD

**Issue by sibasishm** [vercel/swr#2082]
# Bug report

## Description / Observed Behavior

Unmounting the component while the data is being fetched i.e; `isValidating` is true, doesn't trigger refetch on the next mount, even if `reValidateOnMount` is set to true.

## Expected Behavior

Refetch should happen on each mount if `reValidateOnMount` is set to true.

## Additional Context

- Version: 0.5.6
- Framework: React Native

**Comment by koba04** [comment]
@sibasishm Could you reproduce it on CodeSandbox?
