### ISSUE TITLE
Request body isn't passed with Axios fetcher

### ISSUE THREAD

**Issue by tisonkun** [vercel/swr#2086]
# Bug report

## Description / Observed Behavior

According to our [Axios TypeScript demo](https://github.com/vercel/swr/tree/main/examples/axios-typescript) I build a page to fetch data from `api` with URL **and body***. However, although `params` passed can be observed as `query`, `data` passed cannot be observed as `body` as normal `curl` does.

```ts
// /pages/index.tsx
    const {data} = useRequest<StarAffinityRatio[]>({
        url: '/api/affinity/ratio',
        params: {id: 12345},
        data: {
            origins: ['apache/pulsar', 'apache/pulsar-site']
        }
    });
```

For the complete repo settings, see also https://github.com/korandoru/neptune

```ts
// /pages/api/affinity/ratio.ts
    console.log(req.body);
    console.log(req.query);
// This gives:
// {}
// {id:12345}

// Expected:
// {origins: ['apache/pulsar', 'apache/pulsar-site']}
// {id:12345}
```

## Expected Behavior

Properly pass the request body so that I can read from within `api`.

## Repro Steps / Code Example

https://github.com/korandoru/neptune

## Additional Context

SWR version. 

`^1.3.0`.

**Comment by tisonkun** [comment]
Additional:

Although I wrote:

```ts
useSWR<AxiosResponse<Data>, AxiosError<Error>>(
        request && JSON.stringify(request),
        () => {
            console.log("useRequest: " + request!);
            return axios.request<Data>(request!);
        },
        {
            ...config,
            fallbackData: fallbackData && {
                status: 200,
                statusText: 'InitialData',
                config: request!,
                headers: {},
                data: fallbackData
            }
        }
    )
```

the `console.log` statement seems not be executed, which is weird to me.

**Comment by liby** [comment]
Try using POST, SWR seems to ignore the body of GET requests.
```
fetch('/api/affinity/ratio', { 
	method: 'POST', 
	body: JSON.stringify({ message: "It passed." })
})
```

**Comment by promer94** [comment]
**SWR will always pass the origin keys to the fetcher**

This problem is actually axois's strategy. data will not be used for GET request

https://axios-http.com/docs/req_config

>// `data` is the data to be sent as the request body
  // Only applicable for request methods 'PUT', 'POST', 'DELETE', and 'PATCH'
  // When no `transformRequest` is set, must be of one of the following types:
  // - string, plain object, ArrayBuffer, ArrayBufferView, URLSearchParams
  // - Browser only: FormData, File, Blob
  // - Node only: Stream, Buffer
  data: {
    firstName: 'Fred'
  },

**Comment by tisonkun** [comment]
@promer94 thank you! Add a 'POST' method works.

However, if you take a look at `/pages/api/affinity/ratio.ts`, I writes:


```ts
    let result = await axios.get('https://play.clickhouse.com', {
        params: {
            "user": "explorer",
            "default_format": "JSON",
            "param_origins": paramOrigins,
        },
        data: `
            SELECT
                repo_name,
                uniq(actor_login) AS total_stars,
                uniqIf(actor_login, actor_login IN
                (
                    SELECT actor_login
                    FROM github_events
                    WHERE (event_type = 'WatchEvent') AND (repo_name IN ({origins:Array(String)}))
                )) AS our_stars,
                round(our_stars / total_stars, 2) AS ratio
            FROM github_events
            WHERE (event_type = 'WatchEvent') AND (repo_name NOT IN ({origins:Array(String)}))
            GROUP BY repo_name
            HAVING total_stars >= 100
            ORDER BY ratio DESC
            LIMIT 50
        `
    });
```

and it seems the data is sent to remote server.

Although, it can be an Axios issue >_<

**Comment by promer94** [comment]
This is because axios use different http client for different runtime.

For `/pages/api/affinity/ratio.ts`, its runtime is `nodejs`. Axios uses `http` from `nodejs` to send request.

In browser, axios uses `XMLHttpRequest` and it cant send body when request method is GET

> send() accepts an optional parameter which lets you specify the request's body; this is primarily used for requests such as [PUT](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT). If the request method is [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) or [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD), the body parameter is ignored and the request body is set to null.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send

**Comment by tisonkun** [comment]
@promer94 Good to know!

Closed as resolved.
