### ISSUE TITLE
useSWR is not a function

### ISSUE THREAD

**Issue by yonayarin** [vercel/swr#2106]
# Bug report

## Description / Observed Behavior

Hi, lately I am facing issues with useSWR, it seems that something has been changed in the last versions and it is not a function anymore. 
<img width="548" alt="Screen Shot 2022-08-07 at 11 19 43" src="https://user-images.githubusercontent.com/98890583/183286456-5f3285f4-d29f-4e1d-9d95-c30fcc0f3ea2.png">

I got to it by using 
`import useSWRInfinite from 'swr/infinite';`

The problem starts with the last update from 0.5.6 -> 1.3.0

**Comment by huozhi** [comment]
Can you share entire codebase of the minimal reproduction? It feels like sth wrong with bundling that didn't resolve the default import properly

**Comment by yonayarin** [comment]
Unfortunately, I can share the entire codebase but I can share our usage...
```
 const fallbackData = useMemo(
    () =>
      loadDataFromSessionStorage(url, getNextKey as (data: unknown) => string),
    [url, getNextKey]
  );


  const { data, error, mutate, setSize } = useSWRInfinite<T>(
    (pageIndex, previousPageData) =>
      pageIndex === 0 ? url : getNextKey(previousPageData as T),
    fetcher,
    {
      fallbackData,
      onSuccess: (newData, key) => saveInStorage<T>(newData, key, getNextKey),
      revalidateOnMount: true,
      revalidateOnFocus: false,
      shouldRetryOnError: false,
      revalidateFirstPage: false,
    }
```
we are using common.js

**Comment by huozhi** [comment]
The issue is not related to the swr usage, more related to the bundle strategy. The module is loaded by `require` in commonjs but the default export is not been picked correctly.

Might be related to if you forcedly specify commonjs transform somewhere in your project.
