### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'bind')

### ISSUE THREAD

**Issue by joaisa17** [vercel/swr#2129]
# Bug report

## Description / Observed Behavior
When using the useSWR hook like intended, I originally had no problems with it. However, I discovered today that it suddenly threw the error `TypeError: Cannot read properties of undefined (reading 'bind')`.

This error originates from swr/dist/index.mjs at line 153.

### Update
This error only occurred to me when @mux/mux-video-react was installed.

## Expected Behavior
useSWR runs like normal, and returns my data.

## Repro Steps / Code Example
Implemented useSWR in a custom hook called useQuery, which fetches a query from a sanity.io project through a next API. On the server, this query is cached, ensuring as few API calls to Sanity as possible.

```ts
import { useRouter } from 'next/router';

import useSWR from 'swr';
import axios from 'axios';

export default function useQuery<T>(query: string, condition?: boolean) {
    // Data from Sanity gets directly linked to the current path in order to revalidate pages that use it
    const router = useRouter();

    const { data } = useSWR<T>(condition !== false? query:null, async () => {
        const res = await axios.get(`/api/query/${query}?path=${router.asPath}`);
        return res.data;
    }

    return data;
}
```

## Additional Context
SWR version - 1.3.0
Axios version - 0.27.2
Next version - 12.2.4
React version - 18.2.0

Until this issue is resolved, I will either prevent usage of SWR in my code, or create my own way of caching the data.

**Comment by ndimatteo** [comment]
I'm also getting this same error on Next.js builds all of a sudden. Any updates on what could be causing this?

**Comment by ndimatteo** [comment]
Update: For whatever reason, this error only appears for me when I install [@mux/mux-player-react](https://github.com/muxinc/elements/tree/main/packages/mux-player-react) or [@mux/mux-video-react](https://github.com/muxinc/elements/tree/main/packages/mux-video-react) packages via yarn alongside SWR.

If I remove those packages, my Next.js app builds successfully.

Bummed, as I can't seem to figure out how this has any relation to SWR being used in other components.

**Comment by joaisa17** [comment]
> Update: For whatever reason, this error only appears for me when I install [@mux/mux-player-react](https://github.com/muxinc/elements/tree/main/packages/mux-player-react) or [@mux/mux-video-react](https://github.com/muxinc/elements/tree/main/packages/mux-video-react) packages via yarn alongside SWR.
> 
> If I remove those packages, my Next.js app builds successfully.
> 
> Bummed, as I can't seem to figure out how this has any relation to SWR being used in other components.

I also used mux for videos uploaded in Sanity. Will check this out later, to see if that is what's causing the problem for me.

**Comment by joaisa17** [comment]
Can confirm! It started working again as soon as I removed @mux/mux-video-react from the project. I will make an issue about this.

**Comment by ndimatteo** [comment]
@joaisa17 I posted an issue for @mux here: https://github.com/muxinc/elements/issues/342

**Comment by huozhi** [comment]
Close as it’s not the issue for swr itself
