### ISSUE TITLE
Bound mutate from useSWR make useSWR refetching

### ISSUE THREAD

**Issue by demosofa** [vercel/swr#2152]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?
I have a button that uses bound mutate to update filtered data without refetching useSWR. But for unkown reason, useSWR get called after bound mutate completed. This behavior created a flash effect which new data from bound mutate appears and disappears.

## Expected Behavior

How did you expect SWR to behave here?
I don't want useSWR to get called after bound mutate completed

## Repro Steps / Code Example
```
const fetcher = async (config) => {
    const accessToken = expireStorage.getItem("accessToken");
    const response = await axios({
      ...config,
      headers: {
        Authorization: `Bearer ${accessToken}`,
      },
    });
    return response.data;
  };

  const { data, error, mutate } = useSWR(
    { baseURL: `${LocalApi}/profile/order` },
    fetcher,
    {
      onError(err, key, config) {
        if (err.status === 300) return router.back();
        else if (err.status === 401) return router.push("/login");
        else return dispatch(addNotification({ message: err.message }));
      },
    }
  );

const handleFilter = ({ value }) => {
    mutate(async (data) => {
      try {
        const data = await fetcher({
          url: `${LocalApi}/profile/order`,
          params: { status: value },
        });
        return data;
      } catch (error) {
        dispatch(addNotification({ message: error.message }));
        return data;
      }
    });
  };
```
Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version.  ver1.3.0

**Comment by koba04** [comment]
@demosofa I think that's an expected behavior, you can add `{ revalidate: false }` as the option of `mutate` function to disable the behavior.

https://swr.vercel.app/docs/mutation
