### ISSUE TITLE
Global mutation doesn't start http request

### ISSUE THREAD

**Issue by yufengwang** [vercel/swr#2177]
# Bug report

With next.js app, on page a, mutate a global key used in other page

## Description / Observed Behavior

No http request was sent

## Expected Behavior

Send http request and revalidate data

SWR version.  v1.3.0

**Comment by koba04** [comment]
@yufengwang Could you reproduce it on CodeSandbox?

**Comment by yufengwang** [comment]
@koba04 I found that it's because of the component is  unmounted, thanks
