### ISSUE TITLE
`Cannot convert undefined value to object` error when mutating

### ISSUE THREAD

**Issue by diego-paired** [vercel/swr#2193]
```
   "swr": "^1.3.0"
    @react-native-community/cli: ^9.0.0 => 9.1.3
    react: ^18.2.0 => 18.2.0
    react-native: ^0.70.3 => 0.70.3
```
Error `Cannot convert undefined value to object` when calling `mutate` seen thousands of times.
The cache is overridden with a custom MKKV singleton instance.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/55058765/195661811-27e1e090-49f6-4801-af92-4b63b0f3703c.png">

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/55058765/195661323-9daaf661-7b9f-4cf3-bc7b-f084d7564a4a.png">

Any hints on how to fix it will be greatly appreciated.

**Comment by koba04** [comment]
>  The cache is overridden with a custom MKKV singleton instance.

Could you provide your custom cache implementation?
