### ISSUE TITLE
Setting and getting data multiple times in SWR inside a Component (Remirror editor)

### ISSUE THREAD

**Issue by sdanfa** [vercel/swr#2197]
Hi,
It's possible to get the data using a code like <Component data={data} />, but I need a way to set the data and retrieve more data inside a Component in NextJS. For example in <EditorComponent /> in Remirror editor project. It gives me an error `Error: Rendered more hooks than during the previous render. ` if I try to use useSwr in the Component.

Please help me with this.

Thanks!

**Comment by koba04** [comment]
Could you reproduce it on CodeSandbox?
