### ISSUE TITLE
useSWR onError and onErrorRetry changed behaviour in 1.1.0

### ISSUE THREAD

**Issue by GabrielNastase** [vercel/swr#2201]
# Bug report

## Description / Observed Behavior

We have been observed the functionality of onError and onErrorRetry callbacks has changed in the minor 1.1.0
We have cases in our apps where we call useSWR with the same cache key for multiple times, sometimes just for reading data, other times for reading data and handling error scenarios.
Before 1.1.0 ( before https://github.com/vercel/swr/pull/1522) , we could see that all the hooks callbacks were being called back. And that was useful for when you use the same useSWR cache key multiple times in the same page. Useful for when you have multiple panels in the same page - and you want the components to get the data independently from the cache - but you would want to handle differently the error retry in each panel. 
Since 1.1.0 only the first rendered hook is being called back resulting that only the first component that uses the same cache key could change the UI in case of onError is fired or onErrorRetry 

## Expected Behavior

If the useSWR hook has the onError and onError retry option - I would expect it to actually be called back in all the call sites. 

## Repro Steps / Code Example

```javascript

const sameFetcher = () => Promise.reject('Ooups');

const ComponentOne = () => {
  const { data } = useSWR('same-key', sameFetcher, {
    onError: (error) => {
      console.log('ComponentOne onError fired', error) // only this is fired
    },
    onErrorRetry: (error, _key, _config) => {
      console.log('ComponentOne onErrorRetry fired', error, _key, _config) // only this is fired
    }
  })

  return <pre>{data}</pre>
}

const ComponentTwo = () => {
  const { data } = useSWR('same-key', sameFetcher, {
    onError: (error) => {
      console.log('ComponentTwo onError fired', error) // this is not called back
    },
    onErrorRetry: (error, _key, _config) => {
      console.log('ComponentTwo onErrorRetry fired', error, _key, _config) // this is not called back
    }
  })

  return <pre>{data}</pre>
}

const App = () => {

  return <div>
    <ComponentOne />
    <ComponentTwo />
  </div>
}
```

## Additional Context

SWR version. 1.3.0

**Comment by promer94** [comment]
#1580
