### ISSUE TITLE
Default export type not being picked up with `module: "nodenext"`

### ISSUE THREAD

**Issue by wight554** [vercel/swr#2208]
# Bug report

## Description / Observed Behavior

When trying to use imported useSWR hook I'm getting the following error:
```
import useSWR
This expression is not callable.
  Type 'typeof import("/Users/Volodymyr_Zhdanov/playground/blog-template/node_modules/swr/dist/index")' has no call signatures.
 ```

## Expected Behavior

Import should pick-up typings

## Repro Steps / Code Example

1. Add these settings to tsconfig:
```
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
```
2. Add `"type": "module"` to package.json
3. Import and use useSWR hook
4. See the error

## Additional Context
SWR version: ^1.3.0
Typescript version: ^4.8.4

3 possible fixes:

1. Add named export for useSWR
2. Use CJS styled export in typings: `export default useSWR;` => `export = useSWR;`
3. Use declaration merging to make default export namespace and function simultaneously, example here: https://github.com/fastify/fastify-cookie/pull/184/

**Comment by promer94** [comment]
Ref: https://github.com/microsoft/TypeScript/issues/50466

**Comment by wight554** [comment]
> Ref: [microsoft/TypeScript#50466](https://github.com/microsoft/TypeScript/issues/50466)

This can be referenced as well: https://github.com/microsoft/TypeScript/issues/48845

**Comment by promer94** [comment]
After TypeScript 5.0 got released.

This could be a workaround
```json
{
  "compilerOptions": {
    "moduleResolution": "bundler",
   }
}
```
https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler

**Comment by dubiousdavid** [comment]
This still doesn't work for me.
