### ISSUE TITLE
When providing fetcher: null , middleware is defaulting it to undefined 

### ISSUE THREAD

**Issue by jquintozamora** [vercel/swr#2217]
# Bug report

We're building a custom middleware were we interact with fetcher. 
We check if fetcher === null, but we receive fetcher as undefined inside middleware callback.

```ts
 const myCustomMiddleware = (useSwrNext) =>
  (key, fetcher, config) => {
    const extendedFetcher =  fetcher === null ? null : myFetcher
    ....
```
The issue is that `fetcher` comes undefined even if we set it as null in our `useSWRImmutable("myKey", null, options)` 
Types doesn't allow us to define fetcher as undefined in `useSWRInmutable`.

## Expected Behavior

Middleware returns `fetcher` as `null` when we set it `null` in `useSWRInmutable`

SWR version. 
 "swr": "^1.3.0"

**Comment by koba04** [comment]
@jquintozamora Thank you! I've created a PR to fix this.
