### ISSUE TITLE
Mutate seems to do shallow compare for optimisticData

### ISSUE THREAD

**Issue by aloukissas** [vercel/swr#2244]
# Bug report

## Description / Observed Behavior

It appears that when passing `optimisticData` to `mutate`, when the data has changes deep in the object the cache isn't optimistically updated. Problem is solved when updating a top-level key in the object. It's unclear from the docs whether this is expected or not.

## Expected Behavior

If this is expected behavior, document it; otherwise, it's a bug.

## Repro Steps / Code Example

This optimistic data doesn't work:
```
const optimisticData = {
  ...oldData,
  replies: [
    {
       ...
       text: <newtext>
    }
  ]
}
```

This works:
```
const optimisticData = {
  ...oldData,
  replies: [
    {
       ...
       text: <newtext>
    }
  ],
  // trick it to believe that the object has indeed changed
  lastUpdated: new Date().getTime()
}
```

## Additional Context

SWR version: `1.3.0`

**Comment by iraritchiemeek** [comment]
I am having this same issue.

**Comment by naeluh** [comment]
This seems to still be an issue. @iraritchiemeek how did you fix it? thanks !
