### ISSUE TITLE
Revalidate stale data when mutate occurs and useSwr is not mounted

### ISSUE THREAD

**Issue by bordeo** [vercel/swr#2264]
# Bug report

## Description / Observed Behavior
Mutating an unmounted `useSwr` key previously validated will not trigger revalidation when `revalidateIfStale` is `false`.

## Expected Behavior

After a mutation `mutate('key')` all `useSwr()` will be revalidate, if not mounted it will revalidate on mount even if `revalidateIfStale` is `false`

## Repro Steps / Code Example

[StackBlitz](https://stackblitz.com/edit/swr-mutation-unmounted)
StackBlitz steps
1. Navigate [here](https://swrmutationunmounted-sj0s--3000.local-credentialless.webcontainer.io/)
2. Click the link 'mutation page'
3. Click the button 'Add entry' one or more time
4. Click the link 'list page'
5. data is old and it will not revalidate
6. Click the button "Trigger mutate('/api/list')" to revalidate and the see the updated results

Generic steps
1. Navigate to a page with a list of items fetched by `useSwr`
7. Navigato to another page that trigger `mutate` of previous key
8. Navigate to the first page with `useSwr`

## Additional Context
version 1.3.0
config
```
{
  revalidateIfStale: false,
  revalidateOnFocus: false,
  revalidateOnReconnect: false,
}
```

similar issue #751
pull request that resolved issue #1498

**Comment by bordeo** [comment]
Still present in 2.1.0 version
## Repro Steps / Code Example
[StackBlitz](https://stackblitz.com/edit/swr-mutation-unmounted-rgcxdr?file=pages/index.js)

**Comment by promer94** [comment]
```tsx
mutate('/api/list', fetch('/api/add').then((res) => res.json()), {
  revalidate: true,
  populateCache: true
})
```
This will prevent `mutate` to update the cache using the result of `fetch('/api/add').then((res) => res.json()`

and setting 
```tsx
{
        revalidateIfStale: false,
        revalidateOnFocus: false,
        revalidateOnReconnect: false
}
```

is same as https://swr.vercel.app/docs/revalidation#disable-automatic-revalidations


So this behavior is expected.
