### ISSUE TITLE
useSWRMutation do not re-render on other components

### ISSUE THREAD

**Issue by dolie** [vercel/swr#2267]
# Bug report

## Description / Observed Behavior

Hello 👋
When using `useSWRMutation` on two components :  
The `component_A` triggers and rerender with datas, but `component_B` do not rerender with datas.

## Expected Behavior

`Component_A` trigger the fetch (GET/POST/whatever...) via `useSWRMutation`
`Component_B` rerender with data fetched by `Component_B`

## Repro Steps / Code Example

[Here is the CodeSandbox](https://codesandbox.io/s/vibrant-booth-zt7t0i?file=/src/consumer.jsx:148-156)

## Additional Context

SWR version 2.0.0-rc.3.

**Comment by promer94** [comment]
This is a expected behavior. 

https://swr.vercel.app/docs/mutation#useswrmutation

> Also, this hook doesn’t share states with other useSWRMutation hooks.

**Comment by dolie** [comment]
My bad,
I updated the [codesandbox](https://codesandbox.io/s/vibrant-booth-zt7t0i)
Both components are using the same useSWRMutation now. 
Data renders only on the component that triggers mutation.

**Comment by nmateo** [comment]
Can confirm i got the same behavior on 2.0.0 rc-3.
Any ideas on how to share data between components using the same useSWRMutation hook?

**Comment by vetan2** [comment]
@dolie @nmateo 

> `useSWRMutation` doesn’t share states with other `useSWRMutation` hooks.

To get shared data, use `useSWR` with the same key used in `useSWRMutation`.

**Comment by dolie** [comment]
Thank you @vetan2, it works!

**Comment by nmateo** [comment]
> @dolie @nmateo
> 
> > `useSWRMutation` doesn’t share states with other `useSWRMutation` hooks.
> 
> To get shared data, use `useSWR` with the same key used in `useSWRMutation`.

Sorry for the late response, i was on vacation, there is no possibility to use the same useSWRMutation, and get the data that was triggered in another component without re triggering ? Thanks in advance

**Comment by dolie** [comment]
Hello @nmateo 
In our codebase, we used useSWR & useSWRMutation with the same cache-key AND revalidateOnFocus + revalidateOnMount to false. Like this :
```typescript
export default function useSearchPrice(){
  
  // useSWR should not be needed since useSWRMutation returns data but it does not trigger rerender
  // https://github.com/vercel/swr/issues/2267
  const { data } = useSWR<SearchPrice[]>(
    '/v1/search_price',
    { revalidateOnFocus: false, revalidateOnMount: false },
  )

  const { trigger, isMutating } = useSWRMutation(
    '/v1/search_price',
    key => sendRequest(key, someOptions),
    { populateCache: true, revalidate: false },
  )

  return {
    trigger,
    prices: data,
    isMutating,
  }
}
```
Au plaisir 🙂

**Comment by Brandon-Ln** [comment]
> This is a expected behavior.
> 
> https://swr.vercel.app/docs/mutation#useswrmutation
> 
> > Also, this hook doesn’t share states with other useSWRMutation hooks.

Sorry for disturbing you,  I just wonder why `useSWRMutation` is designed not to share returned data between different components, and I also noticed that its default `populateCache` property is false, which seems intended. Just like consuming `useSwr`  returned results, sharing server data through `useSWRMutation` in different components seems like a common use case. 

And what is the recommended practice if I want to do so? Really appreciate it.

**Comment by jackAdsmurai** [comment]
> Hello @nmateo In our codebase, we used useSWR & useSWRMutation with the same cache-key AND revalidateOnFocus + revalidateOnMount to false. Like this :
> 
> ```ts
> export default function useSearchPrice(){
>   
>   // useSWR should not be needed since useSWRMutation returns data but it does not trigger rerender
>   // https://github.com/vercel/swr/issues/2267
>   const { data } = useSWR<SearchPrice[]>(
>     '/v1/search_price',
>     { revalidateOnFocus: false, revalidateOnMount: false },
>   )
> 
>   const { trigger, isMutating } = useSWRMutation(
>     '/v1/search_price',
>     key => sendRequest(key, someOptions),
>     { populateCache: true, revalidate: false },
>   )
> 
>   return {
>     trigger,
>     prices: data,
>     isMutating,
>   }
> }
> ```
> 
> Au plaisir 🙂

When I do this in my projects, the data returned from useSWR is not mutating. Only way around it we found is using the data from useSWRMutation.

**Comment by 4mit** [comment]
I am using it like below but once data is received from API  it should re-render the component and  and response should be updated but it's not re-rendering so no data getting received from useSWR  and useSWRMutation
xxx and yyy should log with data received from API but its not, not sure what's wrong 

import React from 'react';
import {Text, StyleSheet, View} from 'react-native';
import useSWR from 'swr';
import useSWRMutation from 'swr';

const fetcher = async (url: any) => {
  console.log('hello...');
  const res = await fetch(url).then(r => r.json());
  console.log('hello...', res);
  return res;
};

const Home = ({
  navigation,
}) => {
  console.log('AppStack gg  >>>>>>>>>><<<<<<<<<<<');
  const xxx = useSWR(
    'some_url_in_project',
    fetcher,
  );
  console.log('JSON.stringify(xxx) >>>>>>>>>><<<<<<<<<<<', JSON.stringify(xxx));

  const yyy = useSWRMutation(
     'some_url_in_project',
    fetcher,
  );
  console.log('useSWRMutation >>>>>>>>>><<<<<<<<<<<', JSON.stringify(yyy));
  return (
    <View style={styles.container} nativeID="home-container">
      <Text>Home HOME_SCREEN </Text>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    padding: 10,
    backgroundColor: 'white',
  },
  rotatorView: {
    width: '100%',
    height: '50%',
  },
});

export default Home;
