### ISSUE TITLE
Compare(a,b) Config Option is not working 2.0.0

### ISSUE THREAD

**Issue by neagu-dev** [vercel/swr#2278]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

I'm trying to use the compare option function from useSWR in the v2.0.0, I see that in 1.2.2 and 1.3.0 the version is working.

Error : 

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

## Repro Steps / Code Example

[Codesandbox  Link](https://codesandbox.io/s/throbbing-rain-scnqsj?file=/src/App.js)

```js
import "./styles.css";
import useSwr from "swr";
const fetcher = (url) => fetch(url).then((res) => res.json());

export default function App() {
  const data = useSwr("https://pokeapi.co/api/v2/pokemon/ditto", fetcher, {
    compare(d, c) {}
  });
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <pre>{JSON.stringify(data, null, 2)}</pre>
      <h2>Start editing to see some magic happen!</h2>
    </div>
  );
}
```

## Additional Context

SWR version 2.0.0

**Comment by promer94** [comment]
You have to provide a valid function which could return a boolean value here. 
https://swr.vercel.app/docs/api#options
