### ISSUE TITLE
Adding a note about webpack & ESM

### ISSUE THREAD

**Issue by ahmedelgabri** [vercel/swr#228]
A bit of context, we introduced `swr` two weeks ago to our codebase. Everything is working fine, but we started to get some reports about some parts of the app being broken in slightly older browsers (Chrome 49, Firefox 59, Edge 18, etc…) 

We found out that `swr` was causing a syntax error in these browsers because webpack by default picked the ESM build (rightly so) but because it's not transpiled it ended in the bundle without going through our babel config. Which broke these older browsers. So I'd like to add a not in README file, about the ESM build & webpack, what do you think?

**Comment by quietshu** [comment]
Thank you @ahmedelgabri, sounds good!

**Comment by tanmaylaud** [comment]
@shuding , is this an active issue? If yes, could you please provide more context?

**Comment by shuding** [comment]
@tanmaylaud The issue of broken code for old browsers is already resolved in latest releases. So we are only missing documentation (or a notice message) here.

**Comment by tanmaylaud** [comment]
So a note in the parent README that mentions support for older browsers (given in the issue above) would be good enough?

**Comment by thang40** [comment]
Is this issue still valid?

**Comment by huozhi** [comment]
All assets (cjs, esm) output of swr are in es5 now. Thanks for reminding! @thang40
