### ISSUE TITLE
The engine "pnpm" appears to be invalid.

### ISSUE THREAD

**Issue by Hardel-DW** [vercel/swr#2285]
# Bug report

## Description / Observed Behavior
I get a warning when I do "yarn add swr".
`warning swr@2.0.0: The engine "pnpm" appears to be invalid.`

## Expected Behavior
That the warning does not appear.

## Repro Steps / Code Example
1.. "yarn add swr"

## Additional Context
Useful data :
```
    Operating System:
      Platform: win32
      Arch: x64
      Version: Windows 10 Education
    Binaries:
      Node: 16.14.2
      npm: N/A
      Yarn: 1.22.19
      pnpm: N/A
    Relevant packages:
      next: 13.0.6
      swr: 2.0.0
      react: 18.2.0
      react-dom: 18.2.0
```

**Comment by koba04** [comment]
We use `pnpm` as our package manager, and that is for `pnpm`.
https://pnpm.io/package_json#engines

I'd say there is no problem even though `yarn` displays the warning.
