### ISSUE TITLE
useSWRMutation error returned to all instances of a component.

### ISSUE THREAD

**Issue by iamkevb** [vercel/swr#2288]
# Bug report

## Description / Observed Behavior

I have a page that has a list of projects. When selected a the project is displayed in a child component. There are a few mutations that can be made to edit a project. When using useSWRMutation and an error occurs while on one of the child elements, that error gets returned to all children. Each child is request goes to a different url containing the ID.

## Expected Behavior

Only the child where the error occurred should get the error. (errors received from /api/data/1, should not be displayed to when useSWRMutation(/api/data/2)).

## Repro Steps / Code Example

Quick sample app.
Trigger the mutation, an error will be thrown. Toggle back and forth between A and B and see the error stays.

```typescript
import { useState } from "react"
import useSWRMutation from "swr/mutation"

export default function Test() {
  const [ showA, setShowA ] = useState(true)

  const renderChild = () => {
    return <ChildComponent label={showA?"Child A":"Child B"}/>
  }

  return <>
    <a href="#" onClick={() => setShowA(!showA)}>Toggle child</a>
    {renderChild()}
  </>
}

function ChildComponent({ label }: { label: string }) {
  const fetcher = async (url: String, { arg: { labelP } }: { arg: { labelP: String } }) => {
    throw (`ERROR: URL: ${url}   Argument: ${labelP}   Component label: ${label}`)
  }
  const { trigger, error } = useSWRMutation(`/fake/url/${label}`, fetcher)
  return <div className="container">
    <h3>Label: {label}</h3>
    <p>{error}</p>
    <a href="#" onClick={()=>trigger({ labelP: label })}>Trigger fetch</a>
  </div>
}
```

https://user-images.githubusercontent.com/4049705/207762858-46d0151a-fabe-4dda-9a5a-3155d63fc820.mov

## Additional Context

["swr": "^2.0.0"](version: 2.0.0)

**Comment by koba04** [comment]
@iamkevb Thank you! This is caused by being used the stale fetcher rather than the latest fetcher, so I've created a PR to fix this.
