### ISSUE TITLE
0.1.15-beta.0 regression in ssr with initialData: staleness thing doesnt refetch. works fine in 0.1.15

### ISSUE THREAD

**Issue by iamstarkov** [vercel/swr#230]
as described, will add a demo asap

**Comment by iamstarkov** [comment]
the problem for us is that in `0.1.16` `initialData` is behaving more or `defaultData` or `fallbackData`

* PR with a code https://github.com/iamstarkov/swr/pull/2
* notice how Pokemon profile doesnt change https://zeit-swr-230-demo.iamstarkov.now.sh/demo
* with a workaround it does change https://zeit-swr-230-demo.iamstarkov.now.sh/workaround 

workaround in the meantime:

```js
const useFixedSWR = (key, fetcher, {initialData, ...config} = {}) => {
  const initial = React.useRef(initialData);
  React.useEffect(() => {
    if(key){
      initial.current = undefined;
    }
  }, [key]);
  return useSWR(key, fetcher, {...config, initialData: initial.current});
}
```

**Comment by iamstarkov** [comment]
the problem doesnt exist in `0.1.15`

* PR with a code https://github.com/iamstarkov/swr/pull/3
* notice how Pokemon profile **does change** https://zeit-swr-230-demo-0115.iamstarkov.now.sh/demo

**Comment by iamstarkov** [comment]
Looks like regression was introduced in `0.1.15-beta.0`

* PR with a code https://github.com/iamstarkov/swr/pull/4
* notice how Pokemon profile does not change anymore zeit-swr-230-demo-0115.iamstarkov.now.sh/demo

**Comment by iamstarkov** [comment]
this is the diff https://github.com/zeit/swr/compare/0.1.15...v0.1.15-beta.0

**Comment by iamstarkov** [comment]
#211 is also in the diff, so maybe maybe

**Comment by iamstarkov** [comment]
#211 with #186 are both in the diff, so i dunno

**Comment by sambokai** [comment]
I think this PR is issue is not well formatted and described. It might make sense to open a new one with a concise description and not clutter it with references.

**Comment by iamstarkov** [comment]
I dont agree that is "not well formatted and described". Following sentence describes the problem perfectly:

> the problem is that in 0.1.16 initialData is behaving more or defaultData or fallbackData

in regards to reference, I dont control em

**Comment by huozhi** [comment]
could you try the solution posted in https://github.com/vercel/swr/issues/284#issuecomment-869174803 ?
Will close this issue as it seems to be reoslved with `swr@beta`, feel free to comment or reopen if you have any further issues
