### ISSUE TITLE
When calling useSWR isLoading is always undefined

### ISSUE THREAD

**Issue by dodtsair** [vercel/swr#2346]
# Bug report

## isLoading not being set during initial useSWR loading

Per example on the main page:
```
import useSWR from 'swr'

function Profile() {
  const { data, error, isLoading } = useSWR('/api/user', fetcher)

  if (error) return <div>failed to load</div>
  if (isLoading) return <div>loading...</div>
  return <div>hello {data.name}!</div>
}
```
The field isLoading is used to guard data, so that `data.name` does not error.  

However the field `isLoading` is never set, it is always undefined, so the data is never guarded, both isLoading and data are undefined which means that `data.name` results in an error.  

## Expected Behavior

When using `const { data, error, isLoading } = useSWR('/api/user', fetcher)` I expected isLoading to be truthy until the fetcher's promise resolves (which could be undefined).  After the fetcher resolves I expected isLoading to be falsy suggesting that my code can now access the data object and make interpretations based on the data's state.  

## Repro Steps / Code Example

[CodeSandbox](https://codesandbox.io/s/peaceful-firefly-0fn34m?file=/src/App.js)

To produce this code sandbox I combined the first page documentation above with the basic example:
https://swr.vercel.app/examples/basic

I also added a 1 second wait so that the error would be more obvious.

**Comment by mmelnic** [comment]
also have the same problem.

and it would be great to update Quick start in readme, to use `isLoading`, when it will be fixed
because now it shows `if (!data) return <div>loading...</div>` that will be not relevant for new version
