### ISSUE TITLE
Issue with Enums

### ISSUE THREAD

**Issue by thisisclint21** [vercel/swr#2348]
# Bug report

## Description / Observed Behavior

I am using SWR in typescript, so basically something like:
```ts
const { data: purchase } = useSWR<Purchase>(`/v3/purchases/${params.id}`;
// Where purchase.status is a PurchaseStatuses enum, like this:

export enum PurchaseStatuses {
    Live = 0,
    Off = 1
}
```

## Expected Behavior

This enum shouldn't be parsed as string, but when I do `typeof purchase.status` I get a string.

Also what about next13, does SWR will continues to exists? What is the plan?

I use the last version of SWR.

**Comment by thisisclint21** [comment]
Guys wake up lol @jeffrafter @natew @ykzts @javascripter

**Comment by sannajammeh** [comment]
Make a request to the raw JSON API and see if its really a string or not. Afaik, SWR does not modify requests and leaves the fetcher completely in the hands of the user.

**Comment by shuding** [comment]
This isn't something in SWR. A TypeScript application runs in the following process:

- TSC compiles TS into JS
- JS runs

All SWR's code runs in the second step including your `typeof ...` expression. It's likely the first step that doesn't work as you expected.
