### ISSUE TITLE
[Module Federation] Failing to determine SWR version

### ISSUE THREAD

**Issue by Erazihel** [vercel/swr#2356]
# Bug report

## Description / Observed Behavior

Failing to determine what SWR version to use with Module Federation based on Webpack & SWR 2.0.

## Expected Behavior

No warning nor error should be displayed / thrown when using SWR with Module Federation.

## Additional Context

Everything was working great with SWR 1.3.0.

Here is the prompted warning:
```
WARNING in shared module swr -> .../node_modules/swr/core/dist/index.mjs

No version specified and unable to automatically determine one. No version in description file (usually package.json).
Add version to description file .../node_modules/swr/core/package.json, or manually specify version in shared config.
```
(Note that the version is already specified in the shared config)

And this is the error thrown:
```
Uncaught (in promise) Error: Unsatisfied version 0 from micro-frontends of shared singleton module swr (required =2.0.0)
```

After manually adding a version to the `node_modules/swr/core/package.json` file, it seems that everything is working as expected but this is not a viable fix.

**Comment by hongkiulam** [comment]
+1

**Comment by wjkawecki** [comment]
+1

**Comment by Matikun** [comment]
+1
i tried  this : After manually adding a version to the node_modules/swr/core/package.json file, it seems that everything is working as expected but this is not a viable fix.
However, I'm still getting the warnings.

**Comment by nicolaswww** [comment]
Any news on this request? thank you!

**Comment by francosalcedo** [comment]
+1

**Comment by kobayuri** [comment]
+1

**Comment by kobayuri** [comment]
As a fast fix/unblock:

```
      swr: {
        singleton: true,
        strictVersion: true,
        requiredVersion: '0', // Dumb fix
      };
```

**Comment by chaos1ee** [comment]
+1

**Comment by yamaoto** [comment]
Also you can temporary fix it with https://www.npmjs.com/package/patch-package

For error:
```
WARNING in shared module swr -> .../node_modules/swr/core/dist/index.mjs

No version specified and unable to automatically determine one. No version in description file (usually package.json).
Add version to description file .../node_modules/swr/core/package.json, or manually specify version in shared config.
```

1. Open .../node_modules/swr/core/package.json for edit
2. Manually write version from your dependency
```diff
{
  "main": "./dist/index.js",
  "module": "./dist/index.esm.js",
  "types": "./dist/index.d.ts",
+ "version": "2.2.4",
```
3. Generate patch file:

```bash
npx patch-package swr
```
5. Install patch-package in devDependencies
6. Add new script in your package.json 
```diff
 "scripts": {
+  "postinstall": "patch-package"
 }
```

This script will run for every package installation and you can share this patch for your team

**Comment by koba04** [comment]
We updated our bundle convention at https://github.com/vercel/swr/pull/2865.
Unfortunately, this hasn't been released yet, but the change might solve this problem.
I haven't tested this, I might be wrong.

**Comment by koba04** [comment]
Could you try [v2.2.5](https://github.com/vercel/swr/releases/tag/v2.2.5), which includes https://github.com/vercel/swr/issues/2356#issuecomment-1935187859?

**Comment by yamaoto** [comment]
@koba04 
Tried to test on my project with Module Federation on the new v2.2.5 everything works great and without any hacks in .
Thank you very much for the notification.

**Comment by koba04** [comment]
I'll close this as fixed. Please reopen this if you still have a problem with v2.2.5
