### ISSUE TITLE
Arg Type is lost when using Key type

### ISSUE THREAD

**Issue by osrl** [vercel/swr#2361]
# Bug report
## Description / Observed Behavior
I'm using keys as arrays. 

When I use it like below the type of id is string as expected.
```typescript
export function useUpdateAccount() {
  const key = ['api', 'accounts'];

  const fetcher: MutationFetcher<boolean, string, typeof key> = async (
    _url,
    { arg: id }
  ) => {
    const response = await client.updateAccount(id);

    return !!response;
  };

  return useSWRMutation(key, fetcher);
}
```

When I change the first two lines like below:
```typescript
  const key = ['api', 'accounts'];
  const fetcher: MutationFetcher<boolean, string> = async (
```
or
```typescript
  const key = ['api', 'accounts'] as Key;
  const fetcher: MutationFetcher<boolean, string, typeof key> = async (
```
type of id is any.

The the type of any should be string when using `Key` as key type.

SWR version: 2.0.0

**Comment by promer94** [comment]
Thanks for reporting. 


This is expected behaviour. 

When you write your key `const key = ['api', 'account']`. TypeScript will infer `key` as `string[]`

But if you write key like `const key = ['api', 'account'] as Key`. You actually "widen" the `key` type and would break type inference.

For you example, you could just type you fetcher directly without `MutationFetcher`

```tsx
export function useUpdateAccount() {
  const key = ['api', 'accounts'];

  const fetcher = async (_url: any, { arg: id }: { arg: number }) => {
    const response = await client.updateAccount(id);
    return !!response;
  };

  return useSWRMutation(key, fetcher);
}
```

**Comment by osrl** [comment]
I don't understand. Why does setting `SWRKey` arg type to `Key` changes `ExtraArg`'s type to any? I'm explicitly setting `ExtraArg`'s type to string

`type MutationFetcher<Data = unknown, ExtraArg = unknown, SWRKey extends Key = Key>`

**Comment by promer94** [comment]
> if you write key like const key = ['api', 'account'] as Key. You actually "widen" the key type.


`MutationFetcher<any, any, string>` would work because `string` is specific type.
`MutationFetcher<any, any, Key>` would not work because `Key` is too general.
