### ISSUE TITLE
document is `null` when running Jest with React

### ISSUE THREAD

**Issue by GeorgeElRaed** [vercel/swr#2373]
# Bug report

When running Jest with React, dom document appears to become `null`

## Description / Observed Behavior

when SWR calls the `isVisible` function from [web-preset.ts](https://github.com/vercel/swr/blob/main/_internal/utils/web-preset.ts#L23), `isDocumentDefined` would return true because something in jest/jsdom/react set `document` to `null` and `typeof null` is `'object'` and not `'undefined'`. This will let it just to the next instruction being `document.visibilityState` which will throw an error due to `document` being `null`.

## Expected Behavior

return `false` from `isVisible`;

## Repro Steps / Code Example

We are not able to reproduce because we don't exactly know how and when this happens. The current theory is that `cleanup()` in `afterEach` block is running in the background and potentially finishing when the next test starts which is breaking it because that file imports `useSWR` down the line. As a workaround we added a `afterAll(async () => { await new Promise((r) => setTimeout(r, 2000)); });` and that seems to have solved it for now.

## Additional Context

SWR version: 2.0.0 and 2.0.1
Jest: 27.5.1
React: 18.1.0
jest-environment-jsdom: 27.5.1

I'm not sure anyone else is having this issue but i hope this helps.

**Comment by gusgard** [comment]
Same with the dependencies, it started happening after we upgrade to SWR 2.0
```ts
		"@testing-library/dom": "^8.19.0",
		"@testing-library/jest-dom": "^5.16.5",
		"@testing-library/react": "^13.4.0",
		"jest": "^28.1.1",
		"jest-environment-jsdom": "^28.1.1",
		"msw": "^0.42.1",
		"react": "^18.2.0",
		"swr": "^2.0.0",
```

**Comment by GeorgeElRaed** [comment]
We solved it temporarily by doing so in a jest setup file:
```javascript
global.beforeEach(() => {
  const original = jest.requireActual("swr/_internal");
  const originalIsVisible = original.defaultConfig.isVisible;
  original.defaultConfig.isVisible = () => {
    try {
      return originalIsVisible();
    } catch (e) {
      return true;
    }
  };
});
```
just create a setup file `setup-file.js` i.e. and add it to jest config: `setupFilesAfterEnv: ["<rootDir>/setup-file.js"]`

**Comment by huozhi** [comment]
`document` is `null` sounds like gonna break some condition like `typeof document === 'undefined'` on server side for any library? sounds like an issue with jest or jsdom?

**Comment by GeorgeElRaed** [comment]
Yes it seems to be an issue caused by jest and/or jsdom but it does cause an error in SWR which might need to be handled.

**Comment by vtumrukota** [comment]
This issue would appear sporadically for our team when running our react18/jest26 test suite and actually caused our builds to fail today. 

We were able to work around this by adding the fix in the PR to the source code below using the https://www.npmjs.com/package/patch-package. 

Submitted a PR for a fix here: https://github.com/vercel/swr/pull/2686

**Comment by huozhi** [comment]
Feels could be a bug for jest(x-ref: https://github.com/jestjs/jest/issues/12670)

Patching this in swr package is not the right way to go as it could happen in any package doing the same approach

**Comment by vtumrukota** [comment]
@huozhi thanks for the quick response - had a hunch Jest was doing the `null` setting here and recognize it is a potential underlying bug on their side. That being said, is there any reason the document null check is not wanted for extra `document` safety here within SWR? 

From my POV, this fix is trivial overhead compared to the  conditional `?` operator but understand if every byte counts for a library like this (saw your note in https://github.com/vercel/swr/pull/2575)

Also, FWIW the workaround in https://github.com/vercel/swr/pull/2686#issuecomment-1602147023 is not applicable for React (it only applies to React Native). 

I used the workaround @GeorgeElRaed provided above as the fix here which helped me avoid pulling in `patch-package` but having to intercept each test w/ this beforeEach is definitely something we would like to avoid long term.

**Comment by huozhi** [comment]
Not for bundle size concern but It's gonna be weird to cover document is `null` case there to just workaround a bug in jest, that being said all the library supporting SSR rendering that could access document needs to support this as well? I think the right way is to push jest to fix that bug instead of making libraries support an extra case which shouldn't be covered in production.

**Comment by promer94** [comment]
@vtumrukota 

> Also, FWIW the workaround in https://github.com/vercel/swr/pull/2686#issuecomment-1602147023 is not applicable for React (it only applies to React Native).

That is not true. 

Here is a valid test example using SWR with msw and jest

```tsx
/**@jest-environment jsdom */
import * as React from 'react'
import { Hello } from './test'
import { fireEvent, render, screen } from '@testing-library/react'
import { rest } from 'msw'
import { setupServer } from 'msw/node'
import { SWRConfig } from 'swr'

const renderWithSWRConfig = (component) => {
  const map = new Map()
  return render(
    <SWRConfig
      value={{
        provider: () => map,
        isOnline() {
          /* Customize the network state detector */
          return true
        },
        isVisible() {
          /* Customize the visibility state detector */
          return true
        },
        initFocus(callback) {},
        initReconnect(callback) {},
      }}
    >
      {component}
    </SWRConfig>
  )
}
const server = setupServer(
  rest.get('/example', (req, res, ctx) => {
    console.log('hello')
    return res(ctx.json('hello world'))
  })
)
server.listen()

afterAll(() => server.close())

test('hello world', async () => {
  renderWithSWRConfig(<Hello />)
  const textbox = screen.getByRole('textbox')
  fireEvent.change(textbox, { target: { value: 'query' } })
  fireEvent.change(textbox, { target: { value: '' } })
  fireEvent.blur(textbox)
})
```

**Comment by Michaeltaoma** [comment]
Hi @promer94 , thanks for sharing the answer! The code worked for us but I was just trying to understand what is the use of the mock server here. Thanks!!

**Comment by david-mears-2** [comment]
Somehow, I get a similar-flavoured error when I forget any `await` in my tests.

> const visibilityState = isDocumentDefined && document.visibilityState;
                                                          ^
> TypeError: Cannot read properties of null (reading 'visibilityState')
