### ISSUE TITLE
Wrong data passed to custom compare function in version 2.0.x

### ISSUE THREAD

**Issue by fscali** [vercel/swr#2375]
# Bug report

## Description / Observed Behavior

When I configure a custom compare function, the parameters that are passed to my function at runtime are booleans instead of the expected custom type
## Expected Behavior

The expected behaviour is that my custom compare functions receives the expected type returned by the fetcher.
## Repro Steps / Code Example
```
compare(a, b) {
        if (typeof a === 'undefined' || typeof b === 'undefined') {
          return false;
        } else if (typeof a === 'object' && typeof b === 'object') {
          const mappedA = a.results.map((r) => r.id);
          const mappedB = a.results.map((r) => r.id);
          return isEqual(mappedA, mappedB);
        } else {
          return a == b;
        }
      },
```

## Additional Context

SWR version: 2.0.1
Framework: Next.js 12.3.1

**Comment by koba04** [comment]
@fscali  Could you provide a CodeSandbox project to reproduce this?

**Comment by fscali** [comment]
@koba04 here it is:
https://codesandbox.io/p/sandbox/confident-pine-yxt8l1?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A19%2C%22endLineNumber%22%3A22%2C%22startColumn%22%3A18%2C%22startLineNumber%22%3A22%7D%5D

**Comment by koba04** [comment]
@fscali  Thank you!

**Comment by promer94** [comment]
Compare fn is now not only used for comparing data but also other state field (error, isLoading, isValidating).

https://github.com/vercel/swr/blob/ad7bb15bac3cea582bc29a754e87c707cc263871/core/use-swr.ts#L110-L125

**Comment by Retrospection** [comment]
I'd like try solve this~

**Comment by fscali** [comment]
Hi, If I undersand well this bug should have been fixed by 2.0.3 but I still get the error in the sandbox I provided..

**Comment by promer94** [comment]
```js
try {
          return _.isEqual(
            a!.map((val) => val.id),
            b!.map((val) => val.id)
          );
        } catch (_) {
          return false;
        }
```
Your compare fn is buggy, it does not have the correct behaviour as

```
undefined,udefined => true 
undefined, Data => false
Data,undefined => false
Data, Data => boolean
```

**Comment by fscali** [comment]
Thank you @promer94 ...I tried but same error (see same codesandbox). In version 1.3 it works..
