### ISSUE TITLE
Mutate of useSWR not working with string key (Not revalidate and trigger fetch API again)

### ISSUE THREAD

**Issue by conanjs** [vercel/swr#2393]
# Bug report
**Mutate of useSWR not working (Not revalidate and trigger fetch API again)**

Just do a simple like image below
1/ initialize useSWR hook with a **"String**" Key (string type) and a conditional fetcher for test purpose
![image](https://user-images.githubusercontent.com/117878319/215268683-65b90490-08a3-4e95-bb55-9a085ba4cb71.png)
You may have noticed in the image, first declare **x** variable outside component and fetch nothing on first time render
2/ And after that I use **mutate function** by destructuring the object returned from useSWR hook above
to use it in a click event handler
![image](https://user-images.githubusercontent.com/117878319/215268859-6709ca39-3dd9-420a-92e0-8ef4b82c973f.png)

Yeah and like a title, nothing happen, ...no API trigger
But if I change the **key** from string to array type => that works
![image](https://user-images.githubusercontent.com/117878319/215268970-d970e1a0-5729-4f6a-a13e-19de9a59fbd2.png)
Is that a bug or just I missing something from document, can you reply to me as soon as possible...

SWR version. (v2.0.1)
<img width="106" alt="image" src="https://user-images.githubusercontent.com/117878319/215268486-8def0b17-9c21-4f41-874b-6985c9b25471.png">

**Comment by promer94** [comment]
I can't reproduce the problem here https://codesandbox.io/s/swr-basic-forked-e2cmde?file=/src/App.js

**Comment by conanjs** [comment]
Maybe tonight I will try to reproduce this in code sandbox and feedback later

**Comment by conanjs** [comment]
> I can't reproduce the problem here https://codesandbox.io/s/swr-basic-forked-e2cmde?file=/src/App.js

Maybe tonight I will try to reproduce this in code sandbox and feedback later

**Comment by conanjs** [comment]
> Hi, I have tried on code sandbox and it works normally, so I think the problem maybe came from the bundler or something from Vite maybe..., I also tried creating a next project and using SWR on a separate page it works normally too ![image](https://user-images.githubusercontent.com/117878319/215502444-2e0c4c4f-60d6-42df-8585-18e77c4e4d03.png) ![image](https://user-images.githubusercontent.com/117878319/215507955-7b5bdd6e-1104-4514-b653-68c4f215d88a.png) Log and count increments perfectly! But below... And the same code for the react project but this time created by Vite (React + Vite) ![image](https://user-images.githubusercontent.com/117878319/215502960-9df7bf2d-2ae9-439b-8d6a-1c66a73949e4.png) ![image](https://user-images.githubusercontent.com/117878319/215507587-7080d432-a2a5-45f2-9a7c-0867ef5c1129.png) and of course, that failed! No log and no count increment whenever I click Here is my information from the package and version in use, so you can check and try to reproduce that on Vite ![image](https://user-images.githubusercontent.com/117878319/215503324-938411b3-b6e1-4013-85d4-0537e966ef4d.png) ![image](https://user-images.githubusercontent.com/117878319/215503715-3535c8a9-fcfb-4c32-9e88-aca0c221c754.png) I'm not sure but you can also note that react-router-dom v6.7.0 and i use new feature using createBrowserRouter and my Vite config ![image](https://user-images.githubusercontent.com/117878319/215503628-1e7c8d65-e93e-4c9e-9fc6-81eda0ddf7b4.png)
> 
> I create the react project using Vite CLI: **pnpm create vite**

Ah just remind you, if change key from string to array in react vite, that works 💯!
![image](https://user-images.githubusercontent.com/117878319/215509481-0f03c01c-60a6-4ccf-bd2f-152a0b23ae1b.png)
![image](https://user-images.githubusercontent.com/117878319/215509343-852deb51-ab4b-4230-a840-e254ed2f7726.png)

**Comment by promer94** [comment]
It is more like a Vite's bug.
