### ISSUE TITLE
[The same key of useSWR hook in the child component not received loading status as the parent component]

### ISSUE THREAD

**Issue by conanjs** [vercel/swr#2394]
# Bug report
[The same key of useSWR hook in the child component not received loading status as the parent component]

The problem here, the situation that is assumed here is when I have a parent component that uses useSWR hook  with a string key and a fetcher function
And in that child component, use the same hook with the same string key as the parent component but NOT have a fetcher function,
in that situation, on the first render
1/ Parent component render and produce both isValidating, isLoading are TRUE due to first time.
2/ Render the child component and again I destructuring for getting isValidating, isLoading property. But this time, although those values are destructured on the same key of hook, but both of them are FALSE on the child component
If you read here, you may have noticed the thing that I want, When I use this library, I expected that with the same story above, but the child component would have the same state (isValidating, isLoading, and if more...) as their parent

Is that make sense more, because I think the fetcher function will be triggered on something like useLayoutEffect hook lifecycle,
so for the assumed story above
1/ When the parent component renders the first time, the hook checks something blah blah like cache doesn't have value for this key and it also not have this key yet, so returns true for both (because the hook on the parent knows they got a fetcher function on the second params), and because of the fetcher function will be trigger on useLayoutEffect of the parent, so it will wait until the child component render first, and when the child component renders, it wants to get all value of the exact same hook and key(just not have fetcher param), but the cache this time has nothing with this key, so that cause the mismatch problem here

The problem disappears, of course, If the child component also had the fetcher function on the parameter

I also have a test, when API is triggered the first time, I had done something for deferring that API and making render again just for testing purposes, I don't change anything from this render, and the child component has the same value as the parent, that is the normal case because I think the API that was triggered before does something on cache and they have value at that time

I think my expected behavior is a better case.

SWR version. [v2.0.1]

**Comment by promer94** [comment]
> The problem here, the situation that is assumed here is when I have a parent component that uses useSWR hook with a string key and a fetcher function
And in that child component, use the same hook with the same string key as the parent component but NOT have a fetcher function

Would you mind to share your intention for doing this ?

**Comment by conanjs** [comment]
Yes, But I am now in the office, maybe I will share it later. Thanks for replying to me

**Comment by conanjs** [comment]
So before trying to share my intention. Because I also have a bug report that came from Vite (not resolved yet):
https://github.com/vercel/swr/issues/2393
So I will try to explain my idea in Next project... just for sure haha!
Here is my code for Next project with the URL: **/same**
![image](https://user-images.githubusercontent.com/117878319/215515292-7a26c42d-2eca-4971-b9e3-e195853dce59.png)
And the result when I come to the page on the browser
![image](https://user-images.githubusercontent.com/117878319/215514842-e3190761-cb2a-4e4b-8cc2-d73de7d12d43.png)

**Comment by promer94** [comment]
I understood your example here. It is indeed a unexpected behaviour.

But i cant think of any practical user case for this pattern
