### ISSUE TITLE
Error: This Suspense boundary received an update before it finished hydrating.

### ISSUE THREAD

**Issue by iljamulders** [vercel/swr#2401]
# Bug report

## Description / Observed Behavior

When using [next/dynamic](https://nextjs.org/docs/advanced-features/dynamic-import) in combination with SWR 2.0.3 We get an error:
```
Error: This Suspense boundary received an update before it finished hydrating. This caused the boundary to switch to client rendering. The usual way to fix this is to wrap the original update in startTransition
```

## Expected Behavior

SWR 2.0.2 does not throw an error

## Repro Steps / Code Example

https://github.com/iljamulders/nextjs-dynamic-swr

```
$ yarn install

$ yarn dev
```

```tsx
const Books = dynamic(() => import('@/components/Books'))

const fetcher = (url: URL) => fetch(url).then(res => res.json())

export default function Home() {

  const { data: books } = useSWR('https://63d8db905a330a6ae16f31da.mockapi.io/Books', fetcher)

  return (
    <Books books={books} />
  )
}
```

## Additional Context

SWR version: 2.0.3

**Comment by promer94** [comment]
This is actually a react bug which has alrealy been fixed `react@next react-dom@next`

Here is the reproduction
https://codesandbox.io/p/sandbox/priceless-darwin-frq81n?file=%2Fpages%2Findex.tsx&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A1%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A1%7D%5D

The current workaroud for this issuse `const Books = dynamic(() => import('@/components/Books'), { ssr: false })`

**Comment by iljamulders** [comment]
Thanks @promer94 
This bug is indeed fixed in `react@next react-dom@next`

Closing this issue
