### ISSUE TITLE
useSWRConfig mutate function doesn't cause cache revalidation when component unmounted

### ISSUE THREAD

**Issue by yyuurreecc5** [vercel/swr#2416]
# Bug report

## Description / Observed Behavior

I'm using useSWRImmutable and at one moment I need to revalidate cache and request the data from the api. For this purpose I'm using **mutate** function from the hook **useSWRConfig**:

```
const { mutate } = useSWRConfig();
return <button onClick=() => mutate(REQUEST_KEY)}>revalidate</button>
```

I have **Component** that using swr with this key:

```
const Component = () => {
  const { data } = useSWRImmutable(REQUEST_KEY, apiRequest);
  return <>{data}</>;
};
```
If component was mounted at the moment **mutate** function was called, then data revalidating and re-requested from the api (as expected).
But if component wasn't mounted at that moment, then the data returning from the cache and doesn't re-requested from the api.

## Expected Behavior

I expect that data will be re-requested from the server after revalidation regardless of whether the component, using that data,  was rendered at the time of the **mutate** function call or not.

## Repro Steps / Code Example

[CodeSandbox](https://codesandbox.io/s/loving-haibt-ucjkvv?file=/src/App.js
)

## Additional Context

SWR version 2.0.3.

**Comment by promer94** [comment]
This is expected behaviour. Once component is unmounted,  global `mutate` can't find a valid fetcher to revalidate the cache. You have to provide a valid fetcher here.

```
const { mutate } = useSWRConfig();
return <button onClick=() => mutate(REQUEST_KEY, fetcher)}>revalidate</button>
```

**Comment by yyuurreecc5** [comment]
@promer94 Thanks for the answer, but when I do as you answered new problems appear:

1. When show === true (component mounted). The api request is executed twice on one click of the `revalidate` button (why?). And when the first request is executed there is no data in cache, only on the second one. It behavior is repeated on every click.
2. When show === false (component unmounted).  After click on the revalidate button  apiRequest is executed  despite the fact that there is not a single mounted component using swr on page. Is this behavior correct?
