### ISSUE TITLE
`useSWR` - This expression is not callable with `moduleResolution` set to `node16`

### ISSUE THREAD

**Issue by der-daniel** [vercel/swr#2419]
# Bug report

## Description / Observed Behavior

I am using a monorepo setup with pnpm. All packages are declared as `type: module`. In addition I am using `moduleResolution: node16` in my `tsconfig.json`.

This breaks my import of `swr`.

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/7686866/218042197-e71836a1-28c4-47c9-bde1-6e58557423dd.png">

I tried to play around but could not figure out where the error is coming from.

Using a little type conversion like `const useSWRFixed = useSWR as unknown as typeof useSWR.default` makes the error go away - so maybe the issue is with the type definitions.

## Expected Behavior

`swr` should be compatible with `moduleResolution: node16` and `type: module`

## Repro Steps / Code Example

https://github.com/der-daniel/swr-error

**Comment by promer94** [comment]
duplicate as #2208
