### ISSUE TITLE
How to check if there are no pending requests?

### ISSUE THREAD

**Issue by AjaxSolutions** [vercel/swr#242]
I have multiple independent fetch requests located in different files and initiated by useSWR.

How can I know when the last request is done, i.e. there are no pending requests?

I'd like to know the number of active requests initiated by useSWR.

My question is similar to to this [jQuery question](https://stackoverflow.com/questions/1822913/how-do-i-know-if-jquery-has-an-ajax-request-pending).

**Comment by quietshu** [comment]
You can just add the other useSWR as a dependent. Let's say you have 2 requests located in 2 files:

```js
// A.js

export function A() {
  const { data } = useSWR('/api/a')
  return data
}
```

```js
// B.js
export function B() {
  const { data: dependentA } = useSWR('/api/a')
  const { data } = useSWR(dependentA ? '/api/b' : null) // start to fetch when A is ready

  return data
}
```

Note that only 1 `/api/a` request will be initiated, but `/api/b` will be pending on it.

**Comment by AjaxSolutions** [comment]
I was looking for something similar to the [react-query](https://github.com/tannerlinsley/react-query) which has an interesting [useIsFetching](https://github.com/tannerlinsley/react-query#useisfetching) hook.

"useIsFetching is an optional hook that returns true if any query in your application is loading or fetching in the background (useful for app-wide loading indicators)."

**Comment by sergiodxa** [comment]
I think you could code that yourself, using React Context to store an object with the SWR keys as keys and a true if it's loading or false if it's not (or inverted if you want to know if it already loaded), then pass a function to set when a new query starts and ends (set it as true/false), then you can reduce it to a single true/false to know if there is at least one query loading.

Just an idea about how to solve it, right now there is no way to know if there are pending requests.

**Comment by quietshu** [comment]
Just like cache access, having some global APIs might be a good idea. However I think the API should be an event listener, not a hook.

**Comment by akx** [comment]
> Just like cache access, having some global APIs might be a good idea. However I think the API should be an event listener, not a hook.

It should probably be both – an event bus you can register/unregister listeners with, and a hook that does that for you and causes effects.

**Comment by em** [comment]
This is very useful for optimizing preloading - I want to only load things out of view when the network is unsaturated. With a hook that told me the network was free - I could decide to preload things below the fold using SWR conditional loading.

**Comment by testerez** [comment]
I've been trying to implement a hook similar to react-query's `useIsFetching`. But I realize it does not account for the unmounted `useSWR` hooks that could remain in `validating` state forever...
```ts
const getIsSwrLoading = () => cache.keys().some(k => k.startsWith('validating@') && cache.get(k));

function useIsSwrLoading() {
  const [isLoading, setIsLoading] = useState(getIsSwrLoading());
  const update = () => setIsLoading(getIsSwrLoading());
  useEffect(() => cache.subscribe(update), []);
  return isLoading;
}
```
See my monologue here: https://github.com/vercel/swr/discussions/942

A built-in hook and/or event listener as @shuding is suggesting would be a useful addition imho.

**Comment by ivankravets** [comment]
Hi there,

What is the proper way to handle pending requests in SWR 2.0? The "prefix" logic was removed there.
