### ISSUE TITLE
uswSWRImmutable always load `fallbackData` in suspense mode

### ISSUE THREAD

**Issue by Himself65** [vercel/swr#2436]
See test case https://github.com/vercel/swr/pull/2437

**Comment by koba04** [comment]
@Himself65 
SWR treats `fallbackData` as stale data and `useSWRImmutable` doesn't revalidate if there is stale data (`revalidateIfStale: false`).
In this case, you can use `revalidateOnMount: true` to fetch data on mount, which can be combined with `preload`.

**Comment by Himself65** [comment]
Thanks for the suggestion
