### ISSUE TITLE
[BUG] SWRInfinite when getKey returns null, results in fetching "null" endpoint

### ISSUE THREAD

**Issue by Vanuan** [vercel/swr#2439]
# Bug report

## Description / Observed Behavior

It looks like the documentation around `getKey` is incomplete.
The example [here](https://swr.vercel.app/docs/pagination#example-2-cursor-or-offset-based-paginated-api) suggests returning null if we reached the end of pagination.

```
const getKey = (pageIndex, previousPageData) => {
  // reached the end
  if (previousPageData && !previousPageData.data) return null

  // first page, we don't have `previousPageData`
  if (pageIndex === 0) return `/users?limit=10`

  // add the cursor to the API endpoint
  return `/users?cursor=${previousPageData.nextCursor}&limit=10`
}

```

## Expected Behavior

Documentation suggests, fetch should not be called if getKey returned null

## Repro Steps / Code Example

Return `null` from `getKey`. See that "null" gets fetched.

## Additional Context

It appears the problem in this line:
https://github.com/vercel/swr/blob/591726acaf78f3aba39755a8795d454ac88af42e/infinite/index.ts#L143-L145

`serialise(null)` returns `"null"`. So this get passed to fetcher as `(!"null")` is truthy.

Maybe a bug in serializer?

**Comment by Vanuan** [comment]
Probably `stableHash` is supposed to return null? https://github.com/vercel/swr/blob/591726acaf78f3aba39755a8795d454ac88af42e/_internal/utils/hash.ts#L20

**Comment by Vanuan** [comment]
Probably related to this:
https://github.com/vercel/swr/issues/1345

**Comment by koba04** [comment]
@Vanuan Could you reproduce this?

> serialise(null) returns "null". So this get passed to fetcher as (!"null") is truth.

I think `serialize(null)` returns `''`, which is a falsy value, so the key would be skipped.

- https://github.com/vercel/swr/blob/main/_internal/utils/serialize.ts
- https://github.com/vercel/swr/blob/591726acaf78f3aba39755a8795d454ac88af42e/test/unit/serialize.test.ts#L7

**Comment by Vanuan** [comment]
Sorry, my fault. The mistake I did was this:

```
  const getKey = (
    pageIndex,
    previousFetchData,
  ) => {
    if (pageIndex === 0 || !previousFetchData) {
      return ENDPOINT + key; // beginning of pagination
    }
    if (previousFetchData && !previousFetchData.data) {
      return null; // end of pagination
    }
    return previousFetchData.next + key; // returns the endpoint for the next call
  };

```

I concatenated null with empty string "" resulting in "null".
