### ISSUE TITLE
Filter function doesn't work as key in useSWRMutation

### ISSUE THREAD

**Issue by utg1-tdawg** [vercel/swr#2457]
### Discussed in https://github.com/vercel/swr/discussions/2456

<div type='discussions-op-text'>

<sup>Originally posted by **utg1-tdawg** February 25, 2023</sup>
I am trying to revalidate multiple keys upon `trigger` by passing a filter function as key to `useSWRMutation` as suggested in the [docs](https://swr.vercel.app/docs/mutation#mutate-multiple-items). But I am getting an error. 

Here is my code:
```typescript
import useSWR from "swr";
import useSWRMutation from "swr/mutation";

export default function Jokes() {
  const firstJokeQuery = useSWR("first-joke", getJoke);
  const secondJokeQuery = useSWR("second-joke", getJoke);

  const mutation = useSWRMutation(
    (key) => ["first-joke", "second-joke"].includes(key),
    () => null
  );

  return (
    <div>
      <div>
        <h2>First joke</h2>
        <p>{firstJokeQuery.data?.joke}</p>
      </div>
      <div>
        <h2>Second joke</h2>
        <p>{secondJokeQuery.data?.joke}</p>
      </div>

      <button onClick={() => mutation.trigger()}>Get new jokes</button>
    </div>
  );
}

async function getJoke() {
  return fetch("https://v2.jokeapi.dev/joke/Any?type=single").then((res) =>
    res.json()
  );
}
```

And here is the error message that I am getting:
```
Unhandled Runtime Error
Error: Can’t trigger the mutation: missing key.
```

What is the correct way to revalidate multiple keys? I have also tried passing an array `["first-joke", "second-joke"]` as key to `useSWRMutation` but it doesn't work too. 

</div>

**Comment by koba04** [comment]
@utg1-tdawg 
I've answered it at https://github.com/vercel/swr/discussions/2456#discussioncomment-5112438, so I'll close this.
