### ISSUE TITLE
SWR 2.0.3 unnecessary re-render when useSyncExternalStore snapshots are the same value

### ISSUE THREAD

**Issue by domazet93** [vercel/swr#2473]
# Bug report

## Description / Observed Behavior

There is an extra component render caused by SWR hook call. 
In the example below no SWR stateful values are consumed, so we should not see any re-rendering, but still see that one re-render: https://swr.vercel.app/docs/advanced/performance#dependency-collection

This affects performance and overall core web vitals score.

Downgrading to `2.0.2` fixed the issue and can see only one initial render. 

## Expected Behavior

We shouldn't re-render component if the store snapshot & server snapshot return the same value/object.

## React version

React: `18.2.0`

## SWR version

SWR: `2.0.3`

## Repro Steps / Code Example

https://github.com/domazet93/user-swr-2.0.3-app
https://user-swr-2-0-3-app-with-rerendering.vercel.app/

```
import useSWR from "swr";
import axios from "axios";

const fetch = axios.create({
  baseURL: "https://jsonplaceholder.typicode.com"
});

const useFetchUser = () =>
  useSWR("/users/100", (url) =>
    fetch.get(url).then((res) => {
      const { data: userData } = res;

      if (userData) {
        return userData;
      }

      return undefined; 
    })
  );


export default function UserSWR() {
  useFetchUser();

  return <div>Open React Profiler and check each time SWRTest rendered</div>;
}
```

### SWR `v2.0.2` (no re-rendering)
![Screenshot 2023-03-03 at 13 48 18](https://user-images.githubusercontent.com/20770725/222736369-c040809a-ee7f-4d08-a176-05478da3bea4.png)

### SWR `v2.0.3` (with re-rendering)
![Screenshot 2023-03-03 at 13 37 06](https://user-images.githubusercontent.com/20770725/222734780-60083406-bef4-431b-9a09-094b5b9a85c9.png)

![Screenshot 2023-03-03 at 13 37 41](https://user-images.githubusercontent.com/20770725/222734806-33cd9964-6692-4988-b076-f00b04e10d25.png)

## Additional Context
Tested with `"react": "18.2.0"`
Introduced in `v2.0.3`: https://github.com/vercel/swr/compare/v2.0.2...v2.0.3

PR: https://github.com/vercel/swr/pull/2391 

This is the code in question:
```
// To make sure that we are returning the same object reference to avoid
// unnecessary re-renders, we keep the previous snapshot and use deep
// comparison to check if we need to return a new one.
let memorizedSnapshot = getSelectedCache(getCache())
const memorizedInitialSnapshot = getSelectedCache(getInitialCache())

return [
  () => {
    const newSnapshot = getSelectedCache(getCache())
    return isEqual(newSnapshot, memorizedSnapshot)
      ? memorizedSnapshot
      : (memorizedSnapshot = newSnapshot)
  },
  () => memorizedInitialSnapshot
]
// eslint-disable-next-line react-hooks/exhaustive-deps
}, [cache, key])
```

This snapshots (objects) get passed to `useSyncExternalStore` and from the docs we should probably serialize it?
https://beta.reactjs.org/reference/react/useSyncExternalStore#parameters

> The server snapshot must be the same between the client and the server, and is usually serialized and passed from the server to the client.

**Comment by promer94** [comment]
Thanks for reporting. 

Could you provide the version of React you used for this reproduction.

**Comment by domazet93** [comment]
@promer94 Thanks for having a look.
I updated the pr description. The react version is `18.2.0` 
I bootstrapped the app with `create-next-app` and just tweaked the component to use SWR. Here are all dependencies:

```
"dependencies": {
  "axios": "1.3.4",
  "next": "13.2.3",
  "react": "18.2.0",
  "react-dom": "18.2.0",
  "swr": "2.0.3"
}
```

The issue is happening on `development` env for sure. 
I did try to use codesandbox, but could not reproduce the issue so makes me think this could be a dev only issue ? 
I could try to deploy the app to vercel and see if it happens in prod.

**Comment by domazet93** [comment]
@promer94 updated pr desc with repo/production deploy url so you can see reproducible re-rendering (React Profiling not supported for prod env)

https://github.com/domazet93/user-swr-2.0.3-app
https://user-swr-2-0-3-app-with-rerendering.vercel.app/

<img width="1432" alt="Screenshot 2023-03-03 at 16 04 30" src="https://user-images.githubusercontent.com/20770725/222769117-82dfccc4-5de6-4d14-9c32-5d3fb9f79fa2.png">
