### ISSUE TITLE
useSWRMutation trigger type error

### ISSUE THREAD

**Issue by signalxu** [vercel/swr#2500]
# Bug report

Argument of type '{ chainId: number; }' is not assignable to parameter of type 'null | undefined'.ts(2345)

## Description / Observed Behavior

```
export const PlanDetailFunc = async(url:string, { arg }:{arg:{chainId:number}}) => {
  const res = await post(url,arg)
  return res
}

export const usePlanDetailFunc = () => {
  
  const{ trigger, isMutating, error } = useSWRMutation<PlanDetail>('/v1/get_chain_plans',PlanDetailFunc)
  return {
    trigger,
    isMutating,
    error,
  }
}


```
```
const{
    trigger: planDetailTrigger,
    isMutating: planDetailIsMutating,
   } = usePlanDetailFunc()

const res = await planDetailTrigger({chainId:selected.id})
```

Argument of type '{ chainId: number; }' is not assignable to parameter of type 'null | undefined'.ts(2345)

## Expected Behavior

No type error

## Additional Context

SWR Version v2.0.3 / v2.1.0

**Comment by promer94** [comment]
Due to TypeScript limitation, you can't just manually set the `Data` type and expect it could infer the rest of generics.

You could `PlanDetailFunc` a more specific type, then the type inference will work as expected.
```tsx
export const PlanDetailFunc: (url: string, { arg }:{ arg:{chainId:number}}) => Promise<PlanDetail>  = async (url, { arg }) => {
  const res = await post(url,arg)
  return res
}

export const usePlanDetailFunc = () => {
  
  const{ trigger, isMutating, error } = useSWRMutation('/v1/get_chain_plans',PlanDetailFunc)
  return {
    trigger,
    isMutating,
    error,
  }
}
```
