### ISSUE TITLE
Components that depend on `useSWR` return value object are not re-rendered correctly

### ISSUE THREAD

**Issue by swallowtail62** [vercel/swr#2512]
# Bug report

Child components that depend on the return value object of `useSWR` hook as props may not be re-rendered.

## Description / Observed Behavior

It was working correctly up to v1, but not since v2. 

## Repro Steps / Code Example

https://codesandbox.io/s/swr-re-render-dn2whh?file=/src/App.tsx

https://user-images.githubusercontent.com/45661101/225287934-97f671fc-f6ec-451e-851e-7aad0eca6197.mov

## Expected Behavior

In the case of the example above, the expected behavior is that the data is fetched (from cache) when the dialog is displayed.

## Additional Context

SWR version. v^2.0.0

**Comment by koba04** [comment]
This seems to be the same issue with #2446

**Comment by swallowtail62** [comment]
Indeed, it seems so. Thanks.

**Comment by shuding** [comment]
Closing as we're fixing #2446.
