### ISSUE TITLE
Type inference is broken when using options

### ISSUE THREAD

**Issue by numb86** [vercel/swr#2520]
# Bug report

## Repro Steps / Code Example

Passing options to `useSWR` will cause type inference to fail to function properly.

First, here is an example that works correctly.

The following `data`, `error` and `isLoading` are exactly what I want.

```typescript
import useSWR, { Fetcher } from 'swr';

class OriginalError extends Error {
    public override readonly name = this.constructor.name;
    public constructor(message: string) {
        super(message);
    }
}

const fetcher: Fetcher<{ data: unknown }, string> = async (url) =>
    await fetch(url)
        .then(async (r) => {
            const data: unknown = await r.json();
            return { data };
        })
        .catch(() => {
            throw new OriginalError('');
        });

// data: {data: unknown} | undefined
// error: OriginalError | undefined
// isLoading: boolean
const { data, error, isLoading } = useSWR<{ data: unknown }, OriginalError>('key', fetcher);
```

However, passing an option to `useSWR` breaks type inference(In the following example, `{}` is passed, but this behavior seems to occur regardless of the contents of the options.).

```typescript
// data: {data: unknown}
// error: OriginalError | undefined
// isLoading: false
const { data, error, isLoading } = useSWR<{ data: unknown }, OriginalError>('key', fetcher, {});
```

The `undefined` possibility is lost from `data` and the `true` possibility is lost from `isLoading`.
Of course, it is possible that `data` will actually be `undefined`. Likewise, it is possible that `isLoading` will be `true`.

Passing `SWRConfiguration` does not improve the situation.

```typescript
// data: {data: unknown}
// error: OriginalError | undefined
// isLoading: false
const { data, error, isLoading } = useSWR<{ data: unknown }, OriginalError, SWRConfiguration>('key', fetcher, {});
```

If I stop using generics, the `data` and `isLoading` will be correct. But now the `error` will be `any`.

```typescript
// data: {data: unknown} | undefined
// error: any
// isLoading: boolean
const { data, error, isLoading } = useSWR('key', fetcher, {});
```

The only solution I have found is to use `as`. This way, the type becomes desirable.

```typescript
// data: {data: unknown} | undefined
// error: OriginalError | undefined
// isLoading: boolean
const { data, error, isLoading } = useSWR<{ data: unknown }, OriginalError>('key', fetcher, {}) as {
    data: { data: unknown } | undefined;
    error: OriginalError | undefined;
    isLoading: boolean;
};
```

But I want to avoid `as` much as possible.
I expect the generics will make the appropriate type inferences for safer SWR use.

## Additional Context

SWR version.
`2.1.0`

**Comment by koba04** [comment]
@numb86 Thank you! This has been fixed in https://github.com/vercel/swr/pull/2506, and I've added the test case at #2521

**Comment by numb86** [comment]
I understood. Thanks!
