### ISSUE TITLE
useSWRConfig.mutate('/users') is not work with useSWRMutation

### ISSUE THREAD

**Issue by vaynevayne** [vercel/swr#2530]
when muate button clicked, not any request emit

```jsx
import { useSWRConfig } from 'swr'
import useSWRMutation from 'swr/mutation'

async function updateUser(url, { arg }: { arg: Record<string, any> }) {
  await axios({
    url: url,
    params: arg,
    method: 'GET',
  })
}

const App= ()=>{
 const { data, trigger, error } = useSWRMutation('/users', updateUser)
  const { mutate } = useSWRConfig()

return (
  <>
    <button onClick={()=> trigger({page:'2'})} >submit</button>
    <button onClick={mutate('/users')}>mutate </button>  
  </>
  )
}
```

**Comment by hwangyena** [comment]
I think that's the correct response.

[https://swr.vercel.app/docs/mutation](https://swr.vercel.app/docs/mutation)
In this docs, they said.
`Using global mutator only with the key parameter will not update the cache or trigger revalidation unless there is a mounted SWR hook using the same key.`

If you want to update your data, you need any SWR hook (`useSWR`).

**Comment by vaynevayne** [comment]
thanks ,
I thought there was finally a useful hook that didn't rely on a key, but I was wrong.
