### ISSUE TITLE
Global mutate with filter doesn't work with useSWRInfinite keys

### ISSUE THREAD

**Issue by Davasny** [vercel/swr#2533]
# Bug report

## Description / Observed Behavior

Using filter in mutate from `useSWRConfig` doesn't work with cache keys created by `useSWRInfinite` hook.

None of those codes will trigger refresh of cache key:
```js
const { mutate: configMutate } = useSWRConfig();

<button
  disabled={isRefreshing}
  onClick={() => configMutate(() => true)}
>
  () true
</button>
```

```js
const { mutate: configMutate } = useSWRConfig();

<button
  disabled={isRefreshing}
  onClick={() =>
    configMutate((key) =>
      typeof key === "string" && key.includes("instantwebtools")
        ? unstable_serialize(
            () =>
              "https://api.instantwebtools.net/v1/passenger?page=1&size=10"
          )
        : false
    )
  }
>
```

But using bound mutate works:

## Expected Behavior

I expected that mutate will work the same way for `useSWR` and `useSWRInfinite` hooks

## Repro Steps / Code Example

1. Open code sandbox
2. Open devtools
3. Click `boundMutate` button - works
4. Click `() true` button - will not work
5. Click `unstable_serialize` button - will refresh cache as it uses just `unstable_serialize` as cache key passed to `configMutate`
6. Click `unstable_serialize in filter` button - will not work as it just returns true value to filter method.

I guess `configMutate` uses raw key, when internally `useSWRInfinite` uses keys prefixed with `$inf$`

Forked example of `useSWRInfinite` with reproduced bug (changed API to some online mock to avoid github limits):

[https://codesandbox.io/s/swr-infinite-bug-in-mutate-ern1ii?file=/src/App.js](https://codesandbox.io/s/swr-infinite-bug-in-mutate-ern1ii?file=/src/App.js)

## Additional Context

SWR 2.1.1

**Comment by koba04** [comment]
You are right. That's a limitation of the current mutate filter function.
We'll discuss this at https://github.com/vercel/swr/issues/2497
