### ISSUE TITLE
refreshInterval: callback reference issue

### ISSUE THREAD

**Issue by bastischulz** [vercel/swr#2547]
For the refresh interval you have the possibility to specify a callback. If you now pass the same reference, the "data" parameter will not be updated correctly, and thus the callback will not be called correctly.

Conrect:

```
const refreshInterval = (data) => {
      if (!data) return 0;
      return data?.pollingInterval ?? THIRTY_SECONDS * 1000;
};
```

Data is initially `undefined`, which is correct. The problem is, if the reference of the function `refreshInterval` remains identical, the callback will not be executed a second time if data is there.
What else I noticed: If the function `refreshInterval` returns a fixed value (e.g. 10000), data also remains `undefined`.

My use case: I initially create various custom fetch hooks, and some of them should have a `refreshInterval` integrated per se. But the interval depends on the data itself.

I can think of 1 or 2 spontaneous workarounds, but I wonder if this behavior is desired from a performance point of view.

**Comment by promer94** [comment]
Thanks for reporting !

There is a pr #2354 to address this issue.
