### ISSUE TITLE
useSWRSubscription key doesnt deconstruct array

### ISSUE THREAD

**Issue by imownbey** [vercel/swr#2548]
# Bug report

## Description / Observed Behavior
When using an array key the key that is passed to the subscribe function is a string and not an array

## Expected Behavior
I expect it to be deconstructed similar to is shown under "Usage" here https://swr.vercel.app/docs/subscription

## Repro Steps / Code Example

```
  const key = "a key";
  const { data } = useSWRSubscription(["key", key], (passedKey, { next }) => {
    passedKey === '@"key","a key",' // returns true
    return () => {};
  });
```

https://codesandbox.io/s/relaxed-silence-h556kz?file=/src/App.js

## Additional Context
2.1.2

**Comment by promer94** [comment]
we should pass original key here instead of serialized key
https://github.com/vercel/swr/blob/bad51f61bf54166abcb0f2a424eafda88157a6ab/subscription/index.ts#L67

**Comment by Zheaoli** [comment]
I would like to take this issue

**Comment by crutch12** [comment]
By the way
Could we pass `originKey` to `onError/onSuccess` callback?
On it accepts serialized key **only**, it's terrible.

@Zheaoli
