### ISSUE TITLE
useSWR keeps fetching

### ISSUE THREAD

**Issue by anthonyalayo** [vercel/swr#2549]
# Bug report

useSWR continually fetches when it shouldn't be.

## Description / Observed Behavior

I have the following useSWR call:

```
  const {
    data,
    error,
    mutate,
  } = useSWR(
    hash !== '' ? `${hash}` : null,
    (url) => axios.get(url),
    {
      revalidateOnFocus: false,
      revalidateOnReconnect: false,
      dedupingInterval: 120000, // 2 minutes
    }
  );
```

And while nothing is changing, the request keeps happening:

![image](https://user-images.githubusercontent.com/17555572/230505781-803d05a7-9f12-47c4-b1df-96dd1890f0f9.png)

## Expected Behavior

I expect it to make a single request.

## Repro Steps / Code Example

Included in the description.

**Comment by promer94** [comment]
Could you provide a more detailed reproduction using codesandbox ? 

According to your screenshot, i guess the reason is because SWR have a [built-in error retry mechanism](https://swr.vercel.app/docs/error-handling#error-retry), which is expected behavior

**Comment by anthonyalayo** [comment]
@promer94  thank you, that was it! I couldn't find this under the [Automatic Revalidation](https://swr.vercel.app/docs/revalidation) docs and didn't realize the feature existed. Thanks! Closing up.
