### ISSUE TITLE
`isValidating` only updates for one hook instead of all hooks using the same key

### ISSUE THREAD

**Issue by duniul** [vercel/swr#256]
### Current behavior

When rendering multiple hooks using the same key at the same time, only one of the hooks get updated with the current `isValidating` state.

Example to replicate:

```jsx
const Validating = () => {
  const swr = useSWR('/example');
  console.log('isValidating', swr.isValidating);
  return <div>{swr.isValidating}</div>;
}

const ExampleComponent = () => {
  return (
    <Validating />
    <Validating />
  );
}
```

The console output when rendering this will be something like:

```js
isValidating false
isValidating false
isValidating true
isValidating true
isValidating false
```

Only one of the hooks re-renders with the updated `isValidating` after data is returned. `data` and `error` is correctly updated for all hooks.

### Expected behavior

All hooks re-render when `isValidating` changes for a key.

---

This seems to be the case for any request after the initial one and focus/unfocus requests. It does _not_ seem to happen for interval fetches when using `refreshInterval`, in that case all hooks get updated on each interval.

At first I thought this was related to the re-rendering changes from 1.1.16, but this happens on older versions too. I'm guessing this has to do with `isValidating` not tied to the key the same way `data` and `error` is (based on https://github.com/zeit/swr/issues/199#issuecomment-565873662).

**Comment by huozhi** [comment]
@duniul can you try to bump swr to latest (0.3.x). the issue seems to be resolved now
