### ISSUE TITLE
error not cleared upon mutate() without revalidation

### ISSUE THREAD

**Issue by avispeng** [vercel/swr#2586]
# Bug report

## Description / Observed Behavior

Hi there. We have a custom hook `useUser()` that calls `useSWR('/api/user')` inside. There is a component A that uses `useUser()` and diables `shouldRetryOnError`. Inside component A, `mutate(customUser, {revalidate: false})` is used to mutate the user data, and it will then lead to unmount of component A, and mount of component B which also uses `useUser()`. 

The current behaviour is that, useUser() will not fetch the data on mount of component B because the error is not cleared, and retry-on-error is disabled (in component A only). Explicitly using `revalidateOnMount` in useUser() in component B doesn't seem to help. We have to call mutate() explicitly on mount of component B (inside `useEffect()` hook) to fetch the data.

## Expected Behavior

The expected behaviour is that, when error happens in useUser() in component A, it will not retry. When A is unmounted, and B is mounted, useUser() inside B should fetch the data.

## Repro Steps / Code Example

I have made a sandbox that shows the error will not be cleared upon mutation without revalidation. [CodeSandbox](https://codesandbox.io/s/modest-beaver-by3kvn?file=/src/App.js)
In the sandbox, if swr@1.x.x is used, the behaviour is expected. the issue seems to be only in swr@2.x.x

## Additional Context

SWR version: 2.1.5

While I am searching the old issues in the repo, I found [this](https://github.com/vercel/swr/issues/193#issuecomment-931928418) which says the error should be cleared in mutate() without revalidation.

I am wondering if this is a intentional change in v2.

Thanks

**Comment by musme** [comment]
have some problem
