### ISSUE TITLE
trigger of useSWRMutation does not resolve when used with axios and useSWR

### ISSUE THREAD

**Issue by jansepke** [vercel/swr#2589]
# Bug report

## Description / Observed Behavior

I am currently unable to correctly test useSWR and useSWRMutation together with axios in one component. The test works when `revalidate` on `useSWRMutation` is set to `false` OR if I am not using axios. So somehow the problem exists only with the default re-validation setting of useSWRMutation together with axios and an useSWR sharing the same cache key. 

## Expected Behavior

The `trigger` of `useSWRMutation` should resolve if the mocked axios request resolves even if re-validation triggers a new get request.

## Repro Steps / Code Example

run `npm install && npm test` in https://github.com/jansepke/swr-axios-bug
The repo contains a working test without revalidation, a working test without axios and a failing test with revalidation and axios.

**Comment by promer94** [comment]
Thanks for the detail reproduction !

It seems the root cause of this problem is that the revalidation request can't resolve the mocked response, which is not related to SWR itself.

**Comment by jansepke** [comment]
ok that gives me another reason to migrate from axios to plain fetch
