### ISSUE TITLE
Infererd type of Data is wrong with the axios-typescript example

### ISSUE THREAD

**Issue by svenlombaert** [vercel/swr#2613]
# Bug report

## Description / Observed Behavior

I think the returned data property from the axios typescript example should be a union type of Data | undefined. It's always Data, even with suspense set to false

## Expected Behavior

Union type of Data | undefined is returned

## Repro Steps / Code Example

https://codesandbox.io/s/swr-axios-ts-example-bp4w6s?file=/src/index.tsx

![Screenshot 2023-05-12 at 14 31 47](https://github.com/vercel/swr/assets/2846986/02552dc5-ac77-4997-9c63-3024151666ec)

## Additional Context

SWR version: 2.1.5

Edit: with the exact same versions of axios, typescript and swr in a react-native project, the type *is* inferred correctly

**Comment by huozhi** [comment]
It seems working properly with next.js locally, could be sth wrong with the reproduction on codesandbox? I'll close this issue for now as it's not a problem of the library. Can carry on in the discussion
