### ISSUE TITLE
autocomplete for swr doesn't work on vscode

### ISSUE THREAD

**Issue by vikyw89** [vercel/swr#2622]
# Bug report

## Description / Observed Behavior

SWR autocomplete / code suggestion doesn't appear for useSWRImmutable, useSWR, useSWRSubscription import
![image](https://github.com/vercel/swr/assets/112059651/8026660d-6896-424b-a4fd-f7364be64db2)

## Expected Behavior

autocomplete should work for SWR code in vscode

## Repro Steps / Code Example

- Just type the useSWR 
- It doesn't show auto completion and import autocomplete on vscode
- on good news, mutate autosuggestion works

## Additional Context

SWR version.  latest

One fix i can think of is migrating from old default export into named export

**Comment by yash-sharma01** [comment]
I've also observed this behavior.

**Comment by devjiwonchoi** [comment]
Seems like #2563 tried to resolve it but doesn't work as expected.

The reason is that it is bundled by `bunchee` as `export { useSWR as default }`, and it seems like the TypeScript cannot auto-import `as default` modules. I've opened an issue to Typescript [here](https://github.com/microsoft/TypeScript/issues/54839) and will come back to this issue once it is resolved.

**Comment by devjiwonchoi** [comment]
@vikyw89 Resolved with https://github.com/microsoft/TypeScript/pull/54871, let's test it out after the next Typescript release :)

**Comment by devjiwonchoi** [comment]
Hey @vikyw89 it's been a while, TypeScript v5.2.2 has been released and will be supported on the next VS Code release 😄.

If you want to check it out now, you can try it on the [vscode insiders](https://code.visualstudio.com/insiders/).

![Screenshot 2023-09-03 at 9 37 51 AM](https://github.com/vercel/swr/assets/120007119/f4f24bf6-47c0-487b-8aa0-4bbd8addf262)

**Comment by vikyw89** [comment]
Awesome ! Thank you so much

**Comment by devjiwonchoi** [comment]
@vikyw89 @yash-sharma01  New release came out and it seems to be working.

I guess you can close this issue now.

![Screenshot 2023-09-08 at 3 53 15 PM](https://github.com/vercel/swr/assets/120007119/4378ce05-7a99-4817-9897-96f9f60002e0)
