### ISSUE TITLE
[feature] useSWR should provide a refresh as the return parameter

### ISSUE THREAD

**Issue by 51wangping** [vercel/swr#2641]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

## Expected Behavior
```
import fetch from 'unfetch'

const fetcher = url => fetch(url).then(r => r.json())

function App () {
  const { data, error, refresh } = useSWR('/api/data', fetcher)
  // ...
  
  <button onClick={refresh}> refresh </button>
}
```

How did you expect SWR to behave here?

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version.

**Comment by huozhi** [comment]
You can use the returned `mutate` function to revalidate the results

```js
const { mutate } = useSWR(...)
mutate()
```

Or use global mutate
```js
const { mutate } = useSWRConfig()
mutate(() => true)
```
