### ISSUE TITLE
useSWRSubscription， subscribe vs. unsubscribe execution order issues

### ISSUE THREAD

**Issue by keene-dalveytech** [vercel/swr#2646]
```
const subscribeKLinesKeys = useMemo(() => {
    if (!currentSeries || !symbol || !period || !priceData?.length) return null
    const cursor = priceData[priceData.length - 1]?.time
    return [`subscribeKLines-${cursor}`, symbol, period, platform]
  }, [currentSeries, priceData, symbol, period])

  useSWRSubscription(subscribeKLinesKeys, ([key, symbol, period, platform]) => {
    if (!symbol || !period) return () => {}
    const unsubscribeKLines = subscribeKLine({ symbol, period }, platform, (data) => {
      const endTime = key?.split('-')[1]
      if (data && data.time === Number(endTime)) {
        currentSeries.update(data)
      }
    })
    return unsubscribeKLines
  })
```
When priceData changes, **subscribeKLine** and then **unsubscribeKLines** are triggered. As a result, subscribing fails
### expectation

first execute **unsubscribeKLines**, then **subscribeKLine**

<img width="636" alt="image" src="https://github.com/vercel/swr/assets/126315969/759c6c40-316f-4cee-b0a9-0ddb7e99d882">

**Comment by promer94** [comment]
> As a result, subscribing fails

Would you mind to explain more about it and could you provide a simplified reproduction for this problem here.

**Comment by keene-dalveytech** [comment]
> > As a result, subscribing fails
> 
> Would you mind to explain more about your problem here ? What do you mean by `fails` ?
unsubscribe subscribe

The later unsubscribe message overwrites the earlier subscribe message, so the end result is unsubscribe

**Comment by promer94** [comment]
> The later unsubscribe message overwrites the earlier subscribe message, so the end result is unsubscribe

Could you provide a simplified example to demonstrate this problem.

**Comment by promer94** [comment]
https://codesandbox.io/s/2646-lwv4yh
