### ISSUE TITLE
MutatorCallback type too strict when passing a function to populateCache

### ISSUE THREAD

**Issue by svenlombaert** [vercel/swr#2647]
# Bug report

## Description / Observed Behavior

So, I have kind of a complicated example where the typings of the `MutatorCallback` are actually too strict. It's typed with return type `Data` which is good if you use the `populateCache` option with `true`.

There's also the option to use `populateCache` with a function, which is correctly typed as this: `(result: any, currentData: Data | undefined) => Data`. `result` could be `any` but not in `MutatorCallback` where it's restricted to `Data`

## Expected Behavior

It should accept `any` as a return type in the `MutatorCallback` type, preferably *only* when a callback is passed to `populateCache`

## Repro Steps / Code Example

This is a bit hard to set up but I've got something like this:

```typescript
export interface ConnectionListApiResponse {
  EXCHANGE: ExchangeConnection[];
  WALLET: Wallet[];
  BROKER: BrokerConnection[];
}

const { data: connectionsData, mutate: mutateConnectionList } =
  useRequest<ConnectionListApiResponse>(
    {
      url: '/connection/list',
    },
  );
```

I then have separate polling endpoints which return a partial `ConnectionListApiResponse`, one for BROKER, one for WALLET and one for EXCHANGE. My mutate looks something like this:

```typescript
const fetchWallets = async () => {
    const walletConnectionResponse =
      await api.get<{ success: boolean; connections: Wallet[] }>(
          '/wallet-connection'
        );

    return {
      WALLET: walletConnectionResponse.data.connections,
    };
  };

  await mutateConnectionList(fetchWallets(), {
    populateCache: (
      result: Pick<ConnectionListApiResponse, 'WALLET'>,
      currentData,
    ) => {
      if (!currentData) {
        return result;
      }

      return {
        ...currentData,
        data: {
          ...currentData.data,
          ...result,
        },
      };
    },
    revalidate: false,
  });
```

## Additional Context

SWR version: 2.1.3

**Comment by promer94** [comment]
For your specific use case. I would recommend you not to use `populateCache`.

Instead, you could do

```tsx
mutateConnectionList(
  (current = {}) => 
    fetchWallets()
    .then(v => ({...current, WALLET: v}))
    .catch(() => current)
)
```

to partially update the cache.

**Comment by promer94** [comment]
Closing in favor of #2690
