### ISSUE TITLE
Server action mutation doesn't flush updates until the action finishes

### ISSUE THREAD

**Issue by keyz** [vercel/swr#2653]
# Bug report

## Description / Observed Behavior

(see repro below)

I'm experimenting with using (abusing? 🤔) a server action as a mutation fetcher, and I found that a server action mutation doesn't flush updates until the action finishes.

My hypothesis is it probably has something to do with both `swr` and React marking the update as a transition, therefore starving the update, but I haven't got to the bottom of it yet; wanted to open an issue early to see if y'all have any feedback/thoughts.

## Expected Behavior

The mutation should flush an `isMutating` update immediately

## Repro Steps / Code Example

https://codesandbox.io/p/sandbox/determined-dubinsky-wgf568?file=%2Fsrc%2Fapp%2Fpage.tsx%3A17%2C19

- The first "trigger" button doesn't flush updates until the action finishes
- The second "trigger" updates `isMutating` immediately as expected

<img width="489" alt="image" src="https://github.com/vercel/swr/assets/2268452/d711caec-ea00-410d-b8af-9bc490d515a2">

## Additional Context

Tested on latest canary versions: 
- swr: `2.2.0-beta.0`
- next: `13.4.5-canary.4`

**Comment by promer94** [comment]
Thanks for your Repro!

**Comment by keyz** [comment]
Thanks for the quick turnaround @promer94 -- would love to see a new beta release :)

**Comment by huozhi** [comment]
Reopen this issue as reverted in #2681 
x-ref: https://github.com/vercel/swr/pull/2654#issuecomment-1599307815
