### ISSUE TITLE
Unexpected Requirement for Explicit Undefined in useSWRMutation ExtraArg

### ISSUE THREAD

**Issue by saengmotmi** [vercel/swr#2665]
# Bug report

## Description / Observed Behavior

In the current implementation of SWR, if an `ExtraArg` exists in the `useSWRMutation` hook, it's mandatory to pass `undefined` explicitly, even if the `ExtraArg` is optional. This is due to the conditional typing that requires a value for `ExtraArg` if it exists.

In my opinion, I think the problem originated from this PR: https://github.com/vercel/swr/pull/2421

May I create a PR for this issue?

## Expected Behavior

The expected behavior is that if `ExtraArg` is optional, `undefined` should be assumed when no value is passed, instead of requiring `undefined` to be passed explicitly.

## Repro Steps / Code Example

Here is a code snippet demonstrating the issue:

```tsx
import useSWRMutation from 'swr/mutation';

// ...

const {
  data: registeredDevicesData,
  isLoading: isRegisteredDevicesDataLoading,
} = useSWR(getRegisteredDevicesRoute(), getRegisteredDevices);

// ... 

const attemptRegisterDevice = async () => {
  try {
    await registerDeviceTrigger(undefined); // TO-BE: await registerDeviceTrigger()
    // ...
  } catch (e) {
    // ...
  }
};
```

If undefined is not passed as a parameter to the trigger, the following error message will be received:

```
Expected 1-2 arguments, but got 0.ts(2554)
index.d.ts(27, 214): An argument for 'extraArgument' was not provided.
```

My Proposed solution: Modify the conditional typing in the useSWRMutation hook such that ExtraArg is optional, allowing undefined to be assumed when no value is passed. This will eliminate the need to pass undefined explicitly.

```ts
// SWRMutationResponse type
trigger: <SWRData = Data>(
  extraArgument?: ExtraArg, // TO-BE: Optional
  options?: SWRMutationConfiguration<
    Data,
    Error,
    ExtraArg,
    SWRMutationKey,
    SWRData
  >
) => Promise<Data | undefined>
```

## Additional Context
SWR version: 2.1.3

**Comment by promer94** [comment]
Thanks for reporting!

> May I create a PR for this issue?

Sure ! That would be awesome ❤️

Also you could always ping me if you have any question

**Comment by Riley19280** [comment]
I am also encountering this issue in v2.2.1-beta.0. Would be nice not to have to update 200+ api calls with an explicit `undefined` when updating.
