### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'n.fallback[S]')

### ISSUE THREAD

**Issue by andreisocaciu** [vercel/swr#2675]
# Bug report

## Description / Observed Behavior

I'm using `useSWR` with fallback data from `getStaticProps` and I'm getting a lot of errors like this.

## Expected Behavior

Not getting any errors when `useSWR` wants to access fallback data.

## Repro Steps / Code Example

```tsx
// pages/index.tsx
export const getStaticProps: GetStaticProps<
  { fallback: Record<string, any> },
  { business: string }
> = async (context) => {
  // fetch data here
  return {
    fallback: {
        [unstable_serialize(['/book/business', context.params.business])]: business,
    }
  }
}

export default function IndexPage({ fallback }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <SWRConfig value={{ fallback }}>
      <ComponentThatReadFallbackData />
    </SWRConfig>
  );
}
```

## Additional Context

SWR version: `2.1.5`

Self-hosted Next.JS project.

Client browsers: `Instagram 285.0.0`, `Mobile Safari 16.5`

### Stack trace:
```ts
// my code does this:
const { data, error } = useSWR(query.business ? ['/book/business', query.business as string] : null, ([url, link]) =>
  fetchBusiness(url, link)
);

// useSWR code breaks here
// ./node_modules/swr/core/dist/index.mjs in useSWRHandler at line 30:33
const fallback = isUndefined(fallbackData) ? config.fallback[key] : fallbackData;
```

**Comment by promer94** [comment]
It seems like you write a wrong `getStaticProps` function which does not pass `fallback` to the props of page component

https://nextjs.org/docs/pages/api-reference/functions/get-static-props#getstaticprops-return-values

**Comment by andreisocaciu** [comment]
What do you mean? My code is exactly like the one from the [docs](https://swr.vercel.app/docs/with-nextjs#complex-keys) for complex keys.

Console logging the `fallback` prop received from the `getStaticProps` function shows this:

```ts
{
  "@\"/book/business\",\"BusinessName\",": { 
    "dataFromServer": "here" 
  }
}
```

And the website works most of the time, with my useSWR hook having the fallback data available to them, and the SSR delivering the correct page with the server data already loaded. So it can't be that I'm using this feature wrong.

**Comment by promer94** [comment]
This is your example.
```tsx
export const getStaticProps: GetStaticProps<
  { fallback: Record<string, any> },
  { business: string }
> = async (context) => {
  // fetch data here
  return {
    fallback: {
        [unstable_serialize(['/book/business', context.params.business])]: business,
    }
  }
}
```

But according to nextjs docs, you should write

```tsx
export const getStaticProps: GetStaticProps<
  { fallback: Record<string, any> },
  { business: string }
> = async (context) => {
  // fetch data here
  return {
    props: {
      fallback: {
        [unstable_serialize(['/book/business', context.params.business])]: business,
    }
  }
}
```
