### ISSUE TITLE
mutate('/api/login') why won't revalidate

### ISSUE THREAD

**Issue by qiaogaolong** [vercel/swr#2697]
swr ： 2.2.0

**Comment by qiaogaolong** [comment]
I want to implement the function of global interface re-authentication, import { mutate } from 'swr' , mutate('/api/login') does not take effect

**Comment by promer94** [comment]
This is expected behavior.

https://swr.vercel.app/docs/mutation#global-mutate
> Using global mutator only with the key parameter will not update the cache or trigger revalidation unless there is a mounted SWR hook using the same key.

you need to provider a fetcher for `mutate`

```tsx
mutate('/api/login', fetcher)
```
