### ISSUE TITLE
Mock useSWR hook for test cases

### ISSUE THREAD

**Issue by SyedSibtainRazvi** [vercel/swr#2704]
### Discussed in https://github.com/vercel/swr/discussions/2703

<div type='discussions-op-text'>

<sup>Originally posted by **SyedSibtainRazvi** July  4, 2023</sup>
I wanted to discuss a challenge I'm facing while writing test cases for my application that uses the useSWR hook. In my development process, I've successfully implemented useSWR to fetch and manage data from an API, and it's working as expected.

However, when it comes to testing the components that use the useSWR hook, I'm running into an issue. Since test cases should be isolated and not make actual API calls, I need a way to mock the behavior of the useSWR hook and provide predetermined data for testing purposes.

I've explored using Jest for testing, and I'm aware of the mocking capabilities it provides. However, I'm uncertain about the best approach to mock the useSWR hook effectively within my test cases.

I'd greatly appreciate any insights, suggestions, or examples from those of you who have experience with testing React components that use useSWR or have encountered similar challenges in mocking hooks with Jest.</div>

**Comment by devjiwonchoi** [comment]
I'd start from using the test cases that the `swr` project uses, located [here](https://github.com/vercel/swr/tree/main/test).
Have you taken a look on them?

**Comment by promer94** [comment]
You could use library like https://mswjs.io/ to mock the api call.
