### ISSUE TITLE
useSWRMutation no longer accepts throwOnError as a parameter

### ISSUE THREAD

**Issue by szalayak** [vercel/swr#2710]
# Bug report

According to this PR (https://github.com/vercel/swr/pull/2604), the default behaviour of useSWRMutation was changed to return a trigger that returns a Promise<Data> instead of Promise<Data|undefined> by default. The PR advises that the old behaviour can be achieved if throwOnError = false is explicitly provided. This parameter however has been removed from SWRMutationConfiguration, so it can't be passed in.

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

I now can't get SWR to return Promise<Data | undefined>, where I don't have it wrapped in a try ... catch block and rely only on the "error" returned by the hook instead.

## Expected Behavior

How did you expect SWR to behave here?

I'd like an optional parameter so I can still use the mutation in a way that is doesn't throw an error and it only updates the error variable returned by the hook.

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version.

**Comment by promer94** [comment]
#2604 did not change any runtime behaviour and you can always pass `throwOnError` as option.

**Comment by szalayak** [comment]
Not if you're using typescript, the type had the parameter removed from it - please restore
