### ISSUE TITLE
Expose more custom config

### ISSUE THREAD

**Issue by cncolder** [vercel/swr#274]
This's a feature request.

Currently swr config depend on `document` `navigator` and `Map` cache.

I think we can make config configurable. User provide custom `isDocumentVisible` and `isOnline` functions. Even a custom cache to dump data into localStorage(or another storages). Or a cache with expires e.g. isaacs/node-lru-cache

Put these configuration in React context `SWRConfig` is not a good idea. Provide a new api `setSWRConfig`?

**Comment by huozhi** [comment]
Now swr can support those customizations already!
