### ISSUE TITLE
SWR Cache on Error Response

### ISSUE THREAD

**Issue by geogeorgiou** [vercel/swr#2740]
# Bug report

## Description / Observed Behavior

When fetching first time using SWR let's say on a route then let's say an error occurs and it's being cached.

## Expected Behavior

Given the example repo steps following below I'm expecting that SWR should fetch a new when visiting the route again with the following configuration.

## Repro Steps / Code Example

I'm sharing a simple [Github Repo here](https://github.com/geogeorgiou/swr-cache). It has 2 routes a home page and the data page which fetches some data. Now maliciously I place a wrong url on the data page for it to fail which is normal.

Now imagine this lets say that this route fetches from the backend some actual data that get broken for a while then they become stable again if this caching occurs we can never get new data without doing a full browser refresh. 💥 💥 💥 

- Why doesn't SWR retry to fetch new data with a configuration as follows when revisiting the page a 2nd time?
- Do we need to always change the `cacheKey` for this to be applicable or `SWRConfig` ? 

I'm thinking that revalidateOnMount (since we're changing pages should be more than enough) any thoughts on this.

The following code is placed under Data page 

 ```
const { data } = useSWR(`/brewery`, dataApi.getBrewery, {
    revalidateOnFocus: false,
    revalidateOnReconnect: false,
    refreshWhenOffline: false,
    shouldRetryOnError: false,
    suspense: true,
    revalidateOnMount: true,
  });
```

Core libraries used for repro:

- SWR version: 2.1.5
- React Version: 18.2.0
- axios: 1.4.0
- sentry/react: 7.52.1

Thanks for your time ! 😀

**Comment by promer94** [comment]
If you are using suspense, you need to implement error retry by yourself.
You could find a example here https://github.com/vercel/swr/tree/main/examples/suspense-retry

**Comment by geogeorgiou** [comment]
The issue remains even if for example we change the configuration from `suspense: true` to `suspense: false` + adding the loader state since we no longer would have the suspended functionality.
So in both scenarios of `suspense` or `no suspense` we should do manual error re-try ? Is that how it's supposed to work ?

**Comment by promer94** [comment]
Oh i misunderstood this problem. You are right. This should be improved. 

duplicate of #2543
