### ISSUE TITLE
Mutate typescript

### ISSUE THREAD

**Issue by eposha** [vercel/swr#2744]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

## Expected Behavior

How did you expect SWR to behave here?

## Repro Steps / Code Example

<img width="358" alt="image" src="https://github.com/vercel/swr/assets/54452472/af9711a0-82cf-4839-9464-827ea2b0899b">

<img width="330" alt="image" src="https://github.com/vercel/swr/assets/54452472/08c94342-f0fb-4f40-89c3-7342095377ef">

<img width="282" alt="image" src="https://github.com/vercel/swr/assets/54452472/f9d9eb09-cf3e-406f-be2c-6ce6109a2fcb">

<img width="362" alt="image" src="https://github.com/vercel/swr/assets/54452472/e7e8cdce-7d8d-434f-82c6-7e383344c393">

## Additional Context

SWR version. 
2.2.1

The 2.2.0 version works fine for me

**Comment by driaug** [comment]
Just noticed I am now also experiencing this bug! 
No changes to version, dev environment etc.

**Comment by Marco-Daniel** [comment]
I'm running into the same issue, it appears as if the generic for the datatype isn't passed down from the hook into the mutate

**Comment by satoren** [comment]
Since https://github.com/vercel/swr/pull/2708
