### ISSUE TITLE
Trigger typing breaks typescript inference because of missing export

### ISSUE THREAD

**Issue by ckruppe** [vercel/swr#2755]
# Bug report

## Description / Observed Behavior

Since Version 2.2.0 the new typing of the trigger function of useSwrMutation breaks type inference if its used in an own NPM module.

Exported variable 'useMutateApi' has or is using name 'TriggerWithArgs' from external module "C:/projekte/Intern/Libraries/nfq-typed-next-api/node_modules/.pnpm/swr@2.2.1_react@18.2.0/node_modules/swr/mutation/dist/index" but cannot be named.ts(4023)
---
Exported variable 'useMutateApi' has or is using name 'TriggerWithOptionsArgs' from external module "C:/projekte/Intern/Libraries/nfq-typed-next-api/node_modules/.pnpm/swr@2.2.1_react@18.2.0/node_modules/swr/mutation/dist/index" but cannot be named.ts(4023)
---
Exported variable 'useMutateApi' has or is using name 'TriggerWithoutArgs' from external module "C:/projekte/Intern/Libraries/nfq-typed-next-api/node_modules/.pnpm/swr@2.2.1_react@18.2.0/node_modules/swr/mutation/dist/index" but cannot be named.ts(4023)

## Expected Behavior

It would help to at least export these types so typescript can use them on compile time to include them in its own generated *.d.ts file.

## Repro Steps / Code Example

```typescript
/**
 * Get request hook.
 *
 * @param url        API URL.
 * @param swrOptions SWR options.
 * @returns SWR response.
 */
export const useMutateApi = <T extends ApiMethod>(
    url: string | null,
    swrOptions?: SWRMutationConfiguration<Jsonify<ApiResponse<T>['data']>, any> | undefined
) => {
    const {
        data,
        error,
        isMutating,
        reset,
        trigger
    } = useSwrMutation<Jsonify<ApiResponse<T>['data']>, RequestError<T>, Key, MutationRequestOptions<T>>(
        url ? `${basePath}${url}` : null,
        mutationFetcher,
        swrOptions
    );

    return {
        data,
        error,
        isMutating,
        reset,
        trigger
    };
};
```

## Additional Context

SWR version. 
Since Version 2.2.0

**Comment by monolithed** [comment]
<img width="1016" alt="Screenshot 2023-08-27 at 03 32 31" src="https://github.com/vercel/swr/assets/803674/23306163-e7c6-469f-a775-5a238fee8aec">

**Comment by der-daniel** [comment]
when will this fix be live?
