### ISSUE TITLE
mutate ,but isLoading not change

### ISSUE THREAD

**Issue by vaynevayne** [vercel/swr#2762]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

## Expected Behavior

How did you expect SWR to behave here?

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version. 

<img width="946" alt="image" src="https://github.com/vercel/swr/assets/124666577/2d346d7f-6a27-4281-a75c-3a587489eb79">

<img width="390" alt="image" src="https://github.com/vercel/swr/assets/124666577/389d3229-22eb-47f9-bef7-d5441d23ccb1">

**Comment by leonardlib** [comment]
Was there a solution for this @vaynevayne?
