### ISSUE TITLE
Mutation errors are local and cannot be shared to other SWR hooks

### ISSUE THREAD

**Issue by IlyaGershman** [vercel/swr#2765]
# Bug report
Mutation errors are local and cannot be shared with other SWR hooks

## Description / Observed Behavior
I have a case where I would like every component that uses a key to be updated with an unsuccessful mutation result.
For example, I have a modal window that has a form. When filling form values I want the update request to be sent and the modal to be closed. Other page components should indicate to the user, that the operation was unsuccessful.

## Expected Behavior
I want mutation results to be shared between other SWR hooks with the same key

## Repro Steps / Code Example
https://codesandbox.io/p/sandbox/goofy-feather-g69xrg

## Additional Context
I understand that I can work around this issue with the use of some other global state solution, but I think SWR should allow for such a pretty common use case

SWR version. (2+)

**Comment by promer94** [comment]
It is currently by design.
