### ISSUE TITLE
StrictMode: data is not re-fetched on second render after cancellation-on-unmount 

### ISSUE THREAD

**Issue by skyboyer** [vercel/swr#2766]
# Bug report

## Description / Observed Behavior

In short: with `<StrictMode>` re-mounting component, `useSWR` does not fetch data on the second render. If we have cleanup in `useEffect(() => ..., []` which cancels active request, we will never get the data - first request is cancelled, second request is never sent.

## Expected Behavior

As when using `useEffect` directly I expect to see:

```
fetching
aborting
fetching
```

and finally to get the data from the `useSWR`+fetcher callback

## Repro Steps / Code Example

```
import { useEffect, useState } from "react";
import useSWR from "swr";

function useCustomSWR() {
  console.log("hook is called");

  useSWR(
    "does-not-matter",
    () => {
      console.log("fetching");
      return new Promise(() => {}); // am not sure if return value from `fetcher` callback matters but let it be the pending Promise()
    },
    {
      revalidateOnMount: true
    }
  );

  useEffect(() => {
    return () => {
      console.log("aborting");
    };
  }, []);
}

export default function App() {
  useCustomSWR();

  useEffect(() => {
    console.log("normal useEffect");

    return () => {
      console.log("normal useEffect cleanup");
    };
  }, []);

  return null;
}
```

When wrapped into `<StrictMode>` it prints:

```
fetching 
normal useEffect 
aborting 
normal useEffect cleanup 
normal useEffect 
```

side `useEffect` here just to demonstrate why 

Sandbox: https://codesandbox.io/s/epic-chihiro-nq86yr

## Additional Context

SWR 2.1.1
React 18.2.0

This [raised on SO](https://stackoverflow.com/questions/77021339/reactstrictmode-useswr-with-axios-abortcontroller-makes-my-request-canceled), I'm not the one who asked but I find current behavior confusing.

This may be related to #2082

**Comment by skyboyer** [comment]
or do I completely miss something important and it's expected?

**Comment by promer94** [comment]
> if we have cleanup in useEffect(() => ..., [] which cancels active request

I don't understand the purpose of doing this. 

I will close this for now. Feel free to reopen this if you have more practical use case for this problem.

**Comment by batgos** [comment]
I think that I'm getting the same problem. 
I created a wrapper for useSWR hook to handle abortion on request when my component gets unmounted. When I'm using my custom hook with the ReactStrictMode on, it just directly cancels my request and does not re-fetch it again.

But I'm not sure that's the correct behavior... Maybe to not make the request get canceled and the app to fetch two times would be the best?

Here is a short example of my custom hook :
```
const useRequest = (request: AxiosRequestConfig | null): RequestType => {
  const abort_controller = new AbortController();

  const fetcher = async (
    requestFetcher: AxiosRequestConfig | null
  ): Promise<unknown> => {
    return await axios({
      ...requestFetcher,
      signal: abort_controller.signal,
    })
      .then((response) => {
        return response;
      });
  };

  const {
    data: dataSWR,
    isLoading,
    error
  } = useSWR(
    request && request.method === 'get' ? request.url : null,
    () => fetcher(request),
    {
      revalidateOnFocus: false,
      shouldRetryOnError: false,
    }
  );



  useEffect(() => {
    return () => {
      if (request !== null) {
        abort_controller.abort();
      }
    };
  }, []);

  return {
    loading: isLoading,
    status: dataSWR ? dataSWR?.status : 0,
    headers: dataSWR ? dataSWR?.headers : null,
    data: dataSWR ? dataSWR?.data.result : null,
    error: error,
  };
};
```

**Comment by vaynevayne** [comment]
@promer94  hi, i meet same issue , please reopen it   https://github.com/vercel/swr/issues/2837
