### ISSUE TITLE
Troublesome generics in useSWR (error is `any` by default and specified `Error` breaks automatic infer)

### ISSUE THREAD

**Issue by ludwighogstrom** [vercel/swr#2778]
# Bug report

## Description / Observed Behavior

The default typing of `error` in `useSWR` is `any`.

## Expected Behavior

Isn't it better to type it as `unknown`? 

Then the ESLint error `typescript-eslint/no-unsafe-assignment` could be avoided. If typed like `unknown` it also follow how TypeScript automatically types an error in a try/catch.

## Repro Steps / Code Example

Code example when the `error` type is `any` and ESLint complains with `typescript-eslint/no-unsafe-assignment`
<img width="605" alt="Skärmavbild 2023-09-07 kl  19 00 15" src="https://github.com/vercel/swr/assets/3797543/11925bed-e402-4318-9a22-d5fa8a3923e0">

### Bonus (this should maybe be a separate report?) 
When specifying types for `Data` and `Error` the fetcher function argument (`url`) get typed as `any`. When not specified, the correct type of key/url is inferred by TypeScript as expected (`string`).
<img width="665" alt="Skärmavbild 2023-09-07 kl  19 08 29" src="https://github.com/vercel/swr/assets/3797543/0bf63e90-31da-40d3-8371-3afd9fd60a73">

## Additional Context

SWR version 2.2.2

**Comment by promer94** [comment]
> When specifying types for Data and Error the fetcher function argument (url) get typed as any.

This is expected. Since typescript currently does not support partial generic inference.


> Isn't it better to type it as unknown?
Yes, you are right. We will update the `error` type to unknown in next major. 
Now we have to keep it for compatibility.

**Comment by ludwighogstrom** [comment]
> > When specifying types for Data and Error the fetcher function argument (url) get typed as any.
> 
> This is expected. Since typescript currently does not support partial generic inference.
> 
> > Isn't it better to type it as unknown?
> 
> Yes, you are right. We will update the `error` type to unknown in next major. Now we have to keep it for compatibility.

Thank! Ok, I understand! 

Is it possible to give a ballpark estimate when the next major version is out?

**Comment by monarchwadia** [comment]
Thank you for all of the great work on SWR!

Wanted to say, this is still an issue. Unfortunately, since `error` is typed as `any`, I am forced to write very ugly code. I am unwilling to get rid of `typescript-eslint/no-unsafe-assignment` just for SWR.

![Image](https://github.com/user-attachments/assets/e2f22a1e-cfdc-4e98-b168-d26e07ab18fc)
