### ISSUE TITLE
Composite/multiple arguments key creates more cache

### ISSUE THREAD

**Issue by 3pleFly** [vercel/swr#2779]
Hi yall, I have been battling composite key for a bit and will appreciate your input whether or not this is a bug.

SWR continues to create more and more cache entries instead of overwriting the same cache key

Here is an example:
https://codesandbox.io/s/swr-basic-forked-n53wnc?file=/src/App.js

I am trying to replicate an issue where I have some query params which change and according to the documentation this is the perfect example where I can send parameters through the key to the fetcher function.

But alas more cache is being created every time the query params change. It seems to be suggested that doing : useSWR([API.ENDPOINT, params], fetcher) , would generate a cache entry of API.ENDPOINT, but instead its API.ENDPOINT + params. 
like so -
cache : {
"@API.ENDPOINT","PARAMS": Object  (object is the data)
}

Not sure how to send params to the fetcher otherwise.

**Comment by promer94** [comment]
This is by design. The whole `key` arguments will be serialized and used as cache key.
