### ISSUE TITLE
use-sync-external-store-shim.development.js has error after pnpm watch run

### ISSUE THREAD

**Issue by thetnaingtn** [vercel/swr#2790]
# Bug report

## Description / Observed Behavior
I can't watch the swr library by running `pnpm watch` as the `CONTRIBUTION.md` suggest and I got `use-sync-external-store-shim.development.js` have ` Unexpected token (1:3)`.
What kind of issues did you encounter with SWR?
I try to run swr locally as the `CONTRIBUTION.md` suggest by running `pnpm install` and `pnpm watch` but I got this error.
<img width="1512" alt="Screenshot 2566-09-16 at 01 01 15" src="https://github.com/vercel/swr/assets/28681575/87343d1f-f982-49e1-a27f-4c030daba2bf">

## Expected Behavior

How did you expect SWR to behave here?

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version. 
2.2.2

**Comment by huozhi** [comment]
Hi this looks like a bug on [bunchee](https://github.com/huozhi/bunchee), I'll transfer the issue to that repo. For swr you can still use `pnpm builld` to update the changes for now
