### ISSUE TITLE
Error: (0 , swr__WEBPACK_IMPORTED_MODULE_1__.default) is not a function

### ISSUE THREAD

**Issue by Victor716** [vercel/swr#2792]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

This is the error I got when using swr
<img width="933" alt="image" src="https://github.com/vercel/swr/assets/25873924/3fd38b77-25ae-4179-a384-51ef988b4f2f">
## Expected Behavior

How did you expect SWR to behave here?

## Repro Steps / Code Example
```
 npm i swr

import useSWR from "swr"
```

## Additional Context
<img width="446" alt="image" src="https://github.com/vercel/swr/assets/25873924/c75278bf-850e-4610-bce3-eab57d5ff138">

**Comment by yoansj** [comment]
Having the same issue right now, found this that should help you however https://github.com/vercel/swr/issues/2694

**Comment by koba04** [comment]
From your error log, this is the same as #2694.

**Comment by MinSomai** [comment]
it is expected.

In Next.js App Router, all components are React Server Components (RSC) by default. You could only import the key serialization APIs from SWR in RSC.

https://swr.vercel.app/docs/with-nextjs#rsc
