### ISSUE TITLE
mutate modify data problem

### ISSUE THREAD

**Issue by qiaogaolong** [vercel/swr#2798]
const { data } = useSWR('/api/user', fetcher)
When I modify data.a = 1, without calling mutate, I request /api/user again, and data.a is also 1.Unless you refresh the page

If you use cloneDeep(data) there will be no problem

**Comment by koba04** [comment]
We don't support modifying `data` directly. If you want to update `data`, you have to call `mutate`.
https://swr.vercel.app/docs/mutation

**Comment by qiaogaolong** [comment]
Yes, but after I directly modify the data and then use mutate(data), the data heap does not change. Then after re-requesting the interface, the data is still modified, not what the interface returns. I don’t know what I said, Is it clear

**Comment by qiaogaolong** [comment]
@koba04 Unless you refresh the page
