### ISSUE TITLE
useSWRInfinite and  mutate

### ISSUE THREAD

**Issue by qiaogaolong** [vercel/swr#2807]
Why is it re-validated when using mutate of useSWRInfinite to change the cache? 
For example mutate(chunk(val, 10), {
          populateCache: true,
          revalidate: false,
        })

**Comment by qiaogaolong** [comment]
example：https://codesandbox.io/s/swr-infinite-forked-g9h4fy?file=/src/App.js:1800-1810

When I click Revise and then modify the first data, and then click load more, I have set `revalidate: false,` and find that the data on the first page will still be requested, and then the value I set will be overwritten. Of course, there is no problem if you use useSwr.

**Comment by qiaogaolong** [comment]
@shuding @promer94 Please help me take a look, thank you

**Comment by koba04** [comment]
This is caused by an inconsistency between the page cache and the infinite cache.
In this example, `title` in the infinite cache is updated, but `title` in the page cache is not. This causes a revalidation.

**Comment by qiaogaolong** [comment]
Yes, I also discovered it, but how to solve it? I am bound to mutate. Please improve it in the example. Thank you.

**Comment by koba04** [comment]
Unfortunately, there is no way to mutate infinite data without revalidations. But I think we should have a way to do it, so I'll consider it. Thank you!

**Comment by qiaogaolong** [comment]
@koba04 Page caching and unlimited caching, I have temporarily implemented it using key values, and I look forward to the encapsulation being completed. Currently I want to know useSWR
Can the returned data data be returned as deep copy data? Because when I implement custom modification of data, directly data.a = 1, then the original data will be changed when mutate is not used. After re-requesting, it will still be a =1

**Comment by agustinb-dev** [comment]
> Unfortunately, there is no way to mutate infinite data without revalidations. But I think we should have a way to do it, so I'll consider it. Thank you!


I managed to mutate without revalidation like this.

```typescript
// useSWRInfinite returns an array of pages so I look for the page index that has the element I want to update
const pageIndex = isArrayTransactionArray(data) ? data.findIndex((subArray) => {
      return subArray.some((t) => t.id === updatedTransaction.id);
    }) : -1;
// then I used mutate directly imported from swr ( import { mutate as swrMutate } from 'swr'; ) to manipulate the cached data
void swrMutate([`transactions${pageIndex}`, pageIndex+1], async (cachedData) => {
  const index = cachedData.findIndex((t: Transaction) => t.id === updatedTransaction.id);
  if (index !== -1) {
    cachedData[index] = updatedTransaction;
  }
return
});
```

**Comment by webdeb** [comment]
> ```ts
> void swrMutate([`transactions${pageIndex}`, pageIndex+1]
> ```

Could you please describe the key format you are using?

**Comment by webdeb** [comment]
Oh, it actually works with `unstable_serialize` pretty neat.

```
                const { trigger, isMutating } = useSWRMutation(unstable_serialize(getPizzaScrollKey), updatePizza)
               ...
                await trigger({ name, pid: pizza.id }, {
                  revalidate: false,
                  optimisticData: (data) => {
                    return data.map(subArray => subArray.map(p => {
                      if (p === pizza) return {...p, name}
                      return p
                    }))
                  }
                })

```

**Comment by stylehuan** [comment]
> Unfortunately, there is no way to mutate infinite data without revalidations. But I think we should have a way to do it, so I'll consider it. Thank you!

I have the same problem, please ask how to deal with it
