### ISSUE TITLE
Errors when fetcher is a class method

### ISSUE THREAD

**Issue by penx** [vercel/swr#2818]
# Bug report

## Description / Observed Behavior

When the fetcher passed to useSWR is a class method, the function is invoked independently of the class (with apply) so loses access to instance variables/this.

## Expected Behavior

A class method should be a valid option to pass as the fetcher.

## Repro Steps / Code Example

https://codesandbox.io/p/sandbox/swr-bug-repro-fsvpss

```tsx
class API {
  constructor(apiUrl) {
    this.apiUrl = apiUrl;
  }
  async fetch([key, id]) {
    return this.apiUrl;
  }
}
const api = new API("foo");

function App() {
  const id = 0;
  const res = useSWR(["item", id], api.fetch);
```

This will error with

> undefined is not an object (evaluating 'this.apiUrl')

## Additional Context

I think I have a workaround that works for me, but raising as I think this may need fixing regardless.

SWR version: 2.2.4

I would like to wrap an existing library that uses a class. I understand I can define a new function for every underlying class function:

```tsx
useSWR(
    ["item", id],
    useCallback(([_, id]) => api.getItem(id), [api]),
  );
```

...but this would be time consuming and cumbersome. I think I will need to map between the key (`["item", id]`) and the function argument(s) (just `id`) anyway so will likely have to go with this approach regardless.

Side note, does the useCallback do anything here, or can I define a new function for the fetcher on every call to useSWR?

**Comment by phaux** [comment]
There is no way to "fix" this on the swr side because that's how javascript works.

You can also define your method like this as a workaround:

```js
class API {
  constructor(apiUrl) {
    this.apiUrl = apiUrl;
  }
  fetch = async ([key, id]) => {
    return this.apiUrl;
  }
}

```

**Comment by penx** [comment]
@promer94 is there a reason this was closed?

**Comment by promer94** [comment]
> There is no way to "fix" this on the swr side because that's how javascript works.

**Comment by penx** [comment]
Apologies, I thought you were doing something internally with .apply, but @phaux was right above (you need to bind class methods when passing them as arguments). Thanks!
