### ISSUE TITLE
useSWR()  will not fetch when set `fallbackData` and `revalidateIfStale: false`

### ISSUE THREAD

**Issue by gonlyk** [vercel/swr#2823]
# Bug report

## Description / Observed Behavior

useSWR()  will not fetch when set `fallbackData` and `revalidateIfStale: false`

## Expected Behavior

useSWR should always fetch

## Repro Steps / Code Example

```js
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";

import useSWR from "swr";
import "./styles.css";

function api() {
  return new Promise((r) => {
    setTimeout(() => {
      r("init config");
    }, 1000);
  });
}

async function fetcher() {
  console.log("start fetch"); // not run
  return await api();
}

function App() {
  const { data } = useSWR("key", fetcher, {
    fallbackData: "waiting",
    revalidateIfStale: false,
  });
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>fetch result from api: '{data}'</h2>
    </div>
  );
}

const rootElement = document.getElementById("root");
const root = createRoot(rootElement);

root.render(
  <StrictMode>
    <App />
  </StrictMode>,
);

```

## Additional Context

SWR version. 
"swr": "^2.2.4"

**Comment by koba04** [comment]
I think that's an expected behavior. If you want to fetch data with `fallbackData`, `revalidateIfStale` should be `true`.

**Comment by marmotgary** [comment]
Could it be more clearly documented, that the fallbackData is also treated as cached data? It feels slightly unintuitive that the first fetch is not being done, if using both fallbackData and revalidateIfStale: false.
