### ISSUE TITLE
[TS Error] Did you forget to use 'await'?

### ISSUE THREAD

**Issue by vaynevayne** [vercel/swr#2828]
Doesn't match the document. https://swr.vercel.app/docs/typescript#generics. 

```jsx
  useSWR(
    ['/accidents/consult'],
    ([url]) => axios<{ code: number; data: any; message: string }>(url),
    {
      onSuccess(data, key, config) {
        console.log('事故data', data)
        if (data?.message) {
          message.current = data?.message
        }
      },
    }
  )
```

<img width="950" alt="image" src="https://github.com/vercel/swr/assets/124666577/056929ac-5d05-4578-ac72-d0594571fb05">

**Comment by vaynevayne** [comment]
```jsx
 useSWR(
    ['/accidents/consult'],
    ([url]) => axios<{ code: number; data: any; message: string }>(url),
    {
      onSuccess: async (data, key, config) => {
        const { message, code } = await data
        if (message) {
          content.current = message
          open()
        }
      },
    }
  )
```
You need to add an await here, but it's actually possible to do it without, because the return is not a promise, and I suspect it's a problem with swr.

**Comment by devjiwonchoi** [comment]
Your `fetcher` is returning `Promise`.

This is why there's `.then` on the example.

`const fetcher = url => axios.get(url).then(res => res.data)`

In your case, this will work:

```ts
useSWR(
  ['/accidents/consult'],
  ([url]) =>
    axios<{ code: number; data: any; message: string }>(url).then(
      (res) => res.data
    ),
  {
    onSuccess(data, key, config) {
      console.log('事故data', data)
      if (data?.message) {
        message.current = data?.message
      }
    },
  }
)
```

**Comment by koba04** [comment]
We have the [Data Fetching](https://swr.vercel.app/docs/data-fetching#axios) documentation with `axios`, which is exactly the same as @devjiwonchoi's suggestion.
