### ISSUE TITLE
Wrong key serialization

### ISSUE THREAD

**Issue by standbyoneself** [vercel/swr#2844]
# Bug report

There is no way retrieve data from cache by key if it is an array not string.

## Expected Behavior

I want to write the decorator that would be reset cache on component unmount. I need to call cache.delete(), but keys are surely different. Why?

## Repro Steps / Code Example

https://codesandbox.io/p/sandbox/loving-maxwell-52tqpv?file=%2Fsrc%2FApp.js%3A9%2C23

1) Reload the sandbox. Open the console. There would be undefined as cache.get() because there were no data before.
2) Type "World" in `<p>`. You'll able to see that data was retrieved only for string key. For array key there would be undefined.

## Additional Context

SWR version. 2.2.4

**Comment by DimaTkachev** [comment]
i have this problem too

**Comment by promer94** [comment]
https://swr.vercel.app/docs/with-nextjs#complex-keys

**Comment by gregbrowndev** [comment]
Just to add - I had this exact same problem too, and was left trying to guess how the key should be serialised. But @promer94's solution works. It would be good if the key in`fallback` had the same type as `key` so serialisation is handled for you.

**Comment by standbyoneself** [comment]
Why did you close the issue? And why are you proposing me for using unstable API?

**Comment by standbyoneself** [comment]
Also don't you want to move this doc into "Arguments" section?
