### ISSUE TITLE
The `onLoadingSlow` and `onSuccess` callback miss unmount check

### ISSUE THREAD

**Issue by thoamsy** [vercel/swr#286]
```js
 setTimeout(() => {
   if (loading) config.onLoadingSlow(key, config)
}, config.loadingTimeout)
```

```js
// trigger the success event,
// only do this for the original request.
config.onSuccess(newData, key, config)
```
The two callback should also be checked if `unmountRef` is true, or we will see the:
> Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.

**Comment by shuding** [comment]
Should be fixed in #433
