### ISSUE TITLE
useSWR not making the fetch request

### ISSUE THREAD

**Issue by gustavotrapp** [vercel/swr#2867]
# Bug report

## Description / Observed Behavior

I working in this NextJS project that uses useSWR. The page just isn't making the fetch request, which I find odd. This behavior also started happening after I deleted my .next file, before that it was working correctly

## Expected Behavior

I expected my useSWR hooks to function the way they should

## Repro Steps / Code Example

```ts
const fetcher = async <T>(
	input: RequestInfo | URL,
	init?: RequestInit | undefined
): Promise<T> => {
	const { APP_HOST } = useContext(EnvProviderContext);
	const resp = await fetch(`${APP_HOST}${input}`, init);
	if (resp.status >= 200 && resp.status < 300) {
		const jsonResponse = await resp.json();

		if (!isAmbisisResponseType(jsonResponse))
			throw new Error(`ERROR: Invalid ambisis response: ${jsonResponse}`);

		const { data } = jsonResponse;
		if (typeof data !== "string")
			throw new Error(`ERROR: Invalid ambisis response: ${jsonResponse}`);

		const parsedData = JSON.parse(data);

		return parsedData;
	}
	if (resp.status === 500) {
		throw new Error(await resp.text());
	}
	throw new Error(await resp.json());
};

export const useAPI = <T, E>(route: string, fetchOptions?: RequestInit) =>
	useSWRHook<T, E>(route, (args: string) => fetcher<T>(args, fetchOptions));
```

## Additional Context

SWR version ^2.2.4. 
If you need anything extra like config files, etc please say so I will reply with whatever you need, althought keep in mind that I can't share the whole project with you guys

**Comment by oskarssylwan** [comment]
Did you find a solution to this, I seem to be having a similar problem
