### ISSUE TITLE
useSWRInfinite continually fetches the first page (no caching observed)

### ISSUE THREAD

**Issue by bworline** [vercel/swr#2878]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

`useSWRInfinite` either doesn't appear to cache the first page, or it is not using the cache for the first page.

## Expected Behavior

How did you expect SWR to behave here?

The fetcher should only be called once for each unique key.

## Repro Steps / Code Example

Go to https://swr.vercel.app/examples/infinite-loading, add logging by changing the fetcher code to look like this:

```
const fetcher = (url) => { 
  console.log(`fetching ${url}`);
  return fetch(url).then((res) => res.json()); 
};
```
 
Hit the 'load more' five times.  Note that the console shows a load of page 1 over and over.

![image](https://github.com/vercel/swr/assets/35072931/6e48b3b4-33a2-48eb-bd28-dc0750d161bb)

## Additional Context

SWR version: 2.2.4 (latest)

**Comment by fhyfhyfhy** [comment]
`useSWRInfinite(getKey, fetcher, { revalidateFirstPage: false })`
https://swr.vercel.app/zh-CN/docs/pagination#parameters

**Comment by bworline** [comment]
Thanks, @fhyfhyfhy.  That solved the issue.

I have to say though, that is an odd choice for default behavior.  [The Power Of Defaults](https://medium.com/@tanayj/the-power-of-defaults-976bc8b015b7)

**Comment by koba04** [comment]
Closed via https://github.com/vercel/swr/issues/2878#issuecomment-1905609385. Thank you @fhyfhyfhy!
