### ISSUE TITLE
Got "None of the selected packages has a "watch" script" when pnpm watch run

### ISSUE THREAD

**Issue by thetnaingtn** [vercel/swr#2883]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?
I try to run swr locally as per CONTRIBUTION.md say. I got None of the selected packages has a "watch" script message when I run `pnpm watch`.

## Expected Behavior

How did you expect SWR to behave here?

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context
Can run `pnpm watch` on this commit hash 1d8110900d1aee3747199bfb377b149b7ff6848e

SWR version. 
<img width="1495" alt="Screenshot 2024-01-25 at 7 52 16 PM" src="https://github.com/vercel/swr/assets/28681575/17c32868-8e2e-4bfc-a1c9-151896188722">

**Comment by promer94** [comment]
The `watch` script should be updated to `bunchee -w`

**Comment by restartgr** [comment]
Can i try to fix this problem?
