### ISSUE TITLE
revalidate() on usePagesSWR does not work

### ISSUE THREAD

**Issue by Arman92** [vercel/swr#289]
I double-checked, I can not revalidate the SWRs when using useSWRPages().

Steps to reproduce are a bit long but I can provide a non-working example if needed.

**Comment by Ashot-KR** [comment]
Object returned from `useSWRPages` has `pageSWRs` property which contains all triggered SWRs.
You can use it to revalidate.
```js
const {
    pageSWRs
  } = useSWRPages(…)

pageSWRs.forEach((swr) => swr.revalidate())
```

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!
