### ISSUE TITLE
Revalidation does not run on key change when I use initialData

### ISSUE THREAD

**Issue by pawelphilipczyk** [vercel/swr#304]
I've got SSR rendered next.js app and I'm trying to understand why does this case not work. 

On server side I'm getting some data with `getInitialProps` and it goes into `initialData` inside my component's `useSWR` hook and it all works perfectly fine until this point. The key looks exactly like in examples and it's basically `/product/${id}`. 

**Problem:** when the key changes there is no triggered rerun of the hook. 

I've tried multiple things including different keys (array and strings) and I've added multiple `useEffect` just to make sure it's actually changing. 

If I just removed `initialData` in the same setup then it works perfectly fine. It also revalidated on window focus if I left the default config for that. 

Is this a bug or I'm missing some intentional behaviour?

**Comment by sergiodxa** [comment]
This issue is similar to https://github.com/zeit/swr/issues/284

**Comment by pawelphilipczyk** [comment]
You're right and I agree with the comment there. My initial data is strictly related to the key I'm passing in at the first run of the hook. When this key changes we cannot assume this initialData is still ok to be used. 

To put this in other words I think it is not possible to use it with SSR the way it's described in examples and make it work unless I'm missing something.

**Comment by pawelphilipczyk** [comment]
There's one more strange thing I've found out. I've tried using react-async and react-query and I'm getting the same effect everywhere. 

This makes me thing either I'm doing something wrong or I should just give up on solving this :D

**Comment by huozhi** [comment]
@pawelphilipczyk could you try the solution posted in #284 (comment) ?
Will close this issue as it seems to be reoslved with swr@beta, feel free to comment or reopen if you have any further issues
