### ISSUE TITLE
React 19 Not Supported

### ISSUE THREAD

**Issue by timothyerwin** [vercel/swr#3051]
Time to release another update to npm

**Comment by jpbnetley** [comment]
I think the SWR team are still making some upgrades and doing testing.
I did see they updated the peer dependencies: https://github.com/vercel/swr/pull/3047

**Comment by icyJoseph** [comment]
@Homanism it'll come in the next release, 2.6.x something ~ you can see that the package.json of this repository has the correct peer dependencies already

**Comment by dgtllion** [comment]
@icyJoseph When do you plan to publish it?

**Comment by Homanism** [comment]
@icyJoseph Do you think we can expect @v2.2.6 to be released this week?

**Comment by tintinthedev** [comment]
Why not pushing the current `main` version (which already has React 19 as a peer) to NPM? This issue is 2 weeks old now...

**Comment by brunomaffei** [comment]
Can anyone tell me if I use legacy-peer-deps can it break and not work on react19?

**Comment by dgtllion** [comment]
Vercel guys... @icyJoseph / @promer94 / @koba04...
NextJS / ReactJS is stable and running and now i'm waiting for swr to move to the latest NextJS version! 
Can you give us any estimation when we can expect release 2.6.0 of swr?

If there is no estimation, can you explain why not? Are you facing some problems with React 19 or Next 15?
May be we can help somehow?

**Comment by tintinthedev** [comment]
> Can anyone tell me if I use legacy-peer-deps can it break and not work on react19?

I used `--force` with NextJS 15 and it went well. You can try to create a new branch just to test that, just in case something breaks

**Comment by koba04** [comment]
Sorry for being late 🙏  We've just released v2.3.0, which support React 19 🎉 
https://github.com/vercel/swr/releases/tag/v2.3.0
