### ISSUE TITLE
[question][documentation] Request deduplication

### ISSUE THREAD

**Issue by andrewmclagan** [vercel/swr#306]
Seems request deduplication is a feature as its mentioned in the docs and this PR: https://github.com/zeit/swr/pull/235

If this is the case would you accept a PR to extend the documentation around this feature? As at present its very minimal.

Does request deduplication work as follows? Only one request would be made?

```javascript
import useSWR from "swr";

function UserProfile() {
  const { data, error } = useSWR("/api/user", fetcher);

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;
  return <p>Name: {data.name}!</p>;
}

function UserAvatar() {
  const { data, error } = useSWR("/api/user", fetcher);

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;
  return <img src ={data.avatarUrl} alt="Profile image" />;
}

export default function App() {
  return (
    <div>
      <UserAvatar />
      <UserProfile />
    </div>
  );
}
```

**Comment by sergiodxa** [comment]
Yes, only one request will be made in that case in that, and once the promise is fulfilled it will update both components.

**Comment by andrewmclagan** [comment]
Should I PR to extend the docs? or not worth it?

**Comment by quietshu** [comment]
Thank you @andrewmclagan! Yeah it's worth to document it 👍

**Comment by tanmaylaud** [comment]
@shuding ,  I addressed this issue in [this PR](https://github.com/vercel/swr/pull/519) .
Please accept.
Sincere thanks to Andrew Mclagan for suggesting the documentation. I saw that it was not addressed for a few months so  added it myself.
