### ISSUE TITLE
Interaction of mutate & initialData appears to be incorrect

### ISSUE THREAD

**Issue by tmcw** [vercel/swr#308]
Hi folks! Lovely module here. Ran into a bit of an issue.

If you use initialData in your initial call to useSWR,

```js
const { data } = useSWR(key, loadData, {
  initialData: initialData
})
```

And then someone calls `mutate` with a callback function on the page, then the `mutate` callback gets _undefined_ as its input, not the `initialData` value. Mutate [pulls data from the cache](https://github.com/zeit/swr/blob/master/src/use-swr.ts#L87), but [initialData is not set in the cache](https://github.com/zeit/swr/blob/master/src/use-swr.ts#L170).

```
mutate(key, data => ({ ...data, foo: 1 }))
```

The end result is that if someone clicks a button that triggers a callback-based mutation _before_ the initial data is revalidated, then the page likely crashes, because you just set the data to `undefined`.

Unfortunately, its not easy to work around this issue: I'd be okay with delaying the UI's appearance until there's an item in the cache, but the cache is internal. If I hid the UI based on isValidating, then it would blip whenever there are mutations. The mutate callback can't choose to return `undefined` for 'no effect'.

Ideally, mutate would be able to mutate the data in initialData, but I am probably missing something in the philosophy of swr that makes that incorrect.

**Comment by oran1248** [comment]
facing the same issue...
When the fix will be released???

**Comment by aj-may** [comment]
Yea, this is a bit of an annoying bug.  I'm working around it for now by immediately calling mutate to fill the cache.  Not a great long term solution.

```
const { data, mutate } = useSWR(myKey);
useEffect(() => { mutate(); }, []);
```

Hope my PR is reviewed and merged soon.  I don't see any reason why the `initialData` shouldn't be put in the cache.  Seems like a simple fix.

**Comment by oran1248** [comment]
> Yea, this is a bit of an annoying bug. I'm working around it for now by immediately calling mutate to fill the cache. Not a great long term solution.
> 
> ```
> const { data, mutate } = useSWR(myKey);
> useEffect(() => { mutate(); }, []);
> ```
> 
> Hope my PR is reviewed and merged soon. I don't see any reason why the `initialData` shouldn't be put in the cache. Seems like a simple fix.

It seems like a very basic and common behavior. I hope they will fix it very soon.

**Comment by oran1248** [comment]
@aj-may 
When this issue will be fixed? It is very critical to me..

**Comment by mikestopcontinues** [comment]
Yeah, I'm having this bug too. I use SWR to do live edits, where the first time it makes sense to revalidate is when the user saves to the db, not during the edits themselves. Thanks @oran1248 for the workaround.

**Comment by mikestopcontinues** [comment]
I found another workaround, if you're only referencing the SWR key in one place:

```js
const {data: rawData} = useSWR('/key', {initialData});
const [data, mutate] = useState(rawData);
useEffect(() => mutate(rawData), [rawData]);
// data + mutate() work roughly as you'd expect
```

**Comment by mikestopcontinues** [comment]
Is there any movement on this issue?

**Comment by dungkaka** [comment]
I face the same issue when mutate with fallbackData at new version. How can I fix it ?

**Comment by shuding** [comment]
As the new option name `fallbackData` suggests, this works more like a **fallback**, which is **not** stored in the cache. To correctly do initial cache right now I think you will need to use https://swr.vercel.app/docs/advanced/cache instead.
