### ISSUE TITLE
How can I return data from useSWRPages

### ISSUE THREAD

**Issue by timurmaio** [vercel/swr#311]
I have a table component that accepts data as a prop and I want to make an infinite scroll that populates the data. As far as I understood useSWRPages return the actual view, but can I return the resolved data from useSWRPages?
I need to pass it to table like this, the prop is "rows":
`<BaseTable columns={columns} rows={localRows} isFetching={isFetching} />`

**Comment by sergiodxa** [comment]
`useSWRPages` returns an object with the following format:

```js
{
    pages,
    pageCount,
    pageSWRs,
    isLoadingMore,
    isReachingEnd,
    isEmpty,
    loadMore
  }
```

`pageSWRs` is an array with the result of each page you fetched, this object has the same format useSWR returns, that means:

```js
{ data, error, isValidating, revalidate, mutate }
```

You can then iterate this array, get all the data attributes and concatenated to get the data from all pages.

**Comment by timurmaio** [comment]
Thank you very much for the detailed answer! I read the doc, but I did not fully understand the case, thank you again!

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!
