### ISSUE TITLE
SWRConfig not applied to hook calls

### ISSUE THREAD

**Issue by ranisalt** [vercel/swr#332]
I am trying to wrap my entire application inside a `SWRConfig` to disable revalidation on focus, like this:

```jsx
<SWRConfig value={{ revalidateOnFocus: false }}>
	<Provider store={store}>
		<Router history={history}>
			<App />
		</Router>
	</Provider>
</SWRConfig>
```
Then components inside `<App />` use `useSWR` to fetch data.

The problem is `SWRConfig` is not applied at all, and every time I focus on the page again everything reloads. This is especially cumbersome as some routes to edit information are reloaded, rerendered and changes are lost every time the user changes page.

Reading the docs I couldn't spot the misusage of functions here, what am I doing wrong that the setting is being ignored?

**Comment by shuding** [comment]
Hi @ranisalt! Do you mind creating a minimal reproduction on https://codesandbox.io? The code looks correct to me.

**Comment by chaddjohnson** [comment]
I am most definitely seeing this issue as well. From my _app.js:

```jsx
import { SWRConfig } from 'swr';

// ...

<ThemeProvider theme={theme}>
  <ErrorBoundary>
    <SWRConfig value={{ revalidateOnFocus: false }}>
      <Contexts>
        <Component {...pageProps} />
      </Contexts>
    </SWRConfig>
  </ErrorBoundary>
</ThemeProvider>
```

Things load on initial page load, and then when I tab away and back, things reload...every time I tab away and back.

**Comment by maxcountryman** [comment]
Running into the same issue.

**Comment by nzpopa** [comment]
Same

**Comment by shuding** [comment]
Hi @nzpopa, I'm not able to reproduce this issue personally. Would be great if you can provide a basic reproduction on CodeSandbox to help me identify the problem, thanks! 

I'll re-open this issue when more information is provided (version, reproduction, etc.).
