### ISSUE TITLE
SWR should suspense when key is falsey

### ISSUE THREAD

**Issue by shuding** [vercel/swr#339]
When using SWR with Suspense, it's guaranteed that render won't continue unless `data` is ready:

```js
function App() {
  const { data } = useSWR('key', fetcher, { suspense: true })
  assert(data !== undefined)
}
```

However if the key is conditional or falsey,

```js
function App() {
  const { data } = useSWR(() => ready ? 'key' : null, fetcher, { suspense: true })

  assert(data !== undefined) // error!
}
```

SWR will treat `undefined` as a returned data because there's no promise created.

**Comment by enzoferey** [comment]
Related to https://github.com/zeit/swr/issues/266 I believe 👍

**Comment by shuding** [comment]
Commented here: https://github.com/zeit/swr/pull/357#issuecomment-627089889
