### ISSUE TITLE
Revalidate doesn't work when refreshInterval enabled

### ISSUE THREAD

**Issue by loveholly** [vercel/swr#340]
I'm using `swr` on `react-native`, when I enabled `refreshInterval`, I found that `revalidate` doesn't work any more. And when I disabled `refreshInterval`, revalidate works again.

```bash
react-native version: 0.61.5
swr version: 0.1.18
```

I'm not sure whether it is a bug or a feature?

**Comment by sergiodxa** [comment]
Is your interval smaller than 2s? SWR has a deduping mechanism with a default time of 2s, if the last request was 2s ago or less it may be being deduped. You can try to disable this setting dedupingInterval to 0 and see if that solves the issue.

**Comment by loveholly** [comment]
Actually, my interval is `60000`, however your solution still works for me. Thanks for your help.
