### ISSUE TITLE
Scroll position not retained when clicking back

### ISSUE THREAD

**Issue by shirazz** [vercel/swr#347]
CodeSandbox: https://codesandbox.io/s/using-paginated-data-with-swr-9g0y4

If we navigate from the paginated list page to another page and click back, the scroll position is not retained. As per the docs, retaining scroll position seems automatic. Please correct me if wrong.

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!

**Comment by shirazz** [comment]
Thanks @shuding This is amazing stuff. I was able to get it working as expected. Adding a [sample implementation](https://codesandbox.io/s/flamboyant-gauss-5isme) using your example CodeSandbox demo.

**Comment by Nithur-M** [comment]
Hey @shirazz, may I know how did you get it to working?
Currently, when I navigate back to my lists, it loads everything from zero again.
