### ISSUE TITLE
Uncaught (in promise) issue with fetcher function

### ISSUE THREAD

**Issue by fakekamrankhan** [vercel/swr#352]
I'm using SWR with `unfetch` as the fetcher, but I am stumped on why rejected Promises are throwing uncaught exceptions errors.

My fetcher function:
```
async function fetcher(endpoint, getToken) {
	const token = await getToken();
	const response = await fetch(endpoint, {
		headers: {
			'Authorization': `Bearer ${token}`
		}
	});
	if (response.ok) {
		return response.json()
	}
	return Promise.reject('Not allowed')
}
```

`Promise.reject` throws an 'uncaught (in promise)' error. If I `catch` the promise it loads the `Not allowed` message inside the `data` property of the useSWR hook, not the `error` property which doesn't seem intuitive?

Maybe I'm just confused and don't understand how the `useSWR` hook populates the `error` and `data` properties from the fetcher function?

Any help would be appreciated.

**Comment by sergiodxa** [comment]
I think you need to do `throw new Error("Not allowed")` instead of returning a rejected promise.

**Comment by fakekamrankhan** [comment]
That just changes the error from 'Uncaught (in promise)` to `Uncaught Not allowed` but the behaviour is the same.

If I catch the error, again, useSWR populates the `data` property, not the `error` property.

**Comment by muratsu** [comment]
```
  async function fetcher(endpoint) {
    return Promise.reject('not allowed');
  }

  const { data, error, isValidating, mutate } = useSWR(
    `localhost/api`,
    fetcher
  );

  console.log(`data:${data} error:${error}`);
```

this prints `data:undefined error:not allowed` on the console. Could it be the case where your `getToken` or `fetch` functions are throwing and you're not catching the error?

**Comment by Vern-at-Motional** [comment]
For anyone else reading: the original user likely needs to disable suspense in useSWR. The two don't play together nice. (When suspense is enabled, useSWR throws the error instead of catching it.)
