### ISSUE TITLE
mutate seems to return a fulfilled promise

### ISSUE THREAD

**Issue by samselikoff** [vercel/swr#355]
This might be a misunderstanding of mine, but in this scenario `mutate()` seems to return a resolved promise:

```js
setIsSaving(true)

await fetcher("/api/todos", {
  method: "POST",
  body: JSON.stringify({ todo: newTodo }),
});

await mutate("/api/todos")

setIsSaving(true)
```

The intention here is set `isSaving` to true, then POST the new Todo, then refresh the `"/api/todos"` cache, then set `isSaving` to false. But `isSaving` gets set to false before the mutate call has returned from the server.

Is this intentional? I know `mutate()` takes a second function which can be async, but it also seems like just a call to `mutate("/api/todos")` should also return a promise that fulfills once the revalidation has occurred.

**Comment by sergiodxa** [comment]
I found this issue, looks like when `mutate` is called without a second argument is calling `revalidate` internally, which is not returning a promise, what you can do in your case is to merge the fetcher call and mutate.

```js
await mutate("/api/todos", async todos => {
  const todo = await fetcher("/api/todos", {
    method: "POST",
    body: JSON.stringify({ todo: newTodo }),
  })
  return todos.concat(todo)
})
```

This way `mutate` will return a promise which will be resolved when `fetcher` is resolved, the data returned by the second argument will be also used to update the cache while a revalidation is happening.
