### ISSUE TITLE
[bug?] Updating key to null doesn't update data to undefined

### ISSUE THREAD

**Issue by derindutz** [vercel/swr#375]
```
const { data } = useSWR(key);
console.log(data);
```

If I start with `key` as `null`, `data` is `undefined` as expected.

If I update `key` from `null` to a url, `data` is populated with data on load as expected.

However, when I then update `key` from a url back to `null` again, I still get the old data associated with the url. Is this on purpose? I'd expect data to go back to `undefined`.

**Comment by lolenko** [comment]
I think it's wrong behavior
Dependent Fetching should't work like this from my point of view

**Comment by shuding** [comment]
Hi, are you still able to reproduce this bug? It seems to be working fine for me: https://codesandbox.io/s/swr-test-lun1r?file=/src/App.js

**Comment by derindutz** [comment]
Hi Shu, I'm no longer able to repro on the latest version! Thank you for your response and thanks for your awesome work on this library!

**Comment by zeing** [comment]
I try on 0.5.5 , it doesn't work
https://codesandbox.io/s/swr-test-forked-px3cl?file=/src/App.js
