### ISSUE TITLE
Dependent fetching with paging not working

### ISSUE THREAD

**Issue by GustavPS** [vercel/swr#384]
```javascript
const { pages, error } = useSWR(validated ? `http://${server.server_ip}:4000/api/movies/list` : null, fetcher)
````
The above line work, the request is being run after validated get the value true.

The block below does not work, the request is never runned, even when validated gets equal to true
```javascript
   const { pages, isLoadingMore, loadMore } = useSWRPages(
        "movie-list",
        ({ offset, withSWR }) => {
          const url = offset || `http://${server.server_ip}:4000/api/movies/list`;
          const { data } = withSWR(useSWR(validated ? url : null, fetcher));
          console.log(data);
          if (!data) return null;
    
          const  results = data;
          console.log("results");
          console.log(results);
          return results.data.map(result => (
            <h1>Test</h1>
          ));
        },
        SWR => SWR.data.next,
        []
      ); 
```

**Comment by illuminist** [comment]
Sounds like you need to put `validated` into deps array as well.

**Comment by GustavPS** [comment]
> Sounds like you need to put `validated` into deps array as well.
> 
> Edit: Addition to need deps array, I dug into source code a bit, I just found something wrong in useSWRPages, will investigate further.

Thanks, but what exactly is the deps array?

**Comment by illuminist** [comment]
> Thanks, but what exactly is the deps array?

It's the same thing as in useEffect, useMemo, useCallback, etc hook. It's use for the hook to reevaluate its data or run it's callback when some value in dependency array is difference from the last render.

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!
