### ISSUE TITLE
[feature] instancing or namespacing cache and config

### ISSUE THREAD

**Issue by MHA15** [vercel/swr#386]
Hi
I was thinking about a new feature to handle multiple namespaces alongside global namespace
which is something like this:
```
const itemsNamespace: (typeof SWR package) = createSWRNamespace({
    ...config,
    fetcher: (id: string) => getItemById(id)
}) ;


// usage
// item id is 5
const item = itemsNamespace.useSWR(5);
itemsNamespace.cache.get(5);
itemsNamespace.mutate(5);
```

**Comment by MHA15** [comment]
this also will help for ts typings and better splitting and isolating local data in a module

**Comment by MHA15** [comment]
this also will help us to not using Context to providing configs when we can set them in createInstance

**Comment by shuding** [comment]
Hi @MHA15, namespaced cache is a planned feature that we are going to work on! But we will most likely use React Context for the API, see the **API Design** part of [this comment](https://github.com/vercel/swr/pull/388#issuecomment-638085648).

**Comment by MHA15** [comment]
> But we will most likely use React Context for the API, see the **API Design** part of [this comment](https://github.com/vercel/swr/pull/388#issuecomment-638085648).

Thanks for your response
I think that it could be a good idea to use a context to provide namespace object but still we could use namespace directly without using context with `namespace.useSwr` 
like redux and react-router which are also let us import and using their global object or providing them to context 
I think we need to use them without context because we don't want to use exactly one provider and we want to use multiple namespaces in multiple level and components so it could be hard to wrap our component with a context provider before exporting it

**Comment by shuding** [comment]
The new `<SWRConfig value={{ provider: () => ... }}>` and `useSWRConfig()` APIs added in [SWR 1.0](https://swr.vercel.app/blog/swr-v1) should be able to address this, you can safely scope your application into different namespaces with it. Gonna close this issue for now but all new ideas are welcome!
