### ISSUE TITLE
[BUG?] Inconsistent value while doing conditional rendering.

### ISSUE THREAD

**Issue by 0xkoffee** [vercel/swr#387]
I am doing conditional rendering. So when the data is not ready I don't show children.

**Expected behavior:**
Consistent value across components regardless of conditional rendering.

**Current behavior:**
Value update is not synchronized, previous value is shown in Children.

**Minimal reproduction:**
https://codesandbox.io/s/swr-mutate-bug-uryb6
When you click into the mutate button twice, you see inconsistent values in the console.

**Comment by cwiller** [comment]
Is this issue confirmed and going to be touched in some near future? 
Or do you recommend migrating to react-query, seriously?

**Comment by huozhi** [comment]
additional context repro version

seems this issue is been resolved with

**Comment by huozhi** [comment]
this issue is reproed with v0.2.1-beta.2. seems to be resolved in the new versions. @0xkoffee you can upgrade to latest version of swr to solve this issue.
