### ISSUE TITLE
[feature] Allow to pass config as a function

### ISSUE THREAD

**Issue by vojty** [vercel/swr#390]
Use case:
```
useSWR(key, '/somewhere', globalConfig =>  {
  return {
    ...globalConfig,
    onError: (error, key) => {
      if (error.response?.status === 403) {
         // some special logic here
         return
      }
      return globalConfig.onError(error, key)
    }
  }
})
```
What do you think?

**Comment by huozhi** [comment]
supplement more information here

config callbacks would be overridden when pass callbacks in 3rd argument `options`.
thus, if user directly execute global config callback inside the callback with same name in options, it will fall into recursion.

```js
useSWR(key, fetcher, {
   // this will override the global config onError
   onError(err, key, config) { 
      config.onError(err, key)
   }
})
```

user might need some way to access the original callbacks in global config or have some methods to intercept the callbacks. not sure if this would be a probable reason why @vojty want this approach.

### Other Possible Solutions

1. give each callback with one more argument `context` to access the global config

```js
useSWR(key, fetcher, {
   onError(err, key, config, context) {
      context.onError(err, key)
   }
})
```

2. expose context out to let user use it directly. pretty aggressive, might not be ideal

```js
import {SWRConfigContext} from 'swr'

const globalConfig = useContext(SWRConfigContext)
useSWR(key, fetcher, {
   onError(err, key, config) {
      globalConfig.onError(err, key)
   }
})
```

**Comment by shuding** [comment]
I'm not sure if this will be a popular demand (I don't see many people requesting for this). As of now, if you really need to reuse the logic, I think you can copy the implementation in config.ts and do changes on top of it.

**Comment by huozhi** [comment]
Recommend to use `SWRConfig` provider to configure global config, and you can override the specific config option per hook. Default config value is also exposed as `SWRConfig.default` in swr@0.5.3.
