### ISSUE TITLE
[Documentation] tough to parse what this part of the README is saying

### ISSUE THREAD

**Issue by cacabo** [vercel/swr#393]
Hey, I can't quite understand what this part of the README, it would be great if someone with more knowledge of the project could revise the text

https://github.com/zeit/swr/blob/master/README.md#returned-data-from-mutate

> ### Returned Data from Mutate
> 
> Most probably, you need to data mutate used to update the cache when you passed a promise or async function.
> 
> The function will returns the updated document, or throw an error, everytime you call it.

**Comment by huozhi** [comment]
try to rephrase this sentence:

> Most probably, you need some data to update the cache. The data is resolved or returned from the promise or async function you passed to `mutate`.
>
> The function will return an updated document to let `mutate` update the corresponding cache value. It could throw an error somehow, every time you call it.

hope this can help @cacabo
