### ISSUE TITLE
useSwrPages doesn't work with filters (dynamic URLs)

### ISSUE THREAD

**Issue by aladinflux** [vercel/swr#396]
If you have a table with filters and your query depends on the filters, useSwrPages doesn't perform well and starts to duplicate results.

Here's the use case:
1 - Setup a useSwrPages to fetch from an api that returns the next offset number (skip in mongo terms) and "null" if it knows there are no more skips (end of data).
2 - Make your page's SWR depend on some filters that are added as a query string to the URL and add the filters to the dependencies.
3 - Load 3 or 4 pages without filters
4 - Apply filters (which will change the query string).
5 - Each SWR will fetch again with the filters and when there are not enough results, the offsetter function will return null (because API returned null). However, because there are 4 pages already, SWR will run them anyway with null as offset and retrieve the same set of results duplicated in the 4 pages.

Trying to pass null to the swr so that it doesn't fetch again won't work because "null" is the initial value of the offset and the page has no way of knowing if it's the first or not.

A way to overcome this is to not restrict us with null values or expose a method `cleanup` to remove all the pages. We can call `cleanup` after `filters` has changed to make useSwrPages restart from page 0.

**Comment by konstaner** [comment]
I think I encountered the same problem: https://github.com/zeit/next.js/discussions/13093
Hope the fix will be merged soon )

**Comment by illuminist** [comment]
I had a workaround which is to use `key` prop to force component with useSWRPages to unmount and remount with a new page key.

**Comment by konstaner** [comment]
I tried this, but it doesn't work in my case. Do you mean this key?
```
...
useSWRPages(
    'this-key-pass-as-prop', // key of this page
    ({ offset, withSWR }) => {
...
```

**Comment by konstaner** [comment]
> ```
> ...
> useSWRPages(
>     'this-key-pass-as-prop', // key of this page
>     ({ offset, withSWR }) => {
> ...
> ```
I add key to SWRPages based on selected filters and key prop to the component. And now it rerenders without duplication. Thanks

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!
