### ISSUE TITLE
How to use useSWRPages with graphql?

### ISSUE THREAD

**Issue by jackyang1984** [vercel/swr#399]
Anyone knows how to use useSWRPages with graphql, the examples just use rest api.

**Comment by w3bdesign** [comment]
Here's a simple example. 

It's not the best code or the most functional code, but it should at least get you started. 

Obviously you need to change GRAPHQL_ENDPOINT_URL.

I am using graphql-request for GraphQL.

```
const App = () => {
  const FETCH_ALL_CATEGORIES_QUERY = `
query MyQuery {
  productCategories      {
    nodes {
      name
    }
  }
}
`;

  const { data, error } = useSWR(FETCH_ALL_CATEGORIES_QUERY, (query) =>
    request('GRAPHQL_ENDPOINT_URL', query)
  );

  console.log(data); // TODO pass this to a component or do something with it
  console.log(error); // TODO do error handling

  return <p>Example</p>;
};
```

**Comment by jackyang1984** [comment]
@w3bdesign  thanks a lot, i want to know how to use useSWRPages , not useSWR.

**Comment by shuding** [comment]
Hi @jackyang1984 please take a look at our new API in #435

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!
