### ISSUE TITLE
useRef is returning wrong data from the cache

### ISSUE THREAD

**Issue by Kerumen** [vercel/swr#400]
I have a list of item where I fetch each item by its id. 

Here is the scenario:
- I click on the first item (key: `/api/data/cka9elscf0003x2s5sbqxm5ad`) to fetch it
- I click on the second one (key: `/api/data/cka9elnv60002x2s5kj40qviz`)
- Then I click on the first one again

Before revalidation, swr is returning for the first item the cached data from the second one. I tried to understand why and I nailed it to the [`useRef` hook](https://github.com/zeit/swr/blob/8b9038890d79d113149bd1c7fef1f3ab5fe804cc/src/use-swr.ts#L181-L185).

Here are 2 screenshots of the debugger where the problem is.

When the swr hook is triggered again for the first item, the `initialData` from the cache is right (notice the `id` - it's the first item):

<img width="342" alt="Screenshot 2020-05-16 at 12 24 51" src="https://user-images.githubusercontent.com/5436545/82117509-b068a200-9770-11ea-9247-5c677f699f40.png">

But right after, the `useRef` hook set its data (from `initialData`) and the returning value is the previous one (notice the `id` - it's the second item).

<img width="354" alt="Screenshot 2020-05-16 at 12 25 31" src="https://user-images.githubusercontent.com/5436545/82117508-afd00b80-9770-11ea-80c4-6041eae75cfb.png">

I think the problem comes from the `useRef` hook. Maybe a `useEffect` hook is necessary to update it?

Happy to help debugging this issue!

Code:

```jsx
const DataDisplay = ({ id }) => {
  const { data } = useSWR(`/api/data/${id}`)
  console.log(`/api/data/${id}`, data)

  return (<Card>Id: {id}</Card>)
}
```

----

Edit: I've just tried using `useRef({ data: id })` directly in my component and even tho my props changed, the ref is still returning the old data.

Incorrect code (swr like):
```jsx
const DataDisplay = ({ id }) => {
  const ref = useRef({ id })
  console.log(`/api/data/${id}`, ref.current.id)

  return (<Card>Id: {id}</Card>)
}
```

Correct code:
```jsx
const DataDisplay = ({ id }) => {
  const ref = useRef({ id })
  useEffect(() => {
    ref.current.id = id
  }, [id])

  console.log(`/api/data/${id}`, ref.current.id)

  return (<Card>Id: {id}</Card>)
}
```

**Comment by illuminist** [comment]
useEffect runs after render, here's how:

1. ref get assign with initial data: assume the id is "first"
2. log "/api/data/first", and "first"
3. render out card with "first"
4. useEffect runs, ref.current.id gets assign with "first" (nothing changed)
5. the component update id prop: id is now "second"
6. prepare ref, but it already has initialized so it gets ignored
7. log "/api/data/second", and "first".
8. render out card with "second"
9. useEffect runs, ref.current.id gets assign with "second" (changed)
10. end

**Comment by shuding** [comment]
Feel free to reopen if you have other questions! 👍
