### ISSUE TITLE
How to modify data that getting from SWR

### ISSUE THREAD

**Issue by xyyolab** [vercel/swr#402]
How to migrate this use case to `SWR`?
Thanks in advance!

``` 
const [value, setValue] = useState('')

useEffect(() => {
  const fn = async (() => {
    const {data} = await axios.get(API)
    setValue(data)
    }
  fn()
  }, [value])

return <input value={value} onChange={(e) => setValue(e.currentTarget.value)} />
```

**Comment by huozhi** [comment]
you can make the `async fn()` as fetcher argument for swr, and use `value` as key. like

```js
const {data} = useSWR(key, async () => { const {data} = await axios.get(API); return data; })
```

@xyyolab do you mind providing more information about the use case? when user input sth, changes will lead to a new get request and the response data, which will change the value again and it will go into the new cycle?

**Comment by xyyolab** [comment]
Thanks for your response!
I'm making a detail page with a form that gets data from API like below.
There is only one submit button with a post request to update(don't need to re-fetch data after load everything).

I figure out this possible way to do my job.

I'm new to SWR which is great! Do you have any advice on this situation?

```js
function productDetail () {

  const [value, setValue] = useState('')
  const [fetched, setFetched] = useState(false)
  const fetcher = (url) => fetch(url).then((r) => r.json())
  const { data } = useSWR(GET_API, fetcher)
  const handleClick = async () => {
     await axios.post(POST_API, {value})
  }

  useEffect(() => {
      if (data) {
        setValue(data.value)
        setFetched(true)
      }
  }, [data])

  if (!fetched) return <div>loading</div>
  return (
    <>
      <input value={value} onChange={(e) => setValue(e.currentTarget.value)} />
      <button onClick={handleClick}>submit</button>
    </>
  )
}

**Comment by huozhi** [comment]
thanks I think I understand your approach here 😄 looks great. not sure if the `fetched` could be replaced with `isValidating` return from useSWR I guess?

```js
const {data, isValidating} = useSWR

if (isValidating) return <div>loading</div>
```

**Comment by sergiodxa** [comment]
You need to use the mutate function, either the one returned by useSWR with the key already applied if the one exported by the library without the key already applied.

```js
import { mutate } from “swr”

mutate(key, oldData => newData, false)
```

Or

```js
const { mutate } = useSWR(key, fetcher)
// ...
mutate(oldData => newData, false)
```

**Comment by xyyolab** [comment]
@sergiodxa 
Could you please help me with this full use case?

I think I need to use `mutate`, but still not sure how to implement it.

> ```js
> function ProductDetail () {
> 
>   const [value, setValue] = useState('')
>   const [fetched, setFetched] = useState(false)
>   const fetcher = (url) => fetch(url).then((r) => r.json())
>   const { data } = useSWR(GET_API, fetcher)
>   const handleClick = async () => {
>      await axios.post(POST_API, {value})
>   }
> 
>   useEffect(() => {
>       if (data) {
>         setValue(data.value)
>         setFetched(true)
>       }
>   }, [data])
> 
>   if (!fetched) return <div>loading</div>
>   return (
>     <>
>       <input value={value} onChange={(e) => setValue(e.currentTarget.value)} />
>       <button onClick={handleClick}>submit</button>
>     </>
>   )
> }
> ```

**Comment by sergiodxa** [comment]
Something like this should do the work:
```js
const fetcher = (url) => fetch(url).then((r) => r.json());

function ProductDetail() {
  const { data, mutate } = useSWR(GET_API, fetcher);

  const handleClick = async () => {
    await axios.post(POST_API, { value: data });
    mutate(); // revalidate data
  };

  function handleChange(event) {
    // mutate the data without revalidating it
    mutate(event.currentTarget.value, false);
  }

  if (!data) return <div>loading</div>;

  return (
    <>
      <input value={data} onChange={handleChange} />
      <button onClick={handleClick}>submit</button>
    </>
  );
}
```

**Comment by radomir-mijovic** [comment]
> You need to use the mutate function, either the one returned by useSWR with the key already applied if the one exported by the library without the key already applied.
> 
> ```js
> import { mutate } from “swr”
> 
> mutate(key, oldData => newData, false)
> ```
> 
> Or
> 
> ```js
> const { mutate } = useSWR(key, fetcher)
> // ...
> mutate(oldData => newData, false)
> ```

Thanks man, this is what i was looking for
