### ISSUE TITLE
How to write a global fetcher function with variable args?

### ISSUE THREAD

**Issue by hk86** [vercel/swr#412]
I'm using GraphQL and would like to write a global fetcher function. 

Normally you could do: `useSWR(['/api/user', id], (url, id) => query(url, { id }))` or `useSWR(['/api/user', id, key], (url, id, key) => query(url, { id, key }))`

But how would the function look, if I would like to make it global? Something like `useSWR(['/api/user', id], (url, ...args) => query(url, { ...args }))` does not work.

**Comment by illuminist** [comment]
`...args` supposed to be an array and you cannot spread an array into an object.

```js
const array = [1,2,3]
const obj = { ...array } // this won't work
```

**Comment by shuding** [comment]
Currently it's impossible to do that. There're 2 work arounds but both are not perfect:

```js
// correct but wastes resources to serialize/deserialize
const fetcher = (url, args) => query(url, { ...JSON.parse(args) })
useSWR(['/api/user', JSON.stringify({ id })], fetcher)
```

```js
// useMemo is per-component, so SWR cache can't be shared across contexts
// would be better if you use a global memo, but GC will be an issue
const fetcher = (url, args) => query(url, { ...args })
useSWR(['/api/user', useMemo(() => ({ id }), [id])], fetcher)
```

Hope that helps!
