### ISSUE TITLE
Add an example on how to mutate an item from a list

### ISSUE THREAD

**Issue by Kerumen** [vercel/swr#414]
I have a list of users coming from my API. I'd like to update one user and optimistically update the UI.

Currently I'm doing this (by mimicking the example from the README):

```javascript
const updateUser = (userId, data) => {
  mutate(users.map((users) => users.id === userId ? { ...user, ...data } : user), false)
  mutate(users => {
    const newUser = fetch(`/api/users/${userId}`, { method: 'PUT', body: JSON.stringify(data) })
    return users.map((users) => users.id === userId ? newUser : user)
  })
}
```

The first mutate is here to update the UI, then I trigger the call to update my database and I mutate with the result.

Is it the correct way to do it? It seems a bit redundant.

**Comment by shuding** [comment]
Yes currently what you are doing is correct. We have discussions in #157 on how to improve this specific case, feel free to join the discussion there!

**Comment by bryankang** [comment]
hi - apologies for opening this. 

i was wondering how to handle this if the example above used query strings to sort/filter the user list (e.g., `/users?sort=desc&assignee=bob`)?

if the filters change, we edit a user and return to the previous filters which contains the same user, wouldn't it be outdated?
