### ISSUE TITLE
Compatibility with graphql-tag

### ISSUE THREAD

**Issue by binary64** [vercel/swr#415]
Hi, I have vscode and the Apollo extension for it. It beautifully highlights my gql statements, as well as autocomplete.

```
import gql from 'graphql-tag'

const USER_SUBSCRIPTION = gql`
  subscription getContacts {
    contacts {
      id
      first_name
    }
  }
`
```

but this produces a problem in hasura/apollo/swr (I think swr):

```
{"type":"connection_error","payload":"parsing ClientMessage failed: Error in $.payload.query: expected Text, encountered Object"}
```

I think the solution is https://github.com/apollographql/graphql-tag/issues/144#issuecomment-359367651

It would be cool if you could support for this!

Without the `gql` bit on my USER_SUBSCRIPTION , vscode no longer highlights it.

**Comment by sergiodxa** [comment]
SWR doesn't do anything special to support GQL, it will receive the query generated by Graphql-tag and pass it as is to the fetcher function, I think your fetcher will need to support graphql-tag.

**Comment by shuding** [comment]
Would be great if you can create a minimal reproduction on CodeSandbox. 👍

Closing this PR for now.
