### ISSUE TITLE
Mutate and Update conflicts

### ISSUE THREAD

**Issue by oran1248** [vercel/swr#420]
Hi,

I have a components of users reviews.
The component use `useSWR` to fetch the reviews.
The user can delete/edit a review.
After the user delete/edit a review, I use `mutate` to update the cached version.

How can I avoid the following scenario?

1. User click "delete review" button on review `R`
2. SWR fires a request to fetch reviews (and get a list of reviews with `R` in it)
3. Review `R` removed from DB
4. Call `mutate` to remove `R` from the reviews list
5. The response to the request in step 2 arrives and showed to the user.
6. The user will see review `R` in the list until next SWR fetch.

**Comment by shuding** [comment]
Hi @oran1248, do you have a reproduction (a CodeSandbox link would be great)?

> 5. The response to the request in step 2 arrives and showed to the user.

Ideally this step will never happen. Because when you call `mutate` in step 4, it will *invalidate* all ongoing requests (including the one fired in step 2). So a race condition should never happen.

If you are interested in the related code, it's implemented [here](https://github.com/vercel/swr/blob/master/src/use-swr.ts#L282-L288).

**Comment by oran1248** [comment]
> Ideally this step will never happen. Because when you call mutate in step 4, it will invalidate all ongoing requests

@shuding , that's what I was missing, thanks!

**Comment by oran1248** [comment]
@shuding , What about the following scenario:
1. User click "delete review" button on review R
2. Call mutate to remove R from the reviews list
3. SWR fires a request to fetch reviews (and get a list of reviews with R in it)
4. Review R removed from DB
5. The response to the request in step 3 arrives and showed to the user.
6. The user will see review R in the list until next SWR fetch.

Even if in step 2 I call mutate with `false` param (do not revalidate), swr possibly can revalidate again depends on the `options` param.
How can I avoid this scenario? What is the best practice for optimistic UI? thanks!
