### ISSUE TITLE
Use the refreshed token on new requests

### ISSUE THREAD

**Issue by afmihai** [vercel/swr#424]
Hi there, I am still new to using swr, but I can't figure out yet how can I invalidate the fetcher. If one header is changed, useSWR will use the old one for upcoming requests. How should this be handled?

**Comment by shuding** [comment]
There're 2 ways to invalidate the fetcher. The easiest way is to include the token in the [key array](https://github.com/vercel/swr#multiple-arguments): 

```js
useSWR([url, token], (url, token) => fetch(url, { headers: { token } }))
```

Or, you can just use a global reference of the token inside the fetcher, then revalidate the SWR manually:

```js
const { mutate } = useSWR(url, url => fetcher(url, { headers: { token } })

// whenever token is updated, call mutate
token = newToken
mutate()
```

**Comment by aganjali** [comment]
> There're 2 ways to invalidate the fetcher. The easiest way is to include the token in the [key array](https://github.com/vercel/swr#multiple-arguments):
> 
> ```js
> useSWR([url, token], (url, token) => fetch(url, { headers: { token } }))
> ```
> 
> Or, you can just use a global reference of the token inside the fetcher, then revalidate the SWR manually:
> 
> ```js
> const { mutate } = useSWR(url, url => fetcher(url, { headers: { token } })
> 
> // whenever token is updated, call mutate
> token = newToken
> mutate()
> ```

Hi is there any way to clear cache of all the keys that use the token whenever the token updated?

**Comment by sergiodxa** [comment]
You can import the cache, get all the key and delete them
```
import { cache } from "swr"

cache.keys().filter(filterYourKeys).forEach(key => cache.delete(key))
```
