### ISSUE TITLE
Mutating toggle on/off optimistic causes flash of old data

### ISSUE THREAD

**Issue by TheHolyWaffle** [vercel/swr#425]
Imagine the following scenario where a user can optimisticly toggle a checkbox on and off:
```javascript
const { data, mutate } = useSWR("/api/toggle", fetch);

const toggle = (e) => {
   const isToggled = e.target.checked:

   // mutate optimisticly without revalidation
   mutate(isToggled , false);

   // execute POST and update without revalidation
   mutate(
        fetch("/api/toggle", {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            },
            body: JSON.stringify({isToggled}),
        }),
        false
    );
}

return <Checkbox onChange={toggle} checked={data} />
```

The problem is that when a user clicks the checkbox (or switch) twice in rapid succession, he'll see a flash of stale data:
![checkbox](https://user-images.githubusercontent.com/787914/83793986-964e1f80-a69d-11ea-9081-6f1cf0c5eb44.gif)

Starting state: checkbox is toggled off
1. User clicks checkbox 
    - checkbox is toggled on
    - POST request to toggle on is fired
1. User clicks checkbox again
    - checkbox is toggled off
    - POST request to toggle off is fired
1. POST request of step 1 returns
   - checkbox is incorrectly turned on
1. POST request of step 2 returns
   - checkbox is turned off

The problem is at step 3, where the first POST request returns with stale data. I'd expect SWR to cancel any old ongoing mutates when calling new mutates?

**Comment by shuding** [comment]
Thanks for the great reproduction! 

This is indeed a race condition bug, probably introduced [here](https://github.com/zeit/swr/blob/cd095dd4e11e135eee7eabfb8b3db872195a5b8b/src/use-swr.ts#L87). It should check if `MUTATION_TS[key]` or `CONCURRENT_PROMISES_TS[key]` was updated _after_ the `await` calls. If so, the mutation should be ditched.

**Comment by TheHolyWaffle** [comment]
@shuding I'll work on this
