### ISSUE TITLE
Suspense mode always seems to fetch first

### ISSUE THREAD

**Issue by Narigo** [vercel/swr#429]
Hi there and thanks for a very awesome library!

When using `useSWR` with `initialData` and `suspense: true`, I was expecting to see the `initialData` as result of the `useSWR`. Instead it seems to always suspend and retrieve data (and fails, if offline). Is my expectation wrong for these settings?

I'd like to read data from the local storage initially and refresh it with `useSWR`, if something changed.

I've been checking out the source and changing [the following lines in the `if (config.suspense)` part](https://github.com/vercel/swr/blob/0109c021d2e78b9cb0afca20fabe222417cefcfb/src/use-swr.ts#L549-L550):
```
        let latestData = cache.get(key);
        let latestError = cache.get(keyErr);
```
to
```
        let latestData = cache.get(key) || initialData;
        let latestError = cache.get(keyErr) || initialError;
```
seemed to solve the issue. But I'm unsure about other implications that might have or I'm missing something...

**Comment by shuding** [comment]
Hi @Narigo I think that fix you proposed should work! Please feel free to open a PR for it 👍
