### ISSUE TITLE
Code is missing one prop in example Custom Data Fetching at https://swr.now.sh/

### ISSUE THREAD

**Issue by diegovfeder** [vercel/swr#430]
First of all I would like to know if this is the right place to post this. I'm kind of new here in github and now next.js / vercel.

Then I would like to congratulate the team on creating such a good product!

So... I started studying next.js recently and found this code example at https://swr.now.sh/ headlined by "Custom Data Fetching" is missing the .Movie prop at the last return

- Instead of :
```
return data.actors.map((actor) => <li key={actor.id}>{actor.name}</li>)
```
- It should be:
```
return data.Movie.actors.map((actor) => <li key={actor.id}>{actor.name}</li>)
```
That is all. My 2 cents or even would be 1 or half a cent :)

**Comment by shuding** [comment]
Thank you! The code example is now fixed.
