### ISSUE TITLE
`deps` in `useSWRPages` doesn't seem to do anything

### ISSUE THREAD

**Issue by timwachsener** [vercel/swr#434]
I have a paginated list that can be filtered. So I thought putting the filter string in `deps` would help to get the pages refetched when it changes - but it doesn't. Also including the filter in the `pageKey` didn't help.

```
useSWRPages(
  `items-${id}`,
  ({ offset, withSWR }) => { ... },
  ({ data }) => { ... },
  [filter]
)
```

**Comment by shuding** [comment]
The new pagination API has launched: https://swr.vercel.app/docs/pagination. Feel free to reopen if you are still encountering an issue!
