### ISSUE TITLE
Observables support

### ISSUE THREAD

**Issue by mateja176** [vercel/swr#437]
Similar to:
- https://github.com/LeetCode-OpenSource/rxjs-hooks
- https://github.com/crimx/observable-hooks

This would be especially useful with libraries like [rxfire](https://npmjs.org/package/rxfire)

This ties into web socket (or similar), server subscriptions.

If you're not convinced consider the popularity of [rxjs](https://www.npmtrends.com/rxjs).

**Comment by sergiodxa** [comment]
How would you use SWR with Observables? Do you want support in the fetcher or as a way to get the data?

**Comment by shuding** [comment]
I've been thinking about this too. (but I don't have a clear way in mind to do that). 🤔

```js
const { data } = useSWRSubscription('key', (onData, onError) => {
  const starCountRef = firebase.database().ref('posts/1/starCount')
  starCountRef.on('value', function(snapshot) {
    onData(snapshot.val())
  })
  return () => starCountRef.off()
}
```

But there're a lot of challenges, and it doesn't seem to have any benefits from `useSWR`.

**Comment by sergiodxa** [comment]
Maybe an API like that should be used together with useSWR, as a way to mutate the cache and not to get the data directly, this way you can subscribe to WebSockets or GraphQL subscriptions there and get new values, but you still get the normal SWR features like in focus revalidation.
