### ISSUE TITLE
Data not fetched when missing from cache, when revalidateOn* config set to false

### ISSUE THREAD

**Issue by jamescrowley** [vercel/swr#455]
There are some requests that I'm happy to fill the cache, and then always return the cached value without revalidating. However, I can't figure out the correct config to achieve this?

My understanding from #@sergiodxa's comment here: https://github.com/vercel/swr/issues/450#issuecomment-642280493

was that setting the revalidate config properties to false would enable data to be fetched when it is not present in the cache, and then not fetched again. However, this doesn't seem to be the case:

https://codesandbox.io/s/still-thunder-wq9df?file=/src/App.js

The following just always shows 'no data'.

```
import React from "react";
import useSWR from "swr";

export const App = () => {
  const { data, error, isValidating } = useSWR(
    "/api/user",
    async () => {
      console.log("fetching user");
      return { name: "Amy " + Math.random() };
    },
    {
      revalidateOnFocus: false,
      revalidateOnMount: false,
      revalidateOnReconnect: false
    }
  );

  if (error) return <div>failed to load {error}</div>;
  if (isValidating) return <div>validating...</div>;
  if (!data) return <div>no data...</div>;
  return <div>hello {data.name}!</div>;
};

```

Am I missing something? Thanks!

**Comment by eh-dub** [comment]
Also experiencing this. I'm just using `revalidateOnMount: false` and the hook never triggers the initial call.

**Comment by shuding** [comment]
That’s expected because you have enabled `revalidateOnMount`. It stops the initial fetch.

**Comment by eh-dub** [comment]
Is there no out of the box configuration for a single fetch and no revalidation? Not every fetch needs revalidation. I suppose one could use two different data-fetching hooks, but that seems unnecessary.

**Comment by sergiodxa** [comment]
You can set `revalidateOnMount` to `true` and call `mutate` in an effect.
```js
import React from "react";
import useSWR from "swr";

export const App = () => {
  const { data, error, isValidating, mutate } = useSWR(
    "/api/user",
    async () => {
      console.log("fetching user");
      return { name: "Amy " + Math.random() };
    },
    {
      revalidateOnFocus: false,
      revalidateOnMount: false,
      revalidateOnReconnect: false
    }
  );

  React.useEffect(() => {
    if (!data) mutate()
  }, [data, mutate]);

  if (error) return <div>failed to load {error}</div>;
  if (isValidating) return <div>validating...</div>;
  if (!data) return <div>no data...</div>;
  return <div>hello {data.name}!</div>;
};
```
That should trigger a fetch and update the cache, the function to be used to fetch is the fetcher you passed to useSWR.

**Comment by shuding** [comment]
If I understand it correctly, you want to do **only 1 fetch then always use the cache**, globally?  
Although it can be done with some tricks, we don't recommend it because it can't ensure the freshness of the data when transitioning to a page. 

| | SSR | Traditional SPA | SPA + Global Cache* | SWR |
|-|---|---|---|---|
|fresh data on transition|✅|✅|❌|✅|
|fast transition w/ cache|❌|❌|✅|✅|
|skeleton on transition|❌|✅|✅|✅|
|auto update|❌|❌|❌|✅|

However if you still want it (global cache), what @sergiodxa shared can definitely work and you can make it a util too.

**Comment by jamescrowley** [comment]
@shuding for our use case, we have data that we read where the records are static (think event log type data) - hence we want the caching benefit, but have no need to re-validate.

I'll go with @sergiodxa 's suggestion for now, thanks.

**Comment by shuding** [comment]
Gotcha! I'll close this issue for now.
