### ISSUE TITLE
Move the `online` event listener to config

### ISSUE THREAD

**Issue by shuding** [vercel/swr#474]
# Bug report

## Description / Observed Behavior

SWR registers multiple `online` event listeners:

![image](https://user-images.githubusercontent.com/3676859/85142081-647eb080-b27a-11ea-8108-2e76180d0aef.png)

## Expected Behavior

There should be only 1 listener, just like `visibilitychange`.

## Additional Context

https://github.com/vercel/swr/blob/03c7b8320dde30fab24c9706cd33c5eb27d0552e/src/use-swr.ts#L494-L497

needs to be moved to

https://github.com/vercel/swr/blob/03c7b8320dde30fab24c9706cd33c5eb27d0552e/src/config.ts#L87-L88

**Comment by galanggg** [comment]
Hello @shuding , is this issue still open ?
