### ISSUE TITLE
Axios & initialData. data is different from the one came from initialData

### ISSUE THREAD

**Issue by Migggz** [vercel/swr#503]
# Bug report

## Description / Observed Behavior

While I'm using `getStaticProps` or `getInitialProps` and `return` the data to props and pass it to `initialData`, it give me object different from using `useRequest` directly in the page

```js
const Index = ({ initialData }) => {
  const { data } = useRequest("/endpoint", { initialData })
  const { data: anotherName } = useRequest("/endpoint")

  console.log(data)
  // {
  //   status: 200,
  //   statusText: 'InitialData',
  //   headers: {},
  //   data: {someData: {firstName: "Maged", lastName: "Mohamed"}}
  // },
  
  console.log(anotherName)
  // data: {someData: {firstName: "Maged", lastName: "Mohamed"}}
  
  // UNWATED CHECK !
  const whatToRender = data.statusText === 'InitialData' ? data.data.someData : data.someData

  return (
    <div>
      <div>{whatToRender.firstName}</div>
      <div>{whatToRender.lastName}</div>
    </div>
  )
}

export async function getStaticProps() {
  const { data: initialData } = await axios("/endpoint")

  return {
    props: {
      initialData
    }
  }
}

export default Index
```

## Expected Behavior

I was expecting the data came from `initialData` is identical to `data` came from `useRequest` without passing any initial data.
Is there any reason to make data different from 

I think that is good to make data identical. otherwise I'm going to double check if data came from initialData or not to render it without any errors !

## Solution / Code Example
**Here is my solution for this issue.**

 
```js
import useSWR from "swr"
import axios from "axios"

export default function useRequest(request, config = {}) {
  return useSWR(
    request && JSON.stringify(request),
    () => axios(request || {}).then(response => response.data),
    { ...config }
  )
}
```

## Additional Context

SWR version: 0.2.3

**Comment by sergiodxa** [comment]
This is probably because `revalidateOnMount` is disabled when you pass initialData, try adding `revalidateOnMount: true` to force a revalidation, it will still use the initialData for a while until the revalidation finish.

**Comment by Migggz** [comment]
@sergiodxa I don't think passing `revalidateOnMount` solves the problem. It still needs to double check otherwise it will throw an error while rendering.

Is there any need or benefit to structure `initialData` like this?
```js
initialData: initialData && {
    status: 200,
    statusText: 'InitialData',
    headers: {},
    data: initialData
}
```

**Comment by Migggz** [comment]
Fixed by configuring Global SWR
```jsx
const swrConfig = {
  fetcher: async (query) => (await Axios.get(query)).data,
};
```
then
```jsx
<SWRConfig value={swrConfig}>
  {/* ... */}
</SWRConfig>
```
