### ISSUE TITLE
router.query = undefine in useEffect

### ISSUE THREAD

**Issue by IRediTOTO** [vercel/swr#512]
Hi, I tried to get router.query in useeffect but it is undefine. But outside of useeffect router.query have a value. Is this an error ? I just want to take a value in url pathname.

**Comment by sergiodxa** [comment]
This it's more a Next.js issue rather than an SWR issue.

Answering your question, are you adding an empty array to your effect? Try passing `router.query` as dependency.

**Comment by IRediTOTO** [comment]
> This it's more a Next.js issue rather than an SWR issue.
> 
> Answering your question, are you adding an empty array to your effect? Try passing `router.query` as dependency.

Yes i tried pass `process.browser` as dependency, it work, just don't like page render loading component.

**Comment by shuding** [comment]
It's the Next.js behavior, that `query` will be empty (`{}`) during the hydration (first render/prerender).

Check https://nextjs.org/docs/api-reference/next/router#router-object, you need to put the value directly in the dependency array or the SWR key value:

```js
useEffect(() => {
  if (!router.query.foo) return
  // ...
}, [router.query.foo])


useSWR(router.query.foo ? myKey : null, fetcher)
```
