### ISSUE TITLE
[enhance] use the latest version of the config callbacks

### ISSUE THREAD

**Issue by lintuming** [vercel/swr#515]
Related issue: #508 

Currently,the config callbacks captured by the [`eventsRef` ](https://github.com/vercel/swr/blob/master/src/use-swr.ts#L237) is the callbacks created in the initial render of the component. 
If the config callbacks is pure, everything is fine.
but if the config callbacks rely on some variables of the components , it would cause some bugs related to the stale closure.

# solution
I think if the `useSWR` hook read the config callbacks via `useRef` would be great, but this may bring some bugs if some APP rely on the current behavior of the config callbacks.
```
  const eventsRef = useRef({
    emit: (event, ...params) => {
      if (unmountedRef.current) return
      configRef.current[event](...params)
    }
  })
```
what do you think?

**Comment by lintuming** [comment]
cc @shuding

**Comment by sergiodxa** [comment]
This looks like a good idea, would you like to send a PR with the change? It would even great to run the whole test suite against it and probably add a few tests to ensure it works as you expect

**Comment by lintuming** [comment]
@sergiodxa 
sure, would love to take it.

**Comment by akafaneh** [comment]
I've been struggling with an issue because of this, i'm relying on some redux state that gets updated a lot in the onError callback, and the fact that it only capture and and save the callback on first render made it impossible to get around the issue with a clean solution, so this fix would save a lot for me.

thanks
