### ISSUE TITLE
useSWRInfinite support arrays in an object

### ISSUE THREAD

**Issue by tifa2UP** [vercel/swr#518]
# Bug report
👋, I'm using `useSWRInfinite` to build infinite scrolling and saw that it doesn't support arrays that are nested in an object.  

## Description / Observed Behavior
For example, the API that I'm using does the following: 

`[api-url]/?page=1`

```
{
 meta: {} //meta data
 array: {} // data for page 1
}
```

`[api-url]/?page=2`

```
{
 meta: {} //meta data
 array: {} // data for page 2
}
```

`useSWRInfinite` tries to append these two objects, which doesn't work, instead, it should attempt to append array of request 2 to array of request 1. There seems to be no way to support this atm.

## Additional Context

SWR version: `0.3.0-beta.6`

**Comment by tifa2UP** [comment]
To clarify, there are workarounds for it by modifying the fetcher function, though it would be nice to have it supported out of the box

**Comment by shuding** [comment]
I'd do this instead:

```jsx
function usePagainatedUsers () {
  const { data } = useSWRInfinite(...)

  // we manually pick and concat the paginated data array
  const users = useMemo(() => 
    [].concat(...data.map(page => page.array)),
    [data]
  )

  return users
}
```

And use the `usePagainatedUsers` hook inside my components.

The reason that this lib can't simply support `.array` is that, every API has a different implementation. Some return the data array directly, some wrap it under a `array` field, and some use other properties.

Right now, it's better to leave the flexibility to the user IMO, until we have a better and more general idea. 

I'll move this issue to discussion.
