### ISSUE TITLE
Storing initialData in cache 

### ISSUE THREAD

**Issue by lukaszromerowicz** [vercel/swr#523]
Hello,

I have a use-case where I would like to take advantage of the `swr` built-in cache and store the `initialData` there.
I found out I can use the cache module e.g.:
```js
import { cache } from 'swr';

cache.set('my-key', initialData);
``` 
But I am wondering if there is any other, preferred way of achieving this?

**Comment by sergiodxa** [comment]
You can also use the mutate function

**Comment by lukaszromerowicz** [comment]
Do you see this ever becoming a feature? 
e.g.
```js
const { data, error } = useSWR('/api/user', fetcher, { initialData, cacheInitialData: true })
```

**Comment by huozhi** [comment]
@lukaszromerowicz explanation for the same topic: https://github.com/vercel/swr/pull/388#issuecomment-638085648

**Comment by zomars** [comment]
I'm dropping my two cents here, what would be an optimal approach to this scenario using Next.js:

```js
export async function getStaticProps() {
  const user = await fetcher('/me');
  return { props: { user } };
}

function Props(props) {
  const { data } = useSWR('/me', fetcher, { initialData: props.user });

  const handleClick = () => {
    mutate('/me', (cachedUser) => {
      // At the first click of the button, cachedUser will be undefined.
      return { ...cachedUser, name: 'other name' };
    });
  };

  return <button onClick={handleClick}>Change my name {user.name}</button>;
}
```

At first my solution was to put `cache.set('/me', user)` inside the `getStaticProps` function, but I don't know if it will have unintended consequences.

**Comment by Develliot** [comment]
> You can also use the mutate function

Would that still work if the key doesn't exist in the cache yet?

**Comment by sergiodxa** [comment]
@Develliot yes, if it's not in cache it will create it

**Comment by ties-v** [comment]
I have the same issue as @zomars and use this workaround for now. Maybe it is helpful for others.

```ts
import { useEffect, useRef } from 'react';
import _useSwr, {cache} from 'swr';
import { ConfigInterface, keyInterface, fetcherFn, responseInterface } from 'swr/dist/types';

/**
 * Patched version of SWR to work around the fact that initial data is not inserted to the cache.
 *
 * This is an issue when using useSWR with initialData and then calling mutate with a function that
 * expects the current value. Before the data is revalidated, the function passed to mutate will
 * receive undefined.
 *
 * Based on:
 * @see https://github.com/vercel/swr/issues/284#issuecomment-706094532
 */
const useSwr = <Data = unknown, Error = unknown>(
    key: keyInterface,
    fn?: fetcherFn<Data>,
    config?: ConfigInterface<Data, Error>
): responseInterface<Data, Error> => {
    const hasMounted = useRef(false);

    if (config?.initialData) {
        const [k, ,] = cache.serializeKey(key)
        // Set initial data as cache value if:
        // initialData is set
        // it is the first render
        // and the cache value for this key is undefined
        if (!hasMounted.current && cache.get(k) === undefined) {
            cache.set(k, config?.initialData)
        }
    }

    useEffect(() => {
        hasMounted.current = true;
    }, []);

    return _useSwr<Data, Error>(key, fn, config);
};

export default useSwr;
```
It basically sets the value of `initialData` into the cache on the first render, if the cache is empty for this key.

**Comment by droplab** [comment]
Nice one @ties-v. I came up with a similar approach, i guess this kinda violates the rfc spec SWR is built on but this would be a sensible default behaviour in or at the very least a config option IMHO.

**Comment by huozhi** [comment]
Close as duplicate with #284. One possible solution per https://github.com/vercel/swr/issues/284#issuecomment-869174803
