### ISSUE TITLE
Using state with  `revalidateOnFocus` and `revalidateOnReconnect` options

### ISSUE THREAD

**Issue by nicholaschiang** [vercel/swr#529]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

I'm trying to dynamically control whether or not to `revalidateOnFocus` and `revalidateOnReconnect` but it seems as if you're unable to connect state variables to those configuration options (i.e. even when the state is `false`, SWR still re-validates):

```typescript
const [validate, setValidate] = useState<boolean>(true);
const { data, isValidating } = useSWR('/api/users/', {
  revalidateOnFocus: validate,
  revalidateOnReconnect: validate,
});

return (
  <Button onClick={() => setValidate((prev: boolean) => !prev)} />
);
```

Even while that `validate` state variable is `false`, SWR still re-validates when I re-focus the tab. It seems as if the existing behavior is that SWR sticks to whatever configuration it was given first (i.e. if the `validate` state variable is initialize to `false` first, it will *never* re-validate **even** when `validate` is changed to `true`).

## Expected Behavior

How did you expect SWR to behave here?

It should only re-validate if those configuration options are `true` (taking into account any state-ful variables).

**Comment by promer94** [comment]
#521 will fix this issue

**Comment by nicholaschiang** [comment]
@promer94 that workaround won't work for my use-case. What it seems to be doing right now is just re-rendering the entire component to update that SWR hook config, right? My component is at the top level of the entire app (so it'd be way too expensive to re-render it just to toggle the SWR config).

**Comment by promer94** [comment]
currently, the useSWR always uses config created in the initial render of your component.
after #521 merged, we could get the latest config in useSWR. Then i would like to make a PR to solve this

**Comment by nicholaschiang** [comment]
Ok, that makes sense @promer94. Though woudn't re-rendering the component containing the `useSWR` hook cause SWR to fetch the data again (thus, when we set `revalidateOnFocus` to `false`, we force SWR to re-validate)?
