### ISSUE TITLE
Uncaught Error: Maximum update depth exceeded (using axios post)

### ISSUE THREAD

**Issue by cseas** [vercel/swr#542]
# Bug report

## Description / Observed Behavior

Code keeps getting called repeatedly eventually ending in a Maximum update depth error.

## Expected Behavior

Call should work as expected. I'm just trying to make a basic axios post request.

## Repro Steps / Code Example

```jsx
// App.tsx
import React from 'react';
import https from "https";
import axios from "axios";
import useSWR from "swr";

type myInput = {
  myInputData: string;
};

export function App() {
  const { data, error } = useSWR(
    [
      "/api/myEndpoint",
      {
        myInputData: "12345",
      },
    ],
    myFetcher
  );

 console.log("SWR response:", data);
 
  return <></>
}

const myFetcher = async (url: string, input: myInput) => {
  const agent = new https.Agent({
    // custom agent config
  });

  const response = await axios({
    method: "post",
    url: url,
    data: input,
    httpsAgent: agent,
  });

  return response.data;
};
```

## Additional Context

SWR version: 0.2.3

**Comment by sergiodxa** [comment]
Objects are not supported as part of a key, they are going to be regenerated on every render, instead try sending more values in the array or if possible move the definition of the object to outside the component (in your example is possible but most probably it will not when using it in an app)

**Comment by cseas** [comment]
@sergiodxa Thank you! Looks like that was the issue. I passed the individual POST request input fields like this:
```js
useSWR(
    [ "/api/myEndpoint", "12345", "abcd" ],
    myFetcher
);
```

Then I modified the fetcher to take those individual and construct the object to send as input before making the axios call. However, this still doesn't ideally solve my use case. I'd like to write an axios POST based fetcher that can take an object and a url and just make a POST request to that url using the object as input.

Here's the fetcher I've written:
```js
async function axiosPOST(inputData, urlEndpoint) {
  const agent = new https.Agent({
    rejectUnauthorized: false,
  });

  const response = await axios({
    method: "post",
    url: urlEndpoint,
    data: inputData,
    httpsAgent: agent,
  });

  return response.data;
}
```

Now if SWR doesn't support passing in objects then I'll need to write a separate fetcher for every API call that constructs the input object inside the fetcher before passing it to axios. Any way we can make a general fetcher like the above work with SWR?

**Comment by cseas** [comment]
For anyone who stumbles into the same error, I'll leave a minimal working code example here for axios post with typescript:
```tsx
// Call.tsx
import React from "react";
import axios from "axios";
import useSWR from "swr";

type myInput = {
  id: string;
  name: string;
};

const inputData = { id: "12345", name: "abcd" };

export function Call() {
  const { data, error } = useSWR(
    ["/api/myEndpoint", inputData],
    axiosPostFetcher
  );

  if (data) console.log("SWR response:", data);
  if (error) console.log("SWR Error:", error);
  if (!data) console.log("SWR undefined");

  return <></>;
}

async function axiosPostFetcher(urlEndpoint: string, inputData: myInput) {
    const response = await axios({
      method: "post",
      url: urlEndpoint,
      data: inputData,
      httpsAgent: agent,
    });
    return response.data;
}
```

**Comment by sergiodxa** [comment]
If you want to use objects with a single fetcher function instead of a custom one per useSWR call you can serialize it like this:

```ts
function fetcher(url: string, serializedParams: string) {
  const params = JSON.parse(serializedParams);
  // code here
}

useSWR(["/api", JSON.stringify({ token: userToken })], { fetcher })
```
Something like that

But I'm not sure how performant that could be, you are going to serialize and deserialize a lot.

If you don't enable Suspense on SWR, you may be able to also use `React.useMemo` to memoize the object and pass it directly, but this is also not 100% secure.

**Comment by cseas** [comment]
@sergiodxa Thanks a lot! The JSON serialize/deserialize example works perfectly. I'll mark the issue as resolved.

Documentation improvement suggestions for the SWR team:
- The [axios example] in the docs gives no hint of how to use a post call. I think I figured out from some GitHub issue comment that useSWR() passes arguments to the fetcher.
- The [arguments and object passing](https://swr.vercel.app/docs/arguments) sections of the docs are probably relevant here. The axios example should perhaps mention somewhere that these sections should be referred for POST calls.
- I looked at the [axios typescript](https://github.com/vercel/swr/blob/master/examples/axios-typescript/libs/useRequest.ts) example but that seems too overkill for making a simple axios call. A "getting started" code, something like the one I posted above, is missing from documentation and would probably help beginners.

**Comment by sergiodxa** [comment]
I just realized you are using SWR to do a POST, except when using GraphQL where you need to use POST to fetch data (usually), the recommended way to do a POST request is to don't use SWR, instead run your request in an effect or event handler, SWR can and will run multiple times and a POST is usually used to create new resources, using them combined will cause unwanted side-effects where you are creating new resources even if you don't need them.

**Comment by techandmedia** [comment]
Hi,
I also use Post method to get the data so the URL is clean (no long query param in the browser bar).

Also, still no built-in support for object params? I use object a lot for params, it's very handy when one of the value change, I can re-trigger getting the new data by spread object {...previosParams, id: newID}
