### ISSUE TITLE
some falsy value in query will be omitted

### ISSUE THREAD

**Issue by liruinan1995** [vercel/swr#551]
# Bug report

## Description / Observed Behavior

when I use swr like below, 'value' is missed in query,

```
  const query = useMemo(() => ({
      value: 0 // or false
  }), []);

  const { data } = useSwr(['/api, query]);
```
## Expected Behavior

value like 0 of false should not be omit, unless it is undefined

**Comment by shuding** [comment]
What's your `fetcher` function? From your code the `fetcher` function will accept `/api` and `query` for sure, nothing will be omitted.
