### ISSUE TITLE
Better React DevTools support

### ISSUE THREAD

**Issue by shuding** [vercel/swr#574]
# Bug report

## Description / Observed Behavior

Currently in the React DevTools, a SWR hook looks like this:

<img width="62" src="https://user-images.githubusercontent.com/3676859/89051476-e9371100-d386-11ea-9b94-e3e0a0994963.png">

When unfolded:

<img width="482" alt="ss-YfSimTHR@2x" src="https://user-images.githubusercontent.com/3676859/89051016-34045900-d386-11ea-8b96-9f6b47bf56ee.png">

The actual data is located at "SWR → Ref → Data", which is not friendly when debugging.

## Expected Behavior

By using `useDebugValue(data)` (https://reactjs.org/docs/hooks-reference.html#usedebugvalue) we can directly show the data next to the `▶ SWR` toggle. It makes debugging easier:

<img width="422" src="https://user-images.githubusercontent.com/3676859/89051962-96118e00-d387-11ea-9de1-0d43a30fae69.png">

**Comment by Kexin-Li** [comment]
I wanna take this, may I? 🙋
