### ISSUE TITLE
Missing in the documentation: how to implement errors in the fetcher?

### ISSUE THREAD

**Issue by jordymeow** [vercel/swr#575]
Hello,

My custom fetcher is handling different kinds of errors. But how can I pass those errors _nicely_ to useSWR? Throwing exceptions within the fetcher works, but I am only getting a stringified version of the Exception in the _error_ returned by useSWR. Ideally, I would love to get the real Exception object, so that I can properly handle the issue.

I checked the documentation but there is nothing about this.

Thanks for your help!

**Comment by sergiodxa** [comment]
I can make it work https://codesandbox.io/s/swr-error-37rk1?file=/src/App.js

Could you provide a CodeSandbox to produce your issue?

**Comment by jordymeow** [comment]
Indeed, it seems to work... I didn't try to access the member of the error object directly. I am very confused, the Exception is an object, but it seems like console.log stringifies it. I made another example:

https://codesandbox.io/s/swr-error-37rk1?file=/src/App.js

Sorry, I was not aware of this behavior, there is something I really missed. I haven't looked up yet (wanted to tell you first), but now I really wonder how to properly console.log those exceptions.
