### ISSUE TITLE
useSWRInfinite with revalidateAll: true revalidates all pages when loading next page

### ISSUE THREAD

**Issue by lynxtaa** [vercel/swr#590]
# Bug report

## Description / Observed Behavior

I'm using `useSWRInfinite` with `revalidateAll: true` to revalidate all cached pages when component mounts or on focus. But it causes revalidation of all pages when loading next page.

```js
const { size, setSize } = useSWRInfinite(
  (index) => `https://example.com/issues?page=${index + 1}`,
  fetcher,
  { revalidateAll: true }
);

return (
  <button onClick={() => setSize(size + 1)}>Load More</button> 
)
```

Clicking "Load more" button two times will cause 5 requests: 
`https://example.com/issues?page=1`
`https://example.com/issues?page=2`
`https://example.com/issues?page=1`
`https://example.com/issues?page=2`
`https://example.com/issues?page=3`

So loading **N** pages will cause **N(N + 1)/2** requests.

## Expected Behavior

I expect `useSWRInfinite` with `revalidateAll: true` not to revalidate all pages when loading next page but to revalidate all pages on focus, reconnect, mount etc (similar to `useSWR` hook).

Right now I can do something like this to achieve desirable behavior but it feels hacky:
```js
const { size, setSize, mutate } = useSWRInfinite(
  (index) => `https://example.com/issues?page=${index + 1}`,
  fetcher
);

const latestMutate = useRef(mutate)
latestMutate.current = mutate

useEffect(() => {
  latestMutate.current()
}, [])
```

## Additional Context

SWR v0.3.0

**Comment by 4ndv** [comment]
Still an issue (at least for me) on 0.4.2. I want to refetch pages only when it's needed, but not when i'm loading a next page.

**Comment by lynxtaa** [comment]
@4ndv, By now I've moved to [react-query](https://react-query.tanstack.com/guides/infinite-queries) which doesn't have these issues

**Comment by 4ndv** [comment]
Well, for some reasons react-query is less userfriendly choice than swr. Maybe there is any way to fix this?

**Comment by shuding** [comment]
I can't reproduce this bug with the latest version. Also we already have a test to cover this case:

https://github.com/vercel/swr/blob/da7f6f6e34a169bef8f3381bbf245331993b22d9/test/use-swr-infinite.test.tsx#L155-L197

Feel free to reopen with a reproduction in e.g. CodeSandbox if you are seeing it again.

**Comment by lennerd** [comment]
I think @lynxtaa is missing the `revalidateAll` in his example (as the title stated). So the test you posted @shuding is not actually testing this.

**Comment by lennerd** [comment]
@shuding Maybe I'm missing something, but … the test you linked here does not use the `revalidateAll`, does it?

Maybe we also misunderstand the `revalidateAll` option. I thought I need this option to be enabled, to make sure I refresh all entries when refocusing the window. Or does this already work without this option?

**Comment by samnoyes** [comment]
[Link to CodeSandbox repro](https://codesandbox.io/p/sandbox/swr-infinite-forked-qgkqw8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxdhk1m100063b6is639g1k8%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxdhk1m100023b6ius4qpc0f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxdhk1m100033b6i6phqnwdz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxdhk1m100053b6i31r5bv53%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxdhk1m100023b6ius4qpc0f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdhk1m100013b6ievh63k69%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A1%257D%255D%257D%255D%252C%2522id%2522%253A%2522clxdhk1m100023b6ius4qpc0f%2522%252C%2522activeTabId%2522%253A%2522clxdhk1m100013b6ievh63k69%2522%257D%252C%2522clxdhk1m100053b6i31r5bv53%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxdhk1m100043b6itvh40vs2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxdhk1m100053b6i31r5bv53%2522%252C%2522activeTabId%2522%253A%2522clxdhk1m100043b6itvh40vs2%2522%257D%252C%2522clxdhk1m100033b6i6phqnwdz%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxdhk1m100033b6i6phqnwdz%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)


Reopening in a separate issue
