### ISSUE TITLE
Error handling when using global config not working as documented

### ISSUE THREAD

**Issue by benoj** [vercel/swr#593]
# Bug report
Hi there,

Im seeing the error handling when using global fetcher not working as expected. Errors blow up and and never end up being returned from the hook.

## Description / Observed Behavior

Errors are bubbling up to the top of the application and are causing the whole application to blow up (or use global error capture)

## Expected Behavior

Errors when using SWRConfig should capture and result from `useSwr` so that they can be handled on the specific page.

## Repro Steps / Code Example
component level:
```
// error is never returned here
const { data: provider, error } = useSWR(`/providers/${providerId}`, {
    refreshInterval: 0,
    suspense: true,
  })

  if (error) {
      return <ErrorPage />
  }

```
global level
```


//global config
  function checkStatus(response) {
    if (response.ok) {
      return response;
    } else {
      var error = new Error(response.statusText);
      error.response = response;
      return Promise.reject(error);
    }
  }


  return (
    <SWRConfig
      value={{
        refreshInterval: 30000,
        fetcher: (url) => get(url).then(checkStatus).then(res => camelCaseKeys(res.json())),
      }}
    >
      {children}
    </SWRConfig>
  )
}

```

## Additional Context

SWR version.

**Comment by benoj** [comment]
ping

**Comment by promer94** [comment]
When you set ***suspense: true***, the useSWR hook will not catch the error throw by your request promise. You can use [react-error-boundary](https://github.com/bvaughn/react-error-boundary) to handle the error.
