### ISSUE TITLE
useSWRPages is not exported from swr

### ISSUE THREAD

**Issue by marouaneat95** [vercel/swr#618]
I am new to swr package, and I came to know it from a tutorial over the internet, which import a function named useSWRPages from the 'swr' package and uses it to paginate results from call made to API

However when I run the code , it says that 'useSWRPages' is not exported from 'swr'

Did the function exist but has been depreciated or it never was and that's the author's mistake?

**Comment by huozhi** [comment]
@marouaneat95 `useSWRPages` was removed from swr since v0.3.0. you can use `useSWRInfinite` instead. checkout the usage sample in https://swr.vercel.app/examples/infinite-loading
