### ISSUE TITLE
Add change description info to cache.subscribe

### ISSUE THREAD

**Issue by gaoxiaoliangz** [vercel/swr#630]
```js
import { cache } from 'swr'

const listener = (e) => {
  console.log(e) // undefined
  syncAllCacheToLocalStorage()
}

cache.subscribe(listener)
```

Currently nothing is passed to the listener function. I would like to impl some sort of cache sync in my app (sync between localStorage and swr cache). And I would like to know which cache key changed, so that I would not need to iterate through every key and update every cache to localStorage.

**Comment by ryaninvents** [comment]
@gaoxiaoliangz Just as a heads up, looks like #365 will implement this when merged.

**Comment by huozhi** [comment]
@gaoxiaoliangz you can use the following code to access the iterative value pairs in the swr cache, then you can sync/serialize it to local storage as a workaround

```js
const listener = () => {
  const cacheKvPairs = cache.keys().map(key => ([key, cache.get(key)]))
  syncToLocalStorage(cacheKvPairs)
}
```

but since the cache APIs are not documented officially, it means cache calls might have breaking changes in the future when you upgrade swr to higher version.

**Comment by gaoxiaoliangz** [comment]
> @gaoxiaoliangz you can use the following code to access the iterative value pairs in the swr cache, then you can sync/serialize it to local storage as a workaround
> 
> ```js
> const listener = () => {
>   const cacheKvPairs = cache.keys().map(key => ([key, cache.get(key)]))
>   syncToLocalStorage(cacheKvPairs)
> }
> ```
> 
> but since the cache APIs are not documented officially, it means cache calls might have breaking changes in the future when you upgrade swr to higher version.

This is actually what I impl now, but the problem is that there is too much data to sync, and each time new data arrives I have to check them all in order to sync them to local, this is really inefficient.

**Comment by huozhi** [comment]
You could use custom cache to build out this feature now. Checkout [cache#sync-cache-to-localstorage](https://swr.vercel.app/advanced/cache#sync-cache-to-localstorage) for details
