### ISSUE TITLE
data returning { force: true }

### ISSUE THREAD

**Issue by Javo-blip** [vercel/swr#637]
# Bug report

## Description / Observed Behaviour
Sometimes the `data` that is returned from the useSWR hook is a `{ force: true }`
This seems to be caused by the cache value being set to `{ force: true }` to trigger a re-validate? It's only happened since v0.3.x

## Expected Behaviour

`data` should either return undefined or actual returned data from fetcher

**Comment by ChrisLincoln** [comment]
I had useSWR returning "false" in data, plus it was just not performing its function in life. Turns out I had bad usage of a mutate() call in a websocket event.

I had 
```
mutate('somekey', false)
//instead of
mutate('somekey', undefined, false).
```

I actually wanted mutate('somekey', undefined, true), but that isn't relevant.

**Comment by Javo-blip** [comment]
Just using
```
mutate('somekey')
```
should be intended usage according to documentation though?

This error has only occurred after upgrading to v0.3 and when useSWRInfinite was being used

**Comment by shuding** [comment]
Can you provide a reproduction?

**Comment by pke** [comment]
Encountered the same today! Where might it come from?

**Comment by pke** [comment]
Thanks for the fix
