### ISSUE TITLE
SWR swallows React errors thrown inside render when render was triggered during fetch

### ISSUE THREAD

**Issue by derolf** [vercel/swr#644]
# Bug report

## Description / Observed Behavior

When using suspense and an error is thrown during rendering, React complains as it should:

```
  The above error occurred in the <Suspense> component:
     in Suspense
```

However, the actual error is missing since it's "swallowed" by SWR.

## Expected Behavior

The error should not be swallowed.

## Additional Context

I added a manual log to reactjs to capture the stack trace. I see the following:

```
flushSyncCallbackQueueImpl -> React
flushSyncCallbackQueue -> React
scheduleUpdateOnFiber -> React
dispatchAction -> React
rerender({}) -> SWR
dispatch(...) -> SWR
```

The actual problem is that React does a sync update and the rendering error propagates through "dispatch" and is caught by the `catch (err)` handler.

SWR thinks it was a data fetching error, but it actually was not...

I think the big "try"-bracket needs to rethrow errors that were thrown inside of "dispatch".

**Comment by koba04** [comment]
@derolf Could you reproduce the case on CodeSandbox?

**Comment by huozhi** [comment]
@derolf Close as stale, will reopen once have a codesandbox repro
