### ISSUE TITLE
mutate is not rerendering

### ISSUE THREAD

**Issue by EliasSchlatter** [vercel/swr#662]
# Bug report

## Description / Observed Behavior

I'm using mutate() to update data. Here is a little snip of what I do:

```
doRequest("someUrl", "PUT", someData).then(response => {
            mutate({}, false);
            mutate(response, false);
        });
```

this way it is working and  the data of my nextjs app is updated properly, but its pretty ugly since there are two re-renders triggered.

Here is what I want to do:

```
doRequest("someUrl", "PUT", someData).then(response => {
            mutate(response, false);
        });
```

or better would be

`
mutate(doRequest("someUrl", "PUT", someData), false);
`

This way data is not updated. I also tried to this:

```
doRequest("someUrl", "PUT", someData).then(response => {
            mutate({...response}, false);
        });

```
Changing  mutate(response, false); to  mutate({...response}, false); should not be nessesary since the object returned from server already is a new objectReference, but I gave it a try just to be sure.

## Expected Behavior

I would expect swr to re-render every time when I use mutate with a new object reference.

## Additional Context

SWR version: 0.3.4

**Comment by sergiodxa** [comment]
Could it be that the data is the same? To avoid unnecessary request SWR compares the values deep equally and if they are the same it will not render again

**Comment by EliasSchlatter** [comment]
No, the dates are similar, but not the same. At the point where the error occurred, it is about an object that has a list. All other values next to the list are the same, but the list has one element more or less. 

{
   _id: '',
   name: ''
   value: '',
   someOtherValue: '',
   children: []                          <- the length of this list is different  
}

**Comment by troyacodes** [comment]
Having the same issue here

**Comment by sergiodxa** [comment]
Could you provide a CodeSandbox to replicate it?

**Comment by rainforss** [comment]
Yea I am having the same issue where mutate does not trigger a rerender when the object is nested. I thought mutate was gonna do a deep compare.

**Comment by shuding** [comment]
@troyacodes @EliasSchlatter could you provide a reproduction, like a CodeSandbox link? It looks like there's an object reference related issue.

I'd be happy to reopen this issue if anyone can help provide a reproduction. It just works fine for me personally.

**Comment by cwbuecheler** [comment]
@sergiodxa @shuding I don't think I can provide a code sandbox because the problem I'm running into seems to involve my .env file, and because though the variable is labeled `PUBLIC_API_URI` it is not actually a public API. Basically, none of my mutations ever re-render. Here's one piece of the exact code I'm using:

```javascript
  const { data: plateData, error: plateError } = useSWR(
    [`${process.env.NEXT_PUBLIC_API_URI}/device/base/identifier/${id}`, jwt],
    fetcher,
  );

  const updatePlate = async (deviceToUpdate: BaseDevice) => {
    const resp = await fetch(
      `${process.env.NEXT_PUBLIC_API_URI}/device/base/id/` + deviceToUpdate.id,
      {
        method: 'PUT',
        headers: {
          Authorization: `Bearer ${jwt}`,
        },
        body: JSON.stringify(deviceToUpdate),
      },
    );
    const json = await resp?.json();
    if (json.id) {
      mutate(`${process.env.NEXT_PUBLIC_API_URI}/device/base/identifier/${id}`);
    }
  };
```

I've tried even cancelling the actual mutation and using `mutate` to insert the data myself, to no avail. It just does nothing. Am I doing something wrong with my URL structure? For what it's worth, the API URL resolves to an https:// URI, and I'm running the code locally, so perhaps that's the issue?

**Comment by huozhi** [comment]
@cwbuecheler `[`${process.env.NEXT_PUBLIC_API_URI}/device/base/identifier/${id}`, jwt]` is an array key which will be serialized to sth different from the first string url. they key argument need to be consistent between `mutate` and `useSWR` if you want to manipulate it manullay.

**Comment by huozhi** [comment]
@EliasSchlatter I feel it's the similar issue to #313 . check out https://github.com/vercel/swr/issues/313#issuecomment-638099853, this might help?

**Comment by cwbuecheler** [comment]
@huozhi - ah, got it. Makes sense that it'd need the entire array rather than just the string. Thanks!

**Comment by EliasSchlatter** [comment]
Hi everybody,

sorry for my late response on this. 

@huozhi thanks for mentioning #313 this post. However, I think there is a different problem here because the object that mutate is called with comes from the backend and should be a object reference in any case.  About the key argument thing, I'm not sure if I understood you right, but I'm using bound mutate so I think this is also not the source of my issue.

@sergiodxa @shuding here you can find a [CodeSandbox](https://codesandbox.io/s/billowing-field-s8d11?file=/pages/index.js)

**Comment by wobsoriano** [comment]
Having problems with `useSWRInfinite` and the bound mutate function. Trying to mutate array of arrays, which does not throw an error and logs the updated data correctly in console, but doesn't rerender the components. Anyone having the same problem?

**Comment by harutofujihara** [comment]
@wobsoriano 
Isn't this only revalidate on inside `mutate()`?

**Comment by sjchmiela** [comment]
@wobsoriano I was able to make `useSWRInfinite` rerender after calling global `mutate` without revalidation by specifying an internal form of `key` for the mutated cache:

```ts
import { mutate, cache } from "swr";

const KEY_FOR_FIRST_PAGE = ...;
const [serializedFirstPageKey] = cache.serialize(KEY_FOR_FIRST_PAGE);
const infiniteKey = ["inf", serializedFirstPageKey];

mutate(infiniteKey, data => { ... }, false);
```

Got the idea from:
https://github.com/vercel/swr/blob/10c00808852de8480e2521b9ec68872c502e080d/src/use-swr-infinite.ts#L45-L48
and

https://github.com/vercel/swr/blob/10c00808852de8480e2521b9ec68872c502e080d/src/use-swr-infinite.ts#L102-L103

I'm a little bit afraid it's using internal API which can change unexpectedly, but it works for now.
