### ISSUE TITLE
setSize in useSWRInfinite is not memoizing

### ISSUE THREAD

**Issue by nobodywithbody** [vercel/swr#664]
# Bug report

## Description / Observed Behavior

I'm trying to automate fetching all pages. So, I'm using `setSize` in `useEffect` hook. When previous data contain a link for the next portion data I increment `size`. But every time when my own hook is being recalculated `useSWRInfinite` returns me different `useSize`. 

## Expected Behavior

I expected `setSize` which returning from `useSWRInfinite` not changed and changing only `size` property.

## Repro Steps / Code Example

```js
const getKey = (index, previousData) => {
    if (index === 0) return defaultUrl;

    return previousData?.data?.['@odata.nextLink'];
};

export const useMyDocuments = () => {
    const { data, setSize, mutate, isValidating } = useSWRInfinite(
        getKey,
        fetcher
    );

    useEffect(() => {
        if (data?.[data?.length - 1]?.data?.['@odata.nextLink']) {
            setSize((size) => size + 1);
        }
    }, [data, setSize]); //with `setSize` in dependencies hook executable in infinite loop.

    const docs = useMemo(() => data?.flatMap((el) => el?.data?.value), [data]);

    return {
        data: docs,
        isLoading: isValidating,
        mutate,
    };
};
```

## Additional Context

swr version - **0.3.4**

When I remove `setSize` from dependencies `useEffect` all work is fine. But this is a dirty hack for my opinion.

**Comment by shuding** [comment]
Thanks for reporting! The issue should be fixed in #665.
