### ISSUE TITLE
Using preload link tag sometimes duplicates the request

### ISSUE THREAD

**Issue by vulle5** [vercel/swr#666]
# Bug report

## Description / Observed Behavior

When I navigate from my login page to the show all notes page after successful login SWR duplicates the request to get the notes made by the preload link tag. Normally this would not be a big deal, but when I try to add a new note by using mutate the revalidation fails because the headers of the request did not match. If I reload the page everything works correctly and only one request is made to notes endpoint.

Below an image of duplicate fetches
![image](https://user-images.githubusercontent.com/15669924/94370948-93b78000-00fb-11eb-9036-923c887e20fa.png)

Below an image of the header warning
![image](https://user-images.githubusercontent.com/15669924/94371119-b6966400-00fc-11eb-9f58-0368b562e5fc.png)

Below my preload link
![image](https://user-images.githubusercontent.com/15669924/94371320-54d6f980-00fe-11eb-8b3a-b214722b7a3b.png)

Below my mutations
![image](https://user-images.githubusercontent.com/15669924/94371360-a5e6ed80-00fe-11eb-80df-3492a6316745.png)

## Expected Behavior

Expected the request to not be duplicated and mutate to revalidate.

## Repro Steps / Code Example

Navigate to pages with preload using router.push()

Link to my personal project. https://github.com/vulle5/notes-next

## Additional Context

I'm using the next version 9.5.3

swr version 0.3.5

One thing to note. Seems like this header If-None-Match: "1af-r89aryJGt4rixJuOJiW1yt8wFOE" does not exist when mutate makes a revalidation request. Is this the non-matching header?

**Comment by shuding** [comment]
Yeah `<link rel="preload">` requires the request header to be an exact match. You can try "Copy as fetch" for both requests to see what's the mismatched header:

![image](https://user-images.githubusercontent.com/3676859/97828243-7cbf0b80-1d01-11eb-82e0-2c755db58423.png)
