### ISSUE TITLE
Typescript bug?

### ISSUE THREAD

**Issue by jurajkrivda** [vercel/swr#677]
Hello. I'm not sure about this behavior and I'm not a typescript expert, but look at this:

```
type PostComment = {
  id: String,
  content: String
};

const { data, mutate } = useSWRInfinite<PostComment[]>(
    (index, previousPageData) => {
      if (previousPageData && previousPageData.length === 0) return null;
      return `/api/comments/comments?postId=?page=${PAGE_LIMIT}&skip=${
        index * PAGE_LIMIT
      }`;
    },
  );
```

console.log of data is `PostComment[][] | undefined`.

Why `PostComment[][]` and not only `PostComment[]`

Thank you

**Comment by sergiodxa** [comment]
Because the data is paginated. Data is an array of each page, and because a page is an array it becomes an array of arrays.

**Comment by shuding** [comment]
Indeed, this is intended like @sergiodxa said. Close this issue for now.
