### ISSUE TITLE
Race condition with double successive calls mutate

### ISSUE THREAD

**Issue by nobodywithbody** [vercel/swr#682]
# Bug report

## Description / Observed Behavior

Race condition when mutating consistently single `useSWR` hook

## Expected Behavior

When I call mutate with callback I expect the first argument in the callback is the equal previous state after first mutating.

And I expected when I set `initialData` to some value then it passes to the first argument in mutating callback, but it's set undefined.
## Repro Steps / Code Example

https://codesandbox.io/s/laughing-sky-xzllr?file=/src/App.js:0-706

## Additional Context

SWR version 0.3.5

Sorry for my English guys.

**Comment by shuding** [comment]
This issue was fixed in #735, please upgrade to the latest version (`0.3.9`).

Also there's a small issue in the sandbox which is `old.filter((el) => el === id)`, I believe it should be `!==`. Let me know if you have other question!
