### ISSUE TITLE
Variable data cannot be renamed

### ISSUE THREAD

**Issue by lucaspdfborges** [vercel/swr#697]
When renaming the `data` variable such as:

`let { data2 , error } =  useSWR(url,  fetcher)`

the request is correctly made to the backend server, however, `data2` is not updated throughout the code.

**Comment by sergiodxa** [comment]
To rename the destructores variable you need to do:
```js
let { data: data2 , error } = useSWR(url, fetcher)
```
Doing `{ data2 }` directly will try to get a `data2` key from useSWR returned value instead of renaming `data` to `data2`.
