### ISSUE TITLE
React 17 Support

### ISSUE THREAD

**Issue by bcomnes** [vercel/swr#724]
Opening an issue to track SWRs support for react/react-dom 17.  It appears to work fine, but I didn't spot any motion on updating the peer dep requirements.  Apologies if this ends up being duplicate.  

# Bug report

`swr` appears to work great with react 17 but reports a missing peer dep of react 16.

## Description / Observed Behavior

`swr` is throwing a peer dep warning on react 17 for v16, but appears to work fine. 

## Expected Behavior

`swr` support react 17 peer deps.

## Repro Steps / Code Example

Simply install next 10, react + react-dom 17 and SWR ^0.3.2. and you will see the warning.

**Comment by feross** [comment]
With npm 7, this is actually an error that blocks installation.

**Comment by brandonpittman** [comment]
> With npm 7, this is actually an error that blocks installation.

Had to pass it `--legacy-peer-deps` (or something like that) to make it work locally.

**Comment by shuding** [comment]
Released `swr@0.3.7` with the patch from @bcomnes 🎉
