### ISSUE TITLE
concerns about passing null as fetcher 

### ISSUE THREAD

**Issue by promer94** [vercel/swr#738]
## Background
 [@pacocoursey 's idea for SWR as a local cache](https://paco.sh/blog/shared-hook-state-with-swr) is great.
```js
const useSharedState = (key, initial) => {
  const { data: state, mutate: setState } = useSWR(key, {
    initialData: initial
  })
  return [state, setState]
}
```
But after #367 this won't work anymore because window.fetch will be used when fn is undefined
https://github.com/vercel/swr/blob/10e18cc9e6e607309db1aee81ac22b58690a76c3/src/use-swr.ts#L245-L248

However passing null as fetcher will work since we ***only replace the fetcher to window.fetch when fetcher is undefined***.
```js
useSWR(key, null ,{ initialData: initial })
```
But the typescript will complain this kind of usage.  #730 fix this problem by accepting null as as the fetcher function.

## Problem
1. This usage is not well documented.
2. passing null as the fetcher function is like a hack here to disable the whole stale-while-revalidate process in swr. I am not sure it is a good api design. I feel like it somehow leaks the implementation details.
3.  Passing null as the fetcher function makes most of the options useless here.
 ```js
useSWR(key, null ,{ initialData: initial, /** most of options here will not be used since the revalidation is disabled here */ })
```
## Possible alternatives
1. a passive options and a different options type
```js
useSWR(key, { 
  initialData: initial, 
  passive: true 
  /** typescript should complain about set options like onSuccess 
  which will only be used at  stale-while-revalidate process  */
})
```
2. a new hooks share the caches
```js
const { data: state, mutate: setState } = useSWRPassive(key, { initialData })
```

**Comment by loopmode** [comment]
I'd like to drop my two cents regarding API design and passing null for fetcher, even while it's only slightly related.
In my fetching hooks i typically use a concept where I can pass an option `autostart` or `autoload` which defaults to true, and my hooks typically return a `load` or `start` function, which can be used manually if autostart is set to false.
Maybe something similar could be considered in this library too. It creates a slightly larger API surface, but also provides huge flexibility and new features/possibilities, like submitting forms and any kind of user/gui-controlled fetching.

For this specific issue, it would mean instead of passing null for fetcher, you could just explicitly state that whatever the fetcher, it shouldn't be automatically invoked just because the hook was mounted.

**Comment by TommySorensen** [comment]
@promer94 I recent used the [same approach](https://paco.sh/blog/shared-hook-state-with-swr) but found it kind of buggy when using it as a shared hook with initialData several places with something like this: 

```js
// use-navigation.js
const initialData = {
  isOpen: false,
  searchIsOpen: false,
  searchHasItems: false,
  level: 0,
  levels: {}
}

const useNavigation = () => {
  const { data: navState, mutate } = useSWR('navigation', null, {
    initialData
  })

  const setNavState = newState => mutate({
    ...navState,
    ...newState
  }, false)

  return { navState, setNavState }
}

// Some other component
const { navState, setNavState } = useNavigation()
setNavState({ isOpen: !navState.isOpen})
// Shortly after somewhere else
setNavState({ searchHasItems: true})
```

The main issue was that when doing multiple `mutate`, to set the `searchHasItems` to `false`or `true`, then the useSwr suddenly returns the initialData from previous like on the screenshot.

![image](https://user-images.githubusercontent.com/4134473/104181997-08df6480-5410-11eb-819e-bea71fbba061.png)

I never found a fix for it, so i just assumed the API was not really ready for doing stuff like this, and like you mention, there is not a lot of documentation saying this something i should do 🙂

**Comment by webda2l** [comment]
Instead using null as fetcher, I use ```(key, value) => new Promise(value)```, you can give a try.

An example:
```
  const { data, mutate } = useSWR<BookingSelection>(
    'local-booking',
    (key, bookingSelection) => new Promise(bookingSelection),
    {
      initialData: initialBookingSelection,
      revalidateOnFocus: false,
    }
  )
```

**Comment by lukeshumard** [comment]
I've spent a little bit of time playing around with this, also inspired by @pacocoursey's blog post. His approach is a very eloquent and simple solution, but it is important to consider what using `null` as a fetcher means.


Here's my `useSharedState` hook based off of @shuding's [suggestion](https://github.com/vercel/swr/pull/918#issuecomment-764889331).
```jsx
import useSWR from 'swr'

export default function useSharedState(key, initialData) {
  return useSWR(key, null, {
    initialData,
    revalidateOnFocus: false,
    revalidateOnReconnect: false
  })
}
```

In use, it looks like this.
```jsx
const { data, mutate } = useSharedState('username', 'luke')
```

As long as the fetcher is not called again, this will result in having shared state between hooks in a single page.

**Comment by shuding** [comment]
In SWR 1.0, there is [no more default fetcher](https://swr.vercel.app/blog/swr-v1#no-more-default-fetcher) so you don't need to pass `null` as fetcher anymore. Also we think the [`fallback` API](https://swr.vercel.app/blog/swr-v1#fallback-data) is a better way to provide "initial data". I think we can close this issue now :)
