### ISSUE TITLE
[RFC] Configurable Cache

### ISSUE THREAD

**Issue by huozhi** [vercel/swr#742]
##  Background

Currently swr cache (0.4.x by the time) is a kind of hidden functionality, which exposed one experimental `cache` but not really fully documented with guaranteed. swr will leverage cache to store the states of keys, and `mutate` API can also manipulate states and cache at the same time.

We received few issues/Q&A about how to manipulate the cache directly and make its value aligned with swr's state, which confuse users sometimes.

## Goals

* Be able to store cache data elsewhere outside of swr, adaptive to different kinds of data presistence layer
* Be able to declare initial value for cache of swr context

## Proposal

Add a new property `cache` to swr context and let user be able to customize their cache. Fiting one cache API contract, and could be able to switch the underlayer providers like localstorage, RN AsyncStorage, any global state, etc. Note: `cache` is not available for swr hook

```ts
type CacheProvider = {
   initialData?: any;
  set?: (key: string, value: any) => void;
}
```

```tsx
const localStorageCacheProvider = {
  initialData: {},
  set(key, value) {
    window.localStorage.setItem('_swr_cache_' + key, JSON.stringify(value))
  }
}

<SWRConfig value={{cache: localStorageCacheProvider}}>
```

### Discussion

This is just a draft or an idea, won't be happened immediantely or break the current swr usage. Any comments or suggestions please let us hear from you. Thanks

**Comment by bionicles** [comment]
Might be better to use the Cache API instead of local storage because it persists the data to apps installed locally on mobile devices, and it works inside WebWorkers https://developer.mozilla.org/en-US/docs/Web/API/Cache

https://caniuse.com/?search=cache
