### ISSUE TITLE
v0.3.8-beta.2 published as latest

### ISSUE THREAD

**Issue by Kerumen** [vercel/swr#743]
I don't know if this was intended but the version `0.3.8-beta.2` was released as latest on [npm](https://www.npmjs.com/package/swr).

<img width="761" alt="Screenshot 2020-11-01 at 11 29 08" src="https://user-images.githubusercontent.com/5436545/97800438-7a8f7b00-1c35-11eb-9598-c11b2162eec2.png">

**Comment by shuding** [comment]
Thanks for reporting! I just release `0.3.8` as the latest stable version to override this beta, and sorry for inconvenience!
