### ISSUE TITLE
Global mutate doesn't work

### ISSUE THREAD

**Issue by nimabrownlee** [vercel/swr#746]
# Bug report

## Description / Observed Behavior

I want to revalidate the data/send a new request using the global mutate function.

## Expected Behavior

To send a new request.

## Repro Steps / Code Example

I'll just post a code snippet as I am not doing anything fancy. 

```
  const { data, error } = useSWR(
    '/api/tasks' +
      encodeQueryString({
        limit: 3,
        contactId: id,
      }),
  ) 
// /api/tasks?limit=3&contactId=30404
```

and then when I use the global mutate function

`mutate('/api/tasks')`

Now I am not adding the query and I assume thats how it should work. Because I don't have access to contactId in every instance.

**Comment by promer94** [comment]
if you have two hooks mounted
```js
const { data, error } = useSWR('/api/tasks')
const { data, error } = useSWR('/api/tasks?limit=3&contactId=30404')
```
call ```mutate('/api/tasks')``` will only revalidate the first hooks

For more informations, you could check the [mutation section](https://swr.vercel.app/docs/mutation) in [docs](https://swr.vercel.app)

**Comment by nimabrownlee** [comment]
@promer94 Then isn't the global mutate pretty useless? Obviously I can't make `contactId` accessible everywhere. I think there be a change in the specs so that it ignores queries.
