### ISSUE TITLE
SWR not working with @testing-library/react-hooks

### ISSUE THREAD

**Issue by paulhayessilex** [vercel/swr#766]
# Bug report

## Description / Observed Behavior

```
it('should update swr.data', async () => {
  const wrapper = ({ children }) => (
    <SWRConfig value={{ dedupingInterval: 0, fetcher }}>{children}</SWRConfig>
  )
  const {
    result: { current },
    waitForNextUpdate,
  } = renderHook(() => useUser(), { wrapper })
  console.log(current)
  await waitForNextUpdate()
  console.log(current)
})
```

both the before and after awaitForNextUpdate() console logs return the exact same object

```
current {
        revalidate: [Function (anonymous)],
        mutate: [Function (anonymous)],
        error: undefined,
        data: undefined,
        isValidating: true,
        user: undefined
      }
```
I would expect the data to be defined after the awaitForNextUpdate(), why hasn't it resolved?

**Comment by nstepien** [comment]
Sounds similar to #781, can you try to add `await new Promise(requestAnimationFrame)` before/after `await waitForNextUpdate()`?

**Comment by huozhi** [comment]
Close as this is stale and seems to be resolved with comment above. Feel free to open new issues if you still have problem with testing.
