### ISSUE TITLE
Error from different key is returned

### ISSUE THREAD

**Issue by nico-hyperjump** [vercel/swr#789]
# Bug report

## Description / Observed Behavior

What kind of issues did you encounter with SWR?

When a request takes long to load, `useSWR` returns the error from the previous request, even though the keys are different.  

## Expected Behavior

How did you expect SWR to behave here?

`useSWR` should not return error from a different key. 

## Repro Steps / Code Example

1. Use Chrome
2. Install [URL Throttle chrome extension](https://chrome.google.com/webstore/detail/url-throttler/kpkeghonflnkockcnaegmphgdldfnden?hl=en) to simulate slow network for a certain URL.
3. Enable the extension and add this url: `https://pokeapi.co/api/v2/pokemon/ditto` with `10000` ms delay. Toggle on the `Enabled` switch.
4. Open the sample in this Codesandbox: [https://codesandbox.io/s/async-sound-9n2xm?file=/src/App.js](https://codesandbox.io/s/async-sound-9n2xm?file=/src/App.js)
5. First type in the input text: `fafafa`, or any non-pokemon text.
6. The text: `Error searching fafafa: fafafa not found` will appear.
7. Next, enter in the input text: `ditto`.
8. Since we add 10-second delay to the url to search for `ditto`, the request will take 10 seconds to finish. So I expect the text `Searching ditto` will appear, but instead the text: `Error searching ditto: dfadfa not found` appears. It seems `useSWR` returns the error from the previous key, `fafafa`.
9. After 10 seconds, the error text disappears as expected and the response is displayed.

Since the key changes, `useSWR` should not return error from previous request imo.

## Additional Context

SWR version: 0.3.9

**Comment by shuding** [comment]
Thanks for the detailed repro!
