### ISSUE TITLE
Next build crash with swr

### ISSUE THREAD

**Issue by underfisk** [vercel/swr#816]
# Bug report
The compile process is okay but at build time nextjs is throwing errors with ESM export of SWR, not sure what's going on exactly, here is the output of the error

```
> Build error occurred
/Users/user/Documents/test/packages/app/node_modules/swr/esm/index.js:1
export * from './use-swr';
^^^^^^

SyntaxError: Unexpected token 'export'
    at compileFunction (<anonymous>)
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.EldI (/Users/rodrigo/Documents/test/packages/app/.next/server/pages/project/[id].js:9242:18)
    at __webpack_require__ (/Users/rodrigo/Documents/test/packages/app/.next/server/pages/project/[id].js:30:31) {
  type: 'SyntaxError'
}
```

## Description / Observed Behavior
It only happens at build time, i can run app just fine
What kind of issues did you encounter with SWR?

## Expected Behavior
Build successfully
How did you expect SWR to behave here?

## Repro Steps / Code Example
Current next.config (which is the only thing modified)

```
const path = require('path')
const { nextI18NextRewrites } = require('next-i18next/rewrites')
const localeSubpaths = {}

module.exports = {
	rewrites: async () => nextI18NextRewrites(localeSubpaths),
	publicRuntimeConfig: {
		localeSubpaths,
	},
	poweredByHeader: false,
	devIndicators: {
		autoPrerender: false,
	}
	images: {
		domains: ['mydomain.com'],
	},
	webpack: config => {
		//This is needed to avoid react versions collision with theme or another package
		config.resolve = {
			...config.resolve,
			alias: {
				...config.resolve.alias,
				react: path.resolve(__dirname, 'node_modules', 'react'),
				'react-dom': path.resolve(__dirname, 'node_modules', 'react-dom'),
				'@material-ui/styles': path.resolve(__dirname, 'node_modules', '@material-ui/styles'),
			},
		}

		return config
	},
}
```

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version: 0.3.9
Next version: 10.0.3
@babel/core: 7.9.0

**Comment by huozhi** [comment]
hi @underfisk , from the stacktrace I feel like the esmodule assets of swr is processing by commonjs module loader, but without compiling the syntax to commonjs first.

I guess you might need to process the `node_modules/swr` to commonjs syntaxes (import/export -> require/exports) first?

**Comment by underfisk** [comment]
@huozhi I'm only using import/export (project is with typescript) therefore require/exports is not being used. Fun fact this was working before and all of the sudden after upgrading next/swr i got these issues

**Comment by huozhi** [comment]
@underfisk could you provide the previous workable versions of next and swr for us to identify the issue? I'm not sure if it's an issue on next.js side, since swr esm version has been published for quite a while

**Comment by underfisk** [comment]
@huozhi That's the strange part now, if i rollback next or swr versions, it doesn't work anymore.. Its very strange this behavior
I rollback to the previous next which was (10.0.0) and swr (0.2.2)

**Comment by underfisk** [comment]
@huozhi Sorry for making you lose time, the issue has been found and probably this might help any other that run into this same issue. Basically, since our codebase is so large, there was a PR that instead of consume the global mutate function from swr it was importing from 'swr/esm'
