### ISSUE TITLE
Fetcher with an AWS signedRequest is not updating data

### ISSUE THREAD

**Issue by josoroma** [vercel/swr#821]
# Bug report

## Description / Observed Behavior

useSWR is not updating data when using a custom fetcher:

```
  const request = { method: "GET", path: "/test" };

  const { data, error } = useSWR([request], fetcher);
```

## Expected Behavior

To get data populated with the custom fetcher response.

## Repro Steps / Code Example

My component:

```
import React, { memo, FC } from "react";
import { AmplifySignOut } from "@aws-amplify/ui-react";
import useSWR from "swr";

import fetcher from "./service/fetcher";

const AppWithRoutes: FC = () => {
  const request = { method: "GET", path: "/test" };

  const { data, error } = useSWR([request], fetcher);

  console.log("AppWithRoutes - data ===>", data);
  console.log("AppWithRoutes - error ===>", error);

  return (
    <>
      <AmplifySignOut />
      My AppWithRoutes
    </>
  );
};

export default memo(AppWithRoutes);
```

The custom fetcher:

```
import { Auth } from "aws-amplify";
import aws4 from "aws4";
import fetch from "unfetch";

import config from "../config";

const fetcher = (payload: any) => {
  Auth.currentCredentials()
    .then((currentCredentials) => {
      const credentials = Auth.essentialCredentials(currentCredentials);

      const apiGateway = {
        host: config.apiGateway.HOST,
        url: config.apiGateway.URL + payload.path,
      };

      const stage = config.apiGateway.URL.substring(
        config.apiGateway.URL.lastIndexOf("/") + 1
      );

      const request = {
        ...apiGateway,
        ...payload,
        path: `/${stage}${payload.path}`,
      };

      let signedRequest = aws4.sign(request, {
        // assumes user has authenticated and we have called
        // AWS.config.credentials.get to retrieve keys and
        // session tokens
        secretAccessKey: credentials["secretAccessKey"],
        accessKeyId: credentials["accessKeyId"],
        sessionToken: credentials["sessionToken"],
      });

      signedRequest.headers["Content-Type"] = "application/json";

      delete signedRequest.headers["Host"];
      delete signedRequest.headers["Content-Length"];

      // console.log("signedRequest *************>", signedRequest);

      return fetch(apiGateway.url, signedRequest).then(async (resp) => {
        const result = await resp.json();

        console.log(
          "signedRequest - result.response *************>",
          result.response
        );

        return {
          data: result.response,
          error: "",
          status: 200,
        };
      });
    })
    .catch((err) => err);
};

export default fetcher;
```

## Additional Context

![image](https://user-images.githubusercontent.com/69951/102342825-67273d80-3f5f-11eb-9dfa-1dc45d9d6093.png)

### SWR version is: ^0.3.9

![image](https://user-images.githubusercontent.com/69951/102342536-fbdd6b80-3f5e-11eb-82b4-f6b6b6a93605.png)

Note: I tried adding a return before Auth.currentCredentials() buuuut it causes an infinite loop of requests.

I also started a discussion here: https://github.com/vercel/swr/discussions/820

Thanks a bunch hackers!

**Comment by crispclean** [comment]
Hi, I have a similar issue: https://github.com/vercel/swr/issues/826

**Comment by josoroma** [comment]
> Hi, I have a similar issue: #826

Hi @crispclean ! What do you think I need to change on my code?

Thanks!

**Comment by promer94** [comment]
```js
const fetcher = (payload: any) => {
  // It seems you miss the return statement here
  return Auth.currentCredentials().then(v => {
   ....
  })
```

**Comment by josoroma** [comment]
> ```js
> const fetcher = (payload: any) => {
>   // It seems you miss the return statement here
>   return Auth.currentCredentials().then(v => {
>    ....
>   })
> ```

@promer94 I tried adding a return before Auth.currentCredentials() buuuut it causes an infinite loop of requests.

**Comment by promer94** [comment]
```js
// move out the request object, so that it would not create a new object in every render
const request = { method: "GET", path: "/test" };
const AppWithRoutes: FC = () => {
  const { data, error } = useSWR([request], fetcher);

  console.log("AppWithRoutes - data ===>", data);
  console.log("AppWithRoutes - error ===>", error);

  return (
    <>
      <AmplifySignOut />
      My AppWithRoutes
    </>
  );
};
```
For more information
https://swr.vercel.app/docs/arguments#passing-objects

**Comment by josoroma** [comment]
> ```js
> // move out the request object, so that it would not create a new object in every render
> const request = { method: "GET", path: "/test" };
> const AppWithRoutes: FC = () => {
>   const { data, error } = useSWR([request], fetcher);
> 
>   console.log("AppWithRoutes - data ===>", data);
>   console.log("AppWithRoutes - error ===>", error);
> 
>   return (
>     <>
>       <AmplifySignOut />
>       My AppWithRoutes
>     </>
>   );
> };
> ```
> 
> For more information
> https://swr.vercel.app/docs/arguments#passing-objects

@pacocoursey thanks a bunch! it works!!!
