### ISSUE TITLE
Component unmounted may cause the state of other same hooks to not be updated

### ISSUE THREAD

**Issue by u3u** [vercel/swr#829]
# Bug report

## Description / Observed Behavior

`updaters[i](!!shouldRevalidate, data, error, undefined, i > 0)` may cause some components to be unmounted
`CACHE_REVALIDATORS[key]` and `updaters.length` may change in the next loop cause some hooks can not update

https://github.com/vercel/swr/blob/984f784c7cab8b072194ef82b223964a885347c6/src/use-swr.ts#L657-L659
https://github.com/vercel/swr/blob/984f784c7cab8b072194ef82b223964a885347c6/src/use-swr.ts#L203-L218

## Expected Behavior

Should ensure state of other same hooks to be updated

## Repro Steps / Code Example

Or share your code snippet or a [CodeSandbox](https://codesandbox.io) link is also appreciated!

## Additional Context

SWR version: 0.3.9

**Comment by u3u** [comment]
@shuding @huozhi 
Hello, is this problem expected behavior or a bug? 🤔️
Can this problem be solved if `setTimeout` is called during `removeRevalidator`?

**Comment by shuding** [comment]
This should have been fixed in the latest version, thanks!
