### ISSUE TITLE
2 subsequent `mutate` doesn't trigger a re-render in the first one

### ISSUE THREAD

**Issue by Kerumen** [vercel/swr#922]
# Bug report

## Description / Observed Behavior

Calling 2 subsequent `mutate` (the second with an async call) doesn't trigger a re-rerender with the first one. I have an UI that I want to optimistic update when the user trigger an updates and an API call which will update the data when the response comes in.

The snippet below is just to illustrate the bug. When I trigger the update, I want the UI to **instantly** updates with the new data and then gets updated another time with the data that comes from the API.

```js
const updateName = () => {
  mutate({ ...data, name: "swr v2" }, false);
  mutate(async (data) => {
    await callMyApi();
    return { ...data, name: "swr v3" };
  }, false);
};
```

If you click on the button, nothing happen during 1s and then the `name` is changed to `swr v3`.

## Expected Behavior

I want the first mutate to update the data and trigger an immediate rerender (without any `await 0` workaround) and then the second mutate to update the data accordingly.

If you click on the button, the name should instantly change to `swr v2` and 1s later be changed to `swr v3`. It works with the `updateName2` function (with the workaround).

## Repro Steps / Code Example

https://codesandbox.io/s/swr-basic-forked-fcilh

## Additional Context

SWR version: `0.4.0`

Probably related to https://github.com/vercel/swr/pull/735

**Comment by promer94** [comment]
SWR will batch the rerender if two or more mutations happen at same time. This behavior is expected.  

Instead of using await 0 as workaround, you could do 

```js
const updateName = async () => {
  await mutate({ ...data, name: "swr v2" }, false);
  mutate(async (data) => {
    return { ...data, name: "swr v3" };
  }, false);
};
```

**Comment by Kerumen** [comment]
@promer94 Thanks for your answer!
I think this should be documented somewhere because the code was working on `v0.3.8` and stopped on `v0.3.9` upgrade. I had to manually check which version caused the "regression" and was not able to fix it on my own.

**Comment by em** [comment]
I would prefer that the API was less magical and didn't do things like support an async mutator functions in mutate so things like this didn't come up.

Typescript is a compromise and most "real" type systems would not allow this. It's Javascript thinking to allow a parameter to do all sorts of different things.

**Comment by promer94** [comment]
#1003 fixed this problem.
