### ISSUE TITLE
Infinite loading when accessing the project from another device

### ISSUE THREAD

**Issue by adrienharnay** [vercel/swr#971]
# Bug report

## Description / Observed Behavior

I'm currently working on a Next.js project with SWR. I am using the useSWR hook. I run the project with either `next dev` or `next build && next start`.

When accessing `localhost:3000`, the query completes fine. When using my local ip (e.g. `192.168.0.1:3000`) on the same computer I run the server on, the query completes fine as well.

When I try accessing `192.168.0.1:3000` on my phone or another computer on my local network though, the project loads fine but the query never completes (`data` stays undefined). `next dev` and `next build && next start` yield the same result.

## Expected Behavior

Work the same when it is accessed on another device than when it is accessed on the same device.

## Repro Steps / Code Example

Can't really be reproduced on Codesandbox sorry... Any Next.js project using SWR would do I guess, as I am using it in the simplest way possible, without extra options.

## Additional Context

SWR: 0.4.1
Node: 14.5.0
Next.js: 10.0.6

Thanks in advance!

**Comment by shuding** [comment]
Hi! Is the API that you are requesting to inside pages/api? It will also be helpful if you can reproduce with another computer and take a look at the console.

**Comment by adrienharnay** [comment]
Hi! It seems that the error was my fault (server was on first machine), I am sorry for the extra issue! Have a nice day.

**Comment by shuding** [comment]
No worries!
