### ISSUE TITLE
How can i persist data in cache but not inside Async Storage in React-Native

### ISSUE THREAD

**Issue by mehthabux** [vercel/swr#973]
i have tried useSWR in my react native app , everything works fine and great! but all the cached data are lost when i reload the app
I was seeing the entire documentation , but no where i could’nt  see the option to persist data in cache.

**Comment by koba04** [comment]
You can use `cache` for that, which is a cache store that SWR uses internally.

```js
import { cache } from "swr";
```

https://github.com/vercel/swr/blob/master/src/cache.ts

But I think it's not an API officially supported because `cache` is not documented, so you have to use it at your own risk.

**Comment by mehthabux** [comment]
Does it persist in React native ? 
My data should persist if  i restart the app

**Comment by koba04** [comment]
@mehthabux 
You have to implement logic to persist cache data to anywhere ReactNative provides.
You can subscribe to changes in `cache` by the `subscribe` method.

**Comment by mehthabux** [comment]
ok Cool , thanks @koba04 
let me try 👍

**Comment by huozhi** [comment]
@mehthabux you can checkout the [custom cache API doc](https://swr.vercel.app/advanced/cache) to implement this. In the example section there's one for syncing state to `localStorage`, I believe it could be replaced with `AsyncStorage` with combination of lifecycle and events in RN.

**Comment by shuding** [comment]
Closing as above.
