### ISSUE TITLE
Mutator function ends up in cache if it throws an error

### ISSUE THREAD

**Issue by skrivanos** [vercel/swr#975]
# Bug report

## Description / Observed Behavior

If you pass a mutator function to `mutate` and it throws an error the function itself will end up in the cache.

## Expected Behavior

Keep the old data in the cache.

## Repro Steps / Code Example

https://codesandbox.io/s/wizardly-tree-ghhb3?file=/src/index.js

## Additional Context

0.4.2

Cause:
https://github.com/vercel/swr/blob/0.4.2/src/use-swr.ts#L171

**Comment by koba04** [comment]
I've created a PR to fix this. #977
