### ISSUE TITLE
When using refreshInterval, requests are not deduplicated 

### ISSUE THREAD

**Issue by cyeb** [vercel/swr#991]
# Bug report

## Description / Observed Behavior

I wrote a hook containing useSWR and use it across multiple components. Requests are not deduplicated when providing `refreshInterval`. When I remove refreshInterval, requests are once again deduplicated.

## Expected Behavior

I expected SWR to deduplicate requests made by refreshInterval.

For example, if I provide `{refreshInterval: 1000}` in the hook, and if I use this hook in 3 different components rendered on a page, I don't expect useSWR to call the callback 3 times a second, I only expect it to happen once a second.

## Repro Steps / Code Example

Hook code:

```
import useSWR from 'swr'

export default function useHook() {
  const { data } = useSWR(
    'useHook',
    ()=> { console.log('hook function called') },
    { refreshInterval: 1000 }
  )

  return {data}
}
```

Used in several different components like so:

```
import useHook from './useHook'

const Component = () => {
    const { data } = useHook()

    return (<>foo</>)
}
```

## Additional Context

SWR version: ^0.4.0

**Comment by shuding** [comment]
Are you using a synchronous fetcher like the example you shared? It's indeed a bug but only reproducible with a sync fetcher. 

By adding `async` to the fetcher: `async ()=> { console.log('hook function called') }` it works fine.

**Comment by cyeb** [comment]
Yes, I was using a synchronous fetcher. Thanks for the workaround! Very helpful.

**Comment by promer94** [comment]
The reason why the requests are not deduplicated is because the sync fetcher returns undefined. 

https://github.com/vercel/swr/blob/eb7fa36920fa5eaca5d68a61ece6eabe54c64907/src/use-swr.ts#L367-L368

**Comment by mr-fibonacci** [comment]
Could someone please put this crucial information in the docs?
